### PR TITLE
[TD-2193] Use correct tags for CI push and CI test

### PR DESCRIPTION
**Pull request by alephnull**
The old architecture of doing ci in a separate job made the larger workflow seemingly more resilient but as the automation grows, failures in CI will make the remainder of the release process unprocessable. So doubling down on making CI push robust.

Removed ci/auto as it lives in tyk-ci now. Tested by re-using [v5.2.1-alpha](https://github.com/TykTechnologies/tyk/actions/runs/5971645065).

I will propagate this fix to gw and dash master and lts branches via templates, the fix will have to be cherry picked for other branches where it is required. Please review https://github.com/TykTechnologies/tyk-analytics/pull/3429 along with this one.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5465/merge
Commit:  
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5971161854)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5465/merge
Commit: f406dcc18b2dcc3164293000b7afa2e46e7c143f 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5971359536)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5465/merge
Commit: 96ae1ad4d7dd08f9e7d9ef26c8fafab359947ebd 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5971301882)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5465/merge
Commit: e1951a3d40c276f06898c27808d375dbc7cd8505 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5971463028)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5465/merge
Commit: 191404f615184ddbe83aab4737d5686faa721b09 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5971554883)

**Review by titpetric — APPROVED** [review]

**Pull request merged**
