### PR TITLE
[TT-4955] replace dgrijalva/jwt-go with golang-jwt/jwt/v4

### PR DESCRIPTION
**Pull request by mitjaziv**
Change replaces unmaintained vulnarable version of jwt library with
maintained golang-jwt/jwt/v4.

## Related Issue

https://tyktech.atlassian.net/browse/TT-4955

## Motivation and Context

Improve code base security.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [X] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [X] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] Check your code additions will not fail linting checks:
  - [X] `go fmt -s`
  - [X] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit:  
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2323954449)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: a0ded719c342b7cd6d836ffec4dac44ae22f61a7 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324097442)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: f4db19bd12226c46ab0c9c823e902755ae71f26a 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324145992)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4053/merge
Commit: a12d5976a287e19d8fc1a1b0b134b5d07be6c52e 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324195648)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 9beef522697004ac758759c8af7c7ef38e59c851 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324442211)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 9beef522697004ac758759c8af7c7ef38e59c851 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324442211)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 9beef522697004ac758759c8af7c7ef38e59c851 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324442211)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 9beef522697004ac758759c8af7c7ef38e59c851 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324442211)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 9beef522697004ac758759c8af7c7ef38e59c851 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324442211)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 9b54bd3b572bba08238b7b5cf7a2979de2c31a89 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324836380)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 9b54bd3b572bba08238b7b5cf7a2979de2c31a89 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324836380)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 9b54bd3b572bba08238b7b5cf7a2979de2c31a89 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2324836380)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 3bfae123cdae844c9a0d243138111804f315b2db 
Triggered by: pull_request (@urbanishimwe)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2413699224)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4053/merge
Commit: 7f4937d1360a081914baa98e41331d7526d1a9b8 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2414029399)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4053/merge
Commit: e6e7bf196a499b790d0399d7f085c154d266e781 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2438869732)

**Comment by jeffy-mathew** [comment]
jwt dep got updated as part fo https://github.com/TykTechnologies/tyk/pull/4347 & https://github.com/TykTechnologies/tyk/pull/4348

**Comment by jeffy-mathew** [comment]
jwt dep got updated as part fo https://github.com/TykTechnologies/tyk/pull/4347 & https://github.com/TykTechnologies/tyk/pull/4348

**Pull request closed without merging**
