### PR TITLE
[TT-7127] Fix goplugin invalid memory address or nil pointer dereference

### PR DESCRIPTION
**Pull request by titpetric**
https://tyktech.atlassian.net/browse/TT-7127

Closes #4198 #4197

### CODE REVIEW

**Review by furkansenharputlu — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5589/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6418053272)

**Comment by titpetric** [comment]
@tomshy We're still in discussion for 4-LTS, if greenlit it would be included into 4.0.15, it will be included in the upcoming 5.0 and 5.2 releases. Do you have a particular version requirement on your side? Any context you can provide is welcome.

**Comment by tomshy** [comment]
We're running 4.0.6 and not ready for upgrades as per our internal upgrade policies. So, we'd appreciate if you could add it there too

**Comment by titpetric** [comment]
The patch has been included into 4-LTS and will be present in 4.0.15.

**Comment by tomshy** [comment]
Well noted. Thanks guys

**Pull request merged**
