### PR TITLE
Update tyk gateway readme

### PR DESCRIPTION
**Pull request by Keithwachira**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit:  
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5413240994)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: a8464a63fecac0757f758cada9fa43eb4a7bc98e 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5413300920)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 3bc7dc430ccaccf7ad099dda4bc3438bc7460bfb 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5413442579)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 26dbdd81daefd85b9d4eaba1c58742b801cd52cb 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5413519113)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 6fc06c6c8aa9720cd82fca22cf75316154663d61 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5413489790)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 234ed6a6b5fa41b7044bdcdc4ed0fb99b111faf2 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5413700382)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 4f7a2b293c9b26193d9c524b5eafc182865ffcf9 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5414641833)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 227e5e61a729ce3bb36949a256824465b17f980e 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5414736738)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 76f9548679d571d9d60d036e7b10c73e0dc7874c 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5414758036)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: b0b88785aa40e8761325facd41647aa2a6238012 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5414906703)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 154d37bd813a1fcb824b23f5411345b89e96487e 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5416487896)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: dfc4a1fe68e9d0c5e667d3609f6867d6ae30cef7 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5416474151)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 46f9e2ac5e98717f62362c4640f3c65c6fbeba2a 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5416547424)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 535653de06359be5a29245c12a95947d95d50234 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5416518046)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 8f18142aa0778d769bd190603c5c6b1e6599e067 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5419861171)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: cac48547486e50492ac6f62be3680c6eaf3a70aa 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5420982781)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: f0ffb339dbd740fd0a1cd2c059fc2e1640c62463 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5421156271)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: c0532778afd5b6cff4fccaaa1b534ad7d700e31e 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5421463561)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: ede0e885190b07655ed1aee451d1582159c1c2ff 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5422145615)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: b538ce1d28e631060edfb29f23215e22add6ef73 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5422256267)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: 5fa2e467ef8aef3e9766cacc888cb8ec22beeaa0 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5422268011)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: ead9787efe05f57952c4c242183ca383bc74d60f 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5422359189)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5241/merge
Commit: c4b8a5908e7d5cca3827c90c7ac48f8701b63c92 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5422513901)

**Review by titpetric — APPROVED** [review]

**Pull request merged**
