### PR TITLE
Multiple authentication types per API

### PR DESCRIPTION
**Pull request by ivaningrooves**
The middleware first checks the header, then the url parameter
and finally the cookie - if any are configured. 

To enable,
either set the flags and use the `auth_header_name` property *or*
define a value for `cookie_name` and/or `param_name`.

This change requires tykcommon with https://github.com/TykTechnologies/tykcommon/pull/2

### CODE REVIEW

**Comment by ivaningrooves** [comment]
Obviously this build fails since tykcommon has not been updated yet.

**Comment by lonelycode** [comment]
Looks awesome - thanks :-)

**Comment by lonelycode** [comment]
(have merged to develop so we carry this all through to the next release)

**Comment by ivaningrooves** [comment]
Thanks! Are you planning on adding UI for this to the dashboard?

**Comment by lonelycode** [comment]
Indeed it will be added :-) It's a great feature, and an elegant way to make it backwards compatible, so adding two new fields for paramname and cokiename will be pretty straightforward.

**Comment by lonelycode** [comment]
It's now in our [roadmap](https://trello.com/c/d8cIzU3V/300-multiauth-param-cookiename-and-header-name-segregation-integation-with-dash), so it willd efinetely end up in the dashboard on the next release.

**Comment by ivaningrooves** [comment]
Awesome, thanks a lot!

**Pull request merged**
