### PR TITLE
[TT-6159] coprocess: add tests for Tyk cgo API and expose GW RedisController for CP functionality

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
## Description
After GW refactor the way Redis is initialized/handled changed and broke the functionality of the Tyk cgo API. This API is documented [here](https://tyk.io/docs/plugins/supported-languages/rich-plugins/python/tyk-python-api-methods/) and it basically allows a developer to interact with Redis from a Python plugin.

Constraints:
- I’ve added tests to cover this functionality, they’re standard Go tests (using cgo of course).
- cgo in tests isn’t allowed so I implemented wrapper functions for both calls (cgoTykGetData and cgoTykStoreData).
- Have added a global cgoRedisController, I know we now try to isolate GW structure for every GW object but cgo doesn’t know about structures or methods associated with it.
- We can’t modify/improve exported cgo functions (TykStoreData and TykGetData), these functions can only receive and return C objects.

## Related Issue
TT-6159

## Motivation and Context
-

## How This Has Been Tested
Manually tested.
Added automatic tests in this PR -previously missing-.

## Screenshots (if appropriate)
-

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4205/merge
Commit:  
Triggered by: pull_request (@matiasinsaurralde)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2735932109)

**Comment by titpetric** [comment]
@matiasinsaurralde could you please take a look at https://github.com/TykTechnologies/tyk/pull/4055 and figure out if there are some test cases that you could merge onto this ticket.

**Review by sredxny — APPROVED** [review]
lgtm

**Comment by matiasinsaurralde** [comment]
@titpetric Thanks Tit, will take a look!

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4205/merge
Commit: 120e1e0afd9701e8a25082b997d0406e60eb4b76 
Triggered by: pull_request (@matiasinsaurralde)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2762290355)

**Comment by ermirizio** [comment]
@matiasinsaurralde is this ready to be released? this will block us on implementation side for internal cluster

**Pull request closed without merging**
