### PR TITLE
Move copyHeader to be included in analytics

### PR DESCRIPTION
**Pull request by titpetric**
## Description

On analytics hit, cache headers have been written directly to the ResponseWriter headers. This PR changes this behaviour, so that the analytics request also logs the X-Tyk-Cached-Response value.

## Related Issue

https://tyktech.atlassian.net/browse/TT-7390

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4666/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3956437616)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4666/merge
Commit: 8c2c1adba8adfa82e5555bba64cae8b86ef1220c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3958180246)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4666/merge
Commit: 5f12f7b33666332c62f829672eb7cef0a89e69f3 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3958211566)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4666/merge
Commit: 9ec87b223074739483ae1a89268d672bfe4e699c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3966222622)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4666/merge
Commit: 8b110e9a3d726c7fc69a0fb9dd0f76129ac3b4c6 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3984714443)

**Pull request merged**
