### PR TITLE
[TT-9628/TT-9715] Allow overriding an OAS API by classic API format

### PR DESCRIPTION
**Pull request by furkansenharputlu**
Parent: https://tyktech.atlassian.net/browse/TT-9628
Subtask: https://tyktech.atlassian.net/browse/TT-9715

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5373/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5713158622)

**Comment by buger** [comment]
@CodiumAI-Agent review

**Comment by buger** [comment]
@CodiumAI-Agent reflect_and_review

**Comment by buger** [comment]
@CodiumAI-Agent describe

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5373/merge
Commit: 6ac8438678a9f30935ad4ad695789091d25145e1 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5735945501)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5373/merge
Commit: c7526c4dfedd35a74dc318565017e8b45b01a73d 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5796695865)

**Pull request merged**
