### PR TITLE
Update config.go

### PR DESCRIPTION
**Pull request by zalbiraw**
Update `connection_timeout` description for dashboard client.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Review by dcs3spp — APPROVED** [review]
Thanks Zaid

**Comment by zalbiraw** [comment]
release to release-5.0.3

**Comment by zalbiraw** [comment]
release to release-5.1

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5190/merge
Commit:  
Triggered by: pull_request (@zalbiraw)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5324901046)

**Pull request merged**
