### PR TITLE
Remove a bunch of unused parameters

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by lonelycode** [comment]
Show off ;-)

**Comment by mvdan** [comment]
And of course, build is broken.

**Comment by mvdan** [comment]
@buger I hit https://github.com/TykTechnologies/tyk/issues/588 here, but I re-ran the CI build and lost the log (damn you, Travis).

PTAL

**Comment by buger** [comment]
I remember it was the same flaky test

**Comment by mvdan** [comment]
Anything blocking this?

**Pull request merged**
