### PR TITLE
Prepend apiid to path 

### PR DESCRIPTION
**Pull request by joshblakeley**
Fixes #860

This make endpoints in aggregate become namespaced by apiid and path so endpoint popularity graphs will be fixed.

i.e. When record has `trackPath=true` record.path becomes apiid/path

First path element before forward slash will always be apiid in aggregate collections.

### CODE REVIEW

**Comment by joshblakeley** [comment]
@buger confirmed as enough for frontend to have working endpoint popularity functions - can you plz review

**Comment by joshblakeley** [comment]
We are back to just apiid again as using api name wouldnt be good due to it being possible to change over time - meaning records could become out of date with old names.

**Comment by buger** [comment]
@joshblakeley I just realized that probably better place for this code can be actually a Pump, and only mongo pumps. It should be more backward compatible, since if person already use ES pump or similar, they setup will be broken with this code.

**Comment by joshblakeley** [comment]
That sounds good to me. Not sure why we didnt think about that at this point. I'll close this and open pump PR.

**Pull request closed without merging**
