### PR TITLE
[WIP] Mark some tests as parallel

### PR DESCRIPTION
**Pull request by mvdan**
Some of the others are flakey if run in parallel. Prioritized trivial
and slow ones here.

'go test' time on my machine is down from ~5s to ~1.5s.

Updates #362.

### CODE REVIEW

**Comment by buger** [comment]
A lot of this tests using RedisClusterStorageManager with same key prefixes. 
Even if we switched to miniredis, it is still a global storage for all tests.

So, maybe for tests that marked as parallel, we will use random prefixes? Assuming that removing global Redis object is not an option right now, smth like this may work:

```
# For purpose used fixed vocabulary, because reading from random may break redis
const letterBytes = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

func randomizePrefix(prefix string) string {
    b := make([]byte, 10)
    for i := range b {
        b[i] = letterBytes[rand.Intn(len(letterBytes))]
    }
    return prefix + "-" + string(b)
}

...

RedisStorageManager{KeyPrefix: randomizePrefix("apikey")}
```

**Comment by mvdan** [comment]
@buger I was thinking the same, but apparently this doesn't happen. If it did, I assume many of the tests would fail. I made sure via `-count 100`, i.e. firing all the tests 100 times. If any keys were stomped, a good part of the runs would have failed then.

Your solution doesn't convince me either - there is still space for flakiness. I would use something like the test name as the prefix, which is known to be unique. I can do that change, if you wish.

I'd first like input from @lonelycode as to whether the keys are repeated or not.

**Comment by buger** [comment]
Maybe in our case it make sense not to add parallel tests at all (considering that test time already great), and instead in TestMain ensure to Cleanup redis after each test call. This should be bulletproof way to avoid any redis related issues.

**Comment by mvdan** [comment]
> Maybe in our case it make sense not to add parallel tests at all (considering that test time already great)

I disagree. Four seconds is better than before, but it's still pretty bad. Remember that we have a 30% test coverage. Once that reaches decent numbers like 80%, the 4s could easily duplicate or triplicate. Parallel tests don't increase linearly in time consumed.

> and instead in TestMain ensure to Cleanup redis after each test call. This should be bulletproof way to avoid any redis related issues.

This is not how TestMain works, unless I'm missing something. In any case, it would be a hack and a workaround for our messy use of redis in the tests (if it is messy).

**Comment by buger** [comment]
Well, we have to find some solution to global Redis object somehow, otherwise chances of getting crazy bugs and flaky tests too high. Especially when we start adding more tests.

**Comment by mvdan** [comment]
@buger sure, but giving up parallel tests altogether isn't a good option IMHO. A few of our tests already take long (half a dozen are around `0.2s`) while not using almost any CPU, so it's definitely the way to go.

This PR is not high priority, we can discuss keys with Martin once he's back.

**Comment by buger** [comment]
>  I would use something like the test name as the prefix, which is known to be unique. I can do that change, if you wish.

This solution you proposed looks fine to me, and should solve our problem.

**Comment by mvdan** [comment]
> I'd first like input from @lonelycode as to whether the keys are repeated or not.

Just in case there's already something in place for this that we've both missed :)

**Comment by buger** [comment]
If you look at the used keys, they are like "zxczxc" or "56423". So I'm sure he have no clue either :)

Even if current keys does not conflict, we can't rely on it in new tests.

**Comment by lonelycode** [comment]
As far as I can remember the keys are not reused between tests (or they shouldn't be), in some other tests I think we started adding random numbers.

**Comment by mvdan** [comment]
@lonelycode thanks, what I'll do is make key prefixes unique.

Unfortunately this will come with 1.8: https://tip.golang.org/pkg/testing/#T.Name

Will pick this up in a couple of days once it's released.

**Comment by lonelycode** [comment]
sgtm

**Comment by mvdan** [comment]
Unfortunately, 1.8 has been delayed by two weeks. So delaying this PR further.

**Comment by buger** [comment]
Even when 1.8 get's released how you gonna keep compatibility between 1.7 and 1.8, assuming that we not going to ship tyk with 1.8 until there will be at least few patch releases?

**Comment by mvdan** [comment]
@buger I can implement the helper func (the one that sets up the prefixes) twice, with test names for 1.8+ and with a random string pre-1.8. This way we can assure no failures going forward. We'll have to live with the potential collisions until we drop support for 1.7, but should be fine as long as the strings are long enough.

Then again, I can implement this right now, no need to wait for 1.8.

**Comment by buger** [comment]
👍

**Comment by mvdan** [comment]
I need to send other incremental patches first, so will redo this PR from scratch.

**Pull request closed without merging**
