### PR TITLE
TT-1740 Adding fallback scenario for ctx Get Apidef and Session

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

Adding a fallback scenario to avoid panics in plugin developments where the plugin compiler has missversion. 
This 

## Related Issue

https://tyktech.atlassian.net/browse/TT-1740
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3875/merge
Commit:  
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1806338562)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3875/merge
Commit: 81b6c727bed8d0d71ee4b726204e79b841d700de 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1806377886)

**Comment by sredxny** [comment]
@tbuchaillot if this doesn't panic how will the user know that its a compiler version issue?does this display any log?

**Comment by tbuchaillot** [comment]
> @tbuchaillot if this doesn't panic how will the user know that its a compiler version issue?does this display any log?

@sredxny I added a log but it shouldn't happen. It's just a fallback scenario based on https://github.com/TykTechnologies/tyk/issues/3612#issuecomment-879307077 workaround for when this error was present.
The original issue was solved in #3750 and #3820

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3875/merge
Commit: 96ebee6f1dc0deb4b60b6ddc44b3ac978e58a203 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1817947347)

**Review by sredxny — APPROVED** [review]
lgtm

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3875/merge
Commit: b3a90b40d343ed8d3310860a9a2cdef011ade2a7 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1830226722)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3875/merge
Commit: 5ccee19f547e271c3eb0d85047c474d89caf78b5 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1846336529)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3875/merge
Commit: 5ccee19f547e271c3eb0d85047c474d89caf78b5 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1846336529)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3875/merge
Commit: 5ccee19f547e271c3eb0d85047c474d89caf78b5 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1846336529)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3875/merge
Commit: d9c25176a5e4fcc6219a9c5dd9b3a67153386a8d 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1851934808)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 44d50ebeef73dfcd351a30551d23e99719770263 TT-1740 Adding fallback scenario for ctx Get Apidef and Session (#3875)

* adding fallback scenario for missversions in ctx Apidef and Session

* Adding test to check go plugin API ctx

* adding log in unmarshalling
Triggered by: push (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1852323175)

**Pull request merged**
