### PR TITLE
[SYSE-307] go 1.21 upgrade caused glibc errors on older distros

### PR DESCRIPTION
**Pull request by alephnull**
Use 1.21-bullseye for builds. Images use bookworm as the starting point.
Removed unused grpc and protobuf python libs.
Repo policy updated with 1.21-bullseye as the required test.

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: failure** :no_entry_sign: 
Branch used: refs/pull/5868/merge
Commit:  
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7206794109)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5868/merge
Commit: 0523c6919ce859c5b7ca60c95c42f092ac318700 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7206860149)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5868/merge
Commit: 0523c6919ce859c5b7ca60c95c42f092ac318700 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7206860149)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5868/merge
Commit:  
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7206793942)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5868/merge
Commit: 0523c6919ce859c5b7ca60c95c42f092ac318700 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7206860065)

**Review by titpetric — APPROVED** [review]

**Review by ermirizio — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5868/merge
Commit: 4cd173c381511ae4951b7b3a3b8273a966fa5987 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7212294389)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5868/merge
Commit: 45fd2d9a42dbdcb31f85ca9f8dcd50576db51bde 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7212774815)

**Pull request merged**
