### PR TITLE
[TD-959]: Add automation for running go mod tidy in release branches.

### PR DESCRIPTION
**Pull request by asutosh**
## Description
Add a GHA  workflow that will update go.mod and go.sum after running `go mod tidy`
on the current release branches.

## Related Issue
TD-959

## Motivation and Context
More details are in the associated issue.

## How This Has Been Tested
Can be tested once it's approved and merged to the appropriate release branches, and a commit is pushed to these
branches.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3999/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2110384832)

**Review by ermirizio — APPROVED** [review]
Changes looks good, we have discussed with @asutosh arround raising awareness of this workflow which will make commits into release branches automatically. This is important to realize when tagging. Just make sure devs understand this workflow could eventually "patch" a release branch when porting. So at the time of tag lets make sure we tag over the new patched commit if that situation happens.
Some automation can be built arround this but, may better leave it as it is for now until we experience a lil bit more into this

**Review by alephnull — COMMENTED** [review]
I have a philosophical objection to such automation. This is better served by a pre-commit hook.

**Comment by ermirizio** [comment]
@alephnull we did consider the pre-hook option, but this won't work in case the release but (/release command) is used to port changes to a release branch. Unless there's a way to configure the bot to call the pre-commit hook. Also I'm concerned that hooks are not enforceable ( on non enterprise gh orgs) , so we'll need to trust on ppl goodwill and memory.
I would say lets create the pre-commit web-hook script as main tool but leave the workflow as fallback mechanism

**Comment by alephnull** [comment]
My point is that it is too late to run such basic things after cherry picking a commit to a release branch.

**Pull request closed without merging**
