### PR TITLE
TT-3705 Adding OMITCONFIGFILE env

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

Added a new config option and a check for <DEFAULT_PREFIX>_OMITCONFIGFILE in order to avoid the content of the config file.

https://tyktech.atlassian.net/browse/TT-3705

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3874/merge
Commit:  
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1805737361)

**Review by matiasinsaurralde — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 3b76adb36499c52cdca289dd0cba4046db1ca6dd adding _OMITCONFIGFILE config (#3874)
Triggered by: push (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1846327335)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 3b76adb36499c52cdca289dd0cba4046db1ca6dd adding _OMITCONFIGFILE config (#3874)
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1846327335)

**Pull request merged**
