### PR TITLE
[TT-3668] Build go plugin from dynamically generated directory 

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description
While building multiple go plugin using tyk-plugin-compiler, the build path for plugin remains the same which causes Go to return error `plugin already loaded`. This PR makes it such that the build path will be a dynamically generated directory inside GOPATH.

### CODE REVIEW

**Review by matiasinsaurralde — APPROVED** [review]
Looks good to me, this is a replacement for the `pluginpath` approach we were previously using.
Randomizing the build path shouldn't affect the plugin compile flow.

**Review by vaske — APPROVED** [review]
ship it 🚀

**Review by furkansenharputlu — APPROVED** [review]

**Review by alephnull — COMMENTED** [review]
Please merge this PR _after_ https://github.com/TykTechnologies/tyk/pull/3749

-For complete context, https://github.com/TykTechnologies/tyk/commit/b638cf3aa4f3c4c3953344de69fda962c01832bb#diff-eab9ce931973d7e6a000ccbd3dd3037310f38c30328dcd4846ac9449c10cc7df had a similar fix using `-pluginpath`, this was removed in https://github.com/TykTechnologies/tyk/commit/415abf8df69c508d23b881c1f07bb789c2e95ab0#diff-eab9ce931973d7e6a000ccbd3dd3037310f38c30328dcd4846ac9449c10cc7df as it didn't work for the latest 1.12 (still needed for LTS)

Does the smoke-test in https://github.com/TykTechnologies/tyk/tree/master/integration/smoke-tests/plugin-compiler pass with your change currently?

**Comment by buger** [comment]
Pls check my Jira comment first.

**Review by alephnull — CHANGES_REQUESTED** [review]
The smoke tests are run in automation by https://github.com/TykTechnologies/tyk/blob/master/.github/workflows/release.yml#L320-L347

The design is for each test to have its own directory and for each test to be independent of the others. The current implementation adds its test in `integration/smoke-tests/plugin-compiler` but I feel it should be in `integration/smoke-tests/plugin-aliasing`.

The reasons for asking for this is to separate the implementation of tests so that they are clear. 

Please also add some further text to https://github.com/TykTechnologies/tyk/blob/master/integration/smoke-tests/README.md describing the behaviour that is being tested. Right now it talks about OAuth2 and doesn't really make clear that the behaviour being tested is that of one plugin file being loaded in multiple APIs.

**Review by alephnull — APPROVED** [review]

**Pull request merged**
