### PR TITLE
[TT-4667] Remove fields that are related to the pump not the gateway

### LINKED ISSUE #3906: [TT-4667] Wrong config fields were added to tyk.conf example files
The following fields were added to the files tyk.conf , tyk.conf.example and maybe more in tyk repo and same for to tyk-gateway-docker 

```
"type": "csv",
"csv_dir": "/tmp",
"mongo_url": "",
"mongo_db_name": "",
"mongo_collection": "",
"purge_delay": -1,
```

1. `type` - can be either `rpc` or `anything else`. Better to put an empty string""
2. `csv_dir` and `mongo_*` - don’t exists (probably were copied from the pump by mistake)
3. `purge_delay` - doesn’t exists (probably were copied from the pump by mistake). Should be `purge_interval` - 

It’s important to first remove this just to avoid confusion for our users.

### PR DESCRIPTION
**Pull request by letzya**
## Description
1. fix #3906 - 
2. Fix description in policies new fields.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3907/merge
Commit:  
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1899350741)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3907/merge
Commit: 9c1684a819e226e8de5260d1fd2d2d20188f5782 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1899678173)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3907/merge
Commit: 934911a76ebeb10b64fd571b3e8a8da5e8fdc5d6 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1945428889)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by agata-wit** [comment]
@furkansenharputlu could you approve this quickly? Seems like an easy one.

**Review by furkansenharputlu — APPROVED** [review]

**Comment by agata-wit** [comment]
@letzya I think this is ready to merge, right?

**Review by armujahid — APPROVED** [review]

**Comment by armujahid** [comment]
Another instance of incorrect `analytics_config.tyk` value is https://github.com/TykTechnologies/tyk/blob/master/ci/tests/python-plugins/src/tyk.conf#L42 (it should either be empty string or rpc).

Other that that I think this is ready to merge.

Reference: `AnalyticsConfigConfig` https://github.com/TykTechnologies/tyk/blob/master/config/config.go#L166

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3907/merge
Commit: 26c0be4e57ae528f9a5a797795c1f785052b04cf 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3574313474)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3907/merge
Commit: ec4d7373425159e904d0c4ad45a3b6afcf5c1527 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3608601771)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3907/merge
Commit: 5f2209287d4bfc3f2787f8c2a8adb6492cc18f65 
Triggered by: pull_request (@letzya)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6076700758)

**Pull request merged**
