### PR TITLE
Add request URI to middleware request object

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
I've added the field to the request object (and not the CP object) so that it looks like what's implemented in #1352 for JSVM.
Let's merge this after #1386.

Note: the field that's generated by the Go generator would look better as `RequestURI` instead of `RequestUri` but I prefer to keep the generator output as is. Feedback appreciated.

### CODE REVIEW

**Comment by buger** [comment]
@matiasinsaurralde  HTTP method merged, ready to be rebased

**Comment by matiasinsaurralde** [comment]
Thanks

**Comment by matiasinsaurralde** [comment]
Updated!

**Comment by buger** [comment]
Merged manually d1e10cfcb290318c617fed827d9c463eb0ae86af

**Pull request closed without merging**
