### PR TITLE
bug: uptime tests respect proxy_ssl_insecure_skip_verify

### LINKED ISSUE #1412: Upstream health checks should respect `proxy_ssl_insecure_skip_verify`
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
If upstream is secured with self-signed https certificate, all health checks will fail because of insecure certificate error
**What is the expected behavior?**
It should respect `proxy_ssl_insecure_skip_verify` configuration option, and if set, allow self-signed certificates
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Configure HTTPS protected upstream, set `proxy_ssl_insecure_skip_verify` to true, and try to configure upstream health checks
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
all

### PR DESCRIPTION
**Pull request by asoorm**
fixes #1412

If upstream is secured with self-signed https certificate, all health
checks will fail because of insecure certificate error

`WARN host-check-mgr: [HOST CHECKER MANAGER] Host is
DOWN: https://test.server:8000/hello`

`CheckHost` function modified to set the `HostCheckerClient` transport
configuration appropriately. This is suitable for both http & https
hosts.

lint: using http constants & camelCase rather than snake_case vars

### CODE REVIEW

**Comment by matiasinsaurralde** [comment]
LGTM

**Comment by buger** [comment]
We can do even more, and support Mutual TLS certificates here too. 

See @joshblakeley PR, he implemented similar for BathRequest function https://github.com/TykTechnologies/tyk/pull/1471

**Comment by buger** [comment]
Well it is a bug too, since if your API protected by mutual TLS, and you configured certificate inside tyk, the gateway will proxy request to API without any issues, but uptime check will fail because it ignore certificates. 

So I propose just include into the same PR.

**Comment by asoorm** [comment]
cool - will work on today

**Comment by buger** [comment]
Lets merge it like this, and will add certificate functionality if someone will complain. 

Host checker is deprecated anyway.

**Pull request merged**
