### PR TITLE
Test all build tag combinations on CI

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
Travis, wake the fuck up.

**Comment by mvdan** [comment]
@matiasinsaurralde as we discussed, this only tests their builds.

PTAL @buger @lonelycode

**Comment by mvdan** [comment]
Also note that this only includes the build dependencies, not the runtime ones. If we ever need to run any python or lua as part of the coprocess tests, we'll need more packages.

**Comment by buger** [comment]
I think it should be a good start for now 👍

**Pull request merged**
