### PR TITLE
remove the replace directive for gorm in go modules file

### PR DESCRIPTION
**Pull request by sredxny**
## Description
Removed the `replace` directiv for gorm

## How This Has Been Tested
- Build gateway

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4296/merge
Commit: c24f24ff8af03c4f9485d2d256b4d9d5a3c55c62 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3038785522)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4296/merge
Commit: ac9a3104c1ee2edbeff2fdc5a1d778edea27c86f 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3038789545)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4296/merge
Commit: 2236e0230a17a2fd75a1cccd268d5820d09d9ebe 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3038812400)

**Review by tbuchaillot — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4296/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3038770488)

**Comment by sredxny** [comment]
@buger should we merge it?

**Pull request closed without merging**
