### PR TITLE
[TT-7399] Add possibility to add oAuth client tags to session tags

### PR DESCRIPTION
**Pull request by buger**
This can allow generating custom analytics dimensions, because each tag generate own dimension. 

For example as a Portal, it can create oAuth clients which contain "tags" string array inside oAuth client object, which contains values like: `["portal-team-<teamId>", "portal-org-<orgId>", "portal-dev-<devId>"]`. For each of those tags pump will generate a separate analytics dimension.

JIRA: https://tyktech.atlassian.net/browse/TT-7399

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4658/merge
Commit:  
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3939313033)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4658/merge
Commit: 3d64c3a44693a2b18e05c78860b4df84d4e328a4 
Triggered by: pull_request (@padiazg)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4065806949)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4658/merge
Commit: f5d7a952b958d04d4034ce33229c13bc0c60109d 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4895258058)

**Review by titpetric — DISMISSED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4658/merge
Commit: 8b535ce4193cdc99021229195cb087b49de666a2 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5269421833)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4658/merge
Commit: c24e3522aa0b91e21c22c6bbb4a20b2053b01b11 
Triggered by: pull_request (@MFCaballero)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5314513798)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4658/merge
Commit: 98d8d5bbe9855b5f4a6bf15f035cf83acf8a6d64 
Triggered by: pull_request (@padiazg)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5726709957)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4658/merge
Commit: 9d43b9f353e3295e0cf033617da8efb89e360f7b 
Triggered by: pull_request (@MFCaballero)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5820639526)

**Review by titpetric — COMMENTED** [review]
Make sure to add a unit test covering the additions. Restructure to smaller functions to keep tight test scope

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4658/merge
Commit: ee110e27557dfbe9badad46cd02fb0d60bbd107b 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5830425806)

**Review by titpetric — APPROVED** [review]
LGTM

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4658/merge
Commit: 057c0964d32a73690e7aa80365307b054471a06f 
Triggered by: pull_request (@padiazg)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5835847165)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4658/merge
Commit: d750de381b742c4951e43de0c1612fd9433255e8 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5835883208)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4658/merge
Commit: bba7e0088d74b75d881d76408ed40ac74ad54389 
Triggered by: pull_request (@padiazg)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5836241600)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4658/merge
Commit: 78a39574a00d800d2d210b86dc61fca39ea037bd 
Triggered by: pull_request (@padiazg)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5836230535)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4658/merge
Commit: e73fd21659fefb57e1ea345497096cb3f97101b1 
Triggered by: pull_request (@padiazg)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5836346872)

**Pull request merged**
