### PR TITLE
[TT-9987] [4.0.8.4] plugin compiler cves

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description
fix plugin compiler CVEs.
not fixing the remaining ones since they're with glibc and stdlib.

## Related Issue
https://tyktech.atlassian.net/browse/TT-9987
## Screenshots (if appropriate)
Screenshot 2023-10-02 at 10 38 37 AM
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6355243668)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6355243668)

**Review by titpetric — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6355243668)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.8.4
Commit: c0085beb268064c641b0562827216957b0a1effd 
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6389202818)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit: 6a8a5d9f09df74ea78711ad7eb3ad7f62162b43e 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6389346548)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit: 8007e5714ad86f50c2d4065c13543c1ce5277648 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6389624662)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit: c4ca81c6c46367f1ae860dd2dcc109413c2e8d7d 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6389708828)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit: 00737acf41f6c46ecb446c03fd4487dabbb1d3e3 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6389846843)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit: e31d702f3e342181bbace83e759321a3404ec4a6 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6390035519)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit: e31d702f3e342181bbace83e759321a3404ec4a6 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6390035519)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5573/merge
Commit: a5f30b86a8a21b3aa850aebd3795bfeadfe683f2 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6390328283)

**Comment by titpetric** [comment]
Closing in favor of #5586

**Pull request closed without merging**
