### PR TITLE
Notify dashboard whenever monitor for a key quota limit kicks in

### PR DESCRIPTION
**Pull request by adelowo**
Per discussion in https://github.com/TykTechnologies/tyk-analytics/issues/1013

~~Will send the PR for the dashboard in the appropriate repository~~ See https://github.com/TykTechnologies/tyk-analytics/pull/1186

### CODE REVIEW

**Comment by buger** [comment]
I think we need it more general purpose, to accept multiple event types.

**Comment by lghiur** [comment]
Can we integrate this somehow with analyitics? So we can maybe highlight it on the charts?

**Comment by buger** [comment]
So far I do not know how to do that. It will require some separate "events" collection, which can be mapped to existing analytics data.

**Comment by buger** [comment]
@lghiur it should for sure be logged to Audit. So when we integrate Audit to the dashboard and expose this thing to UI by default, events should be available there as well.

**Comment by buger** [comment]
@lghiur https://github.com/TykTechnologies/tyk-analytics/issues/344

**Comment by adelowo** [comment]
> I think we need it more general purpose, to accept multiple event types.

Done in https://github.com/TykTechnologies/tyk/pull/2134/commits/f458e8bc0148e7ac0d767473ac268657add280da

**Comment by adelowo** [comment]
I figured out that this webhook only returned the trigger limit not the usage of the API key, I have updated it to also contain usage percentage as it makes much more sense if the dashboard sends an email with the actual usage percentage

**Comment by buger** [comment]
Pls rebase and can be merged

**Pull request merged**
