### PR TITLE
[TT-13439] update response content-length when response body is modified by coprocess response hook

### PR DESCRIPTION
**Pull request by jeffy-mathew**
### **User description**
<details open>
  <summary><a href="https://tyktech.atlassian.net/browse/TT-13439" title="TT-13439" target="_blank">TT-13439</a></summary>
  <br />
  <table>
    <tr>
      <th>Summary</th>
      <td>Analytics data is corrupted when a response plugin changes the response</td>
    </tr>
    <tr>
      <th>Type</th>
      <td>
        Bug
        Bug
      </td>
    </tr>
    <tr>
      <th>Status</th>
      <td>In Dev</td>
    </tr>
    <tr>
      <th>Points</th>
      <td>N/A</td>
    </tr>
    <tr>
      <th>Labels</th>
      <td><a href="https://tyktech.atlassian.net/issues?jql=project%20%3D%20TT%20AND%20labels%20%3D%20'24Bugsmash%20ORDER%20BY%20created%20DESC" title="'24Bugsmash">'24Bugsmash</a>, <a href="https://tyktech.atlassian.net/issues?jql=project%20%3D%20TT%20AND%20labels%20%3D%20customer_bug%20ORDER%20BY%20created%20DESC" title="customer_bug">customer_bug</a>, <a href="https://tyktech.atlassian.net/issues?jql=project%20%3D%20TT%20AND%20labels%20%3D%20jira_escalated%20ORDER%20BY%20created%20DESC" title="jira_escalated">jira_escalated</a></td>
    </tr>
  </table>
</details>

---

## Related Issue
https://tyktech.atlassian.net/browse/TT-13439

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

___

### **PR Type**
Bug fix, Tests

___

### **Description**
- Fixed a bug where the `Content-Length` header was not updated when the response body was modified by a coprocess response hook.
- Updated the `HandleResponse` function to set the `Content-Length` header based on the size of the modified response body.
- Enhanced test cases to verify that the `Content-Length` header matches the length of the modified response body.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>coprocess_grpc_test.go</strong><dd><code>Update test case to verify Content-Length header</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

coprocess/grpc/coprocess_grpc_test.go

<li>Added import for <code>strconv</code> package.<br> <li> Added import for <code>header</code> package.<br> <li> Updated test case to match <code>Content-Length</code> header.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6732/files#diff-c5b0bcf682a084942dee611f5b6c7ff202dd49424b90d39658c4634f0422064a">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>coprocess.go</strong><dd><code>Update Content-Length header for modified response body</code>&nbsp; &nbsp; </dd></summary>
<hr>

gateway/coprocess.go

<li>Set response body length in response object.<br> <li> Updated <code>Content-Length</code> header based on modified response body.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6732/files#diff-9cbfe628982b2afb94d1e9a5200fc9a4fdc00cb58fe65d1090a3725e4e4c5953">+6/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by buger** [comment]
<p>
    Let's make that PR title a 💯 shall we? 💪
    </p>
    <p>
    Your <em>PR title</em> and <em>story title</em> look <strong>slightly different</strong>. Just checking in to know if it was intentional!
    </p>
    <table>
      <tr>
        <th>Story Title</th>
        <td>Analytics data is corrupted when a response plugin changes the response</td>
      </tr>
      <tr>
          <th>PR Title</th>
          <td>[TT-13439] update response content-length when response body is updated by coprocess response hook</td>
        </tr>
    </table>
    <p>
      Check out this <a href="https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests">guide</a> to learn more about PR best-practices.
    </p>

**Review by andrei-tyk — APPROVED** [review]

**Pull request merged**
