### PR TITLE
[TT-9169/TT-9186] Add config disable_key_actions_by_username to disable key actions by username

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description
Add config disable_key_actions_by_username to disable key actions by username.

## Related Issue
https://tyktech.atlassian.net/browse/TT-9186

## Motivation and Context

For more context, refer https://tyktech.atlassian.net/browse/TT-9169

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5165/merge
Commit: 0744bd26369c2921cbbfd5d635e9b37733b5707f 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5318265808)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5165/merge
Commit: 49f30fd37a14685a9b2d13efc212150a5f39467b 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5318594806)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5165/merge
Commit: 9156bc617ea39c4c62faa0cf8cd00d596c72cc91 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5325765513)

**Review by titpetric — APPROVED** [review]

**Pull request merged**
