### PR TITLE
TT-10962

### PR DESCRIPTION
**Pull request by kofoworola**
## Description
[TT-10962](https://tyktech.atlassian.net/browse/TT-10962)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

[TT-10962]: https://tyktech.atlassian.net/browse/TT-10962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

## **Type**
bug_fix

___

## **Description**
- Disabled the `EnableSingleFlight` feature in both `ProxyOnly` and `UniversalDataGraph` adapters to address existing issues.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>adapter_proxy_only.go</strong><dd><code>Disable SingleFlight in ProxyOnly Adapter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/adapter/gqlengineadapter/adapter_proxy_only.go
<li>Disabled <code>EnableSingleFlight</code> feature by setting its value to <code>false</code>.<br>

</details>
    

  </td>
  <td><a href="https:/TykTechnologies/tyk/pull/6072/files#diff-c3d2491b83997adf408861dc51e396c95e2baabba8286309f5c344cfcee7d78b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>adapter_udg.go</strong><dd><code>Disable SingleFlight in UniversalDataGraph Adapter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/adapter/gqlengineadapter/adapter_udg.go
<li>Disabled <code>EnableSingleFlight</code> feature by setting its value to <code>false</code>.<br>

</details>
    

  </td>
  <td><a href="https:/TykTechnologies/tyk/pull/6072/files#diff-f01b6f97ed0e7bbe78b66c8d0c5e34fbabf49683a4a0784f7b25ebaabe97c03b">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6072/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8050049826)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6072/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8050049826)

**Review by buraksezer — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 9ed401d9a82f3df1f86da94d9b642f542bc10402 TT-10962 (#6072)

## **User description**


## Description
[TT-10962](https://tyktech.atlassian.net/browse/TT-10962)



## Related Issue






## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why


[TT-10962]:
https://tyktech.atlassian.net/browse/TT-10962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ


___

## **Type**
bug_fix


___

## **Description**
- Disabled the `EnableSingleFlight` feature in both `ProxyOnly` and
`UniversalDataGraph` adapters to address existing issues.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Bug
fix</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>adapter_proxy_only.go</strong><dd><code>Disable
SingleFlight in ProxyOnly Adapter</code>&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; </dd></summary>
<hr>

apidef/adapter/gqlengineadapter/adapter_proxy_only.go
<li>Disabled <code>EnableSingleFlight</code> feature by setting its
value to <code>false</code>.<br>


</details>
    

  </td>
<td><a
href="https:/TykTechnologies/tyk/pull/6072/files#diff-c3d2491b83997adf408861dc51e396c95e2baabba8286309f5c344cfcee7d78b">+1/-1</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>adapter_udg.go</strong><dd><code>Disable SingleFlight
in UniversalDataGraph Adapter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; </dd></summary>
<hr>

apidef/adapter/gqlengineadapter/adapter_udg.go
<li>Disabled <code>EnableSingleFlight</code> feature by setting its
value to <code>false</code>.<br>


</details>
    

  </td>
<td><a
href="https:/TykTechnologies/tyk/pull/6072/files#diff-f01b6f97ed0e7bbe78b66c8d0c5e34fbabf49683a4a0784f7b25ebaabe97c03b">+1/-1</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions

Co-authored-by: Shakira Salazar <69164527+rhianeKobar@users.noreply.github.com>
Triggered by: push (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8108880368)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 9ed401d9a82f3df1f86da94d9b642f542bc10402 TT-10962 (#6072)

## **User description**


## Description
[TT-10962](https://tyktech.atlassian.net/browse/TT-10962)



## Related Issue






## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why


[TT-10962]:
https://tyktech.atlassian.net/browse/TT-10962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ


___

## **Type**
bug_fix


___

## **Description**
- Disabled the `EnableSingleFlight` feature in both `ProxyOnly` and
`UniversalDataGraph` adapters to address existing issues.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Bug
fix</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>adapter_proxy_only.go</strong><dd><code>Disable
SingleFlight in ProxyOnly Adapter</code>&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; </dd></summary>
<hr>

apidef/adapter/gqlengineadapter/adapter_proxy_only.go
<li>Disabled <code>EnableSingleFlight</code> feature by setting its
value to <code>false</code>.<br>


</details>
    

  </td>
<td><a
href="https:/TykTechnologies/tyk/pull/6072/files#diff-c3d2491b83997adf408861dc51e396c95e2baabba8286309f5c344cfcee7d78b">+1/-1</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>adapter_udg.go</strong><dd><code>Disable SingleFlight
in UniversalDataGraph Adapter</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; </dd></summary>
<hr>

apidef/adapter/gqlengineadapter/adapter_udg.go
<li>Disabled <code>EnableSingleFlight</code> feature by setting its
value to <code>false</code>.<br>


</details>
    

  </td>
<td><a
href="https:/TykTechnologies/tyk/pull/6072/files#diff-f01b6f97ed0e7bbe78b66c8d0c5e34fbabf49683a4a0784f7b25ebaabe97c03b">+1/-1</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions

Co-authored-by: Shakira Salazar <69164527+rhianeKobar@users.noreply.github.com>
Triggered by: push (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8108880368)

**Pull request merged**
