### PR TITLE
[TT-10838] Reorder config load to happen before gateway is used/referenced

### PR DESCRIPTION
**Pull request by titpetric**
This PR reorders the config.Load to happen when we create a gateway instance. Previously, the `config.Default` value was being passed, and the configuration was loaded later on in `initialiseSystem`. The change enables referencing a valid gateway configuration from the services declared in NewGateway() and elsewhere.

Moved config logic into cli/ where it belongs.

https://tyktech.atlassian.net/browse/TT-10838

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5889/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7261327246)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5889/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7261327246)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5889/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7261327246)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5889/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7261327246)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7261327211)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: f678fd1c62918bef3f28c4b5f816eb1f5c10e482 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7262940122)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: 84d830befcb5d53e943d2ab9da57cac4dc32e6e0 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7264879201)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: f3023e0baf855022693448ba2e16b1ed675e5b4b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7274318571)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: d86c7259064ac7ad571b63f25e11b182ee750648 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7274795949)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: 953a60878f5f9f64550e6e41b835626bc6b65097 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7275376834)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: 673a0428b8ce1489ed406f797f2fee691d94a247 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7287494833)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: 629a970854d02d03784a0d42c80cc25ef671d09a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7288168872)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: dc691fbb71ef68e41ffbb086af13f6e849d79870 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7288312428)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: ee42812b1a7b62f0f749efb4921cd2f01e621fb8 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7288928423)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: bad0aa3f0864e48bf5f2e5064085e6d3608d64cd 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7288954199)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: c72b1d3031b22ca90d04d83be85dfc821a0625a8 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7289359302)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5889/merge
Commit: b67674deb0a7b3417ab01ba863e06b62d4c4f39a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7289886513)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: a2886051399ba430f41f04c8cbb4ff7f7b34fd5f 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7289932176)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: 055ada57f94802c9416559a2b1495fc338c8fb7a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7290085074)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: 215fe37ffa27071c7131703d2824e8c60d0759b9 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7291013077)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5889/merge
Commit: af69104f6b1b15909580a7aa4a5d65bffe82b037 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7291157046)

**Review by alephnull — COMMENTED** [review]
lgrm

**Pull request closed without merging**
