### PR TITLE
exit CI when gofmt is not clean

### PR DESCRIPTION
**Pull request by jeffy-mathew**
[changelog]
fixed: exit CI when gofmt returns non empty file list

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3946/merge
Commit: 2eb1b52e66e302d26904867bc19a36ed342ad580 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1999584850)

**Review by alephnull — APPROVED** [review]

**Review by tbuchaillot — APPROVED** [review]
Nice one!

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: ac80321b679dc4754dee3b11d9c98dd2f95955c0 exit CI when gofmt is not clean (#3946)

go fmt existing files
[changelog]
fixed: exit CI when gofmt returns non empty file list
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2002102744)

**Pull request merged**
