### PR TITLE
[TT-7383] Return base api id in versioned api get

### PR DESCRIPTION
**Pull request by furkansenharputlu**
https://tyktech.atlassian.net/browse/TT-7383

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4543/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3713477054)

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4543/merge
Commit: 30d5ce2e6285fb360cc041423ee410870f3cb57b 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3713636665)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4543/merge
Commit: 6f5486a4b54fb3fec6ad7beaf6039793d6dac9e7 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3713750664)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: b488b70752a69b073b2c47acf78eb9ecc4ead081 [TT-7383] Return base api id in versioned api get (#4543)

https://tyktech.atlassian.net/browse/TT-7383
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3715414813)

**Pull request merged**
