### PR TITLE
Merging to release-5-lts: [TT-5012] add schema pattern for domain name validation (#5975)

### PR DESCRIPTION
**Pull request by buger**
[TT-5012] add schema pattern for domain name validation (#5975)

[TT-5012]: https://tyktech.atlassian.net/browse/TT-5012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/6010/merge
Commit:  
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7738976802)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/6010/merge
Commit: f447474996fc1f725ca195bf05ca6d676b9d8ead 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7739008195)

**Review by furkansenharputlu — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/heads/release-5-lts
Commit: 4cd1c5f1a6d41fe63472f063b8b70430f4a186f8 Merging to release-5-lts: [TT-5012] add schema pattern for domain name validation (#5975) (#6010)

[TT-5012] add schema pattern for domain name validation (#5975)

[TT-5012]:
https://tyktech.atlassian.net/browse/TT-5012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Co-authored-by: Jeffy Mathew <jeffy.mathew100@gmail.com>
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7742353249)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/heads/release-5-lts
Commit: 4cd1c5f1a6d41fe63472f063b8b70430f4a186f8 Merging to release-5-lts: [TT-5012] add schema pattern for domain name validation (#5975) (#6010)

[TT-5012] add schema pattern for domain name validation (#5975)

[TT-5012]:
https://tyktech.atlassian.net/browse/TT-5012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Co-authored-by: Jeffy Mathew <jeffy.mathew100@gmail.com>
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7742353249)

**Pull request merged**
