### PR TITLE
[TT-959] Initial DCR changes

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Depends on dashboard PR https://github.com/TykTechnologies/tyk-analytics/pull/2181/files
- Adds a flag for skipping SSL verification on JWT secret URLs (useful for testing).
- Tweak OAuth client creation to handle the scenario on JWT enabled APIs.

### CODE REVIEW

**Comment by buger** [comment]
Tests are failing with:
>        jwt_ssl_insecure_skip_verify: Additional property jwt_ssl_insecure_skip_verify is not allowed

**Comment by matiasinsaurralde** [comment]
> jwt_ssl_insecure_skip_verify

@buger Have updated the linter

**Pull request merged**
