### PR TITLE
Un-fork logrus, vendor stable versions of its pkgs

### PR DESCRIPTION
**Pull request by mvdan**
The reason why we forked all of these libs is because of the Sirupsen vs
sirupsen (case sensitive) issue. But we are immune to those issues if we
vendor all the libs and we're careful when updating them.

Moreover, we were running HEAD versions of all these libs. Use the latest
stable version of all of them as of March 2017.

### CODE REVIEW

**Comment by mvdan** [comment]
I realise this is a bit of a mindfuck at the moment - it was tricky to do too - but I think this is important and should simplify things going forward. Keeping our own forks is not sustainable and adds quite a lot of complexity.

And, as said above, keeping our own forks doesn't really help us in any way.

**Comment by lonelycode** [comment]
So, the question is, at any point were any of the forks modified or touched? I can't remember messing with any, but might be worth confirming first.

**Comment by buger** [comment]
bump

**Comment by mvdan** [comment]
Nothing to do - this is on hold until the security releases are out.

**Comment by mvdan** [comment]
Confirming that the only changes we ever did to all of those libs was just replace `foo/*` with `TykTechnologies/*` in the imports.

Rebased on master. @buger PTAL

**Pull request merged**
