### PR TITLE
[TT-7414] Call ApplyPolicies after go plugin

### PR DESCRIPTION
**Pull request by furkansenharputlu**
Jira ticket: https://tyktech.atlassian.net/browse/TT-7414

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5642/merge
Commit: d928229889f581a56cbfd7ef802d0551a29f8d09 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6564182759)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5642/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6564150638)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5642/merge
Commit: 956a577ea66064a31f081668caa60d79f1b8b7a3 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6603357855)

**Review by titpetric — APPROVED** [review]

**Pull request merged**
