### PR TITLE
[TT-376] Import swagger paths in old whitelist format + track endpoint

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR adds track endpoint as another default plugin for imported swagger documentation paths along with whitelist plugin. Note that this PR uses old whitelist configuration. The new configuration will be released with version 5 and in that version the import functionality will have more features and for that reason the new import functionality will be implemented separately. This is for old APIs before OAS features.

### CODE REVIEW

**Comment by joshblakeley** [comment]
Needs to be optional with some flag otherwise it's a breaking change ? - track endpoint should stay also

**Comment by furkansenharputlu** [comment]
@joshblakeley We change behavior but we don't break anything, we don't change already imported APIs.

**Comment by agata-wit** [comment]
@buger @joshblakeley @lghiur have any of you had a change to progress with this??

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3844/merge
Commit: 0bb1bdceae9abb9e4867f946961817b92d41c428 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1740316409)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3844/merge
Commit: fc3670a0752ac225469f3af9db5bb8f87b9720ba 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1740333445)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3844/merge
Commit: 57e8d918a48904ae307bb921942301f1ed045868 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1740443142)

**Review by vaske — APPROVED** [review]

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3844/merge
Commit: 714d228c22c9485f6994df12438ca944ab3ed680 
Triggered by: pull_request (@vaske)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1744520860)

**Review by urbanishimwe — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: d3b082458c9af2a9e1c15784e1dc851f12706763 [TT-376] Import swagger paths in old whitelist format + track endpoint (#3844)

* Import swagger paths in old whitelist format instead of track endpoint

* Add trackendpoint too

Co-authored-by: Milan Vasic <milan.vasic.su@gmail.com>
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1745186807)

**Pull request merged**
