### PR TITLE
TT-6407 Edge key quota reset bugfix

### PR DESCRIPTION
**Pull request by sredxny**
## Description
In worker gateways when a key is recreated we should not always remove the quota, we should preserve the quota locally if quotaReset=0 and remove it if quotaReset=1, hence in this PR we validate that while removing the key. When worker gateways receive a signal that a key has been updated this is what is done:

- remove the key locally 
- Pull new version of the key

In the first step we were removing the quota everytime (in non hashed environments) so now we check based on the flag. Also added unit tests that cover hashed and non hashed envs 

## Related Issue
https://tyktech.atlassian.net/browse/TT-6407

## Motivation and Context
Give solution to https://tyktech.atlassian.net/browse/TT-6407

## How This Has Been Tested
- Added unit tests, but also:
- Run an MDCB env.
- Create an API with standard token, assigning a quota directly to the key
- Consume the API using the key, so as to use up some of the quota
- Search for the un-hashed key in the Dashboard
- Update any value and save by clicking "Update without quota reset"
- Check the Redis in the worker node: you will see that the quota is not reseted

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4300/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3049660548)

**Review by tbuchaillot — APPROVED** [review]
LGTM 👌

**Review by mativm02 — APPROVED** [review]
lgtm

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4300/merge
Commit: a8dc13ac65503bc7966e52b8b458edf8253f6134 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3058815114)

**Comment by buger** [comment]
**API tests result: cancelled** :no_entry_sign: 
Branch used: refs/pull/4300/merge
Commit: 5bca11094bb21bb4187e806d888c48885b49b8f5 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3058870135)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4300/merge
Commit: 5bca11094bb21bb4187e806d888c48885b49b8f5 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3058870135)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 9fd9687d3226ba75a40a9521095ba210fa00b948 TT-6407 Edge key quota reset bugfix (#4300)

Co-authored-by: Matias S <83959431+mativm02@users.noreply.github.com>
Co-authored-by: Tomas Buchaillot <tombuchaillot89@gmail.com>
Triggered by: push (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3059378776)

**Pull request merged**
