### PR TITLE
Aws/pkr176

### PR DESCRIPTION
**Pull request by ermirizio**
Hybrid AMI to be similarly fixed
 Automation needs to be fixed based on this branch
 The AMIs generated by the automation need to be used in an end-to-end test
To be merged into,

- [x] master
- [x] release-3-lts
- [ ] release-4
- [ ] release-4.0

### CODE REVIEW

**Review by alephnull — APPROVED** [review]
CI is failing. You'll need it to pass to merge.

**Comment by ermirizio** [comment]
> CI is failing. You'll need it to pass to merge.

It seems grommit is complaining on the release workflow for all 3 repos with a 500 err. Last success workflow execution was  avg 5 months ago since started failing.

**Comment by ermirizio** [comment]
Unfortunatelly I can not access the place where Gromit is deployed it seems (based on what I read on confluence) I need an engineering AWS account.
Also I don't have the Gromit Github Token,
I tried this dummy curl call but it really requires auth, it can not be omited, or at least I don't know another way
image

Lets take a look together @alephnull you can baby sit me and I can take this

**Review by gwotg — APPROVED** [review]
Thanks @ermirizio! Looks good to me!

**Pull request merged**
