### PR TITLE
[TT-10943] Enforce schema validation of XTykAPIGateway

### PR DESCRIPTION
**Pull request by titpetric**
This PR improves the OAS X Tyk API Gateway schema:

- adds additionalFields: false to all definitions,
- adds a linter to verify code conforms to schema,
- fixes schema with missing objects, invalid types

https://tyktech.atlassian.net/browse/TT-10943

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5935/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7473922806)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5935/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7473922806)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5935/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7473922806)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5935/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7473922806)

**Review by andrei-tyk — APPROVED** [review]

**Pull request merged**
