### PR TITLE
Tt 1188 mdcb testing framework

### PR DESCRIPTION
**Pull request by sredxny**
## Description
refactor GW in order that we can run multiple instances as objects via code (not docker, not binaries), added method to run gw in testing mode as a worker node.  Created gw object that wrapps some information and methods specific for a gateway instance. This must be merged in tandem with:
- https://github.com/TykTechnologies/tyk-analytics/pull/2166
- https://github.com/TykTechnologies/tyk-sink/pull/109

## Related Issue
https://tyktech.atlassian.net/browse/TT-1188

## Motivation and Context
Created the proper structure so we can run integration tests for MDCB environment

## How This Has Been Tested
- Run Gw 
- Run GW instances from MDCB testing framework

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [x] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by sredxny** [comment]
Merge when we are ready for these big changes!

**Comment by sredxny** [comment]
@gernest I would like your help to understand what happens with some tests that timeout, I was investigating but not sure about the issue. Since the last commit now some tests (Eg: `TestSyncAPISpecsDashboardSuccess`) are throwing:

```
=== RUN   TestSyncAPISpecsDashboardSuccess
[Apr 11 15:08:50]  INFO coprocess: Rich plugins are disabled
    testutil.go:170: Timedout waiting for reload to be queue
--- FAIL: TestSyncAPISpecsDashboardSuccess (0.12s)
FAIL
exit status 1
FAIL    github.com/TykTechnologies/tyk/gateway  0.544s
```

To be specific, its failing in `func (r *ReloadMachinery) EnsureQueued(t *testing.T)`

**Comment by gernest** [comment]
@sredxny you have changed alot of stuff so, I will just offer my opinion on what might be the case(can't be certain so you will need to verify)

`ReloadTestCase.ReloadTicker()` and `ReloadTestCase.OnQueued` were registered on `reloadLoop` and `reloadQueueLoop` like this.

```
	go reloadLoop(ctx, ReloadTestCase.ReloadTicker(), ReloadTestCase.OnReload)
	go reloadQueueLoop(ctx, ReloadTestCase.OnQueued)
```

I don't see any changes in this PR reflecting this. A quick check, you might need something like this to have similar effect.

```diff
diff --git a/gateway/testutil.go b/gateway/testutil.go
index 6f662334..58f7debc 100644
--- a/gateway/testutil.go
+++ b/gateway/testutil.go
@@ -1006,8 +1006,8 @@ func (s *Test) BootstrapGw(ctx context.Context, genConf func(globalConf *config.
 		go s.Gw.RPCListener.StartRPCLoopCheck(slaveOptions.RPCKey)
 	}
 
-	go s.Gw.reloadLoop(ctx, time.Tick(time.Second))
-	go s.Gw.reloadQueueLoop(ctx)
+	go s.Gw.reloadLoop(ctx, s.Gw.ReloadTestCase.ReloadTicker())
+	go s.Gw.reloadQueueLoop(ctx, s.Gw.ReloadTestCase.OnQueued)
 	go s.reloadSimulation()
 }
 
```

**Comment by sredxny** [comment]
currently the test `TestHotReloadSingle` is failing even in master, some other tests fails from time to time, there's no pattern defined and they pass if we run them individually

**Review by matiasinsaurralde — APPROVED** [review]
LGTM

**Review by tbuchaillot — APPROVED** [review]

**Pull request merged**
