### PR TITLE
TT-9363 regenerated bindings with older protobuf

### PR DESCRIPTION
**Pull request by sredxny**
## Description

Compiled the bindings using protobuf v3.20 and grpcio v1.24.0

## Related Issue

https://tyktech.atlassian.net/browse/TT-9363

## How This Has Been Tested

- Build the gateway
- loaded a python plugin
- it works

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5281/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5466919053)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5281/merge
Commit: ed2b0adf11c07d1baef8225b875a672849685485 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5470581578)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5281/merge
Commit: e4ab552eb0ee962baa9814146bb67487fef2212b 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5470885181)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5281/merge
Commit: 786c3274612b375cd8314f1743e86ff7bd7cf51b 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5470934599)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5281/merge
Commit: 20159008b7c217804c969fe7fab4bfe2581b2a1f 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5471068167)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5281/merge
Commit: 75161426c21dcba206ab69d24b90a5159ef574f3 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5478297456)

**Review by mativm02 — APPROVED** [review]

**Comment by titpetric** [comment]
@sredxny can you make sure you pin the versions in tests/ci everywhere: https://github.com/search?q=repo%3ATykTechnologies%2Ftyk%20grpcio&type=code

**Review by tbuchaillot — APPROVED** [review]

**Pull request merged**
