### PR TITLE
[TT-5105] use go embed instead of go bindata to embed static files.

### PR DESCRIPTION
**Pull request by jeffy-mathew**
[changelog]
internal: use go embed to embed static files.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4286/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2997991452)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4286/merge
Commit: fdec2a0681671b22e6c741a69fb5e261cadfbec4 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2998006958)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4286/merge
Commit: fdec2a0681671b22e6c741a69fb5e261cadfbec4 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2998006958)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4286/merge
Commit: aa99ed8ec89bd8604c3a850b086fed45107c6e33 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3020941687)

**Review by furkansenharputlu — APPROVED** [review]

**Review by titpetric — APPROVED** [review]
Lovely.

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 0df2dc46287366d4f4832da7f968b0e6230a1e0a use go embed instead of go bindata to embed static files. (#4286)

[changelog]
internal: use go embed to embed static files.
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3051434649)

**Pull request merged**
