### PR TITLE
TT-653 on delete key by username then loop over all apis to update properly the key

### PR DESCRIPTION
**Pull request by sredxny**
## Description
When we attempt to remove a key and we do not receive the id of the api, then in some cases (such keys by username) we need the orgId to perform the deletion of the key. As we do not receive that information from sink, then we must loop over apis and use the orgId for each api to attempt the removal of the key, otherwise the key will not be updated in slaved nodes

## Related Issue
https://tyktech.atlassian.net/browse/TT-653

## Motivation and Context
give solution to https://tyktech.atlassian.net/browse/TT-653

## How This Has Been Tested
- Create basic API and key
- Search by username and update (check changes are being replicated in slaved nodes)
- Search by hash and update (to check that nothing is broken so changes are replicated)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by matiasinsaurralde — APPROVED** [review]

**Comment by buger** [comment]
I do not think it is 3.0 specific issue. Can you confirm that 2.9 also affected?

**Comment by matiasinsaurralde** [comment]
Applied to `release-3.1` and `release-3-lts`.

**Comment by sredxny** [comment]
@buger I confirm it works in `2.9.4`

**Pull request closed without merging**
