### PR TITLE
[TT-7572] fix customplugin bson marshal

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description

fix marshalling issue with bson and pointer

driver supports only structs and maps to be inlined - https://github.com/go-mgo/mgo/blob/v2-unstable/bson/bson.go#L488

## Related Issue
https://tyktech.atlassian.net/browse/TT-7572

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4685/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3993267110)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4685/merge
Commit: a870b04bb209b47b45ccb7ab5b3a0869178a143d 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3993619705)

**Review by furkansenharputlu — APPROVED** [review]

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4685/merge
Commit: e49d45fb311794b863cadb4f2dfd61543e20eec0 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3995308373)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4685/merge
Commit: 8aa3d3cd7070d6628be0402ee3ff23376ed35a47 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3995330834)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4685/merge
Commit: 8d3fdbd33dc73cf62a182ef1d8a2ee0b5f7a588e 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3995327945)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4685/merge
Commit: 2b8a95dc348394111885f3ae92f5e29fcd633e5d 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3995574437)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4685/merge
Commit: 8b2dc64c8a5f0a1c27f1b16e34fa6a9df1c91d58 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3995590050)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4685/merge
Commit: cb92de79fe664273529028a705808c13c3404230 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3995647452)

**Pull request merged**
