### PR TITLE
Implemented autocert

### PR DESCRIPTION
**Pull request by maxencehenneron**
This is a work in progress, I updated to autocert as described in this issue: https://github.com/TykTechnologies/tyk/issues/834

A few things: 

- Lets Encrypt disabled TLS-SNI http://www.zdnet.com/article/lets-encrypt-disables-tls-sni-01-validation/ which is what tyk is currently using to generate the certificates
- I had to use the http-01 ACME challenge (see http://letsencrypt.readthedocs.io/en/latest/challenges.html for more informations) which needs to have the port 80 available. 
- I have no idea what the NoticeGatewayLENotification is, it's not used anywhere in the source code, does anyone have any idea what it refers to in the current code base?
- I made a redirection to the https endpoint in case someone tries to access the gateway from the port 80.
- I created a new config variable a user has to set to agree with Letsencrypt's TOS

I'd appreciate to have feedbacks

### CODE REVIEW

**Comment by dernise** [comment]
Also, the build seems to fail because I added accept_lets_encrypt_tos, why is the linter not recognizing my newly-created field?

**Comment by buger** [comment]
Hi! Thank you for contribution. 

> I created a new config variable a user has to set to agree with Letsencrypt's TOS

Does this step required?

**Comment by dernise** [comment]
It's a legal requirement. Let's Encrypt wants the user to explicitly agree their TOS. We could override it and force it to be true but it would leave you  legally reliable I guess..

**Comment by lonelycode** [comment]
The notification is used here: https://github.com/TykTechnologies/tyk/blob/master/redis_signals.go#L108

When gateways are load balanced the cluster should be sharing the LE SSL cert to prevent spamming LE, IIRC it stashed the cert in redis and tells the cluster to use that.

**Pull request closed without merging**
