### PR TITLE
[TT-7972] Fix/jaegertracing import path

### PR DESCRIPTION
**Pull request by titpetric**
Bump uber/jaegertracing to @master versions to hopefully resolve the following issue:

```
task: [plugins-gowork-testplugin:test-plugin] ./tyk plugin load -f ../plugin/plugin.so -s MyPluginPre
tyk: error: unexpected error: plugin.Open("../plugin/plugin"): plugin was built with a different version of package github.com/uber/jaeger-client-go/log, try --help
task: Failed to run task "plugins-gowork-testplugin:default": task: Failed to run task "plugins-gowork-testplugin:test-plugin": exit status 1
```

https://tyktech.atlassian.net/browse/TT-7972

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4760/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4143837579)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4760/merge
Commit: 102627f855bc58db197310a0839bef217ea35344 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4145525721)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4760/merge
Commit: fb687ab9927bc645344fde3d52c1d4046c51a94e 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4145527035)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4760/merge
Commit: b6501b0fe98406a34425663a2f364eb970cf01be 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4161814875)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4760/merge
Commit: 13acdfe3617b57867d748a98cb763d6378e7cc62 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4240598263)

**Review by buger — APPROVED** [review]

**Review by sredxny — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4760/merge
Commit: b06f00ac777a80b81c255e176865c97722c19326 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4281308776)

**Pull request merged**
