### PR TITLE
Add API-level rate limiter, fixes #643

### LINKED ISSUE #643: Make swagger imports generate tracked URLs instead of white listed URLs
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When I import a swagger definition, it generates a base API with all the paths listed as white lists, thbis is not ideal as it locks down the API unnecessarily.

**What is the expected behavior?**
The paths that are generated should be "tracked paths" instead as this is more useful and serves as a better start

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
This is only really possible since v2.2 or so because that's when tracked paths were introduced.

**NOTE**: This must be ported to the dashboard too.

### PR DESCRIPTION
**Pull request by lonelycode**
Uses the same rate limiting mechanism as per-token limits but at the api level. Adds RL section to the apidef:

```
"global_rate_limit": {
		"rate": 3,
		"per": 1
	}
```

Will require FE work as well.

### CODE REVIEW

**Comment by mvdan** [comment]
Is this PR pulling in all the swagger stuff by mistake?

**Comment by mvdan** [comment]
Otherwise looks good - glad to see you coding again :)

**Comment by lonelycode** [comment]
Swagger stuf removed

**Comment by ilijabojanovic** [comment]
During testing this PR i found issue:
ENV: On-prem
Dashboard branch: TykTechnologies/tyk-analytics#453

When we set rate limit on api level and update rate limit after some time, old limit is applied on api def. Rate limit changes are visible only when we restart gateway, on gateway reload gateway does not propagate new rate limit values.

**Comment by lonelycode** [comment]
@ilijabojanovic https://github.com/TykTechnologies/tyk/pull/1208

**Pull request merged**
