### PR TITLE
use $CGO_CGOENABLED  instead of $CGO_CGOENABLE that doesnt exist

### PR DESCRIPTION
**Pull request by sredxny**
## Description
In the plugin compiler, in the command to compile a plugin use the proper value to set for CGO_CGOENABLE var. It's an outcome for the comment in https://github.com/TykTechnologies/tyk/pull/3873#discussion_r908340190

At this point I think as well we should remove it as officially the plugin compiler will only work for linux OS and not windows/darwin etc... so it sounds to me that we should not support this param.

## Related Issue
- To be created

## Motivation and Context
Be consistent

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4160/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2577629278)

**Comment by titpetric** [comment]
I don't see why we couldn't extend support to arm64 targets for example. Given goos and goarch arguments and a cross build dockerfile base, unofficially at the very least, we do enable people doing that.

You made a quick find/replace, but you missed the variable name, it's CGO_ENABLED; currently it's unset (unless it's in the Dockerfile), setting it to =1 would likely change behavior? I'd appreciate a bit of an investigation, or a short think. I think, we shouldn't set CGO_ENABLED and just remove the non functional bits here, keep behavior.

**Comment by titpetric** [comment]
Hate to say it, but still a typo (missing underscore). Next one will cost you a michelada 📃😅

Check out the rest of the first comment, maybe we don't need any changes at all, other than a cleanup/removal. I'd prefer that over this

**Comment by titpetric** [comment]
Closing as stale/incorrect multiple times, if you need it file a ticket.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4160/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2932688781)

**Pull request closed without merging**
