### PR TITLE
session: allow applying multiple policies

### LINKED ISSUE #355: As a user I should be able to assign multiple policies to a token as a list
I should be able to add multiple policy IDs to a token, if they are present, then their partitions are evaluated. If they have overlapping partitions, where it is possible, they should be merged, e.g. if the ACLs are enforced on both, they should be extended to be an aggregate ACL.

I should be able to set these in the dashboard.

### PR DESCRIPTION
**Pull request by mvdan**
Fixes #355.

### CODE REVIEW

**Comment by mvdan** [comment]
@lonelycode a few TODOs remain:

* How do I merge `IsInactive`? True if any of them are true, false if any of them are false, whatever the first policy has, whatever the last policy has?
* Should `coprocess.SessionState` be updated exactly like the internal struct, or in a different way?
* In the JWT code, now only the first policy is used. Is that correct, or should it use all policies somehow?

**Comment by mvdan** [comment]
Also, I kept the merging of ACL since it's fairly simple, and not much work on top of the work that is already being done. I doubt that merging a few maps will be a noticeable amount of work on top of everything else that is being done.

**Comment by lonelycode** [comment]
> How do I merge IsInactive? True if any of them are true, false if any of them are false, whatever the first policy has, whatever the last policy has?

If any one policy sets this to true, it should be active on the key.

> Should coprocess.SessionState be updated exactly like the internal struct, or in a different way?

That's one for @matiasinsaurralde 

> In the JWT code, now only the first policy is used. Is that correct, or should it use all policies somehow?

JWT and OIDC would need extending to support multiple policies, JWT would need a new claim for policies (or a bool to expect multiple policy IDs) and OIDC would need the ability to add more than one policy in the UI and against a Client

I would suggest we make this a 2.4.1 enhancement.

**Comment by matiasinsaurralde** [comment]
We should update the protocol definition and update the bindings!

**Comment by mvdan** [comment]
@matiasinsaurralde please ensure that I did everything correctly with coprocess. I struggled to update the bindings so I improved the docs a little bit.

Otherwise, this should be ready for a review now.

**Comment by buger** [comment]
Looks good, but this functionality is a perfect candidate to be covered with unit tests.

**Comment by mvdan** [comment]
The priority here was unblocking Laurentiu, which is why I didn't include tests at first. I can work on them later this week.

**Comment by mvdan** [comment]
@buger see the added tests, they cover all possible combinations and errors. I've also kept all changes in separate commits to simplify review and the history.

Don't squash-merge, as this would all make for one huge commit.

**Comment by buger** [comment]
@lghiur you can start testing this branch with your PR.

**Comment by mvdan** [comment]
He's missing the dashboard bit, since it has a thin layer for this stuff that needs updating. Working on that now.

**Comment by ilijabojanovic** [comment]
@mvdan @lghiur 

**Branches:**
Gateway: PR/1016
Dashboard API: PR/397
Dashboard UI: PR/138

Reproduction steps:
1. Create API definition
2. Create Policy
3. Attach policy on portal
4. Register new developer over portal and request key

Actual:
When developer got key that key doesn't have properties from policy enabled for portal. Rate and Quota are not enabled for that key

Policy:
```
{
    "_id" : ObjectId("59c0cf3148e7d101d7e80185"),
    "org_id" : "59bfa529dfd25101d2b88ef2",
    "rate" : 4000.0,
    "per" : 60.0,
    "quota_max" : NumberLong(-1),
    "quota_renewal_rate" : NumberLong(3600),
    "access_rights" : {
        "d23d337a6a2f4f455eab146191dc9ea7" : {
            "apiname" : "test",
            "apiid" : "d23d337a6a2f4f455eab146191dc9ea7",
            "versions" : [ 
                "Default"
            ],
            "allowed_urls" : []
        }
    },
    "hmac_enabled" : false,
    "active" : true,
    "name" : "polisa",
    "is_inactive" : false,
    "date_created" : Date(-62135596800000),
    "tags" : [],
    "key_expires_in" : NumberLong(21600),
    "partitions" : {
        "quota" : false,
        "rate_limit" : false,
        "acl" : false
    },
    "last_updated" : "1505808178"
}
```
Developer key:
```
{
	"last_check": 0,
	"allowance": 0,
	"rate": 0,
	"per": 0,
	"expires": 1505829836,
	"quota_max": 0,
	"quota_renews": 1505808236,
	"quota_remaining": 0,
	"quota_renewal_rate": 0,
	"access_rights": {
		"d23d337a6a2f4f455eab146191dc9ea7": {
			"api_name": "test",
			"api_id": "d23d337a6a2f4f455eab146191dc9ea7",
			"versions": ["Default"],
			"allowed_urls": []
		}
	},
	"org_id": "59bfa529dfd25101d2b88ef2",
	"oauth_client_id": "",
	"oauth_keys": null,
	"basic_auth_data": {
		"password": "",
		"hash_type": ""
	},
	"jwt_data": {
		"secret": ""
	},
	"hmac_enabled": false,
	"hmac_string": "",
	"is_inactive": false,
	"apply_policy_id": "59c0cf3148e7d101d7e80185",
	"apply_policies": null,
	"data_expires": 0,
	"monitor": {
		"trigger_limits": null
	},
	"enable_detail_recording": false,
	"meta_data": {
		"tyk_developer_id": "59c0cf6948e7d101d7e80186",
		"tyk_key_request_fields": {},
		"tyk_user_fields": {}
	},
	"tags": null,
	"alias": "dev@test.com",
	"last_updated": "1505808236",
	"id_extractor_deadline": 0,
	"session_lifetime": 0
}
```

**Comment by ilijabojanovic** [comment]
Branches:
Gateway: PR/1016
Dashboard API: PR/397
Dashboard UI: PR/138

Reproduction steps:

1. Create api definition 
2. Create one policy and select created api definition
3. Create second policy and select created api defitnion 
4. Create key and select first and second policy 
5. Generate some traffic over created key
6. Edit both polices and enable "Deny acess"

Actual:
When we disable access to keys over polices, keys is still active. 

Policy one
```
{
    "_id" : ObjectId("59c0d69548e7d101d7e80188"),
    "org_id" : "59bfa529dfd25101d2b88ef2",
    "rate" : 2998.0,
    "per" : 60.0,
    "quota_max" : NumberLong(-1),
    "quota_renewal_rate" : NumberLong(3600),
    "access_rights" : {
        "af08a80fc22449695878dbded2558274" : {
            "apiname" : "test-api",
            "apiid" : "af08a80fc22449695878dbded2558274",
            "versions" : [ 
                "Default"
            ],
            "allowed_urls" : []
        }
    },
    "hmac_enabled" : false,
    "active" : true,
    "name" : "policy1",
    "is_inactive" : true,
    "date_created" : Date(-62135596800000),
    "tags" : [],
    "key_expires_in" : NumberLong(21600),
    "partitions" : {
        "quota" : false,
        "rate_limit" : false,
        "acl" : false
    },
    "last_updated" : "1505810225"
}
```
Policy two:
```
{
    "_id" : ObjectId("59c0d6ae48e7d101d7e80189"),
    "org_id" : "59bfa529dfd25101d2b88ef2",
    "rate" : 3000.0,
    "per" : 60.0,
    "quota_max" : NumberLong(-1),
    "quota_renewal_rate" : NumberLong(21600),
    "access_rights" : {
        "af08a80fc22449695878dbded2558274" : {
            "apiname" : "test-api",
            "apiid" : "af08a80fc22449695878dbded2558274",
            "versions" : [ 
                "Default"
            ],
            "allowed_urls" : []
        }
    },
    "hmac_enabled" : false,
    "active" : true,
    "name" : "policy2",
    "is_inactive" : true,
    "date_created" : Date(-62135596800000),
    "tags" : [],
    "key_expires_in" : NumberLong(21600),
    "partitions" : {
        "quota" : true,
        "rate_limit" : true,
        "acl" : false
    },
    "last_updated" : "1505810181"
}
```

**Comment by mvdan** [comment]
(that was a rather complicated rebase, nothing interesting to see)

**Comment by buger** [comment]
@mvdan what is the latest status of it, issues fixed and ready for a new QA round?

**Comment by mvdan** [comment]
We were looking into this with @ilijabojanovic early last week, and we got sidetracked by support and the more important regressions. Getting back to it now - I was asking him for more info last.

**Comment by ilijabojanovic** [comment]
@buger approved for merge

**Pull request merged**
