### PR TITLE
Fix Spelling of IncrementWithExpire function

### PR DESCRIPTION
**Pull request by ahoglund**
## Description

The `IncrementWithExpire` was spelled incorrectly. This PR fixes it.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by lghiur** [comment]
@ahoglund Thanks for spotting that, we'll include this in the next patch.

**Comment by lghiur** [comment]
@ahoglund can we bring this out of Draft state?

**Comment by titpetric** [comment]
I apologize, the decision to include it has been a bit rash. There is work being done in /storage, and the PR is incomplete (draft + doesn't update all occurences of the function), and sadly it's also a breaking change in the APIs. As we were lready aware of this and we're addressing this in our pre-existing work, I'm closing the PR in favor of that.

**Comment by ahoglund** [comment]
Ok thank for the update. I was going to update the other occurrences/calls but if you are tracking this elsewhere that makes sense.

**Pull request closed without merging**
