### PR TITLE
[TT-6669] Updated graphql-go-tools commit hash

### PR DESCRIPTION
**Pull request by buraksezer**
[changelog]
internal: Updated graphql-go-tools commit hash.

### CODE REVIEW

**Review by Aenimus — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4342/merge
Commit:  
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3234244780)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4342/merge
Commit:  
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3234244780)

**Review by kofoworola — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 9b61e5b2118038888280fa71115cbc4e26e3d65d [TT-6669] Updated graphql-go-tools commit hash (#4342)

* [TT-6669] Updated graphql-go-tools commit hash

[changelog]
internal: Updated graphql-go-tools commit hash.
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3235705021)

**Pull request merged**
