### PR TITLE
whitelist for ciphersuites available for TLSconfig

### LINKED ISSUE #1372: Way to specify TLS Ciphers
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Right now only default set of ciphers is supported
**What is the expected behavior?**
Security standards vary across companies, and there should be a way to whitelist allowed ciphers
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.4, master

### PR DESCRIPTION
**Pull request by joshblakeley**
User can add values of TLS ciphersuites to array in config, the values of which are defined in the Go TLS lib https://golang.org/pkg/crypto/tls/#Config

Fixes #1372

### CODE REVIEW

**Comment by buger** [comment]
Nice! Would love to see a small test. 

The basic idea here is that you specify some ciphersuites on server side, next specify incompatible ones on the http client side, you should get an error. 

If we talking in terms of test framework:

```
config.Global.HttpServerOptions.Ciphers = []string{.....}

ts := newTykTestServer()
defer ts.Close()

buildAndLoadAPI(function(s *APISpec){
   s.Proxy.ListenPath = "/"
})

t.Run("Cipher match", function(t *testing.T) {
  client := &http.Client{&http.Transport{TLSClientConfig: &tls.Config{
     CipherSuites: getCipherAliases([]string{....}} // matching ciphers
  }}}

  // If there is internal TSL error it will fail test
  ts.Run(t, test.TestCase{Path: "/"})
})

t.Run("Cipher not match", function(t *testing.T) {
  client := &http.Client{&http.Transport{TLSClientConfig: &tls.Config{
     CipherSuites: getCipherAliases([]string{....}} // not matching ciphers
  }}}

  ts.Run(t, test.TestCase{Path: "/", ErrorMatch: "tls: some internal error"})
})
```

**Comment by joshblakeley** [comment]
Thanks @buger will see where I get

Have slightly altered some imports in main  too as goimports was being annoying and removing them on save.

**Comment by buger** [comment]
Nice job! I made small refactoring, removing unnecessary logic.

**Comment by buger** [comment]
@joshblakeley the final thing left is to prepare documentation update for this page https://tyk.io/docs/security/tls-and-ssl/

Make a separate PR to tyk-docs repo

**Comment by joshblakeley** [comment]
Will do!

Thanks, i'm very happy with what i've done today.

**Comment by buger** [comment]
Note that I also renamed config variable from `ciphers` to `ssl_ciphers`, to reflect what it is

**Comment by joshblakeley** [comment]
Makes sense, thanks.

**Comment by joshblakeley** [comment]
You killed the linter, i'll fix

**Pull request merged**
