### PR TITLE
[TT-5700] block import API in dashboard mode.

### PR DESCRIPTION
**Pull request by jeffy-mathew**
[changelog]
internal: block import API in dashboard mode.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4131/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2499781127)

**Review by lghiur — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4131/merge
Commit: c2e2f9525518a8230ca204f8f80d3ba3cfa8fefc 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2499781489)

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 038d11a539fb2482f36b0729dca0621e5a018664 block import API in dashboard mode. (#4131)

[changelog]
internal: block import API in dashboard mode.
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2500109031)

**Pull request merged**
