### PR TITLE
Fix parsing jwk public key

### LINKED ISSUE #2790: JWKs URL is assumed to be a PEM file
**Branch/Environment/Version**
- Branch/Version: 2.9.2
- Environment: On-prem

**Describe the bug**
When attempting to setup JWK as per https://tyk.io/docs/security/your-apis/json-web-tokens/#option-3-dynamic-public-key-rotation-using-jwks, it is not clear where the URL is to be supplied in the UI.

Once the URL is made available in base64 form in `jwt_source`, the behaviour is to assume it is a PEM file even when it is DER. See https://community.tyk.io/t/jwt-jwks-error-key-must-be-pem-encoded-pkcs1-or-pkcs8-private-key/3150 for more details.

### LINKED ISSUE #2873: ECDSA Signature validation of JWTs
**Is your feature request related to a problem? Please describe.**
I'm trying to find a way to make Tyk validate JWTs signed with ECDSA keys (e.g. P-256, P-384, P-521). However, it does not seem to be supported. 

**Describe the solution you'd like**
I would like Tyk to be able to verify ECDSA signatures of JWTs

**Describe alternatives you've considered**
I've considered lowering the security settings of the IDP (Ping Access), but it does not seem reasonable to downgrade.

### PR DESCRIPTION
**Pull request by gernest**
This checks if the key is PEM and decodes it as PEM.

It uses the raw key if it isn't in PEM format.

fixes #2790
closes #2873

### CODE REVIEW

**Comment by gernest** [comment]
The ci failure has nothing to do with this its on `TestPythonBundles`

**Comment by sedkis** [comment]
Would it be possible to add an example of JWKs in the docs please?
https://tyk.io/docs/basic-config-and-security/security/your-apis/json-web-tokens/#option-3-dynamic-public-key-rotation-using-jwks

**Comment by buger** [comment]
@sedkis essentially JWKs automatically provided by identity provider and not written manually.

**Pull request merged**
