### PR TITLE
[TT-4213] pass down wrapped http response writer to plugin

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description

Auth failed from plugin results in 
```
{
    "error": "Session state is missing or unset! Please make sure that auth headers are properly applied"
}
```

This is due to passing down raw `http.ResponseWriter` instead of wrapper `customResponseWriter`. 
Since the plugin receives `w` instead of `rw` in `ProcessRequest`, `rw.responseSent` always remains false. 
This PR intends to fix this issue

## How This Has Been Tested

Added response body to auth plugin [here](https://github.com/TykTechnologies/tyk/pull/3803/files#diff-6b57b162c0610abdd8c4edf02dab0718ef7daa1c986aeae2e13adf9904ec3459R34) and corresponding test has been updated to validate the response

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Review by vaske — APPROVED** [review]

**Comment by buger** [comment]
Looks good! But we need Jira ticket

**Review by furkansenharputlu — APPROVED** [review]

**Pull request merged**
