### PR TITLE
[TT-7129] Fix global size limit

### LINKED ISSUE #2887: Global size limit on api definition is broken
**Branch/Environment/Version**
- Branch/Version: Stable
- Environment: All

**Describe the bug**
Global size limit on api definition is ignored

**Reproduction steps**

1. Create api definition
2. Set `"global_size_limit": 500 ` on api definition 
3. Send request with 1mb image

**Actual behavior**
Gateway will proxy request to upstream

**Expected behavior**
Gateway should reject request since size limit is exceeded

**Screenshots/Video**
If applicable, add screenshots or video to help explain your problem.

**Logs (debug mode or log file):**
Log from console or from log file.

**Configuration (tyk config file):**
Attach tyk configuration file

**Additional context**
Testing definition:
```
{
    "api_model": {},
    "api_definition": {
        "id": "5e414015cce9f3080921a0e1",
        "name": "api1",
        "slug": "api1",
        "listen_port": 0,
        "protocol": "",
        "enable_proxy_protocol": false,
        "api_id": "95f50b735be94b94534f338a5c9dfff2",
        "org_id": "5e413f80cce9f3080921a0dd",
        "use_keyless": false,
        "use_oauth2": false,
        "use_openid": false,
        "openid_options": {
            "providers": [],
            "segregate_by_client": false
        },
        "oauth_meta": {
            "allowed_access_types": [],
            "allowed_authorize_types": [],
            "auth_login_redirect": ""
        },
        "auth": {
            "use_param": false,
            "param_name": "",
            "use_cookie": false,
            "cookie_name": "",
            "auth_header_name": "Authorization",
            "use_certificate": false,
            "validate_signature": false,
            "signature": {
                "algorithm": "",
                "header": "",
                "secret": "",
                "allowed_clock_skew": 0,
                "error_code": 0,
                "error_message": ""
            }
        },
        "auth_configs": {
            "authToken": {
                "use_param": false,
                "param_name": "",
                "use_cookie": false,
                "cookie_name": "",
                "auth_header_name": "Auth",
                "use_certificate": false,
                "validate_signature": false,
                "signature": {
                    "algorithm": "",
                    "header": "",
                    "secret": "",
                    "allowed_clock_skew": 0,
                    "error_code": 0,
                    "error_message": ""
                }
            },
            "basic": {
                "use_param": false,
                "param_name": "",
                "use_cookie": false,
                "cookie_name": "",
                "auth_header_name": "Authorization",
                "use_certificate": false,
                "validate_signature": false,
                "signature": {
                    "algorithm": "",
                    "header": "",
                    "secret": "",
                    "allowed_clock_skew": 0,
                    "error_code": 0,
                    "error_message": ""
                }
            },
            "coprocess": {
                "use_param": false,
                "param_name": "",
                "use_cookie": false,
                "cookie_name": "",
                "auth_header_name": "Authorization",
                "use_certificate": false,
                "validate_signature": false,
                "signature": {
                    "algorithm": "",
                    "header": "",
                    "secret": "",
                    "allowed_clock_skew": 0,
                    "error_code": 0,
                    "error_message": ""
                }
            },
            "hmac": {
                "use_param": false,
                "param_name": "",
                "use_cookie": false,
                "cookie_name": "",
                "auth_header_name": "Authorization",
                "use_certificate": false,
                "validate_signature": false,
                "signature": {
                    "algorithm": "",
                    "header": "",
                    "secret": "",
                    "allowed_clock_skew": 0,
                    "error_code": 0,
                    "error_message": ""
                }
            },
            "jwt": {
                "use_param": false,
                "param_name": "",
                "use_cookie": false,
                "cookie_name": "",
                "auth_header_name": "Authorization",
                "use_certificate": false,
                "validate_signature": false,
                "signature": {
                    "algorithm": "",
                    "header": "",
                    "secret": "",
                    "allowed_clock_skew": 0,
                    "error_code": 0,
                    "error_message": ""
                }
            },
            "oauth": {
                "use_param": false,
                "param_name": "",
                "use_cookie": false,
                "cookie_name": "",
                "auth_header_name": "Authorization",
                "use_certificate": false,
                "validate_signature": false,
                "signature": {
                    "algorithm": "",
                    "header": "",
                    "secret": "",
                    "allowed_clock_skew": 0,
                    "error_code": 0,
                    "error_message": ""
                }
            },
            "oidc": {
                "use_param": false,
                "param_name": "",
                "use_cookie": false,
                "cookie_name": "",
                "auth_header_name": "Authorization",
                "use_certificate": false,
                "validate_signature": false,
                "signature": {
                    "algorithm": "",
                    "header": "",
                    "secret": "",
                    "allowed_clock_skew": 0,
                    "error_code": 0,
                    "error_message": ""
                }
            }
        },
        "use_basic_auth": false,
        "basic_auth": {
            "disable_caching": false,
            "cache_ttl": 0,
            "extract_from_body": false,
            "body_user_regexp": "",
            "body_password_regexp": ""
        },
        "use_mutual_tls_auth": false,
        "client_certificates": [],
        "upstream_certificates": {},
        "pinned_public_keys": {},
        "enable_jwt": false,
        "use_standard_auth": true,
        "use_go_plugin_auth": false,
        "enable_coprocess_auth": false,
        "jwt_signing_method": "",
        "jwt_source": "",
        "jwt_identity_base_field": "",
        "jwt_client_base_field": "",
        "jwt_policy_field_name": "",
        "jwt_default_policies": [],
        "jwt_issued_at_validation_skew": 0,
        "jwt_expires_at_validation_skew": 0,
        "jwt_not_before_validation_skew": 0,
        "jwt_skip_kid": false,
        "jwt_scope_to_policy_mapping": {},
        "jwt_scope_claim_name": "",
        "notifications": {
            "shared_secret": "",
            "oauth_on_keychange_url": ""
        },
        "enable_signature_checking": false,
        "hmac_allowed_clock_skew": -1,
        "hmac_allowed_algorithms": [],
        "request_signing": {
            "is_enabled": false,
            "secret": "",
            "key_id": "",
            "algorithm": "",
            "header_list": [],
            "certificate_id": "",
            "signature_header": ""
        },
        "base_identity_provided_by": "",
        "definition": {
            "location": "header",
            "key": "x-api-version",
            "strip_path": false
        },
        "version_data": {
            "not_versioned": true,
            "default_version": "",
            "versions": {
                "Default": {
                    "name": "Default",
                    "expires": "",
                    "paths": {
                        "ignored": [],
                        "white_list": [],
                        "black_list": []
                    },
                    "use_extended_paths": true,
                    "extended_paths": {
                        "cache": [
                            "get"
                        ]
                    },
                    "global_headers": {},
                    "global_headers_remove": [],
                    "global_size_limit": 500,
                    "override_target": ""
                }
            }
        },
        "uptime_tests": {
            "check_list": [],
            "config": {
                "expire_utime_after": 0,
                "service_discovery": {
                    "use_discovery_service": false,
                    "query_endpoint": "",
                    "use_nested_query": false,
                    "parent_data_path": "",
                    "data_path": "",
                    "port_data_path": "",
                    "target_path": "",
                    "use_target_list": false,
                    "cache_timeout": 60,
                    "endpoint_returns_list": false
                },
                "recheck_wait": 0
            }
        },
        "proxy": {
            "preserve_host_header": false,
            "listen_path": "/api1/",
            "target_url": "http://httpbin.org/",
            "disable_strip_slash": false,
            "strip_listen_path": true,
            "enable_load_balancing": false,
            "target_list": [],
            "check_host_against_uptime_tests": false,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 0,
                "endpoint_returns_list": false
            },
            "transport": {
                "ssl_insecure_skip_verify": false,
                "ssl_ciphers": [],
                "ssl_min_version": 0,
                "ssl_force_common_name_check": false,
                "proxy_url": ""
            }
        },
        "disable_rate_limit": false,
        "disable_quota": false,
        "custom_middleware": {
            "pre": [],
            "post": [],
            "post_key_auth": [],
            "auth_check": {
                "name": "",
                "path": "",
                "require_session": false,
                "raw_body_only": false
            },
            "response": [],
            "driver": "",
            "id_extractor": {
                "extract_from": "",
                "extract_with": "",
                "extractor_config": {}
            }
        },
        "custom_middleware_bundle": "",
        "cache_options": {
            "cache_timeout": 60,
            "enable_cache": true,
            "cache_all_safe_requests": true,
            "cache_response_codes": [
                200
            ],
            "enable_upstream_cache_control": false,
            "cache_control_ttl_header": "",
            "cache_by_headers": []
        },
        "session_lifetime": 0,
        "active": true,
        "internal": false,
        "auth_provider": {
            "name": "",
            "storage_engine": "",
            "meta": {}
        },
        "session_provider": {
            "name": "",
            "storage_engine": "",
            "meta": {}
        },
        "event_handlers": {
            "events": {}
        },
        "enable_batch_request_support": false,
        "enable_ip_whitelisting": false,
        "allowed_ips": [],
        "enable_ip_blacklisting": false,
        "blacklisted_ips": [],
        "dont_set_quota_on_create": false,
        "expire_analytics_after": 0,
        "response_processors": [],
        "CORS": {
            "enable": false,
            "allowed_origins": [],
            "allowed_methods": [],
            "allowed_headers": [],
            "exposed_headers": [],
            "allow_credentials": false,
            "max_age": 24,
            "options_passthrough": false,
            "debug": false
        },
        "domain": "",
        "certificates": [],
        "do_not_track": false,
        "tags": [],
        "enable_context_vars": false,
        "config_data": {},
        "tag_headers": [],
        "global_rate_limit": {
            "rate": 0,
            "per": 0
        },
        "strip_auth_data": false,
        "enable_detailed_recording": false
    },
    "hook_references": [],
    "is_site": false,
    "sort_by": 0,
    "user_group_owners": [],
    "user_owners": []
}
```

### PR DESCRIPTION
**Pull request by titpetric**
https://tyktech.atlassian.net/browse/TT-7129

Closes #2887 #3979

### CODE REVIEW

**Review by tbuchaillot — APPROVED** [review]
lgtm - please gofmt the files first

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4967/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4735405243)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4967/merge
Commit: e363980792a836b65b68dff62faf74c438ad3b02 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4735466256)

**Pull request merged**
