### PR TITLE
Fix -h/--help not exiting the program

### PR DESCRIPTION
**Pull request by mvdan**
Rebase and cleanup of #281. Thanks @stevensu1977!

### CODE REVIEW

**Comment by buger** [comment]
This is what last argument stands for:

> By default, docopt calls `os.Exit(0)` if it handled a built-in option such as
`-h` or `--version`. If the user errored with a wrong command or options,
docopt exits with a return code of 1. To stop docopt from calling `os.Exit()`
and to handle your own return codes, pass an optional last parameter of `false`
for `exit`.
https://github.com/TykTechnologies/tyk/blob/60003580cd3e50c4809ddae9ec0f06898da2a1db/vendor/github.com/docopt/docopt.go/docopt.go#L36

**Comment by lonelycode** [comment]
@buger Are you happy for this to be merged?

**Comment by buger** [comment]
So basically right now with last `false` option it expected us to manually call os.Exit in case of `-h` flag. By removing this option, we allow docparse to exit program by himself. 

If my assumption is right, then 👍

**Comment by mvdan** [comment]
Yeah, that's my understanding too.

**Pull request merged**
