### PR TITLE
[TT-9573] Adding DetailedTracing to OAS APIs

### PR DESCRIPTION
**Pull request by mativm02**
## Description
Adding `detailed_tracing` field to OAS APIs. If this is set to true, then each OpenTelemetry trace will propagate the context and multiple spans will be shown. Otherwise, only the main span and a span showing the request to the upstream service will be present.

## Related Issue
https://tyktech.atlassian.net/browse/TT-9573?atlOrigin=eyJpIjoiNWM4NGRkZTI3ZGQxNGY2NjhiZGU0YzFkMGFlMWZiOWYiLCJwIjoiaiJ9

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5966/merge
Commit: d259c92da098028d6f54caf57907d4ca56bf7435 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7668880287)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5966/merge
Commit: d259c92da098028d6f54caf57907d4ca56bf7435 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7668880287)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: c8ebddcdbdb0143501cbf3402f763942258dbd08 [TT-9573] Adding DetailedTracing to OAS APIs (#5966)



## Description
Adding `detailed_tracing` field to OAS APIs. If this is set to true,
then each OpenTelemetry trace will propagate the context and multiple
spans will be shown. Otherwise, only the main span and a span showing
the request to the upstream service will be present.


## Related Issue

https://tyktech.atlassian.net/browse/TT-9573?atlOrigin=eyJpIjoiNWM4NGRkZTI3ZGQxNGY2NjhiZGU0YzFkMGFlMWZiOWYiLCJwIjoiaiJ9





## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why
Triggered by: push (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7711318104)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: c8ebddcdbdb0143501cbf3402f763942258dbd08 [TT-9573] Adding DetailedTracing to OAS APIs (#5966)



## Description
Adding `detailed_tracing` field to OAS APIs. If this is set to true,
then each OpenTelemetry trace will propagate the context and multiple
spans will be shown. Otherwise, only the main span and a span showing
the request to the upstream service will be present.


## Related Issue

https://tyktech.atlassian.net/browse/TT-9573?atlOrigin=eyJpIjoiNWM4NGRkZTI3ZGQxNGY2NjhiZGU0YzFkMGFlMWZiOWYiLCJwIjoiaiJ9





## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why
Triggered by: push (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7711318104)

**Pull request merged**
