### PR TITLE
[TT-7338] disable auth_headers and use request headers

### PR DESCRIPTION
**Pull request by kofoworola**
## Description
The `auth_headers` are used by the gateway for upstream requests and are used by the dashboard for introspection request, This [ticket](https://tyktech.atlassian.net/browse/TT-7338) aims to only allow a new field called `request_headers` be used for upstream requests to allow the use of context variables. So this PR does that by disabling the use of `auth_headers` in the gateway for upstream requests. 

## Related Issue
[TT-7338](https://tyktech.atlassian.net/browse/TT-7338)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

[TT-7338]: https://tyktech.atlassian.net/browse/TT-7338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TT-7338]: https://tyktech.atlassian.net/browse/TT-7338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TT-7338]: https://tyktech.atlassian.net/browse/TT-7338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4562/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3738045890)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4562/merge
Commit: 99cff29dfe9b0d8cc6efb07afdfcb3d8203f61c7 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3738056478)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4562/merge
Commit: bf90da276f88ba6708f4520b0f6e3ab8660ceb44 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3739010037)

**Review by buraksezer — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4562/merge
Commit: 988b5a3f59d79bf674322f13cd859a10070ec47a 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3756523658)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4562/merge
Commit: 5fa94d61945bd2ca2bd3d7114708df9268e31246 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3828105364)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4562/merge
Commit: a73d42d714d79cce90426afc033a8bd57256655e 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3837067449)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4562/merge
Commit: 5f62afdea994983bb46437cef9f50d9b2d8574ef 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3880606167)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4562/merge
Commit: 43f01800f940e5c7c3c5f52cc17160f8d43526f9 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3882089459)

**Pull request merged**
