### PR TITLE
[TT-10918] Update dependencies

### PR DESCRIPTION
**Pull request by titpetric**
| Dependency                       | Old Version | New Version |
|----------------------------------|-------------|-------------|
| github.com/robertkrimen/otto     | v0.2.1      | v0.3.0      |
| golang.org/x/sync                 | v0.5.0      | v0.6.0      |
| google.golang.org/protobuf        | v1.31.0     | v1.32.0     |
| go.uber.org/mock                  | v0.3.0      | v0.4.0      |

https://tyktech.atlassian.net/browse/TT-10918

### CODE REVIEW

**Review by jeffy-mathew — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5926/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7421594287)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5926/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7421594287)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5926/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7421594287)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5926/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7421594287)

**Pull request merged**
