### PR TITLE
[TT-6933] Implement introspection cache OAS conversion

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR implements introspection cache conversion for OAS. It doesn't have a test because it is already covered with the existing tests.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4369/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3335137226)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4369/merge
Commit: e16773d2c3694ceb697694866d19f2377535ca69 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3335383067)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4369/merge
Commit: a8c5cc7ac6870d85ebc12871e95f61617e57dddc 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3335393394)

**Review by lghiur — APPROVED** [review]

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 2dd015b8d9bda756e300bbe49e131a9f3b306558 [TT-6933] Implement introspection cache OAS conversion (#4369)

* Implement introspection cache OAS conversion

* Make caching omittable
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3335594051)

**Pull request merged**
