### PR TITLE
test: add an api loader sort test

### PR DESCRIPTION
**Pull request by mvdan**
Wrote it while investigating #1271. The test passes, so it's unlikely
that the sort itself isn't broken, but this test is useful nevertheless.

It loads a bunch of API definitions with overlapping listen paths in a
semi-random initial order, and then uses them all making sure that the
right API spec responded to the request.

### CODE REVIEW

**Comment by buger** [comment]
I think it makes sense add all permutations to this test, using smth like this https://play.golang.org/p/Ulyo1H2Bii

Basically mix them up, in all possible orders. Also, I would suggest adding sub urls, like `/ab/a` `/ab/c` and etc.

**Comment by buger** [comment]
I think it makes sense add all permutations to this test, using smth like this https://play.golang.org/p/Ulyo1H2Bii

Basically mix them up, in all possible orders. Also, I would suggest adding sub urls, like `/ab/a` `/ab/c` and etc.

**Comment by mvdan** [comment]
Doing all possible permutations in every test run is a bad idea IMHO. It limits the number of APIs we can work with, and it means the test will take O(n!). It's simply too overkill and would waste time and CPU.

However, something I could do (which I planned to do, but ran out of time today) is generate a long list and shuffle it. That way, you could get similar results by doing `go test -run=ThisTest -count=1000`, the test itself would still be fast, and Travis would still catch probabilistic issues over time (much like it finds race bugs, even though you can run the test suite many times without running into them).

**Comment by ewah** [comment]
re. my comment in #1271, would you be able to add custom domains into this test?

**Comment by mvdan** [comment]
I should be able to, yes. Thanks for the heads up.

**Comment by mvdan** [comment]
I mostly re-wrote the test and now I'm working on a fix too, so I'm going to open a new PR.

**Pull request closed without merging**
