### PR TITLE
[TT-9586] Prevent panic in setHasMock func

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR fixes a panic case inside `APISpec.setHasMock` func.

### CODE REVIEW

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5361/merge
Commit: 9ce9f68c8f49ec2854859498daced3d8f4b27110 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5668327630)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5361/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5668315262)

**Pull request merged**
