### PR TITLE
[TT-162] Fix JSVM session metadata usage

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Fix for #3218.

## Description
When `use_session` is enabled, the `SessionMeta` object is expected to contain a content with the following structure:
```json
{"tyk_developer_id":"5f1937ad4ea4611eefb8ede6","tyk_key_request_fields":{},"tyk_user_fields":{}}
```
Because we were previously using `map[string]string`, the key request and user fields break the unmarshalling step.
Using `map[string]interface{}` fixes the issue.

## Related Issue
#3218.

## How This Has Been Tested
Steps described in #3218.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
Can we add simple test for this?

**Comment by matiasinsaurralde** [comment]
Added tests and rebased the changes 👍

**Review by tbuchaillot — APPROVED** [review]
LGTM

**Review by buger — APPROVED** [review]

**Comment by tomshy** [comment]
has this fix been released to v3.1?

**Pull request merged**
