### PR TITLE
Versioning enhancements

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
For #1664.

### CODE REVIEW

**Comment by buger** [comment]
@matiasinsaurralde does it still a WIP? Do you want to include bencmp output?

**Comment by matiasinsaurralde** [comment]
I'm still testing this, have found that my whitelist cache code was making things slower, currently `BenchmarkDefaultVersion` is around 8% faster than `master` but `GetVersionFromRequest` calls can be improved.

**Comment by buger** [comment]
@matiasinsaurralde this PR becomes very old, pls rebase it against latest master and let's merge it.

**Comment by matiasinsaurralde** [comment]
Updated!

**Comment by buger** [comment]
Merged manually

**Pull request closed without merging**
