### PR TITLE
pass auth headers as query params for subscription operation

### PR DESCRIPTION
**Pull request by jay-deshmukh**
- This PR makes a change to pass auth headers as url search params for graphiql playground if the operation is subscription.
- Adds snackbar in case there's an error while establishing connection.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3864/merge
Commit:  
Triggered by: pull_request (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1755273273)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3864/merge
Commit: dc9ab005110d670693f139243ee19c965dc448c6 
Triggered by: pull_request (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1772060832)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3864/merge
Commit: 71da1d840b9cbc284507a6cac52aff60bc2433c5 
Triggered by: pull_request (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1772151501)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3864/merge
Commit: 944fbba7cb87c9aeb08049da3495b2b81eb38019 
Triggered by: pull_request (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1772804036)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3864/merge
Commit: ca7786b2d2d054defb08396eccced4440452a34c 
Triggered by: pull_request (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1776807824)

**Review by spetrunin — APPROVED** [review]

**Review by pvormste — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 044d6fe55cbb09e8fca44ab1481428735d4e6ced pass auth headers as query params for subscription operation (#3864)

* pass auth headers as query params for subscription operation

* modify test

* fix playground test case
Triggered by: push (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1789677968)

**Pull request merged**
