### PR TITLE
[TT-8134] remove driver from required field in OAS schema

### PR DESCRIPTION
**Pull request by jeffy-mathew**
https://tyktech.atlassian.net/browse/TT-8134

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4812/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4289651847)

**Review by titpetric — APPROVED** [review]

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4812/merge
Commit: 1bd558efcef27e6f6127dc47f0a42c9757d79eae 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4290864456)

**Pull request merged**
