### PR TITLE
update graphql-go-tools

### PR DESCRIPTION
**Pull request by pvormste**

### CODE REVIEW

**Review by buraksezer — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3899/merge
Commit:  
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1876758330)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3899/merge
Commit: 65df58baef7a0e6afadbb0a7d441d67ec02ecffc 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1882077430)

**Review by spetrunin — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 5a61b4ae1b41cb234351969dafb8c854c12c91be update graphql-go-tools (#3899)

* update graphql-go-tools

* add `__typename` to the expectedDataSources

Co-authored-by: Burak Sezer <burak.sezer.developer@gmail.com>
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1886156994)

**Pull request merged**
