### PR TITLE
TD-876/release-3.2.3-cleanup

### PR DESCRIPTION
**Pull request by ermirizio**
Cleanup of the files that were already moved under the ci folder

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3917/merge
Commit: 99b26bd79b58d082b7b2fc302235ee0fddad3952 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1946801484)

**Comment by alephnull** [comment]
CI tests failing due to consul. Is it a known flaky test?

**Comment by ermirizio** [comment]
@sredxny , @furkansenharputlu could you please take a look at CI test github action failing?, it seems consul is failing:

https://github.com/TykTechnologies/tyk/blob/f603dec31b91ae9c7221c990b078d82aa04bfece/storage/kv/consul_test.go

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3917/merge
Commit: 486b6c94b9d77652e57b14835fb29a136329dfa0 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2004466097)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3917/merge
Commit: e7cfa5c044bf6b0e90a875ded26b0a9598cadc8d 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2089857152)

**Comment by ermirizio** [comment]
Besides TLSMutual issue on CI, merging , a ticket has been created for this already : https://tyktech.atlassian.net/browse/TT-4954

**Pull request merged**
