### PR TITLE
fix field selection on interface types (TT-4419)

### PR DESCRIPTION
**Pull request by pvormste**
This PR fixes field selection on interface types.
Given a schema:
```graphql
type Query {
  idType: IDType!
}

interface IDType {
  id: ID!
}

type User implements IDType {
  id: ID!
  name: String!
}
```

... and a query:
```graphql
{
  idType {
    id
    ... on User {
      name
    }
  }
}
```

... will now work properly

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

### CODE REVIEW

**Review by spetrunin — APPROVED** [review]

**Review by buraksezer — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3859/merge
Commit:  
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1739765227)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 85fb7c63ce4cb5c55a5673834716e69a614d7e78 fix field selection on interface types (#3859)
Triggered by: push (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1739998386)

**Comment by pvormste** [comment]
manually merged to `release-4-lts`: https://github.com/TykTechnologies/tyk/commit/214cd8211723a2eb68c2bca4742c9c444a2e3550

**Comment by pvormste** [comment]
manually merged to `release-3.2.3`: https://github.com/TykTechnologies/tyk/commit/2cf05087b760e28abb106928d29f225d539a8232

**Pull request merged**
