### PR TITLE
[TT-9168] Improvement: Fix smoke tests docker-compose envs

### PR DESCRIPTION
**Pull request by titpetric**
## Description

Fixes observed smoke tests defects:

- docker compose envs for smoke tests did not work,
- use env before declaring in test.sh, reordered,
- plugin compiler smoke test update go.mod/sum gateway pkg,

Plugin compiler smoke test has go.mod/sum issues, filed TT-9111 to remove a dependency.

## Related Issue

https://tyktech.atlassian.net/browse/TT-9168

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by alephnull** [comment]
I've forgotten why this change was made. I remember discussing this with Asutosh and this was the least terrible option.

@titpetric, @sredxny is joining our catchup today to talk about this, I'll send you an invite. Please try to join us.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5186475255)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: efef17a1b7cb3fff21bc1eb5355cea8c32760f4d 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5187408611)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: 75daa2c576aeb1efbc8164fb3d8c27d08b830e9a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5187887378)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: bc0f7fc058aa360f012b5d0f3e1a4ad2263fd93f 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5187948196)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: b7a2e2049a84239c9493fc2837a4794535a68d10 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5188993950)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: 8b487c35e080642950b70d7da9e1074786ffb4f6 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5189161067)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: e6fd4ef6439edb843a13c2cbdd04f5acdfaf340f 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5189205967)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: 2af4f3fd8c44cba72e60520b5c0bb593c1eaeabe 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5189427856)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: e0c7f8333fe29f3fde6bb4d66f7148be1b86ebc1 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5190024207)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: 08e5f1b6a6d5beaa1c4b8f396c3192b124d18f77 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5190369413)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: 3215d6b0924611db3b1654980c07b78c50a1ccd6 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5191020239)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: 7b2c37aafaf1822b5f3e5a4b7aae214511bc9012 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5190694236)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: 602d32bdd1c154436b6c93697ca69e8690cf89e6 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5191403411)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: fa6aa30c312d31a22aa7a0362e11de8f0630d452 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5191742915)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: 74f40f9deb99ccccfcdbb8ec6381a841b77ded20 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5192045731)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: 5e2fe376eb0dcd0082e6c6c03b35329a0c749c2b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5192259486)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: e599d84bdfd119a9fa88228698f20f392ae3430e 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5192925419)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: f741862b669592d1b193552375f9c13a813fce51 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5193309229)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: 5539af99ffe936bff594a14064820babe5b1dccb 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5196591063)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: 4a1bf4459b2a24613fc573b5157a692d5272903f 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5196838506)

**Review by alephnull — APPROVED** [review]

**Review by sredxny — APPROVED** [review]
lgtm!! 🤞 🚀

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: c06ff30c554a70f750de60a7d49a47c61a260ea5 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5222281970)

**Review by ermirizio — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5106/merge
Commit: 6c68c1a948a329014f770e466c47aebc0de90b65 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5266684921)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5106/merge
Commit: 4edd57195c3b3b5aae69737c18a77646dd34828b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5410622609)

**Pull request merged**
