### PR TITLE
nested gql datasource config

### PR DESCRIPTION
**Pull request by pvormste**
This PR adds new fields to the API definition for GraphQL Data sources, so that they can be used as nested data sources.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4976/merge
Commit:  
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4798014499)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4976/merge
Commit: b2f9694680a0acb1069be17d88dac1d2b9c1f485 
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4798100985)

**Review by tbuchaillot — COMMENTED** [review]
@pvormste do we need to add those new fields to the apidef schema?

**Review by kofoworola — APPROVED** [review]
LGTM

**Comment by pvormste** [comment]
> @pvormste do we need to add those new fields to the apidef schema?

Good catch, haven't looked it up.
The answer is actually: no, because the whole object where the fields are in will be serialized to a json string. That's also way none of the fields in the object are in the schema

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4976/merge
Commit: b2f9694680a0acb1069be17d88dac1d2b9c1f485 
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4798100985)

**Review by tbuchaillot — APPROVED** [review]
LGTM

**Review by buraksezer — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4976/merge
Commit: 5f1abd763f83efccdf47660fffb66911e01f700c 
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4809034127)

**Pull request merged**
