### PR TITLE
Always use pointers for HostList

### PR DESCRIPTION
**Pull request by mvdan**
As discussed in #368. Together with #369, this will make go vet have zero warnings.

### CODE REVIEW

**Comment by mvdan** [comment]
BTW, I'm aware that I'm changing the vendored tykcommon. This makes my life easier to apply all the changes in a single PR and be able to test them and get it reviewed at once. IMO that's better than a first PR to tykcommon.

If this is merged, then I'd do a PR to tykcommon to sync the change.

**Comment by buger** [comment]
I'm not sure if it is a good idea, but for example if we make "tykcommon" git submodule, instead of folder, it may work. What do you think?

**Comment by mvdan** [comment]
I would instead suggest just making it part of this repo. I don't see an advantage in a separate one.

**Comment by lonelycode** [comment]
@mvdan 
> I would instead suggest just making it part of this repo. I don't see an advantage in a separate one.

API Definition objects are big, and they change a lot, instead of having to manually copypasta the object into Tyk Pump and Tyk Dashboard (and MDCB, and Host Manager and Tyk CLI), and hope they are all in sync we have it in a third party repo, it makes life a lot easier.

@buger 
> I'm not sure if it is a good idea, but for example if we make "tykcommon" git submodule, instead of folder, it may work. What do you think?

Not a fan of submodules, I'd rather just not vendor it. The vendoring thing came about because our pipeline CD was having connectivity problems with GH and I was tired of the go get taking an age.

I'd ultimately prefer changes to be made to the original repo instead of the vendor version - we use govendor to handle it and so far it's done an ok job.

With regards to this PR, it looks and smells ok to me, a quick smoke test implies it's safe, needs more rigorous test, but that can be handled at integration.

Any objections? Otherwise I will merge it.

**Comment by buger** [comment]
👍

**Comment by mvdan** [comment]
The same could be done with this repo - all others could depend on this one. I still don't see why a separate git repo helps - if anything, it makes changes like this more complicated.

**Comment by lonelycode** [comment]
> The same could be done with this repo - all others could depend on this one.

Fair point, and one to consider later down the line. Modifying the dependencies across a whole host of projects isn't particularly palatable at the moment :-)

**Pull request merged**
