### PR TITLE
Update global event handlers code

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Not sure if this feature is documented at all but it was breaking my local installation and this was necessary to keep the compatibility (#1678).
Have also changed the variable names a bit, would like to add tests in a separate PR. This might also be related to #1269.

### CODE REVIEW

**Comment by buger** [comment]
@dencoded so, do you approve it?

**Comment by matiasinsaurralde** [comment]
I've simplified this and added the patch from #1693, have also found the reason why global event handlers aren't working anymore (#1678).

**Comment by dencoded** [comment]
looks OK but there is some data race in CI

**Comment by matiasinsaurralde** [comment]
@dencoded Thanks, have found the issue after adding the patch from #1693, will work on a fix

**Comment by matiasinsaurralde** [comment]
Have fixed the issue, tweaked the log handler in order to accept an alternative `logrus.Logger`, by default it will take the standard logger, when running tests we use a custom one to capture the output (something we do in the JSVM tests). Basically removed dup code that caused a race when accessing the buffer from this custom logger.
Note that we use the event system in `event_handler_webhooks_test.go`, in this scenario it's ok to keep using the standard logger (so we can't force the custom logger for the whole event system code), the proposed solution also takes care of this.

**Comment by matiasinsaurralde** [comment]
Also, tried to use these [test hooks](https://github.com/sirupsen/logrus#testing) but the current solution looked simpler.

**Pull request merged**
