### PR TITLE
[TT-2584] Fix panic in JWT when JWK source and no kid in token

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4823/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4322074643)

**Review by andyo-tyk — APPROVED** [review]
Discussed with Furkan and Jeffy (in absence of other engineers).

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4823/merge
Commit: d3534347d2c12c9cf09e8b49a42adad95059d621 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4322098953)

**Pull request merged**
