### PR TITLE
Update test.sh

### PR DESCRIPTION
**Pull request by ermirizio**
Increasing the sleep time for docker compose to avoid flaky smoke tests

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4027/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2242120631)

**Review by alephnull — APPROVED** [review]
ok for now

**Comment by titpetric** [comment]
I proposed to Esteban to use timeout/nc with /dev/tcp devices, to actually check if service is up. Please don't merge as-is.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4027/merge
Commit: 476e52125c904b77f6dbcfd373018234f605b796 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2265719743)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4027/merge
Commit: 299d2f24e65ecc5da0d3df0278d0d2bdbb688e9d 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2266949039)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4027/merge
Commit: 9173fbbbb65aa97b39cb8655f1d2068b054f0c71 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2268976540)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4027/merge
Commit: 757cdcfcee6c631221cc9e4074bae694fa362e8f 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2268980758)

**Comment by ermirizio** [comment]
@titpetric , @asutosh  This is from my perspective what I would like to propagate as mechanism for ensuring a pod is ready to receive API call (Readiness/healthy).
We need a valid health-check that comes from the application itself (done by developers) that we can query, this is best practice and a must. Checking for the port status can be a fair and fallback mechanism but does not tell the whole truth. In this case /hello for GW does the job since it has a json we can parse:
`{"status":"pass","version":"v4.0.0","description":"Tyk GW","details":{"redis":{"status":"pass","componentType":"datastore","time":"2022-05-04T01:18:59Z"}}}`

Implementing the health-check from the docker-compose side is for me better approach since you can rely on native retry mechanism and some other useful options, plus you ensure you move forward with the workflow only if docker compose has succed.
The drawbacks are health-check **test** support a **single command**, so your health-check endpoint needs to be somehow clear to query and easy to parse/process, otherwise you will end-up relying  on external scripts.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4027/merge
Commit: df54dc614c2af304b6280ad26662f801bd7f6e7b 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2271968057)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4027/merge
Commit: 331da80cd002d0ecd6b35bdddf3a6db92452bfc6 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2271963235)

**Review by titpetric — APPROVED** [review]
Much better :) Thank you

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: a4c0c50f85ce1f9a229c3d4450c55b5a2c307d23 Sanitize flaky smoke test python plugin

[Changelog]

* internal: add docker compose v1 propper health-check for python plugin test
Triggered by: push (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2275506936)

**Pull request merged**
