### PR TITLE
[TT-4664] update sprig to v3

### PR DESCRIPTION
**Pull request by jeffy-mathew**
update sprig library to v3 (v3 is compatible with v2, refer - https://tyktech.atlassian.net/browse/TT-4664)
import using `github.com/Masterminds/sprig/v3` instead of `github.com/Masterminds/sprig`
refer - https://github.com/Masterminds/sprig/issues/278

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/3897/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1874975144)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/3897/merge
Commit: 65c0729efc1b8063db2a13d02531391884228ea1 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1887011238)

**Review by furkansenharputlu — APPROVED** [review]

**Review by urbanishimwe — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3897/merge
Commit: 945037d4eb143b52657dd28fc7a7fb12a491c0e0 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1897785408)

**Pull request merged**
