### PR TITLE
[TT-5093] Implement disabled field to validate json plugin

### PR DESCRIPTION
**Pull request by furkansenharputlu**
`disabled` flag is added to validate request plugin to make disable possible for the feature.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4006/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2167018205)

**Review by jeffy-mathew — APPROVED** [review]

**Review by urbanishimwe — APPROVED** [review]
LGTM!

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4006/merge
Commit: 63a10af9f73571ad777a2ca6536498e92ed219ca 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2167160644)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: c4fdc8c837205e6f2bfb3ee47aaed8f0fb5129bd Implement disabled field to validate json plugin (#4006)
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2167291764)

**Pull request merged**
