### PR TITLE
[TT-7126] add authority headers

### PR DESCRIPTION
**Pull request by titpetric**
https://tyktech.atlassian.net/browse/TT-7126

Closes #4221 #3082 

Additional changes:

- added config schema for new `grpc_authority` config option (pass linter tests)

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4966/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4734344240)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by titpetric** [comment]
@vanhtuan0409 thank you for your contribution. Would you be so kind to rerun your grpc service and confirm it resolves your situation with the latest code on master or this branch?

**Pull request merged**
