### PR TITLE
Debug rate limit algorithm being used

### PR DESCRIPTION
**Pull request by gernest**

### CODE REVIEW

**Comment by buger** [comment]
In such sensitive places, we can write it like this:
```
if log.Level == logrus.Debug {
    log.Debug(....)
}
```

**Comment by gernest** [comment]
@asoorm do you have an alternative  suggestion? This was requested by QA team while trying to test rate limiting algorithms feature.

There are about `265` use of `logrus.Fields` in the gateway right now.

**Comment by gernest** [comment]
Ooops, sorry @asoorm I typed my comment faster before @buger comment showed up.

**Comment by buger** [comment]
@gernest, for now, we can apply the trick I mentioned only to rate limiter code (since it is very sensitive)

**Comment by gernest** [comment]
@buger done PTAL

**Pull request closed without merging**
