### PR TITLE
[TD-1044]: Fix some more errors in sync-automation.

### PR DESCRIPTION
**Pull request by asutosh**
## Description
The sync-automation implementation still had some errors. This might fix these.
A modified sample run on tyklabs can be seen here - https://github.com/tyklabs/tyk/runs/7973319658?check_suite_focus=true

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4251/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2911643183)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4251/merge
Commit: 29d5bae7c6e6add73db826166efc9459b3d98082 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2911652096)

**Review by ermirizio — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4251/merge
Commit: b4c7bd93e05547dbe9215ae4e75c205dc2608d2e 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2914179558)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4251/merge
Commit: c68082e4b9a0853d1737b62eb107d5de0f5839e3 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2915992305)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: e19e682bd6a9e8b79c356f9555801f5d7e630504 [TD-1044]: Fix some more errors in sync-automation. (#4251)

* Fix a variable interpolation error.

* Update token for github-script step.
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2917669369)

**Pull request merged**
