### PR TITLE
TT-423 fix grpc proxy connection

### PR DESCRIPTION
**Pull request by sredxny**
## Description
Fix grpc proxy over h2c

## Related Issue
https://tyktech.atlassian.net/browse/TT-423

## Motivation and Context
enable grpc proxy

## How This Has Been Tested
- Run gRPC server (I used https://github.com/grpc/grpc-go/tree/master/examples/helloworld )
- Have an instance of dashboard and gw running
- Create Api definition for the gRPC service:
        - Set an specific port to serve our service via gw (I set 12345)
        - Set Listen Path: /
        - In target-url set the ip:port where the gRPC server is running, it should contain h2c as protocol, in that way the gateway infers that for this API it should use h2c, as an example: `h2c://myservice:50051`
- Consume the gRPC service (I used grpcurl ): `grpcurl -plaintext -proto helloworld.proto -d '{"name": "sredny"}' tyk-gateway:12345 helloworld.Greeter/SayHello`
- Received response:
```
{
  "message": "Hello sredny"
}
```
- Consumed from client app as well
- Consume a REST API, to check that nothing is broken

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [x] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [x] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by sredxny** [comment]
could not set h2c enabled by default for http, it breaks the rest apis and they are not served well. So, it will be enabled only for those apis where target url have the prefix "h2c://"

**Review by matiasinsaurralde — APPROVED** [review]
Have tried the specified scenario. It's looking good.
In addition to the instructions that were described, I've set `disable_ports_whitelist` to `true` in order to allow the gateway to use the additional port that's specified in the API definition.

**Review by tbuchaillot — APPROVED** [review]

**Comment by sredxny** [comment]
> Have tried the specified scenario. It's looking good.
> In addition to the instructions that were described, I've set `disable_ports_whitelist` to `true` in order to allow the gateway to use the additional port that's specified in the API definition.

Good insight! Will add that to the documentation

**Comment by sredxny** [comment]
**Tests Performed**

Here will be described step by step the tests performed using HTTPS and H2C to consume the grpc service via gateway.

**HTTPS**
Pre-requisites:
- gRPC server application (for the terms of testing I used https://github.com/grpc/grpc-go/tree/master/examples/route_guide as its a streaming grpc service). 
- Dashboard and gw running
- One certificate to add to the API
- One certificate to expose the grpc service (the app already support tls)
- `grpcurl` installed in your machine (optional)

Steps:
1. Run the gRPC service using TLS, the route guide application only requires the flag `tls=true` in order to expose it via https. For this example I exposed this server via `https://grpc.test.example.com:10000`
2. Via dashboard create a new API with the next configuration:
           - Protocol: HTTPS
           - Set a custom port (for my test I set 54321)
           - Set a custom domain: I set `tyk`. The certificate that you use for this API will affect which domains can you set.
           - As I tested locally, I had to update the hosts file, I added `127.0.0.1 tyk` to `/etc/hosts`
           - Attach the certificate to the API
           - Set listen path (I set `/`)
           - Now we need to set the Target URL, here it should be the HTTPS location of the service, for this example it will `https://grpc.test.example.com:10000`
3. Now we should be ready to test the solution, and in order to do so, I used grpcurl, so I typed in the terminal: `grpcurl -proto route_guide.proto -d '{"latitude": 1, "longitude":2}' tyk:54321 routeguide.RouteGuide/GetFeature`  and we get a proper response from the server.
4. Worth to notice that we are doing the mapping of the values into headers that are being sent to the grpc server, in the next screenshot we can see that behavior:
Captura de Pantalla 2020-11-01 a la(s) 3 02 38 p  m


**H2C**
Pre-requisites:
- gRPC server application
- Dashboard and GW
- `grpcurl` installed in your machine to consume the service via terminal

Steps:
1. Run the gRPC service (I exposed the service in `localhost:50051`)
2. Create a new API via dashboard, with the next configuration:
- Protocol: HTTP
- Set a custom port (I used `12345`)
- Set a listen path (I set `/`)
- For the Target we must set as protocol `h2c` in the format: `h2c://grpc-service-location`, so I set `h2c://localhost:50051`. Worth to notice that currently the frontend validates the protocol and doesn't allow us to create the API unless we edit this value via _raw definition_ hence, we must create an issue to consider this protocol in the frontend.
3. Now we can test the solution, to consume my service I did: `grpcurl -plaintext -proto helloworld.proto -d '{"name": "sredny"}' tyk-gateway:12345 helloworld.Greeter/SayHello` and get as response:

```
{
  "message": "Hello sredny"
}
```

As a client, to consume the service using H2C is very important to send the flag `-plaintext` in grpcurl. Also we can see that we do a mapping of headers when we use h2c, see the next image:

Captura de Pantalla 2020-11-01 a la(s) 3 20 53 p  m

**Pull request merged**
