### PR TITLE
Fix/tt 11835/go111module 5.0.11

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Related Issue

https://tyktech.atlassian.net/browse/TT-11835

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Review by asutosh — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v5.0.11-alpha3
Commit: ee2d1b06e5cdf5eb3462edf902ba7dd9bedb56ee 
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8603448555)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/tags/v5.0.11-alpha3
Commit: ee2d1b06e5cdf5eb3462edf902ba7dd9bedb56ee 
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8603448555)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v5.0.11-alpha3
Commit: ee2d1b06e5cdf5eb3462edf902ba7dd9bedb56ee 
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8603448555)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/tags/v5.0.11-alpha3
Commit: ee2d1b06e5cdf5eb3462edf902ba7dd9bedb56ee 
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8603448555)

**Review by asutosh — APPROVED** [review]
LGTM

**Pull request merged**
