### PR TITLE
[TT-5210] Added OAS PATCH API

### PR DESCRIPTION
**Pull request by titpetric**

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4047/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2316208996)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4047/merge
Commit: 3304d89004dcf75b4bac9cee98c7793e69333bf1 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2337413899)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4047/merge
Commit: be430b777b8daffa38b1859c0a0eaca8fac364cb 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2337386501)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4047/merge
Commit: 63a7a31f387127a76f3033ea61c9514330eba3bb 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2338288598)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4047/merge
Commit: 71f6211b5e4095ce8071d554aceee46efdb1aff6 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2338465393)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4047/merge
Commit: 71f6211b5e4095ce8071d554aceee46efdb1aff6 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2338465393)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4047/merge
Commit: 979a56558f4ee97407845efdb39400ad1a99b8af 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2339183417)

**Comment by titpetric** [comment]
Closing as obsolete, was implemented differently

**Pull request closed without merging**
