### PR TITLE
add TestChecker_triggerSampleLimit

### LINKED ISSUE #2698: Uptime tests: `failure_trigger_sample_size` not honoured
**Branch/Environment/Version**
Gateway              :v 2.9.1
Dashboard          :v1.9.1
- Environment: On-prem

**Describe the bug**
Setting `failure_trigger_sample_size` as per the [documentation](https://tyk.io/docs/ensure-high-availability/uptime-tests), defines the number of failures to wait before triggering a `HostDown` event.

However, the HostDown event is not triggered even if the number of failures is exceeded.

**Reproduction steps**
1. Define an API that will return a failure, or times out
2. Define uptime checks as follows:
```
"uptime_tests": {
  "disable": false,
  "config": {
    "failure_trigger_sample_size": 4,
    "time_wait": 300,
    "checker_pool_size": 50
  }
```
3. In the gateway logs that you should see messages of the form: `[HOST CHECKER] [HOST DOWN BUT NOT REACHED LIMIT]: <url>`

**Actual behavior**
The `HostDown` event is never triggered.

**Expected behavior**
The `HostDown` event should be triggered when the number of failures set in `failure_trigger_sample_size` is exceeded.

**Logs (debug mode or log file):**
```
time="Nov 26 17:45:14" level=warning msg="[HOST CHECKER] [HOST DOWN BUT NOT REACHED LIMIT]: http://localhost:8181/status/400"
time="Nov 26 17:46:20" level=warning msg="[HOST CHECKER] [HOST DOWN BUT NOT REACHED LIMIT]: http://localhost:8181/status/400"
time="Nov 26 17:47:22" level=warning msg="[HOST CHECKER] [HOST DOWN BUT NOT REACHED LIMIT]: http://localhost:8181/status/400"
time="Nov 26 17:48:36" level=warning msg="[HOST CHECKER] [HOST DOWN BUT NOT REACHED LIMIT]: http://localhost:8181/status/400"
time="Nov 26 17:49:49" level=warning msg="[HOST CHECKER] [HOST DOWN BUT NOT REACHED LIMIT]: http://localhost:8181/status/400"
time="Nov 26 17:50:50" level=warning msg="[HOST CHECKER] [HOST DOWN BUT NOT REACHED LIMIT]: http://localhost:8181/status/400"
time="Nov 26 17:52:02" level=warning msg="[HOST CHECKER] [HOST DOWN BUT NOT REACHED LIMIT]: http://localhost:8181/status/400"
```

**Additional context**
I suspect that in `if count, found := h.sampleCache.Get(failedHost.CheckURL); found {` which is defined in [HostReporter](https://github.com/TykTechnologies/tyk/blob/67dd91027031b81e2b23286e639b17207ed77503/gateway/host_checker.go#L145) `h.sampleCache` is local to the goroutine. Thus, each time it is called you get the failure count from a different goroutine which leads to the behaviour seen.

### LINKED ISSUE #2839: UptimeTest tyk proxies requests to upstream when Host is Down
**Branch/Environment/Version**
- Branch/Version: master / release-2.9
- Environment: on prem

**Describe the bug**
With Uptime Tests and this feature "Use Uptime Tests with Target URL" we should not proxy request until the host is UP again. However, this currently does not happen and Tyk tries to proxy requests when Host is DOWN. 

part of the log where you can see that host is down and tyk proxies the requests
```
[Jan 27 10:19:04]  WARN host-check-mgr: [HOST CHECKER MANAGER] Host is DOWN: http://w2nothing.org/health
[Jan 27 10:19:31]  WARN HOST CHECKER: [HOST DOWN BUT NOT REACHED LIMIT]: http://w2nothing.org/health
[Jan 27 10:20:02]  WARN HOST CHECKER: [HOST DOWN BUT NOT REACHED LIMIT]: http://w2nothing.org/health
[Jan 27 10:20:29]  WARN HOST CHECKER: [HOST DOWN]: http://w2nothing.org/health
[Jan 27 10:20:29]  WARN host-check-mgr: [HOST CHECKER MANAGER] Host is DOWN: http://w2nothing.org/health
[Jan 27 10:20:59]  WARN HOST CHECKER: [HOST DOWN BUT NOT REACHED LIMIT]: http://w2nothing.org/health
[Jan 27 10:21:32]  WARN HOST CHECKER: [HOST DOWN BUT NOT REACHED LIMIT]: http://w2nothing.org/health
[Jan 27 10:22:01]  WARN HOST CHECKER: [HOST DOWN]: http://w2nothing.org/health
[Jan 27 10:22:01]  WARN host-check-mgr: [HOST CHECKER MANAGER] Host is DOWN: http://w2nothing.org/health
[Jan 27 10:22:31] ERROR PROXY: [LOAD BALANCING] all hosts are down, uptime tests are failing
[Jan 27 10:22:33]  WARN HOST CHECKER: [HOST DOWN BUT NOT REACHED LIMIT]: http://w2nothing.org/health
[Jan 27 10:22:34] ERROR PROXY: [LOAD BALANCING] all hosts are down, uptime tests are failing
[Jan 27 10:22:45] ERROR PROXY: [LOAD BALANCING] all hosts are down, uptime tests are failing
[Jan 27 10:22:54] ERROR PROXY: [LOAD BALANCING] all hosts are down, uptime tests are failing
[Jan 27 10:23:04]  WARN HOST CHECKER: [HOST DOWN BUT NOT REACHED LIMIT]: http://w2nothing.org/health
[Jan 27 10:23:21] ERROR proxy: http: proxy error: dial tcp: lookup w2nothing.org: no such host api_id=178584466495484f46b37d835c220d82 api_name=api mw=ReverseProxy org_id=5e2e9e28fe238f084b91ea38 server_name=w2nothing.org user_id=****ef9d user_ip=127.0.0.1 user_name=
[Jan 27 10:23:33]  WARN HOST CHECKER: [HOST DOWN]: http://w2nothing.org/health
[Jan 27 10:23:33]  WARN host-check-mgr: [HOST CHECKER MANAGER] Host is DOWN: http://w2nothing.org/health
[Jan 27 10:23:38] ERROR PROXY: [LOAD BALANCING] all hosts are down, uptime tests are failing
[Jan 27 10:24:00]  WARN HOST CHECKER: [HOST DOWN BUT NOT REACHED LIMIT]: http://w2nothing.org/health
[Jan 27 10:24:03] ERROR PROXY: [LOAD BALANCING] all hosts are down, uptime tests are failing
[Jan 27 10:24:30]  WARN HOST CHECKER: [HOST DOWN BUT NOT REACHED LIMIT]: http://w2nothing.org/health
[Jan 27 10:24:34] ERROR proxy: http: proxy error: dial tcp: lookup w2nothing.org: no such host api_id=178584466495484f46b37d835c220d82 api_name=api mw=ReverseProxy org_id=5e2e9e28fe238f084b91ea38 server_name=w2nothing.org user_id=****ef9d user_ip=127.0.0.1 user_name=
[Jan 27 10:24:59]  WARN HOST CHECKER: [HOST DOWN]: http://w2nothing.org/health
[Jan 27 10:24:59]  WARN host-check-mgr: [HOST CHECKER MANAGER] Host is DOWN: http://w2nothing.org/health
[Jan 27 10:25:27]  WARN HOST CHECKER: [HOST DOWN BUT NOT REACHED LIMIT]: http://w2nothing.org/health
[Jan 27 10:25:54]  WARN HOST CHECKER: [HOST DOWN]: http://w2nothing.org/health
```

you can see that some requests are correctly rejected with `[LOAD BALANCING] all hosts are down` but some actually are proxied through `proxy: http: proxy error: dial tcp: lookup`

**Reproduction steps**

1. set this in tyk.conf
```
"uptime_tests": {
        "disable": false,
        "config": {
            "failure_trigger_sample_size": 2,
            "time_wait": 30,
            "checker_pool_size": 5,
            "enable_uptime_analytics": true
        }
    },
```
2. create api with those features
- Enable round-robin load balancing
- Use Uptime Tests with Target URL
- Use Uptime Tests with Target URL Check URLs

[sample_api.txt](https://github.com/TykTechnologies/tyk/files/4116387/sample_api.txt)

3. bring down the target host
4. wait for Tyk to send event Host Down
5. send some traffic to API
- first time you get proper response `all hosts are down`

6. Observe logs, at some point Uptime Tests show this in log `[HOST DOWN BUT NOT REACHED LIMIT]` 

6. send traffic to API again

**Actual behavior**
Tyk tries to proxy traffic to upstream

**Expected behavior**
Tyk should not proxy traffic until host is marked as UP in uptime tests.

### PR DESCRIPTION
**Pull request by gernest**
This adds a test for uptime tests failure_trigger_sample_size option

closes #2698

The debug logs are correct. Its just .a misunderstanding on how this
option work. If failure_trigger_sample_size=3 if the check fails 3
consecutive times one event is fired of host down.

there is a difference  between logs and event firing.

This doesn't mean the check loop is stopped, the check will continue
but events will only fire based on the limit.

### CODE REVIEW

**Comment by buger** [comment]
Can we make logs more clear then?

**Comment by gernest** [comment]
@buger they are already clear to me . alok was only fixated on next host checks logs after the event has been fired( probably also before the event was fired. They are what they should be. They were only taken out of context.

**Comment by buger** [comment]
@gernest pls prepare it for merging, needs gofmt

**Comment by gernest** [comment]
@buger done

**Pull request merged**
