### PR TITLE
[TT-9477] Fix hardcoded config in tests, add fillenv

### PR DESCRIPTION
**Pull request by titpetric**
## Description

- Adds config.New()
- Adds config.FillEnv()
- Fixes index out of bounds in config.Load
- Fixes tests that used the defaults

## Related Issue

https://tyktech.atlassian.net/browse/TT-9477

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5392/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5777647044)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5392/merge
Commit: 5d6c35ad3de8c1edf1dcdb04ee0c0466d28afb81 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6639738733)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5392/merge
Commit: 26df0fb66aa081647cc2781788f35c71f9f15ee5 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6640198046)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5392/merge
Commit: 1bda3b29c7065dc2bcdde04ad86ddeede27561c4 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6654145801)

**Pull request merged**
