### PR TITLE
Ensure that RPC loader returns an object, not nil. 

### LINKED ISSUE #510: Ensure that RPC loader returns an object, not nil
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If the RPC API Definition loader has a disconnect event, it can return a nil object which fails up the chain and causes a runtime panic

**What is the expected behavior?**
The RPC loader should return an empty object

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Not easily reproducible, it requires longitudinal monitoring of a live process against MDCB.

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Hybrid / RPC mode of all gateways

### PR DESCRIPTION
**Pull request by lonelycode**
Fixes #510

### CODE REVIEW

**Comment by mvdan** [comment]
Could the commit message or the code mention why this is necessary?

Also, I assume this also affects master? Or it doesn't because we now return `[]*ApiSpec` instead of `*[]*ApiSpec`?

**Comment by mvdan** [comment]
We generally don't use PRs in milestones, we use the issues they fix/refer, so removing.

**Comment by buger** [comment]
So basically, when it experience error it fallback to last cached value, which looks sane. 👍

**Comment by buger** [comment]
@matiasinsaurralde updated comment

**Comment by mvdan** [comment]
> So basically, when it experience error it fallback to last cached value, which looks sane.

Where do you get that from? This just returns an empty list.

**Comment by buger** [comment]
Oops, did not expanded context till that point and was confused a bit by variable name, we have similar global name... :grimacing:

**Comment by buger** [comment]
Actually, I do not think that this fix may work. I will try to add basic test.

But basically, returning `nil` is expected and handled everywhere, like here:
```go
specs := getAPISpecs()
if specs != nil {
    loadApps(specs, defaultRouter)
    getPolicies()
}
```

**Comment by mvdan** [comment]
@buger this is why I'm asking for more details as to why this fixes it.

In any case, we will be doubly safe in 2.4 since it's no longer a pointer in master.

**Comment by buger** [comment]
I wrote a test and found the reason for a `panic`. It fails on this, and following lines:

```
	log.WithFields(logrus.Fields{
		"prefix": "main",
	}).Printf("Detected %v APIs", len(*APISpecs))
```
https://github.com/TykTechnologies/tyk/blob/f82315b8d49a5e4902837af7a443427164a1b49e/main.go#L244:1-L245:1

Basically all `getAPISpecs()` calls handle if it returns `nil` but `getAPISpecs()` itself internally does not handle such situation. Will push a commit soon.

**Comment by buger** [comment]
Added proper fix and tests. 

Since *[] was removed in master, this bug should not affect it, but I still want to merge tests with few changes.

**Comment by mvdan** [comment]
Having the tests in master sounds like a good idea.

**Comment by mvdan** [comment]
Your changes look fine, but I would squash the two commits. Your commit is partly just reverting all of martin's changes.

**Pull request merged**
