### PR TITLE
[TT-5591] Change oas import path to be consistent

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Review by jeffy-mathew — APPROVED** [review]

**Review by urbanishimwe — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4107/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2433210681)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4107/merge
Commit: 1af128d4ff6fe4a118896422fa98d98cb7651de1 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2446580007)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 8cb0da1cc57ca65da14b0b9996f2f952875f1ad9 Change oas import path to be consistent (#4107)
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2446652186)

**Pull request merged**
