### PR TITLE
[TT-13139] Request times out in some cases when sending input via http inputs

### PR DESCRIPTION
**Pull request by buraksezer**
### **User description**
PR for https://tyktech.atlassian.net/browse/TT-13139

* `defaultStreamManager` has removed, I used Gorilla's muxer directly instead of creating a default stream manager at the beginning
* I managed to remove some code because `defaultStreamManager` is gone.
* `ProcessRequest` method has simplified and split into different methods for readability. 
* Tyk Streams not creating a new Bento stream if you publish messages via the HTTP endpoint. It iterates over the existing streams and hands over the request to Bento.
* Added two new integration tests

___

### **PR Type**
Enhancement, Tests

___

### **Description**
- Removed the `defaultStreamManager` and refactored the streaming middleware to use Gorilla's muxer directly, simplifying the codebase.
- Enhanced the `ProcessRequest` method by splitting it into smaller, more manageable functions for better readability and maintainability.
- Introduced new methods such as `registerHandlers`, `inputHttpServerPublishHandler`, and `subscriptionHandler` to improve HTTP request handling.
- Added integration tests to verify the functionality of HTTP server input handling, ensuring that messages are correctly received by WebSocket clients.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>mw_streaming.go</strong><dd><code>Refactor streaming middleware and enhance HTTP handling</code>&nbsp; &nbsp; </dd></summary>
<hr>

gateway/mw_streaming.go

<li>Removed the <code>defaultStreamManager</code> and used Gorilla's muxer directly.<br> <li> Simplified and refactored <code>ProcessRequest</code> method.<br> <li> Added new methods <code>registerHandlers</code>, <code>inputHttpServerPublishHandler</code>, and <br><code>subscriptionHandler</code>.<br> <li> Introduced <code>dummyResponseWriter</code> for handling HTTP responses.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6592/files#diff-6f565750150d990575c808f1ca8f38483160dc6edf05f1534cd0bedb27c2e6c8">+191/-82</a></td>

</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>mw_streaming_test.go</strong><dd><code>Add integration tests for HTTP server input handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

gateway/mw_streaming_test.go

<li>Added integration tests for HTTP server input handling.<br> <li> Introduced new test templates for HTTP server input.<br> <li> Verified WebSocket message reception for single and multiple clients.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6592/files#diff-a0d1bd0196a741537a3c850e340225c8993e49d709c838af0f1b48b9893af1da">+119/-1</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by buger** [comment]
@buraksezer if there is no defaultStreamManager how it would support background jobs? You have to create default streamManager if theare no http_server entries in any case. E.g. you have a input as kafka, and output as webhook. 

Also you can't depend on `findHTTPServerInputPath`, you should use `GetHTTPPaths`, because `findHTTPServerInputPath` does not consider `broker`. Also it check only for `input` but it should work with `output` too.

**Review by buger — CHANGES_REQUESTED** [review]
@buraksezer if there is no defaultStreamManager how it would support background jobs? You have to create default streamManager if theare no http_server entries in any case. E.g. you have a input as kafka, and output as webhook.

Also you can't depend on findHTTPServerInputPath, you should use GetHTTPPaths, because findHTTPServerInputPath does not consider broker. Also it check only for input but it should work with output too.

**Comment by buraksezer** [comment]
> @buraksezer if there is no defaultStreamManager how it would support background jobs? You have to create default streamManager if theare no http_server entries in any case. E.g. you have a input as kafka, and output as webhook.

I tried to fix this by calling `s.createStreamManager(nil)` in `Init` method. Could you please review it again?

> Also you can't depend on findHTTPServerInputPath, you should use GetHTTPPaths, because findHTTPServerInputPath does not consider broker. Also it check only for input but it should work with output too.

I understood the issue but I'm not sure how to extract `path` from the return value of `GetHTTPPaths`. I thought I only need the configuration variable named `path` of the `input` section. 

Here it is: https://warpstreamlabs.github.io/bento/docs/components/inputs/http_server/#path

**Review by kofoworola — APPROVED** [review]

**Comment by buraksezer** [comment]
@buger 
> Also you can't depend on findHTTPServerInputPath, you should use GetHTTPPaths, because findHTTPServerInputPath does not consider broker. Also it check only for input but it should work with output too.

I would like to extend the previous comment.`inputHttpServerPublishHandler` only intended in the case of HTTP Server is configured as input. So `findHTTPServerInputPath` only tries to find this configuration element: https://warpstreamlabs.github.io/bento/docs/components/inputs/http_server/#path

**Pull request closed without merging**
