### PR TITLE
Add mascot headers to healthcheck '/hello' endpoint

### LINKED ISSUE #2930: We should embed some of our amazing mascot branding in the code
**Is your feature request related to a problem? Please describe.**
Per [this Slack thread](https://tyktech.slack.com/archives/CKJM7HK0W/p1584383928024000) we should embed an ASCII rendition of our mascot somewhere in the gateway.

**Describe the solution you'd like**
Have [this ASCII-fied image](https://asciify.me/uploads/5e70b1da92acc) from our branding library be returned from an arbitrary endpoint, e.g. `/mascot` or `/logo` or maybe include it with the existing `/hello` or `/health` endpoints.

**Describe alternatives you've considered**
Outputting ASCII art (especially with this large size) to stdout/stderr would make a mess of the logs, so it definitely shouldn't go there.

**Additional context**
🤩 image 🤩

### PR DESCRIPTION
**Pull request by jlucktay**
## Description

Adds our amazing mascot branding to the code in an inobtrusive way.

## Related Issue

Resolves #2930.

## Motivation and Context

[This Slack thread](https://tyktech.slack.com/archives/CKJM7HK0W/p1584383928024000) and [this tweet](https://twitter.com/thingskatedid/status/1278274012754309120).

## How This Has Been Tested

Locally.

## Screenshots (if appropriate)

```
$ curl --include localhost:8080/hello
HTTP/1.1 200 OK
Content-Type: application/json
X-Mascot-000: 
X-Mascot-001: .                   ╲╲╲╲╲╲
X-Mascot-002: .                   ╲╲╲╲╲╲╲╲╲
X-Mascot-003: .            *******╲╲╲╲╲╲╲╲╲╲╲
X-Mascot-004: .           **********╲╲╲╲╲╲╲╲╲╲
X-Mascot-005: .        ***************╲╲╲╲╲╲╲╲╲╲
X-Mascot-006: .      ******************╲╲╲╲╲╲╲╲╲
X-Mascot-007: .     ********************╲╲╲╲╲╲╲╲╲
X-Mascot-008: .    ***********************╲╲╲╲╲╲╲╲
X-Mascot-009: .   *************************** ╲╲╲╲╲╲
X-Mascot-010: .   ****************************    ╲╲╲
X-Mascot-011: .   *****      *******      ****     _______      _        _
X-Mascot-012: .   ******      *****      *****    |__   __|    | |      (_)
X-Mascot-013: .   ****************************       | | _   _ | | __    _   ___
X-Mascot-014: .   *****************************      | || | | || |/ /   | | / _ \
X-Mascot-015: .   ******************************     | || |_| ||   <  _ | || (_) |
X-Mascot-016: .  ********************************    |_| \__, ||_|\_\(_)|_| \___/
X-Mascot-017: . *********************************         __/ |
X-Mascot-018: . ***  ************* *********  ****       |___/
X-Mascot-019: .       *********************
X-Mascot-020: .         *****************
X-Mascot-021: .          ******* ******
X-Mascot-022: .            ***** *****
X-Mascot-023: .           ****** ******
X-Mascot-024: 
Date: Fri, 03 Jul 2020 10:28:41 GMT
Content-Length: 60

{"status":"pass","version":"v3.0.0","description":"Tyk GW"}
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by excieve** [comment]
Like it! Just a slight concern to voice: health checks are called pretty frequently though LB/k8s/etc. This might increase cumulative traffic for it somewhat without adding a useful payload (the mentioned systems won't be even able to appreciate the beauty of it). Might not be a problem, but would be good to calculate size increase and how it affects e.g. daily LB->gw traffic. Also there are typically limits on header size — shouldn't be a problem in this case I think, but just to keep in mind.

**Comment by jlucktay** [comment]
Are there any other boilerplatey/always-present endpoints to reattach this to? This was just the first place I thought of.
The concern around traffic increase is worth considering for sure. 👍

**Comment by asoorm** [comment]
Application startup?

**Comment by asoorm** [comment]
Or maybe only generate the headers for the very first time the healthcheck endpoint is called?

**Comment by jlucktay** [comment]
> Or maybe only generate the headers for the very first time the healthcheck endpoint is called?

I like that; I'll put it behind a `sync.Once`. 🚀

**Comment by buger** [comment]
Nice! But there is one security issue which we need to solve first. 
Adding a unique way to detect software in any pen-test considered as a security issue.
E.g. all data should be anonymous. 

How we can address it?

**Comment by joshblakeley** [comment]
> Nice! But there is one security issue which we need to solve first.
> Adding a unique way to detect software in any pen-test considered as a security issue.
> E.g. all data should be anonymous.
> 
> How we can address it?

Hello endpoint goes on a secure router so needs a key to get a response?

**Comment by buger** [comment]
It was never protected by a key. 
Also, our default config assume that control API is on the same port. 
If we want to merge it, we also should supply an option to disable this mascot, plus we should update our production setup documentation and tell that control API should be moved to a separate port.

**Comment by joshblakeley** [comment]
> It was never protected by a key.
> Also, our default config assume that control API is on the same port.
> If we want to merge it, we also should supply an option to disable this mascot, plus we should update our production setup documentation and tell that control API should be moved to a separate port.

It was never protected but it was also not giving any real info when it was `hello tiki`. With the nice feature info approach we have now sticking it on the control API router makes sense.

**Comment by buger** [comment]
Ok, lets make it respect `hide_generator_header` existing config options and I'll be happy :)

**Comment by jlucktay** [comment]
> Ok, lets make it respect `hide_generator_header` existing config options and I'll be happy :)

7b041d6 should cover this off @buger

**Comment by jlucktay** [comment]
The `TestGraphQL_HeadersInjection` test seems flaky; it passed 15 times in a row and then failed the 16th when I ran it like this:

```shell
$ go test -timeout 30s -run "^TestGraphQL_HeadersInjection$" github.com/TykTechnologies/tyk/gateway -count=100 -failfast -v
```

**Comment by buger** [comment]
Looks solid!

**Comment by buger** [comment]
(forwarded feedback on GraphQL test)

**Comment by buger** [comment]
@jlucktay can you also create Jira ticket for manage squad, for 3.3, so it will be properly tested and not forgotten.

**Comment by jlucktay** [comment]
I just pushed https://github.com/TykTechnologies/tyk/commit/5d38fb80e836c6c6152af1a6a0f30b2697df7c15 to stabilise the test. Will do the Jira things now.

**Comment by buger** [comment]
I think you will need raise a separate PR for the test, since I already merged your mascot PR.

**Comment by jlucktay** [comment]
> @jlucktay can you also create Jira ticket for manage squad, for 3.3, so it will be properly tested and not forgotten.

The Jira ticket is here @buger: https://tyktech.atlassian.net/browse/TT-2020

**Comment by jlucktay** [comment]
#3509 should stabilise the flaky test.

**Comment by pvormste** [comment]
Thanks @jlucktay !
I created a jira bug for it - seems I can close it then? https://tyktech.atlassian.net/browse/TT-2021

**Pull request merged**
