### PR TITLE
[TT-6905] Add GoDoc for OAS OAuth introspection fields

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR adds GoDoc for OAuth introspection.

### CODE REVIEW

**Review by marksou — APPROVED** [review]

**Review by lghiur — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4370/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3335327580)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4370/merge
Commit: 75ebc73d2b8587f78b4e2313fd67dc90fc95cc04 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3335505699)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4370/merge
Commit: 05a2bbcd9c5ae278722a5713ea978e261f2b4357 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3335617859)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 7d336b516718c8f3310fbaa3d4349ccec7f855d7 Add GoDoc for OAS OAuth introspection fields (#4370)
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3335791999)

**Pull request merged**
