### PR TITLE
Fix/tt 1540 graphql headers

### PR DESCRIPTION
**Pull request by spetrunin**
## Related Issue
https://tyktech.atlassian.net/browse/TT-1539
https://tyktech.atlassian.net/browse/TT-1540

https://tyktech.atlassian.net/browse/TT-1543 - fixing this one by vendoring latest graphql-go-tools

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
How we can add a test for it?

**Review by furkansenharputlu — CHANGES_REQUESTED** [review]
Any test?

**Comment by furkansenharputlu** [comment]
A simple rest http server which returns header value can be used as a datasource.

**Comment by furkansenharputlu** [comment]
I had a small investigation and saw that the existing test server can be expanded. See the following handler functions:

https://github.com/TykTechnologies/tyk/blob/5155e1e2d41f1749b2c29241025b6107cd983e0e/gateway/testutil.go#L581
https://github.com/TykTechnologies/tyk/blob/5155e1e2d41f1749b2c29241025b6107cd983e0e/gateway/testutil.go#L606

**Review by furkansenharputlu — APPROVED** [review]

**Review by pvormste — APPROVED** [review]

**Comment by spetrunin** [comment]
@buger should we merge this to release-3.2?

**Comment by buger** [comment]
if it is part of it yes

**Pull request merged**
