### PR TITLE
releng: [TD-341] fix python plugins

### PR DESCRIPTION
**Pull request by alephnull**
## Description
Reverts 707bb05dd and propagates the python plugin fix from master.

## Related Issue
https://tyktech.atlassian.net/browse/TD-341

## How This Can Been Tested
Once this is merged, make an -rc tag on release-3.2.0 and then use the generated images to check if Python plugins work correctly. Test infra is available at https://github.com/TykTechnologies/tyk-ci/blob/master/compose/python.yml

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by alephnull** [comment]
Known CI test failure:
```
--- FAIL: TestReloadLoop_basic (0.10s)
```

**Review by excieve — COMMENTED** [review]
Looks fine, but there's a CI workflow failure:
```
#17 0.727 Errors were encountered while processing:
#17 0.727  /tyk-gateway_0.0.0-SNAPSHOT-11096db4_linux_arm64.deb
#17 ERROR: executor failed running [/bin/sh -c dpkg -i /*.deb && rm /*.deb]: exit code: 1

#7 [linux/arm64 2/6] RUN apt-get update     && apt-get dist-upgrade -y ca-certificates
#7 sha256:eb9d380ea931a948c4c43c4c9d07231b84e514d809a903160f3402ec61807d49
#7 CANCELED
------
 > [linux/amd64 5/6] RUN dpkg -i /*.deb && rm /*.deb:
------
Dockerfile.std:23
--------------------
  21 |     
  22 |     COPY *.deb /
  23 | >>> RUN dpkg -i /*.deb && rm /*.deb
  24 |     
  25 |     ARG PORTS
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c dpkg -i /*.deb && rm /*.deb]: exit code: 1
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c dpkg -i /*.deb && rm /*.deb]: exit code: 1
```

Also, does it actually fix the Go plugin issues or just the Python runtime?

**Comment by alephnull** [comment]
Yeah, this is still WIP. Converting to draft.

**Comment by alephnull** [comment]
Also fixed title.

**Comment by alephnull** [comment]
the CI tests catch the goplugin problem.

```
--- FAIL: TestGoPluginResponseHook (1.53s)
    --- FAIL: TestGoPluginResponseHook/Run_Go-plugin_all_middle-wares (0.00s)
```

**Review by excieve — APPROVED** [review]
Thanks @alephnull! I'm guessing that test suite failing is some unrelated flakiness?

**Comment by alephnull** [comment]
> I'm guessing that test suite failing is some unrelated flakiness?

The test suite has a couple of known unknowns. TestReloadLoop is one of them.

**Pull request merged**
