### PR TITLE
[TT-9590] Bump the redis import to v9, add internal/redis to manage the imports

### PR DESCRIPTION
**Pull request by titpetric**
This PR bumps the redis/v8 dependency and related packages to v9.

It creates `internal/redis` package to manage the import and list the symbols used in that package.

https://tyktech.atlassian.net/browse/TT-9590

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5941/merge
Commit: 02df873e646aecb0f6cb8223021d271ed8c15def 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7542452903)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5941/merge
Commit: 02df873e646aecb0f6cb8223021d271ed8c15def 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7542452903)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5941/merge
Commit: 02df873e646aecb0f6cb8223021d271ed8c15def 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7542452903)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5941/merge
Commit: 02df873e646aecb0f6cb8223021d271ed8c15def 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7542452903)

**Review by tbuchaillot — APPROVED** [review]

**Pull request merged**
