### PR TITLE
TT-10153 Fix OTel memory leak

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

This PR updates the opentelemetry lib to the latest version (v0.0.19) which includes https://github.com/TykTechnologies/opentelemetry/pull/32 and https://github.com/TykTechnologies/opentelemetry/pull/30 fixes. 
## Related Issue

https://tyktech.atlassian.net/browse/TT-10153
## Motivation and Context

https://tyktech.atlassian.net/browse/TT-10153
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5587/merge
Commit:  
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6416154350)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5587/merge
Commit: 5b7f35f7a69467578240bd777c60741c81c6553f 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6420117856)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5587/merge
Commit: 8b7515bd2c710edd64733e16a58cd0ec72455568 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6420303754)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5587/merge
Commit: 6c0ee4a066901def360fc357138f0a547ab11bdc 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6421013439)

**Review by mativm02 — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5587/merge
Commit: ad3a345c8741750db3e5a42b4b25a1649d0c9f15 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6428984490)

**Pull request merged**
