### PR TITLE
Added ARM64 jobs to .travis.yml file

### PR DESCRIPTION
**Pull request by odidev**
## Description

1. Added ARM64 job in travis.
2. Increased timeout in gateway/testutil.go
3. Increased timeout in bin/ci-tests.sh

## Related Issue
https://github.com/TykTechnologies/tyk/issues/3313

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by alephnull — APPROVED** [review]
This LGTM. This downloads and builds moonjit on _every_ build. If in the future you need this to run a little quicker, you could build and cache the version (2.2.0) so that you do not need to build it everytime. https://docs.travis-ci.com/user/caching/#arbitrary-directories

**Comment by odidev** [comment]
Can you please review and let me know if any changes are required?

**Comment by christtyk** [comment]
@buger @alephnull can we review and merge?

**Comment by furkansenharputlu** [comment]
As we don't use travis anymore, we will close this PR. Thanks for your contribution @odidev!

**Pull request closed without merging**
