### PR TITLE
Generate list of env var names for Config

### PR DESCRIPTION
**Pull request by gernest**
Many people are not so sure about env var names to use
when overiding config values. This  patch generates config_env_vars.md.

The file lists all possible env var names for tyk config.
A test is present to ensure the file is updated when config changes.

## Description
Based on our [docs](https://tyk.io/docs/tyk-configuration-reference/environment-variables/) some variables will be wrongly constructed for instance `TYK_GW_TRACING_ENABLED` might be assumed to be correct while `TYK_GW_TRACER_ENABLED` is the correct env var.
 
## Related Issue
https://github.com/TykTechnologies/tyk-docs/issues/1187

## Motivation and Context
This has been asked so many times on slack.

## How This Has Been Tested
The variables are automatically generated by the library which we use. Tests are included in the library.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [x] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [x] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by sedkis** [comment]
You.
Are.
A.
Legend

**Comment by marksou** [comment]
I'm going to take the markdown file and cross reference with existing GW Config page - https://tyk.io/docs/tyk-configuration-reference/tyk-gateway-configuration-options/. I'll add the equivalent env var to the json value. We can then see if there are any gaps in Config page. Thanks @gernest

**Comment by buger** [comment]
Can we get full JSON key, e.g. with parent keys?

**Comment by gernest** [comment]
@buger  Nope, we can't. That will require separate work outside of the `envconfig` API and I don't see any point of it as it is beyond the scope of this PR.

**Pull request closed without merging**
