### PR TITLE
[TT-9924]remove muxer, proxy from explicitRouteHandler

### PR DESCRIPTION
**Pull request by jeffy-mathew**
Remove muxer, router from explicitRouteHandler

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5482/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6025132942)

**Review by zalbiraw — APPROVED** [review]
LGTM

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5482/merge
Commit: 8661f39405c5c4c3dab74e6b91421690c2f0905b 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6025303981)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5482/merge
Commit: c99ceeef68ff605e610a13aa303c4c4357fdc7fb 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6025376229)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5482/merge
Commit: 94519133b82082276ea7d9feb0a41b244ff7b4c1 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6035509573)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5482/merge
Commit: 88a87ed5b68fb444ab1482f37eba9ebf6ee20066 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6035555240)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5482/merge
Commit: 4d76c17045f856c83ddc2e27648fac2e215cab7a 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6035559007)

**Review by lghiur — APPROVED** [review]

**Pull request merged**
