### PR TITLE
[TT-9060] Makefile improvement : default docker build platform 

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

This PR adds a default build_platform and the option to set the build platform when using Make commands.

This allows developers with MacOS to run `make docker` and build the `internal/tyk-gateway` docker image. 

[https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images](https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images
)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4470/merge
Commit:  
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3592619231)

**Review by ermirizio — APPROVED** [review]
Lgtm

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: cancelled** :no_entry_sign: 
Branch used: refs/pull/4470/merge
Commit: 8f2f81e8b775e91278268489ea4b54f83a07b697 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5143670959)

**Pull request merged**
