### PR TITLE
[TT-5766] Call GraphQL execution engine to run introspection query

### PR DESCRIPTION
**Pull request by buraksezer**
See [TT-5766](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-5766) on Jira.

Related issues:

- https://github.com/TykTechnologies/graphql-go-tools/pull/178
- https://github.com/wundergraph/graphql-go-tools/issues/278

Basically, we started using `introspection_datasource` for the GraphQL engine V2. We also preserve the previous behavior if the version is not 2.

Now, Tyk returns the following result for a simple introspection query. Previously, it was dumping back the JSON of the introspection.

Introspection query:

```graphql
{
  __schema {
    types {
      name
    }
  }
}
```

```json
{
    "data": {
        "__schema": {
            "types": [
                {
                    "name": "Country"
                },
                {
                    "name": "Continent"
                },
                {
                    "name": "Language"
                },
                {
                    "name": "State"
                }
            ]
        }
    }
}
```

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4443/merge
Commit:  
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3575138628)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4443/merge
Commit: 7c3f481cf951317750106add6f01b33c14e7c9ff 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3575140532)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4443/merge
Commit: 3681ec0e283d6070975758d1d1ce98c0bff41ab8 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3581193003)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4443/merge
Commit: 03af822d1d83f7a48f6d81b1a4780743ea6b242e 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3581389028)

**Review by pvormste — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4443/merge
Commit: c554a6cd776ed65e802fd7013817190b8fd7faac 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3581552212)

**Review by Aenimus — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4443/merge
Commit: fd2a54a804417d13419522f7e356c6fa5c46e1da 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3582219731)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 1a3408063cc3163e2a1b28b0c1222031fc57adfc [TT-5766] Call GraphQL execution engine to run introspection query (#4443)

* [TT-5766] Call GraphQL execution engine to run introspection query
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3582522511)

**Pull request merged**
