### PR TITLE
[TT-6110] Updated graphql-go-tools commit hash

### PR DESCRIPTION
**Pull request by buraksezer**
[changelog]
internal: Updated graphql-go-tools commit hash.

### CODE REVIEW

**Comment by buraksezer** [comment]
Related ticket on Jira: [TT-6110](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-6110)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4311/merge
Commit:  
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3088304237)

**Review by Aenimus — APPROVED** [review]

**Review by kofoworola — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 13ed338064ba1f31fb42d6712ca7f8ba7e0bee15 [TT-6110] Updated graphql-go-tools commit hash (#4311)

[changelog]
internal: Updated graphql-go-tools commit hash.
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3090207117)

**Pull request merged**
