### PR TITLE
Fix for CPU slow burn issue

### PR DESCRIPTION
**Pull request by jlucktay**
Fix https://github.com/TykTechnologies/tyk/issues/2687

Move guard statement forward to prevent infinite recursive loop.
Test coverage is forthcoming.

### CODE REVIEW

**Comment by buger** [comment]
While in general, it fixes the issue, what about the deeper issue happening inside ForwardMessage when you run it with `dryrun`?

**Comment by jlucktay** [comment]
> While in general, it fixes the issue, what about the deeper issue happening inside ForwardMessage when you run it with `dryrun`?

I don't have a solid answer for that just yet, still getting my head around all of the moving parts.

**Comment by jlucktay** [comment]
Talking to @gernest the other day, and from some previous conversations as well, sorting out the DRL seems like a much larger piece of work.

**Comment by jlucktay** [comment]
Some existing test coverage already runs through this code, so I'm currently focusing around `TestRequestThrottling` like so:

``` shell
TYK_LOGLEVEL=debug go test \
    -count=1 \
    -run "^TestRequestThrottling$" \
    -timeout 30s \
    -v \
    github.com/TykTechnologies/tyk/gateway
```

**Comment by buger** [comment]
@gernest does it looks good now?

**Comment by gernest** [comment]
@buger I had forgotten about this, please wait I'm looking at it now.

**Comment by gernest** [comment]
@jlucktay I have take a look at this, I apologise that my review comment was less informative I thought you could refer to our last chat regarding the tests.

So, I ran the same test with the old code and your change and they all passed. So This looks like you solved a problem that doesn't exist.

I believe we agreed you should write a test case to showcase the problem with the old code, then submit this patch. Meaning, when you run the test with old code the test should fail, highlighting the infinity loop nature of the code segment. And when you run the test with the patch it should pass highlighting the fix.

The patch itself is harmless(on `RateLimitAndQuotaCheck`), but I'm against incorporating the  tests, they don't serve any purpose with respect to this issue. And saying this patch fixes the issue without steps to reproduce it isn't a good idea.

**Comment by jlucktay** [comment]
I am getting a `Server closed` warning after the test comes back with `PASS` but before the whole `go test` execution wraps up.

It doesn't do this when checked out on the `v2.8.5` tag.

```
--- PASS: TestRequestThrottling (2.74s)
    --- PASS: TestRequestThrottling/APILevel (2.74s)
        --- PASS: TestRequestThrottling/APILevel/InMemoryRateLimiter (2.74s)
PASS
time="Dec 03 13:55:42" level=warning msg="testServer.ListenAndServe() err: http: Server closed"
ok      github.com/TykTechnologies/tyk/gateway  2.771s
```

However, it does happen regardless of whether the `if ... break` is first or second out of the two `if`s inside `ProcessRequest` so I'm wondering if the `test` package is wrapping up the tests prematurely while throttled requests are still pending inside the test gateway.

`go test` still gives an exit code of 0 so everything from the outside would look fine to a CI process.

I'm not sure why I didn't spot this before.

**Pull request merged**
