### PR TITLE
CI: also run go 'test -race -tags coprocess'

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by matiasinsaurralde** [comment]
We'll probably tackle this in a different way after #911 and some test modifications

**Comment by mvdan** [comment]
@matiasinsaurralde I didn't know you were going to do that. Should I close this?

**Comment by matiasinsaurralde** [comment]
@mvdan let's keep it open for now, just wanted to reference it

**Comment by mvdan** [comment]
@matiasinsaurralde said that the `coprocess` tag will disappear, so this will be done without the extra machinery.

**Comment by matiasinsaurralde** [comment]
That's right!

**Pull request closed without merging**
