### PR TITLE
[TT-7813] Match validate request route by OAS api function

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR removes the dependency of Tyk path matching and changes it to OAS library path matching.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4551/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3724647036)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4551/merge
Commit: a1e2fcfee487ae898328695ed152e62ea5793ca2 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3724652120)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4551/merge
Commit: 4f55a521d1bf7f44849123ec1235774dc21134f3 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3816512948)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4551/merge
Commit: 8090895119233f9e0d14e796e0ffa227dfabfafa 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4043496985)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4551/merge
Commit: 847216d2da2c42a4fca38a7f2d839b5aba471455 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4043725442)

**Pull request merged**
