### PR TITLE
[TT-11091] Add support for custom ratelimit key

### PR DESCRIPTION
**Pull request by buger**
## Description
This PR introduces the ability to dynamically set the custom rate limit key in the policies metadata. When `rate_limit_pattern` pattern is specified in the policy metadata (e.g. "rate_limit_pattern": "$tyk_meta.developer_id"), the ratelimit middleware calculates the custom ratelimit key and uses it to enforce the ratelimit and quota.

## Related Issue
https://tyktech.atlassian.net/browse/TT-11091

## Motivation and Context

For customers that expose APIs externally it’s quite important to have flexibility on how to apply rate limit. For public APIs, it’s common to apply rate limit not as a per credential but as per a developer or organization profile because a commercial contract is create for developer that includes all their credentials.

This also will help with abusing the free tier APIs where it’s currently possible to reset a quota by rotating credentials. The problem is that the rate limit key is the credential ID currently, so when a key or a client is rotated, the new key ID is generated therefore effectively reseting quota.

To improve the customer experience in both scenarios, we need to make the rate limit key configurable.

## How This Has Been Tested
- Unit test covering the below scenarios
- Manual test (quota):
   - Create an auth token API
   - Create a policy with that API, make sure that the quota is enabled (for simplicity of testing - quota: 5 calls, never renewed), disable the ratelimit to test the quota in isolation
   - Specify the "rate_limit_pattern" in the policy metadata ("rate_limit_pattern": "$tyk_meta.developer_id")
   - Create two keys with that policy
   - In both key add the following metadata: developer_id = 123
   - Make 5 calls with the first key, all should be 200 OK
   - Make one more call with the first key, should be 403
   - Make one more call with the second key, should be 403 as well
   - In one of the keys set developer_id in the metadata to another value (e.g. 321) and save ***without quota reset**
   - Make one call with the that key, should be 200 OK
- Manual test (ratelimit):
   - Create an auth token API
   - Create a policy with that API, make sure that the ratelimit is enabled (for simplicity of testing - 5 calls per 3600 sec renewed), disable the quota to test the ratelimit in isolation
   - Specify the "rate_limit_pattern" in the policy metadata ("rate_limit_pattern": "$tyk_meta.developer_id")
   - Create two keys with that policy
   - In both key add the following metadata: developer_id = 123
   - Make 5 calls with the first key, all should be 200 OK
   - Make one more call with the first key, should be 429
   - Make one more call with the second key, should be 429 as well
   - In one of the keys set developer_id in the metadata to another value (e.g. 321) and save ***without quota reset**
   - Make one call with the that key, should be 200 OK

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [x] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Review by andrei-tyk — APPROVED** [review]

**Review by jeffy-mathew — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5971/merge
Commit: 4c7bcbda45e8df180b140cbe1d0ec74535c7f3e3 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7733104460)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5971/merge
Commit: 4c7bcbda45e8df180b140cbe1d0ec74535c7f3e3 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7733104460)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 6babb5a3f27a5c11468feb9148c38126d9aaba40 [TT-11091] Add support for custom ratelimit key (#5971)



## Description
This PR introduces the ability to dynamically set the custom rate limit
key in the policies metadata. When `rate_limit_pattern` pattern is
specified in the policy metadata (e.g. "rate_limit_pattern":
"$tyk_meta.developer_id"), the ratelimit middleware calculates the
custom ratelimit key and uses it to enforce the ratelimit and quota.

## Related Issue
https://tyktech.atlassian.net/browse/TT-11091






## Motivation and Context

For customers that expose APIs externally it’s quite important to have
flexibility on how to apply rate limit. For public APIs, it’s common to
apply rate limit not as a per credential but as per a developer or
organization profile because a commercial contract is create for
developer that includes all their credentials.

This also will help with abusing the free tier APIs where it’s currently
possible to reset a quota by rotating credentials. The problem is that
the rate limit key is the credential ID currently, so when a key or a
client is rotated, the new key ID is generated therefore effectively
reseting quota.

To improve the customer experience in both scenarios, we need to make
the rate limit key configurable.

## How This Has Been Tested
- Unit test covering the below scenarios
- Manual test (quota):
   - Create an auth token API
- Create a policy with that API, make sure that the quota is enabled
(for simplicity of testing - quota: 5 calls, never renewed), disable the
ratelimit to test the quota in isolation
- Specify the "rate_limit_pattern" in the policy metadata
("rate_limit_pattern": "$tyk_meta.developer_id")
   - Create two keys with that policy
   - In both key add the following metadata: developer_id = 123
   - Make 5 calls with the first key, all should be 200 OK
   - Make one more call with the first key, should be 403
   - Make one more call with the second key, should be 403 as well
- In one of the keys set developer_id in the metadata to another value
(e.g. 321) and save ***without quota reset**
   - Make one call with the that key, should be 200 OK
- Manual test (ratelimit):
   - Create an auth token API
- Create a policy with that API, make sure that the ratelimit is enabled
(for simplicity of testing - 5 calls per 3600 sec renewed), disable the
quota to test the ratelimit in isolation
- Specify the "rate_limit_pattern" in the policy metadata
("rate_limit_pattern": "$tyk_meta.developer_id")
   - Create two keys with that policy
   - In both key add the following metadata: developer_id = 123
   - Make 5 calls with the first key, all should be 200 OK
   - Make one more call with the first key, should be 429
   - Make one more call with the second key, should be 429 as well
- In one of the keys set developer_id in the metadata to another value
(e.g. 321) and save ***without quota reset**
   - Make one call with the that key, should be 200 OK

## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [x] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why

---------

Co-authored-by: Sergey Lega <legabox@gmail.com>
Co-authored-by: Laurentiu Ghiur <laurentiu.ghiur@gmail.com>
Triggered by: push (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7743822612)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 6babb5a3f27a5c11468feb9148c38126d9aaba40 [TT-11091] Add support for custom ratelimit key (#5971)



## Description
This PR introduces the ability to dynamically set the custom rate limit
key in the policies metadata. When `rate_limit_pattern` pattern is
specified in the policy metadata (e.g. "rate_limit_pattern":
"$tyk_meta.developer_id"), the ratelimit middleware calculates the
custom ratelimit key and uses it to enforce the ratelimit and quota.

## Related Issue
https://tyktech.atlassian.net/browse/TT-11091






## Motivation and Context

For customers that expose APIs externally it’s quite important to have
flexibility on how to apply rate limit. For public APIs, it’s common to
apply rate limit not as a per credential but as per a developer or
organization profile because a commercial contract is create for
developer that includes all their credentials.

This also will help with abusing the free tier APIs where it’s currently
possible to reset a quota by rotating credentials. The problem is that
the rate limit key is the credential ID currently, so when a key or a
client is rotated, the new key ID is generated therefore effectively
reseting quota.

To improve the customer experience in both scenarios, we need to make
the rate limit key configurable.

## How This Has Been Tested
- Unit test covering the below scenarios
- Manual test (quota):
   - Create an auth token API
- Create a policy with that API, make sure that the quota is enabled
(for simplicity of testing - quota: 5 calls, never renewed), disable the
ratelimit to test the quota in isolation
- Specify the "rate_limit_pattern" in the policy metadata
("rate_limit_pattern": "$tyk_meta.developer_id")
   - Create two keys with that policy
   - In both key add the following metadata: developer_id = 123
   - Make 5 calls with the first key, all should be 200 OK
   - Make one more call with the first key, should be 403
   - Make one more call with the second key, should be 403 as well
- In one of the keys set developer_id in the metadata to another value
(e.g. 321) and save ***without quota reset**
   - Make one call with the that key, should be 200 OK
- Manual test (ratelimit):
   - Create an auth token API
- Create a policy with that API, make sure that the ratelimit is enabled
(for simplicity of testing - 5 calls per 3600 sec renewed), disable the
quota to test the ratelimit in isolation
- Specify the "rate_limit_pattern" in the policy metadata
("rate_limit_pattern": "$tyk_meta.developer_id")
   - Create two keys with that policy
   - In both key add the following metadata: developer_id = 123
   - Make 5 calls with the first key, all should be 200 OK
   - Make one more call with the first key, should be 429
   - Make one more call with the second key, should be 429 as well
- In one of the keys set developer_id in the metadata to another value
(e.g. 321) and save ***without quota reset**
   - Make one call with the that key, should be 200 OK

## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [x] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why

---------

Co-authored-by: Sergey Lega <legabox@gmail.com>
Co-authored-by: Laurentiu Ghiur <laurentiu.ghiur@gmail.com>
Triggered by: push (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7743822612)

**Pull request merged**
