### PR TITLE
[TT-6866] fix panic in internal API looping.

### PR DESCRIPTION
**Pull request by jeffy-mathew**
fix panic in internal API looping

### CODE REVIEW

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4361/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3311434678)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4361/merge
Commit: 84ae09182fa750dec72ed89481d4ffc37415472b 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3311479798)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4361/merge
Commit: 9fdfd97e29c03b3d707b8b8b53d89d66f5c0a662 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3311532415)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4361/merge
Commit: 5044e9b18ab6057619a1c5ad2b0f985db3bbe3f4 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3311537558)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4361/merge
Commit: db56c72fa420f9b8c13626b029f534e3bcc79a72 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3311561207)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4361/merge
Commit: 8d872be66f6a14ce29fec87136de85da01a9d272 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3311574014)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4361/merge
Commit: 27a2b2a0be8472ddd176dd92413d2c2716922d0b 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3311623536)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4-lts
Commit: 94988a6e5fc06457d82a2b9394a7d0f8c2ad49ee Fix internal looping. (#4361)
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3311633281)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.8
Commit: 94988a6e5fc06457d82a2b9394a7d0f8c2ad49ee 
Triggered by: push (@ilijabojanovic)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3311945395)

**Pull request merged**
