### PR TITLE
Make C files in the root package symlinks again

### PR DESCRIPTION
**Pull request by mvdan**
These used to be links but were unintentionally replaced by full copies
in 15888757.

There seems to be no way around this symlink, as CGO will only compile C
files that are in the same directory as the package it's compiling.

### CODE REVIEW

**Comment by mvdan** [comment]
Ah, tested coprocess-lua but forgot about coprocess-python :(

**Comment by mvdan** [comment]
Also, the fuckup probably happened on a platform where symlinks are not a thing, like Windows. We should make sure it doesn't happen again.

**Comment by buger** [comment]
@matiasinsaurralde up to you

**Comment by mvdan** [comment]
bump @matiasinsaurralde

**Comment by matiasinsaurralde** [comment]
I will be checking this today!

**Comment by mvdan** [comment]
Thanks!

**Pull request merged**
