### PR TITLE
[TT-10120] Update reverse proxy

### PR DESCRIPTION
**Pull request by titpetric**
https://tyktech.atlassian.net/browse/TT-10120

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5575/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6378247883)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5575/merge
Commit: 46211d2dba802111da5f2005d994875237830b0a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6378347104)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5575/merge
Commit: 7a29584ccca363d36eb6c64cdc12e2e5bd3d3a11 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6378297328)

**Comment by titpetric** [comment]
Sonarcloud issue refers to https://github.com/dominikh/go-tools/issues/1336

Stdlib provides a BufferPool interface which can't satisfy SA6002.

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5575/merge
Commit: 3377da2759b7da7e1a88e8bc01f55419ae13f156 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6379182141)

**Review by furkansenharputlu — APPROVED** [review]

**Pull request closed without merging**
