### PR TITLE
Hide all log output if all tests pass

### LINKED ISSUE #330: Tests are too chatty
By default, the tests should not write anything to stderr unless anything went wrong. This is far from the truth right now.

If this is needed for CI or anything else, it should be behind a custom flag like `-test.log` or https://golang.org/pkg/testing/#Verbose.

```
 $ go test
THIS IS THE TEST SETUP INIT
[Jan 11 11:08:23] ERROR Couldn't load configuration file
[Jan 11 11:08:23] ERROR open /etc/tyk/tyk.conf: no such file or directory
[Jan 11 11:08:23]  INFO Writing a default file to ./tyk.conf
[Jan 11 11:08:23] ERROR Failed to process environment variables: specification must be a struct pointer
[Jan 11 11:08:23]  INFO Loading default configuration...
[Jan 11 11:08:23]  INFO Connection dropped, connecting..
[Jan 11 11:08:23]  INFO main: PIDFile location set to: /var/run/tyk-gateway.pid
[Jan 11 11:08:23] ERROR main: Failed to write PIDFile: error opening pidfile /var/run/tyk-gateway.pid: open /var/run/tyk-gateway.pid642434050: permission denied
[Jan 11 11:08:23] ERROR Failed ot get host pid: open /var/run/tyk-gateway.pid: no such file or directory
[Jan 11 11:08:23] ERROR Instrumentation is enabled, but no connectionstring set for statsd
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  WARN Legacy path detected! Upgrade to extended.
[Jan 11 11:08:23]  INFO main: Initialising Tyk REST API Endpoints
[Jan 11 11:08:23]  INFO main: Loading API configurations.
[Jan 11 11:08:23]  INFO main: Tracking hostname api_name=Tyk Test API ONE domain=(no host)
[Jan 11 11:08:23]  INFO main: Loading API api_name=Tyk Test API ONE
[Jan 11 11:08:23]  INFO main: Checking security policy: Token api_name=Tyk Test API ONE
[Jan 11 11:08:24] ERROR Could not EXPIRE key: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:24]  INFO host-check-mgr: Starting Poller
[Jan 11 11:08:24]  INFO main: Processed and listening on: /v1{rest:.*}
[Jan 11 11:08:24]  INFO host-check-mgr: Loading uptime tests...
[Jan 11 11:08:24]  INFO main: Initialised API Definitions
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:24] ERROR Multi command failed: return index is out of range
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:25] ERROR Multi command failed: return index is out of range
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:25] ERROR Multi command failed: return index is out of range
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:25] ERROR Multi command failed: return index is out of range
ERRO[0001] Transacton failed: dial tcp [::1]:6379: getsockopt: connection refused
[Jan 11 11:08:25] ERROR Multi command failed: return index is out of range
[Jan 11 11:08:25]  INFO main: Initialising Tyk REST API Endpoints
[Jan 11 11:08:25]  INFO main: Loading API configurations.
[...]
```

### PR DESCRIPTION
**Pull request by mvdan**
Fixes #330.

### CODE REVIEW

**Comment by buger** [comment]
Can you break a build to test this feature?

**Comment by mvdan** [comment]
I tested it locally, but I'll push a breaking commit here just to be sure.

**Comment by mvdan** [comment]
@buger see above, is that ok?

**Comment by buger** [comment]
Hm, It kinda weird, because log output is separate from actual test headlines. And there is no way to figure out which test generated output.

**Comment by mvdan** [comment]
That's the whole point of printing all the logs. Even if we kept things as they are, once tests were made parallel, the logs would not be in their proper sections either.

**Comment by buger** [comment]
But how are we going to debug issues then? Just trying to imagine workflow. If you at least could print test name in this buffer, or even better add a prefix to each log line with test name like `[TestMiddleware]..`, it will solve the issue, even with parallel tests.

Right now if tests is failed, this logs is kinda meaningless because I do not know which log line to check.

**Comment by buger** [comment]
Test names added in 1.8, but even now you can get it using reflect package, maybe it can help:
```
v := reflect.ValueOf(*t)
name := v.FieldByName("name")
```

**Comment by mvdan** [comment]
@buger sure, but how? This is precisely what I was commenting about in the issue, and you said ok to both options.

What you're saying, which is the first option I proposed, will need serious tweaking because we use a global logger that is used by all the code. So with parallel tests, it will be impossible (as it is now) to just catch the logs "for this test".

A slight variant is catching all log output between the start and end of a failed test. This will also catch the logs from other tests that ran in parallel to it.

**Comment by mvdan** [comment]
After some discussion with @buger I'll do this another way. Will open another PR.

**Pull request closed without merging**
