### PR TITLE
[TT-5816] Add extra oas validation from getkin library

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Review by titpetric — APPROVED** [review]
Looking good :)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4151/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2554668628)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4151/merge
Commit: 62c26756a5f8200f3ffbd1918e26ecbc2ad64bac 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2554716911)

**Review by lghiur — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 538dca983fb967a312bd240bd12452ad6a2083af Add extra oas validation from getkin library (#4151)
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2554818394)

**Pull request merged**
