### PR TITLE
added flag to pull OAS data in apidef

### PR DESCRIPTION
**Pull request by sredxny**
## Description
Added a flag on request the apis from RPC, this flag is to say when we want to get the OAS section of the api definitions. It defaults to false in MDCB side, but from gws versions that support OAS we should start sending this param as true. This work depends on https://github.com/TykTechnologies/tyk-sink/pull/241 .

## Related Issue
https://tyktech.atlassian.net/browse/TT-6136

## Motivation and Context
Make MDCB environment compatible with OAS but without breaking backward compatibility between MDCB and GW versions.

## How This Has Been Tested
- Run MDCB Environment. MDCB with the changes in https://github.com/TykTechnologies/tyk-sink/pull/241
- Run worker gw with the changes in this pr
- The apis should be loaded in the worker gateway
- Then shutdown the worker gw and run a version that doesn't support OAS. Eg: v4.0.0
- The apis are loaded as well in the worker gw and can be consumed

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4207/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2750578860)

**Review by furkansenharputlu — APPROVED** [review]

**Review by buger — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4207/merge
Commit: cfa95c071dc128970dfc5179a6ed780a6f7b4a9d 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2756859273)

**Review by tbuchaillot — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4207/merge
Commit: 947a3f20a63ddea731f0ff8c064a59c3ac431fe9 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2761781217)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: b72e0f3edb871bdf82001d1b916a963855a83c81 added flag to pull oas data in apidef (#4207)
Triggered by: push (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2761962016)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: b72e0f3edb871bdf82001d1b916a963855a83c81 added flag to pull oas data in apidef (#4207)
Triggered by: push (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2761962016)

**Pull request merged**
