### PR TITLE
add changes to support lts branches

### PR DESCRIPTION
**Pull request by ermirizio**

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5848/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7326970101)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5848/merge
Commit: 88e34fd9d7004c031183128b5771fe0742f004f7 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327064287)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5848/merge
Commit: 88e34fd9d7004c031183128b5771fe0742f004f7 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327064287)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5848/merge
Commit: 88e34fd9d7004c031183128b5771fe0742f004f7 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327064287)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: skipped** :no_entry_sign: 
Branch used: refs/pull/5848/merge
Commit: 88e34fd9d7004c031183128b5771fe0742f004f7 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327064287)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5848/merge
Commit: 88e34fd9d7004c031183128b5771fe0742f004f7 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327064194)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5848/merge
Commit: 0288b4deb5cb2bdd72080b63c75bfa92fc3ec054 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327203289)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5848/merge
Commit: 77fa61f6828f1692bdc824fc85703a99dfe87101 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327295805)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5848/merge
Commit: d71153fe0d99e297fcb577d13cafd28776062d0f 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327386704)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5848/merge
Commit: 9338bd935d72e097a8b73156c91a4dcbbb0b6f51 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327402218)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5848/merge
Commit: edb4b9f76aa75beb59bbae49e2b96def50e57d87 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327665436)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5848/merge
Commit: 2744451605bd80fc6a0e6dc9933743ceeefe01a5 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7327868807)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5848/merge
Commit: ef1afd7fa250ac0b1426510bd775c65bac68c3be 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7329121696)

**Comment by alephnull** [comment]
@ermirizio This one can be closed? I've removed the reviewers so that this doesn't show up in my notifications.

**Comment by ermirizio** [comment]
closed due to https://github.com/TykTechnologies/gromit/pull/242

**Pull request closed without merging**
