### PR TITLE
hostcheck: fix wonkiness when hammered with concurrent requests

### LINKED ISSUE #825: Uptime tests: Load balancer sends traffic to dead host
Branch: **2.3.6 and Master**
Env: **On-prem/community version** 

Load balancer sends traffic to down host during hi traffic on api with multiple upstream hosts.

**Note:** this issue is noticed on 120+ parallel connections to gateway.

Uptime tests configuration:
```
    "uptime_tests": {
        "disable": false,
        "config": {
            "failure_trigger_sample_size": 1,
            "time_wait": 10,
            "checker_pool_size": 25,
            "enable_uptime_analytics": true
```

**Here is console log for host checker:**
```
tyk-gateway_1    | time="Jun 21 13:59:07" level=debug msg="[HOST CHECKER] Checking: http://httpbin.org/"
tyk-gateway_1    | time="Jun 21 13:59:07" level=debug msg="[HOST CHECKER] Checking: http://putsreq.com/DCRT0ZqHndgQKQkbuaW8/de"
tyk-gateway_1    | time="Jun 21 13:59:07" level=debug msg="[HOST CHECKER] [HOST WARNING]: http://putsreq.com/DCRT0ZqHndgQKQkbuaW8/de"
tyk-gateway_1    | time="Jun 21 13:59:07" level=debug msg="Recording uptime stat"
tyk-gateway_1    | time="Jun 21 13:59:07" level=warning msg="[HOST CHECKER MANAGER] Host is DOWN: http://putsreq.com/DCRT0ZqHndgQKQkbuaW8/de"
```
**Here is log for Load balancer:**
```
tyk-gateway_1    | time="Jun 21 12:14:13" level=debug msg="Upstream Path is: ip"
tyk-gateway_1    | time="Jun 21 12:14:13" level=debug msg="UPSTREAM REQUEST URL: ip"
tyk-gateway_1    | time="Jun 21 12:14:13" level=debug msg="[PROXY] [LOAD BALANCING] Load balancer enabled, getting upstream target"
tyk-gateway_1    | time="Jun 21 12:14:13" level=debug msg="[ROUND ROBIN] Returning index: 1"
tyk-gateway_1    | time="Jun 21 12:14:13" level=debug msg="Key is: PollerCheckerInstance:putsreq.com"
tyk-gateway_1    | time="Jun 21 12:14:13" level=debug msg="Session has not changed, not updating"
```

**Here is testing API definition:**
```
{
    "id": "59495d412b31c60276e580d0",
    "name": "test",
    "slug": "test",
    "api_id": "74a4694d6630450a48eaefebb1125687",
    "org_id": "59495cff2b31c60276e580cc",
    "use_keyless": false,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": "Authorization"
    },
    "use_basic_auth": false,
    "enable_jwt": false,
    "use_standard_auth": true,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {},
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [
            {
                "url": "http://httpbin.org/",
                "method": "GET",
                "headers": {},
                "body": ""
            },
            {
                "url": "http://putsreq.com/DCRT0ZqHndgQKQkbuaW8/de",
                "method": "GET",
                "headers": {},
                "body": ""
            }
        ],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/test/",
        "target_url": "",
        "strip_listen_path": true,
        "enable_load_balancing": true,
        "target_list": [
            "http://httpbin.org/",
            "http://putsreq.com/DCRT0ZqHndgQKQkbuaW8/de"
        ],
        "check_host_against_uptime_tests": true,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "hostname",
            "port_data_path": "port",
            "target_path": "/api-slug",
            "use_target_list": false,
            "cache_timeout": 60,
            "endpoint_returns_list": false
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": null
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false
}
```

### PR DESCRIPTION
**Pull request by mvdan**
See the two commits for details.

Fixes #825.

### CODE REVIEW

**Comment by mvdan** [comment]
@ilijabojanovic please confirm if this PR (which includes the other race fixes) fixes #825 in your tests.

I'm 99% sure this was the last race causing that. But there could be another one somewhere.

**Comment by mvdan** [comment]
Also, I forgot to mention - `-race` is happy with the host checker and load balancer code after these two PRs. This is why I said I'm fairly confident that this should fix it.

**Comment by ilijabojanovic** [comment]
@mvdan @buger after few testing cycles, behavior is same. We are still sending traffic to downed host.

**Comment by mvdan** [comment]
Darn. Will keep on looking. @ilijabojanovic does this extra change help a little like the other PR's changes, or does it have zero effect?

Nevertheless, this is another fix that we should include in 2.3.7.

**Comment by ilijabojanovic** [comment]
@mvdan i have better results in tests with this PR https://github.com/TykTechnologies/tyk/pull/823 vs https://github.com/TykTechnologies/tyk/pull/830

**Comment by mvdan** [comment]
You have better results in 830 than in 823?

**Comment by ilijabojanovic** [comment]
@mvdan am typing results....

200 parallel connections on gateway:

PR 830 - 50 requests sent to downed host
PR 823 - 20 requests sent to downed host

Those results are average...

**Comment by mvdan** [comment]
This is unexpected - I'll have a second pass at this patch.

**Comment by mvdan** [comment]
@buger PTAL

@ilijabojanovic please test again

**Comment by ilijabojanovic** [comment]
@mvdan Issue is fixed, but i found other issue....

When both hosts are down gateway send traffic to both downed hosts, same situation is with api definitions which have one upstream host. Host checker triggers event for Host Down but still sending traffic on downed host(s)...

**Comment by mvdan** [comment]
@ilijabojanovic I suspected this yesterday, see #836. Please comment there confirming my suspicion.

@buger please review and merge - all 2.3.7 patches are ready.

**Pull request merged**
