### PR TITLE
mux.Router SkipClean fix, restoring listen() logic.

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Related to #340 and #410.

### CODE REVIEW

**Comment by mvdan** [comment]
What makes this fix correct in comparison to the old fix?

**Comment by buger** [comment]
Yes, pls describe how it fix the bug. And what was the reason behind the bug. 

Also, I'm not sure why this PR even exist, we already have this functionality in our master https://github.com/TykTechnologies/tyk/blob/master/main.go#L1362

To do release we for sure can merge it like this, if it not waits. But we need to add test case which replicate this bug, and verify your fix.

**Comment by lonelycode** [comment]
IIRC when custom http server overrides we're added they did have issues with hot reloads registering properly in some cases, so this might be a deeper issue with how we listen / reload.

**Comment by matiasinsaurralde** [comment]
I thought the previous commits were removed, so this is the actual change we need, I've been able to reproduce this error, and have just tried the steps described by @lonelycode, can you check?

**Comment by buger** [comment]
Is there is a way to add simple test for hot-reload?

**Comment by mvdan** [comment]
+1, tests for this would be very useful since it seems particularly flakey.

**Comment by buger** [comment]
I can confirm that this fix is working 👍 

I'm going to merge it both in master and 2.3.2 and will create a separate issue for adding tests.

**Pull request merged**
