### PR TITLE
[TT-9397] removed the replace for gorm and inherit the version from tyk-pump

### PR DESCRIPTION
**Pull request by sredxny**
## Description

Removed the replace of gorm, this is being used for tests and currently is forcing to use an older version of TykTechnologies/gorm, by remving this, we inherit the version from the tyk-pump. In this way we avoid issues in go plugins where gateway is using one version of gorm, but pump another.

## Related Issue

https://tyktech.atlassian.net/browse/TT-9397

## Motivation and Context

Check ticket details

## How This Has Been Tested

- Built the gw
- Ran tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5342/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5624773166)

**Review by tbuchaillot — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5342/merge
Commit: 97d56b45170c9e2d756f8186e31b72f523699588 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5646962273)

**Review by mativm02 — APPROVED** [review]
lgtm!

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5342/merge
Commit: 2ea97dad1b1f7d3cde112f7e013719badc1f8a28 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5663087014)

**Pull request merged**
