### PR TITLE
Add gorm dependency to build compatible plugins

### PR DESCRIPTION
**Pull request by titpetric**
## Description

Both tyk and tyk-gateway rewrite a gorm dependency, but the versions don't match. As this is a tyk-pump dependency, I've copied the version from there, ran go mod tidy and verified with a testing build that the issue doesn't persist.

```
tyk: error: unexpected error: plugin.Open("plugin_v5.0.0_linux_amd64"): plugin was built with a different version of package gorm.io/gorm/clause, try --help
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4739/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4084520492)

**Comment by buger** [comment]
👌🏻

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4739/merge
Commit: 1f9121e7d1c0332758a7b8b68da728191d94b2ed 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4085062332)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4739/merge
Commit: 7d3439c7348b5f906025c6de2072779fe3bf6e10 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4092121181)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4739/merge
Commit: a8093479aaf2819736853f1d05aab3831477658d 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4101606470)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4739/merge
Commit: a8093479aaf2819736853f1d05aab3831477658d 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4101606470)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4739/merge
Commit: a8093479aaf2819736853f1d05aab3831477658d 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4101606470)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4739/merge
Commit: a8093479aaf2819736853f1d05aab3831477658d 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4101606470)

**Pull request closed without merging**
