### PR TITLE
Fix github-script error while adding team reviewers.

### PR DESCRIPTION
**Pull request by asutosh**
## Description
Fix sync-automation error while requesting reviewers(https://github.com/TykTechnologies/tyk/runs/7994552259?check_suite_focus=true#step:4:33)

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4258/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2919593319)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4258/merge
Commit: 005ba15d49a6960b49691d0ab93dce3bc3ac2e79 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2919598341)

**Review by alephnull — APPROVED** [review]

**Review by ermirizio — APPROVED** [review]
lgtm

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: da05394b1bdc1e14f889b09094362a7549858eb3 Fix github-script error for adding reviewers. (#4258)
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2924207328)

**Pull request merged**
