### PR TITLE
TT-10069 when pulling keys from RPC check if we have connectivity

### PR DESCRIPTION
**Pull request by sredxny**
## Description

When attempting to pull a key from RPC check if the gateway has connectivity, otherwise do not try and return the proper err msg. Also when a rpc-key is not pulled we display what kind of key is it: oauth client, api key, certificate, it defaults to the word "key"

## Related Issue

https://tyktech.atlassian.net/browse/TT-10069

## Motivation and Context

Give solution to https://tyktech.atlassian.net/browse/TT-10069

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5643/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6565166820)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5643/merge
Commit: 0781b733391384b74be4ada2c967d94b4356042a 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6565296298)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5643/merge
Commit: c9eb58a2af217612a90692cbc31ef3b07767cab9 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6565397580)

**Review by tbuchaillot — CHANGES_REQUESTED** [review]
can you add some tests @sredxny ?

**Review by tbuchaillot — COMMENTED** [review]
Also, why do we need `IsInEmergency` fn in MdcbStorage? where is it used?

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5643/merge
Commit: d1de7d1ab16e55721c9f5980f650c98beb7e84b3 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6575420431)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5643/merge
Commit: 9ad77e24754db2eadcbe8aa6ce4ec3027cf82544 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6593450325)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5643/merge
Commit: 7e883996b7ee43556df0a0cb58493c6879815b27 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6628580776)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5643/merge
Commit: 3826bb1ad36a5584e5efba4af5998f47f19d3603 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6628585207)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5643/merge
Commit: e7a8c82a16cc096fa21b9f5d4d7908dc7a4f2ae0 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6628986341)

**Review by tbuchaillot — APPROVED** [review]

**Review by mativm02 — APPROVED** [review]
lgtm!

**Pull request merged**
