### PR TITLE
move adapter helper functions to proper util files (TT-7999)

### PR DESCRIPTION
**Pull request by pvormste**
This PR moves helper functions from the GraphQL adapter to some proper util files. It also adds some missing tests for those helper functions.

*Please note, that the remaining functions inside the adapter will be refactored in the next step.*

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4792/merge
Commit: 9f7e1063d0e18340b5ef500fc2199271b5a1a7e0 
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4252680620)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4792/merge
Commit:  
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4252538692)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4792/merge
Commit: 9f7e1063d0e18340b5ef500fc2199271b5a1a7e0 
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4252680620)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4792/merge
Commit: 9f7e1063d0e18340b5ef500fc2199271b5a1a7e0 
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4252680620)

**Review by kofoworola — APPROVED** [review]
Thanks!

**Review by buraksezer — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4792/merge
Commit: d792bab6911004b8fb996d6ea06d3b17bc5c5acb 
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4312050283)

**Pull request merged**
