### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by spetrunin**
Fix master build

## Description

Tunes and test fixes

## Motivation and Context

Make CI happy again to be able to check PRs corectness

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by sredxny — APPROVED** [review]
LGTM! nice job 🥳

**Review by matiasinsaurralde — APPROVED** [review]

**Comment by spetrunin** [comment]
To keep the branch green (in case we will have to merge this branch into other branches) we should have the next order of applying fixes:
#3163
#3306
#3308

**Comment by matiasinsaurralde** [comment]
@spetrunin Would it be safe to add this to `release-3-lts`? We've found similar errors there.
cc @sredxny

**Comment by spetrunin** [comment]
@matiasinsaurralde I think it should be ok, as here was mostly test fixes, but note, that order of fixes from the comment above was mandatory for correctness

**Pull request merged**
