### PR TITLE
[TT-9748] Update swagger.yml

### PR DESCRIPTION
**Pull request by titpetric**

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5430/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5890805230)

**Review by dcs3spp — APPROVED** [review]
lgtm

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5430/merge
Commit: 1fa10e86a46bb8b5049bb331028ff8a4d56d7ee8 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5891751494)

**Pull request merged**
