### PR TITLE
TT-3973: Patch flaky test for test hmac auth session key missing

### PR DESCRIPTION
**Pull request by titpetric**
Pass cancellation context to RedisController, to exit pubSubLoop without referencing net.DefaultResolver (data race, globals)

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3995/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2109172293)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3995/merge
Commit: 2a98ad3ef4ed58a2180f18d7b41af1243ef5cc14 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2202792140)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3995/merge
Commit: e34feb98b6d5aef1ca9aa9ff939e24ef6ceed787 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2203997490)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3995/merge
Commit: 71dd2771054a5c3b39e27fc5bee8e68495a24b54 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2227049325)

**Comment by titpetric** [comment]
Outdated, flaky tests PRs resolve this differently.

**Pull request closed without merging**
