### PR TITLE
CoProcess Auth should check the policy

### PR DESCRIPTION
**Pull request by asoorm**
Replaces: https://github.com/TykTechnologies/tyk/pull/2650
Fixes: https://github.com/TykTechnologies/tyk/issues/2884

### CODE REVIEW

**Comment by letzya** [comment]
@asoorm wasn't it fixed before?

**Comment by buger** [comment]
Do you have a ticket for this one?

**Comment by buger** [comment]
@asoorm we need a task with a full context on this, if we want it get intcluded to the patch.

**Pull request merged**
