### PR TITLE
[TT-11348] fix inverted logic for detailed activity logs

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description

Fix inverted conversion for detailed activity logs
## Related Issue
https://tyktech.atlassian.net/browse/TT-11348
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

___

## **Type**
bug_fix

___

## **Description**
- Corrected the inverted logic for enabling detailed activity logs in the API definition.
- Removed unnecessary reset of `EnableDetailedRecording` in test setup, streamlining the testing process.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>oas_test.go</strong><dd><code>Update Test Reset List for Detailed Activity Logs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/oas/oas_test.go
<li>Removed <code>APIDefinition.EnableDetailedRecording</code> from a test reset list, <br>indicating it no longer needs to be reset for tests.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6063/files#diff-74029ee88132d30d6478c96a35f8bb2200e0c8e6f42f2c9b147dc6bb7ce74644">+0/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>server.go</strong><dd><code>Fix Inverted Logic for Detailed Activity Logs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/oas/server.go
<li>Corrected the logic for enabling detailed activity logs by setting <br><code>EnableDetailedRecording</code> directly based on the <code>Enabled</code> flag.<br> <li> Updated the <code>Fill</code> method to directly reflect the <br><code>EnableDetailedRecording</code> status in the <code>Enabled</code> flag of <br><code>DetailedActivityLogs</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6063/files#diff-21857c42e8659f7980014e277c3c758703f29e9e5c0c40553f2584cddb870808">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6063/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8009709084)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6063/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8009709084)

**Review by lghiur — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 70b7e9cc2aae41b28a664fa06d429fdac2df6bc9 [TT-11348] fix inverted logic for detailed activity logs (#6063)



## Description

Fix inverted conversion for detailed activity logs
## Related Issue
https://tyktech.atlassian.net/browse/TT-11348
## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8016639386)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 70b7e9cc2aae41b28a664fa06d429fdac2df6bc9 [TT-11348] fix inverted logic for detailed activity logs (#6063)



## Description

Fix inverted conversion for detailed activity logs
## Related Issue
https://tyktech.atlassian.net/browse/TT-11348
## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8016639386)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 70b7e9cc2aae41b28a664fa06d429fdac2df6bc9 [TT-11348] fix inverted logic for detailed activity logs (#6063)



## Description

Fix inverted conversion for detailed activity logs
## Related Issue
https://tyktech.atlassian.net/browse/TT-11348
## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8016639386)

**Pull request merged**
