### PR TITLE
TT-11443 Shim to keep compatibility in goplugins importing tyk redis

### PR DESCRIPTION
**Pull request by sredxny**
## Description

In order to not break compatibility of goplugins importing the redis implementation of the last versions of gw, is required to create a bridge that translates old instructions into new redis store instructions.

## Related Issue

TT-11443

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

___

## **Type**
enhancement

___

## **Description**
- Introduced a `redis_shim.go` file to ensure compatibility with goplugins importing the Redis implementation from previous versions. This acts as a bridge translating old Redis instructions to new Redis store instructions, maintaining backward compatibility without breaking existing implementations.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>redis_shim.go</strong><dd><code>Introduction of Redis Shim for Go Plugins Compatibility</code>&nbsp; &nbsp; </dd></summary>
<hr>

storage/redis_shim.go
<li>Introduced a new file <code>redis_shim.go</code> for creating a bridge between old <br>and new Redis store instructions.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6096/files#diff-b175b26ea2c5bc6f5eb907f40acdaea3f4d100a2bbbf50a12fdb64abdb57a040">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6096/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8150360109)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6096/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8150360109)

**Review by mativm02 — APPROVED** [review]

**Review by padiazg — APPROVED** [review]
LGTM

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v5.3.0-goplugin
Commit: 17fe2a81b563a0a3f11c3623d196a06e1d6beb86 
Triggered by: push (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8181673077)

**Pull request merged**
