### PR TITLE
[SYSE-160] - Replace tyk-ci with TAT

### PR DESCRIPTION
**Pull request by ermirizio**
- Modify release / tyk-automated-test workflow to stop using CI repository and take files back from automated-tests again

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6151569627)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: 4d5ad11c74d993b6e9887aab52d3468925315344 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6151652206)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: aebd7f0510f30618c0815062fba2856221407362 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6151817617)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: 7578bf0b4ff5934c86e11d99c6d0ce0b4ab83ce3 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6151981455)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: 3a9f9d15775ea3ed786567d155c1fc173bf03d29 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6152854178)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: 5304c8f8a3d90496d6c1bee83cf7a2a105cbb2a6 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6152949578)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: ac2c04c49b82bcbc2ed3d6af53fbf3c3ce0640fe 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6153040255)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: 672b2be6f6515313fac901eeab7ba0c2f489b10d 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6153157968)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: beb77646b71cbaf97f6ca2a535efb62c9244c63a 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6154883945)

**Review by alephnull — APPROVED** [review]

**Comment by alephnull** [comment]
It appears that the env does not come up

**Review by alephnull — CHANGES_REQUESTED** [review]
The tests need to be green to merge this.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: f72c8ef1f006311c1122ce548391642820f6f2e5 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6160249367)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5553/merge
Commit: b9bb6ff84912551858f8790c731992bd5cfc35b8 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6163271504)

**Comment by ermirizio** [comment]
@alephnull this is ready to be merged , all tests passing

**Review by alephnull — APPROVED** [review]

**Pull request merged**
