### PR TITLE
Re-organize CLI code

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
This is a first approach on re-organizing the CLI code for #1492, would appreciate reviews/ideas.
- Using `kingpin.Application` makes using different subcommands easier, so if we plan to replace `tyk-cli` this will enhance the code structure.
- A CLI data structure was added, which can be helpful for mocking command-line input.
- It wasn't possible to add subcommands without changing the way we currently use the `lint` command:
```
error: can't mix top-level Arg()s with Command()s, try --help
```
- The `cli` directory will contain different packages for each subcommand (think `tyk bundle build` or `tyk bundle server`, etc.).
- `command_mode` code should be moved and restructured to fit the `cli` idea.
- The compatibility should be ok with this PR (needs tests!).

### CODE REVIEW

**Comment by buger** [comment]
@matiasinsaurralde looks really good! 

Can you clarify how exactly, from user perspective, things are changed for linter and import commands: before and after change.

**Comment by matiasinsaurralde** [comment]
@leon Previously the importer was invoked with a flag ("tyk --import-swagger" or "tyk --import-blueprint"), now "import" is a subcommand, the syntax for all the import parameters remains the same:
Previously:
```
tyk --import-blueprint=blueprint.json --create-api --org-id=<id> --upstream-target="http://widgets.com/api/"
tyk --import-swagger=swaggerfile --create-api --org-id=<id> --upstream-target="http://widgets.com/api/"
```
Now:
```
tyk import blueprint.json --blueprint --create-api --org-id=<id> --upstream-target="http://widgets.com/api/"
tyk import swaggerfile --swagger --create-api --org-id=<id> --upstream-target="http://widgets.com/api/"
```
The linter remains the same:
```
tyk lint
```
In terms of code it's much easier to introduce new commands now by using the structure created here, the help messages also improve (see #1492), testing commands too.

**Comment by matiasinsaurralde** [comment]
I have integrated the bundler from `tyk-cli` too, but will use a different PR for that:
`tyk-cli bundle build`
turns into
`tyk bundle build`

**Comment by leon** [comment]
@matiasinsaurralde I'm the wrong leon :)

**Comment by matiasinsaurralde** [comment]
@leon sorry!

**Comment by buger** [comment]
Nice! Does it still a WIP or ready to be merged? (looks good to me)

**Comment by matiasinsaurralde** [comment]
@buger @dencoded thanks for the reviews
There's a small tweak I will do today, basically when you type `tyk -h` you don't get the help output from the default command (`tyk start -h` does), would be good to enhance this.

**Comment by buger** [comment]
@matiasinsaurralde pls fix your last command and will be ready to be merged

**Comment by matiasinsaurralde** [comment]
I've tried this patch but seems to be very hacky:
```
 // Parse parses the command-line arguments.
 func Parse() {
-       kingpin.MustParse(app.Parse(os.Args[1:]))
+       args := os.Args[1:]
+       if len(args) >= 1 {
+               fmt.Println("arg = ", args[0])
+               if args[0] == "-h" || args[0] == "--help" {
+                       args[0] = "start"
+                       args = append(args, "-h")
+               }
+       }
+       kingpin.MustParse(app.Parse(args))
 }
```
And subcommands are omitted:
```
tyk start -h
usage: tyk start [<flags>]

Starts the Tyk Gateway

Flags:
  -h, --help                Show context-sensitive help (also try --help-long and --help-man).
      --version             Show application version.
      --conf=FILE           load a named configuration file
      --port=PORT           listen on PORT (overrides config file)
      --memprofile          generate a memory profile
      --cpuprofile          generate a cpu profile
      --blockprofile        generate a block profile
      --mutexprofile        generate a mutex profile
      --httpprofile         expose runtime profiling data via HTTP
      --debug               enable debug mode
      --log-intrumentation  output intrumentation output to stdout
```
Without the patch is as follows, what do you think about using this?
```
tyk -h
usage: tyk [<flags>] <command> [<args> ...]

Tyk Gateway

Flags:
  -h, --help     Show context-sensitive help (also try --help-long and --help-man).
      --version  Show application version.

Commands:
  help [<command>...]
    Show help.

  start* [<flags>]
    Starts the Tyk Gateway

  lint
    Runs a linter on Tyk configuration file

  import [<flags>] [<input file>]
    Imports a BluePrint/Swagger file
```
This is my favorite one (`--help-long`, we could also set this as default!):
```
tyk --help-long
usage: tyk [<flags>] <command> [<args> ...]

Tyk Gateway

Flags:
  -h, --help                Show context-sensitive help (also try --help-long and --help-man).
      --version             Show application version.
      --conf=FILE           load a named configuration file
      --port=PORT           listen on PORT (overrides config file)
      --memprofile          generate a memory profile
      --cpuprofile          generate a cpu profile
      --blockprofile        generate a block profile
      --mutexprofile        generate a mutex profile
      --httpprofile         expose runtime profiling data via HTTP
      --debug               enable debug mode
      --log-intrumentation  output intrumentation output to stdout

Commands:
  help [<command>...]
    Show help.


  start [<flags>]
    Starts the Tyk Gateway

    --conf=FILE           load a named configuration file
    --port=PORT           listen on PORT (overrides config file)
    --memprofile          generate a memory profile
    --cpuprofile          generate a cpu profile
    --blockprofile        generate a block profile
    --mutexprofile        generate a mutex profile
    --httpprofile         expose runtime profiling data via HTTP
    --debug               enable debug mode
    --log-intrumentation  output intrumentation output to stdout

  lint
    Runs a linter on Tyk configuration file


  import [<flags>] [<input file>]
    Imports a BluePrint/Swagger file

    --swagger              Use Swagger mode
    --blueprint            Use BluePrint mode
    --create-api           Creates a new API definition from the blueprint
    --org-id=ORG-ID        assign the API Definition to this org_id (required with create-api
    --upstream-target=URL  set the upstream target for the definition
    --as-mock              creates the API as a mock based on example fields
    --for-api=PATH         adds blueprint to existing API Definition as version
    --as-version=VERSION   the version number to use when inserting
```
Subcommands:
```
tyk import -h
usage: tyk import [<flags>] [<input file>]

Imports a BluePrint/Swagger file

Flags:
  -h, --help                 Show context-sensitive help (also try --help-long and --help-man).
      --version              Show application version.
      --swagger              Use Swagger mode
      --blueprint            Use BluePrint mode
      --create-api           Creates a new API definition from the blueprint
      --org-id=ORG-ID        assign the API Definition to this org_id (required with create-api
      --upstream-target=URL  set the upstream target for the definition
      --as-mock              creates the API as a mock based on example fields
      --for-api=PATH         adds blueprint to existing API Definition as version
      --as-version=VERSION   the version number to use when inserting

Args:
  [<input file>]  e.g. blueprint.json, swagger.json, etc.
```

```
tyk lint -h
usage: tyk lint

Runs a linter on Tyk configuration file

Flags:
  -h, --help     Show context-sensitive help (also try --help-long and --help-man).
      --version  Show application version.
```

**Comment by asoorm** [comment]
I think is a small hack given the increased UX. 

not having `tyk -h` and having to do `tyk start -h` may not be too intuitive.

Maybe a comment to explain the hack?

**Comment by matiasinsaurralde** [comment]
Just rebased this to include changes from `master` like `disable_regexp_cache`, `regexp_cache_expire` and other linter additions. Note that the linter has a different location on this PR, it was moved from `lint` in the root directory to `cmd/lint`.
@asoorm I've dropped the hack initial idea because it wouldn't display information about other commands, so I'm +1 on showing  `help-long` instead, this includes every command with its possible flags (see above). Waiting for more feedback to decide:
Initial hack idea (missing the other commands):
```
% ./tyk -h
usage: tyk [<flags>]

Starts the Tyk Gateway

Flags:
  -h, --help                Show context-sensitive help (also try --help-long and --help-man).
      --version             Show application version.
      --conf=FILE           load a named configuration file
      --port=PORT           listen on PORT (overrides config file)
      --memprofile          generate a memory profile
      --cpuprofile          generate a cpu profile
      --blockprofile        generate a block profile
      --mutexprofile        generate a mutex profile
      --httpprofile         expose runtime profiling data via HTTP
      --debug               enable debug mode
      --log-intrumentation  output intrumentation output to stdout
```
Using `help-long` as default:
```
% ./tyk -h
usage: tyk [<flags>] <command> [<args> ...]

Tyk Gateway

Flags:
  -h, --help                Show context-sensitive help (also try --help-long and --help-man).
      --version             Show application version.
      --conf=FILE           load a named configuration file
      --port=PORT           listen on PORT (overrides config file)
      --memprofile          generate a memory profile
      --cpuprofile          generate a cpu profile
      --blockprofile        generate a block profile
      --mutexprofile        generate a mutex profile
      --httpprofile         expose runtime profiling data via HTTP
      --debug               enable debug mode
      --log-intrumentation  output intrumentation output to stdout

Commands:
  help [<command>...]
    Show help.

  start [<flags>]
    Starts the Tyk Gateway

    --conf=FILE           load a named configuration file
    --port=PORT           listen on PORT (overrides config file)
    --memprofile          generate a memory profile
    --cpuprofile          generate a cpu profile
    --blockprofile        generate a block profile
    --mutexprofile        generate a mutex profile
    --httpprofile         expose runtime profiling data via HTTP
    --debug               enable debug mode
    --log-intrumentation  output intrumentation output to stdout

  lint
    Runs a linter on Tyk configuration file


  import [<flags>] [<input file>]
    Imports a BluePrint/Swagger file

    --swagger              Use Swagger mode
    --blueprint            Use BluePrint mode
    --create-api           Creates a new API definition from the blueprint
    --org-id=ORG-ID        assign the API Definition to this org_id (required with create-api
    --upstream-target=URL  set the upstream target for the definition
    --as-mock              creates the API as a mock based on example fields
    --for-api=PATH         adds blueprint to existing API Definition as version
    --as-version=VERSION   the version number to use when inserting
```

**Comment by matiasinsaurralde** [comment]
@buger That's already possible

**Comment by buger** [comment]
Merged manually https://github.com/TykTechnologies/tyk/commit/fd3af4861451e37d676cf8ef14024882323fb737

**Pull request closed without merging**
