### PR TITLE
Fix/fire event on go plugin auth fail

### PR DESCRIPTION
**Pull request by spetrunin**
When Custom Go plugin returns 403 StatusForbidden, fire an event indicating Auth failure.

## Description

- Fire event on auth fail
- Replace IF with a switch statement

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by pvormste — APPROVED** [review]

**Review by furkansenharputlu — APPROVED** [review]
Looks good, however it'd be good if you add a test.

**Comment by maciejwojciechowski** [comment]
verified on release-3.1
```
[Sep 17 14:04:01] ERROR Authentication error in Go-plugin middleware func error=<nil> mwPath=middleware/again.so mwSymbolName=MyPluginAuthCheck
[Sep 17 14:04:01] DEBUG EVENT FIRED: AuthFailure
[Sep 17 14:04:01] ERROR Failed to process request with Go-plugin middleware func error=plugin function sent error response code: 403 mwPath=middleware/again.so mwSymbolName=MyPluginAuthCheck
```

**Pull request merged**
