### PR TITLE
Revert plugin compiler changes made by template update 

### PR DESCRIPTION
**Pull request by asutosh**
## Description

Revert plugin compiler changes made by template update , the independent plugin compiler image build workflow remains and will be used to build plugin compiler docker image.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5407/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5825692737)

**Review by alephnull — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5407/merge
Commit: ddb1a37cd9126896aa69e3ae840c66dc13eaa72a 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5830929689)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5407/merge
Commit: c43a3276027716a9bce825792be964ca93fbe369 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5831350989)

**Review by titpetric — APPROVED** [review]
Verified on `v5.0.5-alpha9`, LGTM

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5407/merge
Commit: b6ca7ca9282cda99e802ebbb423017afa98c731f 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5831931868)

**Pull request merged**
