### PR TITLE
[TT-4758] Implement OAS oauth2 scheme conversion

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3936/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1963308516)

**Review by jeffy-mathew — APPROVED** [review]

**Review by maciejwojciechowski — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3936/merge
Commit: 1bf339fc2619193a9f98b5bd916c1ed75bc87de6 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1993060177)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3936/merge
Commit: 209b34e4d0486df18efe5f0cf3be3423154cedf0 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1993241890)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 92655edd6ae351717513633ef9276fe078afe012 [TT-4758] Implement OAS oauth2 scheme conversion (#3936)

* Refactor basic auth OAS conversion

* Implement OAS oauth2 scheme conversion
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1993325500)

**Pull request merged**
