### PR TITLE
TT-9352 on merging headers, check that they are assigned back

### PR DESCRIPTION
**Pull request by sredxny**
## Description

after merging the headers we want to assign them back to the response

## Related Issue

https://tyktech.atlassian.net/browse/TT-9352

## How This Has Been Tested

- Create an api that uses a python middleware
- create a middleware that appends a new header, like this one:

```
from tyk.decorators import *
from gateway import TykGateway as tyk
import json

@Hook
def MyResponseHook(request, response, session, metadata, spec):
    response_body = str(response.body)
    changed = response_body.upper().encode('utf-8')
    response.raw_body = changed
    response.headers["python-qa"] = "qa-test"

    return response, session, metadata, spec
```

- Consume the api
- Your should receive the header in the response

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5271/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5457273722)

**Review by mativm02 — APPROVED** [review]

**Review by tbuchaillot — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5271/merge
Commit: 7b5f6d42ed1392b6dd4a5500381b6c8d58698e33 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5464900179)

**Pull request merged**
