### PR TITLE
[TT-7129] Fix setting global_size_limit not enabling RequestSizeLimitMiddleware

### PR DESCRIPTION
**Pull request by PatrickTaibel**
## Description
Fix `EnabledForSpec` in `RequestSizeLimitMiddleware` for API global limits without size limits in `extended_paths`.

## Related Issue
https://github.com/TykTechnologies/tyk/issues/3977

## Motivation and Context
Makes the `RequestSizeLimitMiddleware` usable when only API global limits are specified.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
Nice one! 

Keen to add a small test for it? 

It can look like this:

```go
func TestValidateJSONSchema(t *testing.T) {
	ts := StartTest(nil)
	defer ts.Close()

	ts.Gw.BuildAndLoadAPI(func(spec *APISpec) {
		UpdateAPIVersion(spec, "v1", func(v *apidef.VersionInfo) {
			v.GlobalSizeLimit = 1
		})
	})

	ts.Run(t, []test.TestCase{
		{Method: "POST", Path: "/sample/", Data: "foobar", Code: http.StatusBadRequest},
	}...)
}
```

**Comment by PatrickTaibel** [comment]
I've added a small test for this. Thank you very much for the pretty much finished test snippet!

**Comment by titpetric** [comment]
Everything LGTM, please rebase and check the test failures.

**Comment by PatrickTaibel** [comment]
I've rebased the branch onto the current master.
The previous test run seems to have failed on test `--- FAIL: TestEnforcedTimeout (4.27s)`. As far as I can tell, this has nothing to do with the changes in this PR.

**Comment by titpetric** [comment]
I believe the tests on master have been resolved. Can I ask you for the hopefully last rebase? The teams are improving the test case failures, so your best case at merging this soon is unfortunately rebasing until tests pass 😬

**Comment by titpetric** [comment]
I've cherry-picked this over #4967 - your contribution will be included in the 5.1 release. Thank you :trophy:

**Pull request closed without merging**
