### PR TITLE
[TT-11388]: updated opentelemtry library and added tests for new span keys

### PR DESCRIPTION
**Pull request by kofoworola**
## Description
updated opentelemtry library and added tests for new span keys
[TT-11388](https://tyktech.atlassian.net/browse/TT-11388)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

___

## **Type**
enhancement, tests

___

## **Description**
- Updated OpenTelemetry library to version `v0.0.21`.
- Enhanced GraphQL tracing scenarios by including operation names in the query body.
- Added new assertions to validate GraphQL span attributes, ensuring the correct tracking of GraphQL operations.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>tyk_test-graphql-detailed-tracing-disabled_200.yaml</strong><dd><code>Update GraphQL Tracing Scenario and Assertions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

ci/tests/tracing/scenarios/tyk_test-graphql-detailed-tracing-disabled_200.yaml
<li>Updated the GraphQL query body to include an operation name.<br> <li> Added assertions to validate new span attributes for GraphQL <br>operations.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6087/files#diff-77005f007390131ed92b45a70093403c4e3bece1b4b04607d2655393054c9ed2">+8/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>tyk_test-graphql-tracing_200.yml</strong><dd><code>Enhance GraphQL Tracing Tests with New Span Attributes</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

ci/tests/tracing/scenarios/tyk_test-graphql-tracing_200.yml
<li>Modified the GraphQL query to include an operation name.<br> <li> Added assertions for new GraphQL span attributes.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6087/files#diff-2df94df431a444a3778f2b00fd47d911dcfa2e0c9c883de72f72adcd509c890a">+7/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>go.mod</strong><dd><code>Update OpenTelemetry Library Dependency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

go.mod
<li>Updated <code>github.com/TykTechnologies/opentelemetry</code> to version <code>v0.0.21</code>.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6087/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>go.sum</strong><dd><code>Update Checksum for OpenTelemetry Dependency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

go.sum
<li>Updated checksum for <code>github.com/TykTechnologies/opentelemetry</code> to <br><code>v0.0.21</code>.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6087/files#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

[TT-11388]: https://tyktech.atlassian.net/browse/TT-11388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6087/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8113689979)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6087/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8113689979)

**Review by rhianeKobar — APPROVED** [review]

**Review by pvormste — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 8b3b2f0653f3b0143cdcd97603b83be48adf1cb4 [TT-11388]: updated opentelemtry library and added tests for new span keys (#6087)

## **User description**


## Description
updated opentelemtry library and added tests for new span keys
[TT-11388](https://tyktech.atlassian.net/browse/TT-11388)



## Related Issue






## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why


___

## **Type**
enhancement, tests


___

## **Description**
- Updated OpenTelemetry library to version `v0.0.21`.
- Enhanced GraphQL tracing scenarios by including operation names in the
query body.
- Added new assertions to validate GraphQL span attributes, ensuring the
correct tracking of GraphQL operations.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>

<summary><strong>tyk_test-graphql-detailed-tracing-disabled_200.yaml</strong><dd><code>Update
GraphQL Tracing Scenario and Assertions</code>&nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>


ci/tests/tracing/scenarios/tyk_test-graphql-detailed-tracing-disabled_200.yaml
<li>Updated the GraphQL query body to include an operation name.<br>
<li> Added assertions to validate new span attributes for GraphQL
<br>operations.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6087/files#diff-77005f007390131ed92b45a70093403c4e3bece1b4b04607d2655393054c9ed2">+8/-2</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>

<summary><strong>tyk_test-graphql-tracing_200.yml</strong><dd><code>Enhance
GraphQL Tracing Tests with New Span Attributes</code>&nbsp; &nbsp;
&nbsp; </dd></summary>
<hr>

ci/tests/tracing/scenarios/tyk_test-graphql-tracing_200.yml
<li>Modified the GraphQL query to include an operation name.<br> <li>
Added assertions for new GraphQL span attributes.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6087/files#diff-2df94df431a444a3778f2b00fd47d911dcfa2e0c9c883de72f72adcd509c890a">+7/-2</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>go.mod</strong><dd><code>Update OpenTelemetry Library
Dependency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

go.mod
<li>Updated <code>github.com/TykTechnologies/opentelemetry</code> to
version <code>v0.0.21</code>.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6087/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6">+1/-1</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>go.sum</strong><dd><code>Update Checksum for
OpenTelemetry Dependency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

go.sum
<li>Updated checksum for
<code>github.com/TykTechnologies/opentelemetry</code> to
<br><code>v0.0.21</code>.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6087/files#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63">+2/-2</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions



[TT-11388]:
https://tyktech.atlassian.net/browse/TT-11388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Triggered by: push (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8138865509)

**Pull request merged**
