### PR TITLE
[TD-924] Fix path and update sync automation workflow.

### PR DESCRIPTION
**Pull request by asutosh**
## Description
Fix trigger path for the sync automation workflow.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3932/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1962492189)

**Review by alephnull — COMMENTED** [review]
> Don't all repos need the token to trigger the release workflow?

nvm

**Review by alephnull — APPROVED** [review]

**Review by ermirizio — APPROVED** [review]
lgtm

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3932/merge
Commit: ce1c110bcb712a33d6b1c7a9141b9cc848c01daa 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1986966699)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 9e5a14daa6d7e512e1a8f6be1b49bf6e8003c146 Fix path and update sync automation workflow. (#3932)
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1987084242)

**Pull request merged**
