### PR TITLE
[TT-6966] Revert "[TT-6454]  change OAS AddServers signature to return error."

### PR DESCRIPTION
**Pull request by jeffy-mathew**
Reverts TykTechnologies/tyk#4375

### CODE REVIEW

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4387/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3387127659)

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4387/merge
Commit: 232f2ad2b6a1b65dde9062dfbaea7327b07f8418 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3392002879)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 550850b3b0fe3723d9d72a9c94482a1735963e72 Revert "change OAS AddServers signature to return error. (#4375)" (#4387)

This reverts commit 501e860523888b88c2ac3f4669e7377aa7f7b149.
Allow empty servers in OAS AddServers.
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3392073000)

**Pull request merged**
