### PR TITLE
Update DRL dependency, update API usage, go mod tidy

### PR DESCRIPTION
**Pull request by titpetric**
## Description

This PR updates the internal drl dependency, to avoid race conditions over values.

## Related Issue

https://tyktech.atlassian.net/browse/TT-6085

## How This Has Been Tested

Extensive additions of unit tests in the drl package, type safety and pre-existing tests on gateway side.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4280/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2971959741)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4280/merge
Commit: 91890c29caad42f7fcb97a5ae01c09d632e04b37 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3023381455)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4280/merge
Commit: d4c25e9a22740379fa5ca0ceecfe5b968796463d 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3636470747)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4280/merge
Commit: 5db2479b0a96b73c103f328e4bbeaa2d66a9f9be 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3795509412)

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4280/merge
Commit: 9a17357ffc09249fb3b75dcf476cc895145e8909 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3795553622)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: a3cd481fb4737c94d97d6737cdebc422682b1e64 Update DRL dependency, update API usage, go mod tidy (#4280)
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3795656144)

**Pull request merged**
