### PR TITLE
[TT-5586] Handle security scheme map conditions

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4100/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2427113811)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4100/merge
Commit: 4aeacb73a90729e94d01849183d066c229f196a2 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2427142972)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: b4ba81ae61b3cd7508b1d92a7ea8352e35837956 Handle security scheme map conditions (#4100)
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2427713397)

**Pull request merged**
