### PR TITLE
[TT-8351] fix jwt_scope_to_policy_mapping backwards compatibility.

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description

This PRs fixes broken backward compatibility for `jwt_scope_to_policy_mapping`. 
- added migration to new fields in `Migrate()` method.
- keeping `jwt_scope_to_policy_mapping` to be considered in middlewares when the new fields (`scopes.jwt` / `scopes.oidc`) are not configured. 

## Related Issue
https://tyktech.atlassian.net/browse/TT-8351

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4895/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4497326112)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4895/merge
Commit: 292976519f8b371965228b0f1e40d936d1fd6496 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4497327105)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4895/merge
Commit: f402d52ed81d1a6e282452248338776f7cd8fa7e 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4497505927)

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4895/merge
Commit: 3bd7bd25e2aa8ac3c9802dee079d44d68c02a7df 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4503368339)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4895/merge
Commit: 65f07761b8cc510e2124ff61d2cf7a2fa83e9036 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4508431530)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4895/merge
Commit: 27e7b133948e242b44bff9f2a14cf4dfb4c851f0 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4511012456)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4895/merge
Commit: 27e7b133948e242b44bff9f2a14cf4dfb4c851f0 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4511012484)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4895/merge
Commit: c2d02cc465244d84bdac919a144da0d249ee0383 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4511057285)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4895/merge
Commit: 79e3aeb5d73672346480be63612147b74d1dd3b8 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4511079806)

**Pull request merged**
