### PR TITLE
trigger release-5.0.4 and release-5.1.1 branch creation

### PR DESCRIPTION
**Pull request by lghiur**

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5293/merge
Commit:  
Triggered by: pull_request (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5487039854)

**Review by ermirizio — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5293/merge
Commit: 757af27e98202141ebba6bb938c99d2a983ff5ef 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5505563396)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5293/merge
Commit: 1120152502b9f3f3ab9e3460823f7da616bd9317 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5511351932)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5293/merge
Commit: 7042670f62ac9f714a2a18072632a427260dd1fa 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5518618061)

**Pull request merged**
