### PR TITLE
[TT-4905] Deduplicate string slice fields in api schema

### PR DESCRIPTION
**Pull request by titpetric**

### CODE REVIEW

**Review by urbanishimwe — APPROVED** [review]

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4002/merge
Commit: 9bc128b38b8d535d5dc667c9252496ad553c1c7c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2148069118)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4002/merge
Commit: 137541f2d3a6cf596b9c67a043c44958e1f64b9f 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2148072454)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4002/merge
Commit: 375a279aa2244af99b94e652e9691c1de462a4ad 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2153602994)

**Pull request merged**
