### PR TITLE
TT-5026 Initializing OrganizationMonitor with a valid gw pointer

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

OrganizationMonitor monitor was inited without any gateway pointer. This caused panic on execution.

## Related Issue

https://tyktech.atlassian.net/browse/TT-5026
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3987/merge
Commit:  
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2094737471)

**Comment by buger** [comment]
Any chance to have some simple tests for it?

**Comment by tbuchaillot** [comment]
@buger added a test for it

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3987/merge
Commit: ad2b067839590528d0134e8663a257ce2758c529 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2094869730)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3987/merge
Commit: 272099bc4ef2605893abf6bb58a22f1c5ed303c0 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2094899929)

**Review by buger — APPROVED** [review]
Looks good!

**Review by urbanishimwe — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: bf55ebe505adab229da936fbaa6ab94bd5730f93 TT-5026 Initializing OrganizationMonitor with a valid gw pointer (#3987)

* initializing OrganizationMonitor with a valid gw pointer

* adding TestOrganizationMonitorEnabled test

* linting
Triggered by: push (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2095391942)

**Pull request merged**
