### PR TITLE
[TT-11549] remove python plugin smoke tests.

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description

Remove python smoke tests. 
Python is removed from docker image via automation.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

___

## **Type**
enhancement

___

## **Description**
- Removed unnecessary Python packages (`python3-setuptools`, `python3-dev`) from Dockerfiles to reduce the CVE surface and potentially improve build times.
- Maintained essential Python support with `libpython3-dev`, `python3-grpcio` for plugin functionality.
- Streamlined Dockerfile configurations for both standard and hybrid images, focusing on security and efficiency.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Dockerfile.std</strong><dd><code>Reduce CVE Surface by Removing Unnecessary Python Packages</code></dd></summary>
<hr>

ci/Dockerfile.std
<li>Removed installation of <code>python3-setuptools</code>, <code>python3-dev</code> from the <br>Dockerfile to decrease CVE surface and potentially improve build <br>times.<br> <li> Kept <code>libpython3-dev</code>, <code>python3-grpcio</code> for necessary Python plugin <br>support.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6134/files#diff-a3b3e9cabd877d0bd0fc8f20a9fdca7f44d102547a5fdfcd398ea01637e5dfae">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Dockerfile</strong><dd><code>Streamline Hybrid Image by Removing Redundant Python Packages</code></dd></summary>
<hr>

ci/images/hybrid/Dockerfile
<li>Removed <code>python3-setuptools</code> from the Dockerfile, aligning with efforts <br>to minimize the attack surface.<br> <li> Ensured essential packages like <code>libpython3-dev</code>, <code>curl</code>, <code>ca-certificates</code>, <br>and <code>python3-grpcio</code> remain installed for operational requirements.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6134/files#diff-3bd8f7a8edc2a864b0d49a6aee2c344f8f64bde4985e4d7bec549c4799fdded2">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6134/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8231792240)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6134/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8231792240)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v5.3.0-alpha16
Commit: d584ed4b41ec391bc258d48d18cfc86bfd8d1aaf 
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8231799850)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v5.3.0-alpha16
Commit: d584ed4b41ec391bc258d48d18cfc86bfd8d1aaf 
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8231799850)

**Comment by alephnull** [comment]
As discussed, let's get this done via the templates. No need to close it just yet, it will serve as a useful comparison. 
When the templates are applied, this should close automatically as there will be no changes to apply.

**Pull request closed without merging**
