### PR TITLE
[TD-1474]: Update sync-automation with version support.

### PR DESCRIPTION
**Pull request by asutosh**
## Description

Add version support to the sync-automation workflow.

## Related Issue

TD-1474

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4819/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4300522658)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4819/merge
Commit: 422b1dd8a67880c9c88d09cd9b69a6fabe44388f 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4301043221)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4819/merge
Commit: f70529b7335e30af177a5f1d3d973f514861bc50 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4303049971)

**Review by alephnull — APPROVED** [review]

**Review by ermirizio — APPROVED** [review]
lgtm

**Pull request merged**
