### PR TITLE
refactor auth config type with const

### PR DESCRIPTION
**Pull request by jeffy-mathew**
refactor config type usages with const

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3930/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1961792706)

**Review by furkansenharputlu — APPROVED** [review]

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/3930/merge
Commit: 41b3adf5637615631a6ea1b7806ba416838427b0 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3904133198)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3930/merge
Commit: 2600c125ac3bdd6a590d01833199644751707de7 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3904173663)

**Comment by jeffy-mathew** [comment]
closing due to no traction

**Pull request closed without merging**
