### PR TITLE
TT-7594 OTel instrumentation

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

Adding OpenTelemetry instrumentation on our middleware chain and `RoundTripper` to propagate context.

## Related Issue

https://tyktech.atlassian.net/browse/TT-7594
## Motivation and Context

https://tyktech.atlassian.net/browse/TT-7594

## How This Has Been Tested

Unit tests
Manually
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5269/merge
Commit: 5a02f08348f82a02d24d1ba5e29f56fbfa40cd79 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5456182492)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5269/merge
Commit: 1f65f8e20843a302b613a72459589b13de93a48c 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5456253708)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5269/merge
Commit:  
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5456143788)

**Review by mativm02 — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5269/merge
Commit: 30c76ca2478cd4218cde4c19b10f3a2f0d1b24f4 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5457359770)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5269/merge
Commit: fbe0b6e5420fadf1f10bc7a3aa994a521f899355 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5457543060)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5269/merge
Commit: 7caa6187029f077051cc6a757c8e871ac2e24956 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5457584518)

**Review by sredxny — APPROVED** [review]
✅

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5269/merge
Commit: 8a5957d5c5a37b2c2c01d386d586f19f276684d3 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5457759447)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5269/merge
Commit: 525572ba3bc3445440c7f667ee05893211de55e5 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5461494624)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5269/merge
Commit: c52c29eabc20cbb8340d7dcbb3994c3f571025f3 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5461514560)

**Pull request merged**
