### PR TITLE
[TT-8978] Updating to storage v1.0.5

### PR DESCRIPTION
**Pull request by mativm02**
## Description
https://tyktech.atlassian.net/browse/TT-8978?atlOrigin=eyJpIjoiN2ZlZTFkZDA5ZDZhNDg3M2I0N2RkMmVhMzZkZDA3OTkiLCJwIjoiaiJ9

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5044/merge
Commit: 2b900e0d570763dfdf3d2ef7f268736284823054 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5047110095)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5044/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5047107444)

**Review by sredxny — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5044/merge
Commit: c64670a0389657a28d3f1127c8b5cc3c0588ae44 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5047170138)

**Pull request merged**
