### PR TITLE
Remove lonelycode/go-uuid (test dependency)

### PR DESCRIPTION
**Pull request by titpetric**
## Description

lonelycode/go-uuid is a test dependency; remove it to use internal uuid package.

## Motivation and Context

Outdatated dependency, multiple dependencies for same purpose.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Review by jeffy-mathew — APPROVED** [review]

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4797/merge
Commit: a049af3bdcbce104f71ce0625175bcd28b3eceb1 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4383434369)

**Pull request merged**
