### PR TITLE
Sync Automation

### PR DESCRIPTION
**Pull request by ermirizio**
Add Sync automation for tyk

:robot: Beep, boop, this PR has been generated by [automation](https://github.com/TykTechnologies/gromit/blob/master/cmd/policy.go) on Tue Oct 25 22:16:25 UTC 2022
because commits on `master` need to be propagated to the branches `[release-4 release-4.2]`
as per the current repository policy.

## Policy for tyk
Commits affecting these files will be ported as listed below.

### Ports
| Source branch | Destination branches |
|---------------|----------------------|
master |  [release-4 release-4.2] |

Thank you for reading this far. Since this PR is generated by automation, if there
are inconsistencies in the information provided above, they are bugs and merging
this PR will probably do some damage. Please log a jira in the TD project citing this PR.

### CODE REVIEW

**Comment by ermirizio** [comment]
@konrad-sol  Adding the new porting rule, plus removing release-3.2.3 as per @buger request

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4366/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3324667906)

**Review by konrad-sol — APPROVED** [review]

**Review by asutosh — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4366/merge
Commit: 90008db2e7999e6b24dbb331eb629dc720ad141f 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3330071772)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4366/merge
Commit: 9a5dd417275255642ba2c5a8663634794f895ca6 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3339065057)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 8bd6b30595e44fc3d543f58aa7ca5d7b86a81892 Sync Automation (#4366)

* Releng sync

* Releng sync

* Sync Automation

Co-authored-by: Gromit <policy@gromit>
Triggered by: push (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3339147519)

**Pull request merged**
