### PR TITLE
[TT-7316] Use python 3.9 in CI tests

### PR DESCRIPTION
**Pull request by titpetric**
## Description

```
Run actions/setup-python@v2
  with:
    python-version: [3](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:3).5
    token: ***
  env:
    TYK_DB_REDISHOST: localhost
    TYK_GW_STORAGE_HOST: localhost
    GOROOT: /opt/hostedtoolcache/go/1.16.15/x6[4](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:4)
Version 3.[5](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:5) was not found in the local cache
Error: Version 3.5 with arch x[6](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:6)4 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

There are particular 3.5 versions in the manifest, trying to pin 3.5.10 in particular.

Upstream issue tells that we need to update to 3.7 (3.6 was end-of-life in december 2021)

## Related Issue

Blocking CI on multiple PRs.

https://tyktech.atlassian.net/browse/TT-7316

## Motivation and Context

Unblock PRs.

## How This Has Been Tested

CI checks below.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4503/merge
Commit: 9992c43ca79a420b89d28158dee719a45903f100 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3646703494)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4503/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3646616225)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4503/merge
Commit: 0d1d9d9d1a78a3018cae4f23edb1d4fc14556718 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3647334655)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4503/merge
Commit: c70d2bf56a91ba60fd5d93b1227fe4a944f2f895 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3647460396)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4503/merge
Commit: 5bb54f3d4285b84b83295f44360ae22f1fd35971 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3647604749)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4503/merge
Commit: acdabf0bc7138dffd72a3ccd06fc05d41ec2f866 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3647759507)

**Comment by buger** [comment]
So just to fully understand. 
Are we staying that in order to work with newer python this ENV var is required? 
If so, it is fine, just needs additional note to customers/docs, and it probably can be added even now.

**Comment by titpetric** [comment]
@buger this just fixes the tests as suggested:

> Descriptors cannot not be created directly.
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> If you cannot immediately regenerate your protos, some other possible workarounds are:
>  1. Downgrade the protobuf package to 3.20.x or lower.
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

Notes:

1. The offending line is `pip install protobuf` from ci-tests.yaml, as this should have a pinned version (takes an incompatible latest),
2. We need to regenerate the .pb.go files with update bindings with a new enough protoc (separate ticket)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4503/merge
Commit: a139b655caef6633c04bea01faf8683d92ec236c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3647510489)

**Review by furkansenharputlu — APPROVED** [review]

**Review by lghiur — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 516e25e7cb5fab6564870b8959a7dbce161f9693 [TT-7316] Use python 3.9 in CI tests (#4503)



## Description

```
Run actions/setup-python@v2
  with:
    python-version: [3](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:3).5
    token: ***
  env:
    TYK_DB_REDISHOST: localhost
    TYK_GW_STORAGE_HOST: localhost
    GOROOT: /opt/hostedtoolcache/go/1.16.15/x6[4](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:4)
Version 3.[5](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:5) was not found in the local cache
Error: Version 3.5 with arch x[6](https://github.com/TykTechnologies/tyk/actions/runs/3646579334/jobs/6157812544#step:6:6)4 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

There are particular 3.5 versions in the manifest, trying to pin 3.5.10
in particular.

Upstream issue tells that we need to update to 3.7 (3.6 was end-of-life
in december 2021)


## Related Issue





Blocking CI on multiple PRs.

https://tyktech.atlassian.net/browse/TT-7316

## Motivation and Context


Unblock PRs.

## How This Has Been Tested

CI checks below.






## Screenshots (if appropriate)

## Types of changes



- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why

Co-authored-by: Tit Petric <tit@tyk.io>
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3648479787)

**Pull request merged**
