### PR TITLE
[TT-9467]: Added graphstats processing to recorded analytics

### PR DESCRIPTION
**Pull request by kofoworola**
## Description
This PR makes use of the incoming changes to the pump in this [PR](https://github.com/TykTechnologies/tyk-pump/pull/736) to allow the graph pumps to record analytics without the need to enable detailed recording 

[TT-9467](https://tyktech.atlassian.net/browse/TT-9476)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

[TT-9467]: https://tyktech.atlassian.net/browse/TT-9467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6729412541)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit: a0a379ebbea3a416d1de723d0533558eed202ae8 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6729430021)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit: d2bbfa4278e020df9d798219cd3982ee980b5fe7 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6730406135)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit: fa64684c42d421ac4c90a1318358e30f4a527992 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6730436642)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit: 6f9352ceb04314368c44ca01da7fd18beb627bbe 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6743982429)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit: ddcc43c16b259cdfeafecf2791216cf41c9d8411 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6767826953)

**Review by pvormste — APPROVED** [review]

**Review by buraksezer — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit: b3bfae1ae4579d5685bae423ca1fc31a6d5f4179 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6771243531)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit: 4576a5a6c9ba8367687642c546c41e9527cba3d7 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6780284469)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit: 89f99eb30161c8fe40fd25a9ecf3fe02fd535d57 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6781115206)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5716/merge
Commit: 3f53c1dd824f53a843b360e57bb62631cb18da33 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6782135667)

**Pull request merged**
