### PR TITLE
Enable the gateway to use a dashboard (or cluster) as a pub/sub server instead of redis

### PR DESCRIPTION
**Pull request by lonelycode**
To enable the pub/sub client, set `"pubsub_master_connectionstring": "mangos://tyk-dashboard:9001"` in the `tyk.conf file, make sure the dashboard or dashboards are running. The hostnmae can be a single host or a load balancer.

This sits on top of the dq branch.

### CODE REVIEW

**Comment by lonelycode** [comment]
@mvdan might need your help to squash this thing down.

**Comment by mvdan** [comment]
We should do that once the dq branch is merged, as this one seems to depend on that.

**Comment by lonelycode** [comment]
Yep it's based off the original dq cherry pick which is why it's funky. I just wanted a PR in place so that I can start on the k/v piece.

**Comment by mvdan** [comment]
Sure - let's get the dq one merged first. I'll hold off reviewing this one for now.

**Comment by mvdan** [comment]
This one is getting a bit out of control with the conflicts, so I'll do a squash+rebase on monday. @lonelycode do you want to keep any history? Can I do a single commit like the dq branch?

**Comment by lonelycode** [comment]
No go for it - squash away

**Comment by buger** [comment]
Will close it but keep branch for reference

**Pull request closed without merging**
