### PR TITLE
[TT-736] Non-expiring keys priority over session lifetime

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

Non-expiring keys should not expire even if the API session lifetime is set. 

## Related Issue

https://tyktech.atlassian.net/browse/TT-736
## Motivation and Context

https://tyktech.atlassian.net/browse/TT-736

## How This Has Been Tested

Create an API with token auth, set `session_lifetime` to a low value (10 seconds for example).
Create a key for that API and set Do not Expire.
Try the key after 10 seconds. The key should still work.
Create another key for that API with 1 hour expiration.
Try the key after 10 seconds. It should be expired.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by gernest — CHANGES_REQUESTED** [review]
can we have a test for this? Its a serious bug we don't want it happen again.

**Comment by tbuchaillot** [comment]
> can we have a test for this? Its a serious bug we don't want it happen again.

@gernest added a test for this scenario.

**Review by gernest — APPROVED** [review]

**Review by matiasinsaurralde — APPROVED** [review]
LGTM

**Comment by matiasinsaurralde** [comment]
Removed from:
- `release-3-lts`.
- `release-3.1`.
- `release-3`.
- `release-3.0.3`.

**Pull request merged**
