### PR TITLE
Tidy up go.mod.

### PR DESCRIPTION
**Pull request by asutosh**
## Description
The current go.mod has some unused dependencies. This makes
the git state dirty during the release pipeline on the
release-4-lts branch when goreleaser is in release mode
(i.e. when pushing a tag), since we use `go mod tidy` before
vendoring the dependences  and copying them over to GOPATH
before build.
This PR runs a `go mod tidy` so that go.mod and go.sum isn't
changed during the `Fix vendor` stage.

The failing build stage is in: https://github.com/TykTechnologies/tyk/runs/5449267974?check_suite_focus=true

### CODE REVIEW

**Comment by alephnull** [comment]
CI tests are failing.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3920/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1950500952)

**Comment by tbuchaillot** [comment]
@asutosh you need to `gofmt` some files

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3920/merge
Commit: 6860ee36aae4d13c8dc20e627157d7c38d027ddb 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1950756115)

**Review by jeffy-mathew — APPROVED** [review]

**Review by tbuchaillot — APPROVED** [review]

**Review by matiasinsaurralde — APPROVED** [review]
Looks good

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4-lts
Commit: 46ca82e98215261778ea12cef1b1ee055280f7f0 Tidy up go.mod. (#3920)

* Tidy up go.mod.

The current go.mod has some unused dependencies. This makes
the git state dirty during the release pipeline on the
release-4-lts branch when goreleaser is in release mode
(i.e. when pushing a tag) since we use `go mod tidy` before
vendoring the dependencies  and copying them over to GOPATH
before build.
This runs a `go mod tidy` so that go.mod and go.sum isn't
changed during the `Fix vendor` stage.

* go fmt some source files.
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1951050937)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4-lts
Commit: 46ca82e98215261778ea12cef1b1ee055280f7f0 Tidy up go.mod. (#3920)

* Tidy up go.mod.

The current go.mod has some unused dependencies. This makes
the git state dirty during the release pipeline on the
release-4-lts branch when goreleaser is in release mode
(i.e. when pushing a tag) since we use `go mod tidy` before
vendoring the dependencies  and copying them over to GOPATH
before build.
This runs a `go mod tidy` so that go.mod and go.sum isn't
changed during the `Fix vendor` stage.

* go fmt some source files.
Triggered by: push (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1951050937)

**Pull request merged**
