### PR TITLE
NormalisePath and RegExp optimizations

### PR DESCRIPTION
**Pull request by dencoded**
changes for https://github.com/TykTechnologies/tyk/issues/1633

benchmark before:
```
time="May  8 14:09:43" level=info msg="Disabled feature" 
goos: darwin
goarch: amd64
pkg: github.com/TykTechnologies/tyk
BenchmarkURLReplacer-8   	  500000	     17705 ns/op	     848 B/op	      44 allocs/op
PASS
ok  	github.com/TykTechnologies/tyk	9.332s
```
benchmark after:
```
time="May  9 12:28:00" level=info msg="Disabled feature" 
goos: darwin
goarch: amd64
pkg: github.com/TykTechnologies/tyk
BenchmarkURLReplacer-8   	 3000000	      2124 ns/op	     960 B/op	       8 allocs/op
PASS
ok  	github.com/TykTechnologies/tyk	8.614s
```
NOTE: x6 throughput increase (!)

benchcmp output (vs master):
```
benchmark                  old ns/op     new ns/op     delta
BenchmarkURLReplacer-8     17705         2124          -88.00%

benchmark                  old allocs     new allocs     delta
BenchmarkURLReplacer-8     44             8              -81.82%

benchmark                  old bytes     new bytes     delta
BenchmarkURLReplacer-8     848           960           +13.21%
```

what was changed:

- if config is already available in calling part - pass config to function - reduces fight for mutex (gives ~13% improvement) 
- added new package "`github.com/TykTechnologies/tyk/regexp`" (real performance boost comes from this change) which provides the same API as standard `"regexp"` but with caching inside (not for all functions - we can extend it as we go with our optimization changes for other tickets). Also, added some tests for it, still need to figure out how to test cache hits for `Regexp`'s methods

### CODE REVIEW

**Comment by joshblakeley** [comment]
Wow that is huge

**Comment by matiasinsaurralde** [comment]
Great, would like to test this in addition to the versioning enhancements I'm working on

**Comment by buger** [comment]
Don't you think we should limit number of cached items to avoid cache overflow? Especially when there are a lot of unique URLs like on our Cloud?

We are using github.com/pmylund/go-cache all over the code, which allows you to set the expiration of cached item, and in addition, it is already thread-safe. Do you think it makes sense re-use it here too?

**Comment by dencoded** [comment]
I guess we need to decide - if items here need to have expiration or not, I feel like we don't need expiration. I'd apply some LRU logic instead of expiration, to avoid keeping unused items for a long time but it seemed to be over-engineering. So, I made assumption that being memory bound is OK in that case. The chunk of code we are optimizing here is pretty small and we need to do minimal overhead, I mean those -88% can easily turn into -30% or less  if we add a couple of lines of code.

I was thinking about `go-cache` we use but I don't very like it because:

- it is source of `gettimeofday` sys-calls even if items are supposed to be without expiration
- another concern is efficiency of it, Its main purpose in our code is to avoid network I/O to Redis and it beats it easily as network roundtrip will be always slower than access in-app memory. however, here we are trying to avoid CPU intensive operations and code which helps to do that should be efficient enough, we can end up tuning `go-cache` instead of out code
- it stores `interface{}` which means we have to do type casting every time we have cache-hit with `Get`

**Comment by buger** [comment]
I assume that this package should be applied to the rest of regexp usages, like URL rewriter. 
And inside advanced URL rewriter, we can run regexps against body, headers, query attributes: which can be quite big or had random nature. And in this case, such caching mechanism can cause quite big issues.

I wonder if it makes sense to include at least some basic guards here, like the length of the cached key, and a total number of items in the cache, after which, caching of new keys (or too big keys) will be disabled.

**Comment by dencoded** [comment]
@buger added changes:

- to use go-cache with expiration
- new config key `disable_regexp_cache` to disable regexp cache (default `false`)
- new config key `regexp_cache_expire` to set ttl for regexp cache items (default is 0 which means no expire)

Benchmark results look good:
```
benchmark                  old ns/op     new ns/op     delta
BenchmarkURLReplacer-8     18891         1852          -90.20%

benchmark                  old allocs     new allocs     delta
BenchmarkURLReplacer-8     44             12             -72.73%

benchmark                  old bytes     new bytes     delta
BenchmarkURLReplacer-8     848           1088          +28.30%
```

Before:
```
goos: darwin
goarch: amd64
pkg: github.com/TykTechnologies/tyk
BenchmarkURLReplacer-8   	  500000	     18891 ns/op	     848 B/op	      44 allocs/op
```

After:
```
goos: darwin
goarch: amd64
pkg: github.com/TykTechnologies/tyk
BenchmarkURLReplacer-8   	 5000000	      1852 ns/op	    1088 B/op	      12 allocs/op
```

**Comment by dencoded** [comment]
@buger also, added guards for:

- cache item key size is up to 1024 chars (I am not too worried about this one as Go's hash-function applied to map keys is pretty efficient, but still good to restrict)
- cache item value size is up to 2048 chars - this one is for methods which return string as result

I suggest we will follow the same tactic when switch more regexp's methods to cached version.

**Comment by dencoded** [comment]
just noticed old vs. new version is now x10 throughput improvement (used to be x6), I think it is result of rebase on master which is cool

**Comment by dencoded** [comment]
@buger I've changed more places to use this package.

benchcmp of this branch vs. master:
```
benchmark                                                   old ns/op     new ns/op     delta
BenchmarkURLReplacer-8                                      17637         1869          -89.40%
BenchmarkTagHeaders-8                                       953           945           -0.84%
BenchmarkDefaultVersion-8                                   1143315       1094309       -4.29%
BenchmarkGetVersionFromRequest/Header_location-8            502427        504809        +0.47%
BenchmarkGetVersionFromRequest/URL_param_location-8         478343        488246        +2.07%
BenchmarkGetVersionFromRequest/URL_location-8               470380        486483        +3.42%
BenchmarkApiReload-8                                        3582607       3482962       -2.78%
BenchmarkValueExtractor/HeaderSource-8                      121317        127691        +5.25%
BenchmarkValueExtractor/FormSource-8                        132757        134276        +1.14%
BenchmarkRegexExtractor/HeaderSource-8                      126821        123369        -2.72%
BenchmarkRegexExtractor/BodySource-8                        129054        126180        -2.23%
BenchmarkRegexExtractor/FormSource-8                        135812        131541        -3.14%
BenchmarkXPathExtractor/HeaderSource-8                      141782        143546        +1.24%
BenchmarkXPathExtractor/BodySource-8                        140991        139986        -0.71%
BenchmarkXPathExtractor/FormSource-8                        149560        150459        +0.60%
BenchmarkInitGenericEventHandlers-8                         748           757           +1.20%
BenchmarkMultiSession_BA_Standard_OK-8                      1526833       1536099       +0.61%
BenchmarkBearerTokenAuthKeySession-8                        1824252       1330428       -27.07%
BenchmarkMultiAuthBackwardsCompatibleSession-8              1835469       1352967       -26.29%
BenchmarkBasicAuth-8                                        166257872     157838347     -5.06%
BenchmarkContextVarsMiddleware-8                            1503570       1329565       -11.57%
BenchmarkMiddlewareContextVars_ProcessRequest_cookies-8     182296        139072        -23.71%
BenchmarkHMACAuthSessionPass-8                              1345033       1269627       -5.61%
BenchmarkHMACAuthSessionPassWithHeaderField-8               1399417       1366927       -2.32%
BenchmarkIPBlacklistMiddleware-8                            30217         28084         -7.06%
BenchmarkIPMiddlewarePass-8                                 22054         17438         -20.93%
BenchmarkJWTSessionHMAC-8                                   413662        387747        -6.26%
BenchmarkJWTSessionRSA-8                                    500462        496211        -0.85%
BenchmarkJWTSessionRSABearer-8                              503045        500754        -0.46%
BenchmarkJWTSessionRSAWithRawSourceOnWithClientID-8         511657        503926        -1.51%
BenchmarkJWTSessionRSAWithRawSource-8                       508989        510455        +0.29%
BenchmarkJWTSessionRSAWithJWK-8                             503634        509010        +1.07%
BenchmarkJWTSessionRSAWithEncodedJWK-8                      503104        500626        -0.49%
BenchmarkProcessRequestLiveQuotaLimit-8                     609915        603677        -1.02%
BenchmarkProcessRequestOffThreadQuotaLimit-8                455028        455834        +0.18%
BenchmarkProcessRequestLiveRedisRollingLimiter-8            892327        898661        +0.71%
BenchmarkProcessRequestOffThreadRedisRollingLimiter-8       747129        734995        -1.62%
BenchmarkStripAuth_stripFromHeaders-8                       8861          8642          -2.47%
BenchmarkStripAuth_stripFromParams-8                        39694         40192         +1.25%
BenchmarkTransformNonAscii-8                                15730         15390         -2.16%
BenchmarkTransformJSONMarshal-8                             17040         16552         -2.86%
BenchmarkRewriter-8                                         57391         33428         -41.75%
BenchmarkValidateJSONSchema-8                               1856091       1801405       -2.95%
BenchmarkVersioning-8                                       2214420       2045423       -7.63%
BenchmarkVirtualEndpoint-8                                  370865        352968        -4.83%
BenchmarkApplyPolicies-8                                    27679         26821         -3.10%
BenchmarkResponseHeaderInjection-8                          2049338       2046038       -0.16%
BenchmarkRequestIPHops-8                                    449           409           -8.91%
BenchmarkWrappedServeHTTP-8                                 215458        142900        -33.68%
BenchmarkCopyRequestResponse-8                              20595         14475         -29.72%

benchmark                                                   old allocs     new allocs     delta
BenchmarkURLReplacer-8                                      44             12             -72.73%
BenchmarkTagHeaders-8                                       15             15             +0.00%
BenchmarkDefaultVersion-8                                   1637           1641           +0.24%
BenchmarkGetVersionFromRequest/Header_location-8            655            678            +3.51%
BenchmarkGetVersionFromRequest/URL_param_location-8         639            642            +0.47%
BenchmarkGetVersionFromRequest/URL_location-8               628            631            +0.48%
BenchmarkApiReload-8                                        23903          23900          -0.01%
BenchmarkValueExtractor/HeaderSource-8                      50             50             +0.00%
BenchmarkValueExtractor/FormSource-8                        77             77             +0.00%
BenchmarkRegexExtractor/HeaderSource-8                      52             52             +0.00%
BenchmarkRegexExtractor/BodySource-8                        62             62             +0.00%
BenchmarkRegexExtractor/FormSource-8                        79             79             +0.00%
BenchmarkXPathExtractor/HeaderSource-8                      108            108            +0.00%
BenchmarkXPathExtractor/BodySource-8                        116            116            +0.00%
BenchmarkXPathExtractor/FormSource-8                        140            140            +0.00%
BenchmarkMultiSession_BA_Standard_OK-8                      498            498            +0.00%
BenchmarkBearerTokenAuthKeySession-8                        441            451            +2.27%
BenchmarkMultiAuthBackwardsCompatibleSession-8              446            456            +2.24%
BenchmarkBasicAuth-8                                        20077          20062          -0.07%
BenchmarkContextVarsMiddleware-8                            1951           1938           -0.67%
BenchmarkMiddlewareContextVars_ProcessRequest_cookies-8     28             28             +0.00%
BenchmarkHMACAuthSessionPass-8                              294            296            +0.68%
BenchmarkHMACAuthSessionPassWithHeaderField-8               320            324            +1.25%
BenchmarkIPBlacklistMiddleware-8                            152            152            +0.00%
BenchmarkIPMiddlewarePass-8                                 95             95             +0.00%
BenchmarkJWTSessionHMAC-8                                   595            571            -4.03%
BenchmarkJWTSessionRSA-8                                    673            673            +0.00%
BenchmarkJWTSessionRSABearer-8                              705            675            -4.26%
BenchmarkJWTSessionRSAWithRawSourceOnWithClientID-8         724            726            +0.28%
BenchmarkJWTSessionRSAWithRawSource-8                       713            685            -3.93%
BenchmarkJWTSessionRSAWithJWK-8                             717            688            -4.04%
BenchmarkJWTSessionRSAWithEncodedJWK-8                      691            693            +0.29%
BenchmarkProcessRequestLiveQuotaLimit-8                     556            556            +0.00%
BenchmarkProcessRequestOffThreadQuotaLimit-8                527            527            +0.00%
BenchmarkProcessRequestLiveRedisRollingLimiter-8            2120           2116           -0.19%
BenchmarkProcessRequestOffThreadRedisRollingLimiter-8       2303           2306           +0.13%
BenchmarkStripAuth_stripFromHeaders-8                       66             66             +0.00%
BenchmarkStripAuth_stripFromParams-8                        220            220            +0.00%
BenchmarkTransformNonAscii-8                                98             98             +0.00%
BenchmarkTransformJSONMarshal-8                             101            101            +0.00%
BenchmarkRewriter-8                                         269            238            -11.52%
BenchmarkValidateJSONSchema-8                               2528           2535           +0.28%
BenchmarkVersioning-8                                       3177           2863           -9.88%
BenchmarkVirtualEndpoint-8                                  372            374            +0.54%
BenchmarkApplyPolicies-8                                    102            102            +0.00%
BenchmarkResponseHeaderInjection-8                          2507           2541           +1.36%
BenchmarkRequestIPHops-8                                    4              4              +0.00%
BenchmarkWrappedServeHTTP-8                                 144            144            +0.00%
BenchmarkCopyRequestResponse-8                              76             76             +0.00%

benchmark                                                   old bytes     new bytes     delta
BenchmarkURLReplacer-8                                      849           1088          +28.15%
BenchmarkTagHeaders-8                                       384           384           +0.00%
BenchmarkDefaultVersion-8                                   221743        221674        -0.03%
BenchmarkGetVersionFromRequest/Header_location-8            96381         97048         +0.69%
BenchmarkGetVersionFromRequest/URL_param_location-8         96075         96051         -0.02%
BenchmarkGetVersionFromRequest/URL_location-8               93329         93341         +0.01%
BenchmarkApiReload-8                                        1788893       1788776       -0.01%
BenchmarkValueExtractor/HeaderSource-8                      4569          4570          +0.02%
BenchmarkValueExtractor/FormSource-8                        10666         10667         +0.01%
BenchmarkRegexExtractor/HeaderSource-8                      4766          4603          -3.42%
BenchmarkRegexExtractor/BodySource-8                        9214          9058          -1.69%
BenchmarkRegexExtractor/FormSource-8                        10861         10705         -1.44%
BenchmarkXPathExtractor/HeaderSource-8                      9376          9374          -0.02%
BenchmarkXPathExtractor/BodySource-8                        13795         13795         +0.00%
BenchmarkXPathExtractor/FormSource-8                        15987         15988         +0.01%
BenchmarkMultiSession_BA_Standard_OK-8                      83051         83048         -0.00%
BenchmarkBearerTokenAuthKeySession-8                        78279         78572         +0.37%
BenchmarkMultiAuthBackwardsCompatibleSession-8              79935         80210         +0.34%
BenchmarkBasicAuth-8                                        1059877       1060672       +0.08%
BenchmarkContextVarsMiddleware-8                            304452        301282        -1.04%
BenchmarkMiddlewareContextVars_ProcessRequest_cookies-8     2388          2386          -0.08%
BenchmarkHMACAuthSessionPass-8                              47899         48513         +1.28%
BenchmarkHMACAuthSessionPassWithHeaderField-8               50738         51814         +2.12%
BenchmarkIPBlacklistMiddleware-8                            32346         32343         -0.01%
BenchmarkIPMiddlewarePass-8                                 26735         26733         -0.01%
BenchmarkJWTSessionHMAC-8                                   86744         85665         -1.24%
BenchmarkJWTSessionRSA-8                                    107749        107752        +0.00%
BenchmarkJWTSessionRSABearer-8                              110276        108996        -1.16%
BenchmarkJWTSessionRSAWithRawSourceOnWithClientID-8         110075        111178        +1.00%
BenchmarkJWTSessionRSAWithRawSource-8                       107400        107232        -0.16%
BenchmarkJWTSessionRSAWithJWK-8                             107470        106200        -1.18%
BenchmarkJWTSessionRSAWithEncodedJWK-8                      106325        106413        +0.08%
BenchmarkProcessRequestLiveQuotaLimit-8                     85039         85029         -0.01%
BenchmarkProcessRequestOffThreadQuotaLimit-8                83721         83715         -0.01%
BenchmarkProcessRequestLiveRedisRollingLimiter-8            144093        143924        -0.12%
BenchmarkProcessRequestOffThreadRedisRollingLimiter-8       151441        151546        +0.07%
BenchmarkStripAuth_stripFromHeaders-8                       2800          2800          +0.00%
BenchmarkStripAuth_stripFromParams-8                        14161         14161         +0.00%
BenchmarkTransformNonAscii-8                                11060         11060         +0.00%
BenchmarkTransformJSONMarshal-8                             11508         11508         +0.00%
BenchmarkRewriter-8                                         49940         45599         -8.69%
BenchmarkValidateJSONSchema-8                               287704        287562        -0.05%
BenchmarkVersioning-8                                       304356        291761        -4.14%
BenchmarkVirtualEndpoint-8                                  70101         70095         -0.01%
BenchmarkApplyPolicies-8                                    12585         12584         -0.01%
BenchmarkResponseHeaderInjection-8                          399937        398744        -0.30%
BenchmarkRequestIPHops-8                                    432           432           +0.00%
BenchmarkWrappedServeHTTP-8                                 48308         48295         -0.03%
BenchmarkCopyRequestResponse-8                              35584         35584         +0.00%
```

**Comment by buger** [comment]
@dencoded what about `MatchString` usage (especially in api_definition.go), can you also cover it?

**Comment by dencoded** [comment]
@buger both `regexp.MatchString` and `regexp.Regexp.MatchString` are already cached. according to api_definition.go - it should be covered as we switched `URLSpec.Spec` to cached version https://github.com/TykTechnologies/tyk/pull/1689/files#diff-e174c6f6100dfee8c74de8323d464e36R97

I see some test coverage reduction - forgot that I added a couple of new cached methods, I will push one more change with tests for them

**Pull request merged**
