### PR TITLE
[TT-10329] fix getargspec removal from python stdlib in 3.11 (deprecated since python 3.0)

### PR DESCRIPTION
**Pull request by titpetric**
https://tyktech.atlassian.net/browse/TT-10329

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5664/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6614377954)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5664/merge
Commit: ab4122071a39d65a4f20d4db4ff8a55eec3f40f9 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6614805479)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5664/merge
Commit: 0e5a445dfac67e8677cf21684e3c17b637030970 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6615003592)

**Review by sredxny — APPROVED** [review]
lgtm 🚀

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5664/merge
Commit: 6eec3c135751fd77f0fd676a5f4e391f164cde1e 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6615205010)

**Pull request merged**
