### PR TITLE
Test cleanup, flush redis, remove randSeq

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by buger** [comment]
Since you are flushing Redis, is there is a chance to tell the "Tests" use different database number, so it will not override any local data?

**Comment by mvdan** [comment]
You mean flush and use a specific database, instead of flushing everything?

**Comment by buger** [comment]
I'm not sure if it is currently possible, without adding new configuration option which specifies Redis database. In the case of `redisgo` it will look like: "c.Do("SELECT", db);", where `db` is int. By default Redis use `0` database.

**Comment by mvdan** [comment]
We're not using a database that I could see. We could do either of:

* Use a database name for both production and the tests
* Keep the default database for production, but use a specific one for the tests

Or keep things as they are. The only inconvenient now is that it might stomp data when running the tests.

cc @lonelycode

**Comment by buger** [comment]
Actually looks like it is possible, and if in `TestMain` you will set `config.Storage.Database` and `config.CacheStorage.Database` to 1, and will use `c.Do("SELECT", db)` when flushing, tests will use separate Redis database.

**Comment by mvdan** [comment]
SGTM, will update the PR.

**Comment by mvdan** [comment]
@buger done and rebased, PTAL

**Pull request merged**
