### PR TITLE
[TT-5298] Fix resource leak in config.Load, close file handle

### PR DESCRIPTION
**Pull request by titpetric**

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4042/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2312231022)

**Review by jeffy-mathew — APPROVED** [review]

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4042/merge
Commit: 6ade7269b65a10394dd90c4b6af8d9b21462f03f 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2317706236)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4042/merge
Commit: 0336e1adea8f3cda23054f833b6186c059948dbe 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2318924487)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4042/merge
Commit: 642d779f9173e4a126a2df430e1c9f7c37f1d497 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2337240530)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: a0437275a58599e094ac11786d207f2dcbfaa921 Fix resource leak in config.Load, close file handle (#4042)
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2337549991)

**Pull request merged**
