### PR TITLE
Try fixing latest sync-automation  errors.

### PR DESCRIPTION
**Pull request by asutosh**
## Description

Trying to fix the  sync-automation runtime errors.
https://github.com/TykTechnologies/tyk/runs/7851807257?check_suite_focus=true#step:3:21

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4240/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2874014191)

**Review by alephnull — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4240/merge
Commit: c5ffc5b48e5fef7748acb71fa91dff3892c08225 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2874711400)

**Review by ermirizio — APPROVED** [review]
Looks good, we have reviewed together with asutosh

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: eb11d47e78eb6e327a9229e389357bce567ccc3c Try fixing latest sync-automation workflow errors. (#4240)

* Try fixing latest sync-automation  errors.
* Add dependabot to sync-automation.
[changelog]
internal: fix sync-automation workflow.
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2875434813)

**Pull request merged**
