### PR TITLE
[TT-13087] Adjust example gateway config, to have match preficing explicit by default

### PR DESCRIPTION
**Pull request by lghiur**
## Description
TT-13087 Adjust example gateway config, to have match preficing explicit by default

## Motivation and Context
Would be advised that Gateway users, would have by default explicit path matching settings enabled by default, as the wildcard behaviour of the path matching, can be challenging at times to configure properly.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] I ensured that the documentation is up to date
- [x] I explained why this PR updates go.mod in detail with reasoning why it's required
- [x] I would like a code coverage CI quality gate exception and have explained why

___

### **PR Type**
enhancement, configuration changes

___

### **Description**
- Added new configuration options in `tyk.conf.example` to enable strict routing and explicit path matching by default.
- The changes aim to improve the default behavior for gateway users by making path matching settings explicit.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>tyk.conf.example</strong><dd><code>Add explicit path matching options to example gateway config</code></dd></summary>
<hr>

tyk.conf.example

<li>Added <code>http_server_options</code> section.<br> <li> Enabled <code>enable_strict_routes</code>.<br> <li> Enabled <code>enable_path_prefix_matching</code>.<br> <li> Enabled <code>enable_path_suffix_matching</code>.

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6564/files#diff-a6736b4b3cda1ee503675d7b725f6138f4eb83d7145f3afecf6087d219f2b23a">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Review by titpetric — APPROVED** [review]

**Review by andyo-tyk — APPROVED** [review]
Thanks, approved.

**Pull request merged**
