### PR TITLE
add CI tests on PR and push

### PR DESCRIPTION
**Pull request by konrad-sol**
## Description
Adding github action with API tests. Execution will be triggered on every push to master, release-* and test/* branches.

GW, dash, mongo and redis will be running inside docker-compose and python tests from https://github.com/TykTechnologies/tyk-automated-tests will be executed.

if execution will be triggered by PR -> github action will create a comment in PR with the tests status.

## Related Issue
N/A

## Motivation and Context
We will have full integration test suite executed on every push and PR.

## How This Has Been Tested
Tests executed inside this PR

## Types of changes

- [s] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [s] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [s] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/test/add_tests_in_CI
Commit: f51bf75a89938317722e7da0e3e72ae01275cabb detaching docker-sompose process in CI tests
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1718388335)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3851/merge
Commit:  
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1718441239)

**Review by alephnull — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3851/merge
Commit: 4dcc1edbea2f8f1798c0c89da31d315d1a290b8d 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1719026430)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/test/add_tests_in_CI
Commit: 4dcc1edbea2f8f1798c0c89da31d315d1a290b8d fix depth limits for graphql introspection queries (TT-3314) (#3850)

* fix depth-limit calculation for non-silent introspection queries

* fix introspection for silent queries

* update library
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1719026276)

**Review by lghiur — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: f8fa141eb3e8ccbd82b1b7734364e8ff196e5bbe add CI tests on PR and push (#3851)

* add CI tests on PR and push

* fix in CI api tests job

* adjusting docker-compose env vars

* detaching docker-sompose process in CI tests
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1722368140)

**Pull request merged**
