### PR TITLE
Add analytics upstream latency info 

### LINKED ISSUE #2590: Extend analtyics data to store latency information
Store below latency information in the analytics
1. total latency
2. upstream latency

Data will have precision of ms

### PR DESCRIPTION
**Pull request by gernest**
Closes #2590 
Related https://github.com/TykTechnologies/tyk-pump/issues/151
Related  https://github.com/TykTechnologies/tyk-analytics/issues/1526

### CODE REVIEW

**Comment by buger** [comment]
I assume require pump or too? Also does it handle tcp analytics part too?

**Comment by gernest** [comment]
@buger This is still a work in progress will ping you when ready. Only works for http services. Reasoning about tcp right now.

> I assume require pump or too?
Correct, a PR for that is underway.

One use case is already covered `RequestTime` which is the total request time. Only needed to handle upstream latency.

**Comment by gernest** [comment]
After much thought, I believe this makes sense only to cover tcp services. Because of the following reasons

- For tcp analytics stats are not per connection, they are fired during the lifetime of the connection. This makes `upstream latency` blurry, because the connection can last forever, something that comes that close is maybe measuring the time it takes to read /write to upstream which IMHO is not relevant here as its something else entirely.

- Total request time ( see my point above). `n` number of stats will be fired during a single tcp connection. For http only one stat, meaning it is possible to record meaningful total duration in a single analytic record.

So @buger This is ready to be merged. It is backward compatible so everything should just work no breaking changes (no need to wait for tyk-pump)

**Comment by komalsukhani** [comment]
@buger @gernest If `RequestTime` and Total Latency are same then can we skip Total Latency field?

**Comment by asoorm** [comment]
> After much thought, I believe this makes sense only to cover http services. Because of the following reasons

If I configure Tyk as a TCP proxy to a http service, then latency will be useful for me @gernest 

e.g. a L4 load balancer scenario? Considerably more performant than L7.

so dependent on the service type - is it a long/short lived connection - latency might be handy. because http can still go over tcp.

**Comment by buger** [comment]
@komalsukhani I think it’s done for backward compatibility

**Comment by buger** [comment]
@asoorm in TCP mode it will be just packets not HTTP messages. One HTTP message can be 10 TCP packets, and latency, in this case, will show a completely different picture. Not telling if its a bit more complex case like HTTP2 with multiple streams.

**Comment by buger** [comment]
Looks good to me at this point

**Pull request merged**
