### PR TITLE
Use gorilla/mux for filtering of http methods

### PR DESCRIPTION
**Pull request by mvdan**
See the commit messages.

### CODE REVIEW

**Comment by mvdan** [comment]
Note that misusing an endpoint will now be a `404` instead of a `400`. This is by design, as the route will no longer match unless both the path and the method match the filters.

I think this is an okay tradeoff to make. After all, this is common practice and these errors aren't common.

I found no way to keep the old behaviour while still making proper use of gorilla. Perhaps we could have sub-routers for each endpoint, defaulting to a "method unsupported" if the method filter didn't match, but we'd be back to extra code for each endpoint again.

**Comment by buger** [comment]
@mvdan regarding your TODO. Unfortunately when we set route to "/apis/keys", gorilla/mux do not understand "/apis/keys/" path. So we have to do both.

**Comment by buger** [comment]
I'm talking about your TODO comment added in this PR https://github.com/TykTechnologies/tyk/pull/796/files#diff-7ddfb3e035b42cd70649cc33393fe32cR307

Previously we had only "/api/keys/" route, and a lot of our users was confused because querying "/api/keys" (without trailing slash) did not work, so we added the separate route.

**Comment by mvdan** [comment]
Yes - but the TODO is not about why we have to get both working. The TODO is about me not getting gorilla to do this with a single line. I have to add both routes manually and duplicate the rest of the line. Otherwise, only one of the two versions works.

**Comment by mvdan** [comment]
To clarify, this TODO is in case we figure out how to do it with gorilla in the future, or to look at it again if we ever swap the HTTP router library.

**Comment by buger** [comment]
Right 👍

**Comment by mvdan** [comment]
I got confused with your first comment because I hadn't realised the duplication was already in place, and I thought I was introducing it here. Even then, I think the TODO should be there since we want to clean this up eventually.

**Comment by buger** [comment]
@ilijabojanovic ready for testing

**Comment by buger** [comment]
@mvdan for documentation and testing reasons can you list here all the changes made in this PR. I mostly mean list of paths and HTTP methods, and how http codes changed.

**Comment by mvdan** [comment]
The only change is that using the wrong methods will now be a 404 instead of a 405. Some examples:

* `POST /tyk/health/`
* `GET /tyk/keys/create`
* `DELETE /tyk/reload`

**Comment by buger** [comment]
Well, you change lot of internal code, handling of HTTP codes, and move some of this logic to the router. And potentially /keys/* endpoint can have regression.

**Comment by mvdan** [comment]
Of course, existing endpoints should keep on working. I assumed that was always done as part of regression testing.

**Comment by mvdan** [comment]
I'm going to re-do this with our own method filtering middleware, keeping our current 405 status codes.

**Pull request closed without merging**
