### PR TITLE
[TT-11377] Adding “node_is_segmented” flag under “node” to complement “tags”

### PR DESCRIPTION
**Pull request by mativm02**
## Description
Adding `node_is_segmented` flag under `node` to complement `tags`.

MDCB PR: https://github.com/TykTechnologies/tyk-sink/pull/496

## Related Issue
https://tyktech.atlassian.net/browse/TT-11377?atlOrigin=eyJpIjoiNmNiY2VjZjM3NGZlNDBiZjgwNmNlOTMyOWRjYzIwN2EiLCJwIjoiaiJ9

## Motivation and Context
https://tyktech.atlassian.net/browse/TT-11377?atlOrigin=eyJpIjoiNmNiY2VjZjM3NGZlNDBiZjgwNmNlOTMyOWRjYzIwN2EiLCJwIjoiaiJ9

## How This Has Been Tested
Unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

___

## **Type**
enhancement, tests

___

## **Description**
- Added a new boolean field `NodeIsSegmented` to the `NodeData` struct to indicate if a node is segmented.
- Updated `buildNodeInfo` in `rpc_storage_handler.go` to populate the `NodeIsSegmented` field from the configuration.
- Introduced a new test case in `rpc_storage_handler_test.go` to verify the behavior when the `NodeIsSegmented` flag is set to true.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>rpc.go</strong><dd><code>Add NodeIsSegmented Field to NodeData Struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/rpc.go
- Added `NodeIsSegmented` boolean field to `NodeData` struct.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6093/files#diff-8cfd476d3e5aafb95ff2e1ebbf5d797daccc9bde48fa791cdfbd0c9132508c85">+9/-8</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>rpc_storage_handler.go</strong><dd><code>Populate NodeIsSegmented in buildNodeInfo Function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

gateway/rpc_storage_handler.go
<li>Populated <code>NodeIsSegmented</code> in <code>buildNodeInfo</code> function from <br>configuration.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6093/files#diff-8875f75b602664c44b62b67a4da41d748124ad270573a44db4ec977ee5d68021">+8/-7</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>rpc_storage_handler_test.go</strong><dd><code>Test Case for NodeIsSegmented Flag</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

gateway/rpc_storage_handler_test.go
- Added test case for `NodeIsSegmented` flag being true.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6093/files#diff-69de989a02b3bc32ae376c514ee84633c609200db22385c0e16c361d6ea74cd6">+26/-0</a>&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6093/merge
Commit: e8566320354d569b45421a5107ab6095abe24e90 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8140282319)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6093/merge
Commit: e8566320354d569b45421a5107ab6095abe24e90 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8140282319)

**Review by sredxny — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 3799d4f3e2293bc1781cd791306281efcd7fc21c [TT-11377] Adding “node_is_segmented” flag under “node” to complement “tags” (#6093)

## Description
Adding `node_is_segmented` flag under `node` to complement `tags`.

MDCB PR: https://github.com/TykTechnologies/tyk-sink/pull/496


## Related Issue

https://tyktech.atlassian.net/browse/TT-11377?atlOrigin=eyJpIjoiNmNiY2VjZjM3NGZlNDBiZjgwNmNlOTMyOWRjYzIwN2EiLCJwIjoiaiJ9





## Motivation and Context

https://tyktech.atlassian.net/browse/TT-11377?atlOrigin=eyJpIjoiNmNiY2VjZjM3NGZlNDBiZjgwNmNlOTMyOWRjYzIwN2EiLCJwIjoiaiJ9


## How This Has Been Tested
Unit tests





## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why


___

## **Type**
enhancement, tests


___

## **Description**
- Added a new boolean field `NodeIsSegmented` to the `NodeData` struct
to indicate if a node is segmented.
- Updated `buildNodeInfo` in `rpc_storage_handler.go` to populate the
`NodeIsSegmented` field from the configuration.
- Introduced a new test case in `rpc_storage_handler_test.go` to verify
the behavior when the `NodeIsSegmented` flag is set to true.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>rpc.go</strong><dd><code>Add NodeIsSegmented Field to
NodeData Struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/rpc.go
- Added `NodeIsSegmented` boolean field to `NodeData` struct.



</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6093/files#diff-8cfd476d3e5aafb95ff2e1ebbf5d797daccc9bde48fa791cdfbd0c9132508c85">+9/-8</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>rpc_storage_handler.go</strong><dd><code>Populate
NodeIsSegmented in buildNodeInfo Function</code>&nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

gateway/rpc_storage_handler.go
<li>Populated <code>NodeIsSegmented</code> in <code>buildNodeInfo</code>
function from <br>configuration.<br>


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6093/files#diff-8875f75b602664c44b62b67a4da41d748124ad270573a44db4ec977ee5d68021">+8/-7</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>rpc_storage_handler_test.go</strong><dd><code>Test Case
for NodeIsSegmented Flag</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

gateway/rpc_storage_handler_test.go
- Added test case for `NodeIsSegmented` flag being true.



</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6093/files#diff-69de989a02b3bc32ae376c514ee84633c609200db22385c0e16c361d6ea74cd6">+26/-0</a>&nbsp;
&nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions
Triggered by: push (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8155871663)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 3799d4f3e2293bc1781cd791306281efcd7fc21c [TT-11377] Adding “node_is_segmented” flag under “node” to complement “tags” (#6093)

## Description
Adding `node_is_segmented` flag under `node` to complement `tags`.

MDCB PR: https://github.com/TykTechnologies/tyk-sink/pull/496


## Related Issue

https://tyktech.atlassian.net/browse/TT-11377?atlOrigin=eyJpIjoiNmNiY2VjZjM3NGZlNDBiZjgwNmNlOTMyOWRjYzIwN2EiLCJwIjoiaiJ9





## Motivation and Context

https://tyktech.atlassian.net/browse/TT-11377?atlOrigin=eyJpIjoiNmNiY2VjZjM3NGZlNDBiZjgwNmNlOTMyOWRjYzIwN2EiLCJwIjoiaiJ9


## How This Has Been Tested
Unit tests





## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why


___

## **Type**
enhancement, tests


___

## **Description**
- Added a new boolean field `NodeIsSegmented` to the `NodeData` struct
to indicate if a node is segmented.
- Updated `buildNodeInfo` in `rpc_storage_handler.go` to populate the
`NodeIsSegmented` field from the configuration.
- Introduced a new test case in `rpc_storage_handler_test.go` to verify
the behavior when the `NodeIsSegmented` flag is set to true.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>rpc.go</strong><dd><code>Add NodeIsSegmented Field to
NodeData Struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/rpc.go
- Added `NodeIsSegmented` boolean field to `NodeData` struct.



</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6093/files#diff-8cfd476d3e5aafb95ff2e1ebbf5d797daccc9bde48fa791cdfbd0c9132508c85">+9/-8</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>rpc_storage_handler.go</strong><dd><code>Populate
NodeIsSegmented in buildNodeInfo Function</code>&nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

gateway/rpc_storage_handler.go
<li>Populated <code>NodeIsSegmented</code> in <code>buildNodeInfo</code>
function from <br>configuration.<br>


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6093/files#diff-8875f75b602664c44b62b67a4da41d748124ad270573a44db4ec977ee5d68021">+8/-7</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>rpc_storage_handler_test.go</strong><dd><code>Test Case
for NodeIsSegmented Flag</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

gateway/rpc_storage_handler_test.go
- Added test case for `NodeIsSegmented` flag being true.



</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6093/files#diff-69de989a02b3bc32ae376c514ee84633c609200db22385c0e16c361d6ea74cd6">+26/-0</a>&nbsp;
&nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions
Triggered by: push (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8155871663)

**Pull request merged**
