### PR TITLE
Remove curl from basic images

### PR DESCRIPTION
**Pull request by buger**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit:  
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3955474054)

**Review by alephnull — APPROVED** [review]
LGTM. 

When this is merged it will be propagated to `release-4` and `release-4.3` by https://github.com/TykTechnologies/tyk/actions/workflows/sync-automation.yml. Any other branches it is required on can be done via the bot.

**Comment by buger** [comment]
@alephnull any idea why smoke tests for RC are failing? I'm not sure if it is related to my PR or not.

**Comment by asutosh** [comment]
@buger Looks like it's the python plugin test that's failing - the healthcheck for gateway in the compose file for the test depends on curl - so the removal of curl might have probably caused an issue.

**Comment by buger** [comment]
Good catch! Trying to replace with `wget`

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: 1df0a749f1dbe34efa4c3b31281adff54e23b809 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3956014489)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: b8ac7a7e853c45e1c2af6e3a040d267e50c38389 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3956221471)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: 9b019f85990ed2a62ca49d449e0d63d4455342b3 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3956217725)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: 43309be5ce49b4e2ff7d3a01eccc37671539ea96 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3956440880)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: 74471a021259771d228a80ff5dd595c8447d8fdc 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3956464706)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: 6ebf8cff0046f65dd9d2b7375c3b8ecf6848d179 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3956820994)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: 0c3e6811539e70e3dff4ee8bde874feaa7c357d1 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3957284735)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: 458e4c8e72f4de019fb511b1f6c90f7f794114a8 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3957708457)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: d3279f857cfa1032abc778108aaac51a277f04e0 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3965014147)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: 22abdd2c3084741303256fdd4259f3ab6f889f5c 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3985735764)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4662/merge
Commit: f51a795d40347c6a3cb98e4f16b4dffe753a86bd 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3988476730)

**Pull request merged**
