### PR TITLE
[TT-6110] Updated graphql-go-tools commit hash

### PR DESCRIPTION
**Pull request by buraksezer**
[changelog]
internal: Updated graphql-go-tools commit hash.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4333/merge
Commit:  
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3204646573)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4333/merge
Commit: 5ca1ac5ad0ed55a39b39c838254b2d8b9efb8bc8 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3204788900)

**Review by kofoworola — APPROVED** [review]

**Review by pvormste — APPROVED** [review]

**Review by Aenimus — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: a033c16f7ca389f4aaf90cf090bcd77347bc7cf4 [TT-6110] Updated graphql-go-tools commit hash (#4333)

[changelog]
internal: Updated graphql-go-tools commit hash.
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3218862035)

**Pull request merged**
