### PR TITLE
hello endpoint not dependent on there being more than 0 apis at load

### LINKED ISSUE #1393: Health-check (/hello) 404 if no APIs defined
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
the `/hello` endpoint does not work if there are no APIs defined

**What is the expected behavior?**
The `/hello` endpoint should be available when the application has successfully started listening

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Start an instance without any APIs defined
2. Visit `/hello` on the gateway
3. You will get a 404

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
2.4

### PR DESCRIPTION
**Pull request by joshblakeley**
Really dumb fix for issue where hello endpoint is not loaded in gateway when there are no api's present.

fixes #1393

### CODE REVIEW

**Comment by buger** [comment]
Can you link and describe original issue?

**Comment by joshblakeley** [comment]
See root comment

**Comment by buger** [comment]
I do not think your fix is enough, because `mainRouter` gets overridden on each `doReload`

**Comment by joshblakeley** [comment]
If doReload is called then it falls back to how it behaved before and the endpoint is reinitialised in api_loader I think

**Comment by joshblakeley** [comment]
I just tested and it is always there after adding api and reloading too. So I think this covers the fix.

**Pull request merged**
