### PR TITLE
[TT-3972] Add test utilities, improve tests, mark flaky/racy tests

### PR DESCRIPTION
**Pull request by titpetric**
## Description

This marks flaky/racy tests to be skipped in CI environments.

## Motivation and Context

We were hitting significant false-positive failures in tests, sometimes 4-5x per PR. We realize that we need to improve or rewrite the tests, as they don't handle concurrency well, and rely on guesswork to pass (non-deterministic).

## How This Has Been Tested

I ran the complete test suite 100x in a loop as part of #4035 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4043/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2312254481)

**Review by furkansenharputlu — APPROVED** [review]

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4043/merge
Commit: b459d0f667c142291217b99916756003746cd6a5 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2318218900)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4043/merge
Commit: 5f3e9c7aaa63d676b61e710d4e02fd7b5003257a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2337428396)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4043/merge
Commit: 5cc802eeb591aad16104efadfcdbf4394d8a8ce7 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2337671806)

**Comment by titpetric** [comment]
Merged https://github.com/TykTechnologies/tyk/pull/4035

**Pull request closed without merging**
