### PR TITLE
[TT-3162] Forward api spec tags to analytics

### PR DESCRIPTION
**Pull request by ghost**
This enables forwarding the tags that are configured on the api spec to an analytics record that can be used with the data pump.

## Motivation and Context
According to the documentation this should be possible:
https://tyk.io/docs/advanced-configuration/manage-multiple-environments/with-tyk-on-premises/#a-nametarget-api-definition-for-sharda-target-an-api-definition-for-a-shard

## How This Has Been Tested
Tested locally with a custom build, data is forwarded to redis

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by lghiur** [comment]
Thanks for the contribution, this is currently under review and we will get back with an answer soon.

**Review by vaske — APPROVED** [review]

**Review by furkansenharputlu — APPROVED** [review]

**Review by buger — APPROVED** [review]

**Pull request merged**
