### PR TITLE
TT-11485, fix for global rate limit disabled flag not working

### PR DESCRIPTION
**Pull request by andrei-tyk**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

___

## **Type**
Bug fix

___

## **Description**
- Fixed an issue where the global rate limit disabled flag was not properly checked, causing the rate limiter to be incorrectly enabled.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>mw_api_rate_limit.go</strong><dd><code>Fix Global Rate Limit Disabled Flag Check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

gateway/mw_api_rate_limit.go
<li>Added a condition to check <code>GlobalRateLimit.Disabled</code> flag in <br><code>EnabledForSpec</code> function.<br>

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6120/files#diff-46326b04f936c839922e970db5c2924156cc797070948f3dc9c589d04661d6d2">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6120/merge
Commit:  
Triggered by: pull_request (@andrei-tyk)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8190860038)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6120/merge
Commit:  
Triggered by: pull_request (@andrei-tyk)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8190860038)

**Review by titpetric — APPROVED** [review]

**Review by titpetric — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 53886d044c43930b332dbe4a73cf727069df0770 TT-11485, fix for global rate limit disabled flag not working (#6120)

## **User description**


## Description



## Related Issue






## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why


___

## **Type**
Bug fix


___

## **Description**
- Fixed an issue where the global rate limit disabled flag was not
properly checked, causing the rate limiter to be incorrectly enabled.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Bug
fix</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>mw_api_rate_limit.go</strong><dd><code>Fix Global Rate
Limit Disabled Flag Check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; </dd></summary>
<hr>

gateway/mw_api_rate_limit.go
<li>Added a condition to check <code>GlobalRateLimit.Disabled</code>
flag in <br><code>EnabledForSpec</code> function.<br>


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6120/files#diff-46326b04f936c839922e970db5c2924156cc797070948f3dc9c589d04661d6d2">+1/-1</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions
Triggered by: push (@andrei-tyk)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8201725737)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 53886d044c43930b332dbe4a73cf727069df0770 TT-11485, fix for global rate limit disabled flag not working (#6120)

## **User description**


## Description



## Related Issue






## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why


___

## **Type**
Bug fix


___

## **Description**
- Fixed an issue where the global rate limit disabled flag was not
properly checked, causing the rate limiter to be incorrectly enabled.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Bug
fix</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>mw_api_rate_limit.go</strong><dd><code>Fix Global Rate
Limit Disabled Flag Check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; </dd></summary>
<hr>

gateway/mw_api_rate_limit.go
<li>Added a condition to check <code>GlobalRateLimit.Disabled</code>
flag in <br><code>EnabledForSpec</code> function.<br>


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6120/files#diff-46326b04f936c839922e970db5c2924156cc797070948f3dc9c589d04661d6d2">+1/-1</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions
Triggered by: push (@andrei-tyk)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8201725737)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 53886d044c43930b332dbe4a73cf727069df0770 TT-11485, fix for global rate limit disabled flag not working (#6120)

## **User description**


## Description



## Related Issue






## Motivation and Context



## How This Has Been Tested






## Screenshots (if appropriate)

## Types of changes



- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why


___

## **Type**
Bug fix


___

## **Description**
- Fixed an issue where the global rate limit disabled flag was not
properly checked, causing the rate limiter to be incorrectly enabled.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Bug
fix</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>mw_api_rate_limit.go</strong><dd><code>Fix Global Rate
Limit Disabled Flag Check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; </dd></summary>
<hr>

gateway/mw_api_rate_limit.go
<li>Added a condition to check <code>GlobalRateLimit.Disabled</code>
flag in <br><code>EnabledForSpec</code> function.<br>


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6120/files#diff-46326b04f936c839922e970db5c2924156cc797070948f3dc9c589d04661d6d2">+1/-1</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions
Triggered by: push (@andrei-tyk)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8201725737)

**Pull request merged**
