### PR TITLE
add api schema to analytics record

### PR DESCRIPTION
**Pull request by kofoworola**
## Description

This PR adds the Schema of Graphql/UDG based APIs to AnalyticsRecords to be used by pumps that can parse the graphql request for more metric analysis

## Related Issue

[TT-6333](https://tyktech.atlassian.net/browse/TT-6333)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4285/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2992937374)

**Review by Aenimus — APPROVED** [review]

**Review by buraksezer — APPROVED** [review]

**Review by tbuchaillot — CHANGES_REQUESTED** [review]
@kofoworola can you use pump 1.7.0-rc1 there? Also, we need to update dashboard/mdcb dependencies too

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4285/merge
Commit: d49f827c3a2876e7b7d3d06e25e391a13ccf0d0f 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3013256226)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4285/merge
Commit: b80759df4cadbdf67e5788312ffb11de1c44ceb2 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3020884039)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: b090075b8eab56527047746294d91731cecca711 add api schema to analytics record (#4285)

* add api schema to analytics record

* use appropriate pump version
Triggered by: push (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3022535976)

**Pull request merged**
