### PR TITLE
TT-8934 Fix chunked response analytics

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

When transfer-encoding is chunked on the upstream response, analytics records raw responses also contain the chunked characters (example https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding#examples).
This is not expected.

The proposed solution is to delete the transfer-encoding header before reading and writing the response body to the rawResponse field. Without this header, Go will process the header as it should.

## Related Issue

https://tyktech.atlassian.net/browse/TT-8934
## Motivation and Context

https://tyktech.atlassian.net/browse/TT-8934
## How This Has Been Tested

Added tests

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5495/merge
Commit:  
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6035885508)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5495/merge
Commit: 580b1bf9da6daa8c0ac9411dace19f3320428541 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6035887639)

**Review by mativm02 — APPROVED** [review]
lgtm!

**Review by sredxny — APPROVED** [review]
🚀

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5495/merge
Commit: 85f7733824c3d57b461fe2cc2b6fa5d0e81330e8 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6038622326)

**Pull request merged**
