### PR TITLE
Clean unnecessary error check in getSecretToVerifySignature

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Review by titpetric — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5645/merge
Commit: 2b52bcb5a079f2bc528add6477b99d8ad9b910d2 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6572646993)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5645/merge
Commit: ca6c1f210de4881fba8e3aab4b6b833a1c5c29aa 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6572635435)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5645/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6572630625)

**Pull request merged**
