### PR TITLE
[TT-4583]migrate authconfig name

### PR DESCRIPTION
**Pull request by jeffy-mathew**
migrate authconfig name in authConfigs map

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/3890/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1845341461)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3890/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1845341461)

**Review by lghiur — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3890/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1845341461)

**Review by urbanishimwe — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3890/merge
Commit: da7c9e9e3ef855993dfe65d83cc97d63c6d310b1 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1851852492)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/3890/merge
Commit: 67e5b65a25bf78aaa581671e8e67109756eecfea 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1857704523)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 68aa0ef21b7b445a3dc14e57e59a64b67500acde [TT-4583]migrate authconfig name (#3890)

* Add name field to auth config

* migrate authconfig name

Co-authored-by: furkansenharputlu <furkan_senharputlu@hotmail.com>
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1857787799)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 68aa0ef21b7b445a3dc14e57e59a64b67500acde [TT-4583]migrate authconfig name (#3890)

* Add name field to auth config

* migrate authconfig name

Co-authored-by: furkansenharputlu <furkan_senharputlu@hotmail.com>
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1857787799)

**Pull request merged**
