### PR TITLE
[DX-444]change swagger.yml version to 5.1.0

### PR DESCRIPTION
**Pull request by Keithwachira**
## Description
- Since we have released 5.1 we should update the swagger version from 5.0.0 to version 5.1.0.This will help us to update the postman collection.

## Related Issue
https://tyktech.atlassian.net/browse/DX-444

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5224/merge
Commit:  
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5374973332)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5224/merge
Commit: 77b441430f88e87340bbecfedf9a4315b70a8663 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5507192219)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5224/merge
Commit: 7101e0b47c18aa7c25bf740acb0cbd665ea5fdad 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5507658300)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5224/merge
Commit: 930a77a3b98a4d686a6c900b6aec90ba1c5a2266 
Triggered by: pull_request (@Keithwachira)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5507746635)

**Review by titpetric — APPROVED** [review]

**Pull request merged**
