### PR TITLE
[TT-9914] Fork mux 1.8.0, optimize with /regex package, optimize allocations

### PR DESCRIPTION
**Pull request by titpetric**
Before (gorilla/mux 1.8.0):

```
# go test -bench=. -benchmem -memprofile memprofile.out -cpuprofile profile.out -count 10
goos: linux
goarch: amd64
pkg: mux_test
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
BenchmarkNewRouter-8   	   52203	     22857 ns/op	   26326 B/op	     374 allocs/op
BenchmarkNewRouter-8   	   55244	     23864 ns/op	   26326 B/op	     374 allocs/op
BenchmarkNewRouter-8   	   55234	     24674 ns/op	   26326 B/op	     374 allocs/op
BenchmarkNewRouter-8   	   50599	     23557 ns/op	   26326 B/op	     374 allocs/op
BenchmarkNewRouter-8   	   48368	     23387 ns/op	   26326 B/op	     374 allocs/op
BenchmarkNewRouter-8   	   54537	     24206 ns/op	   26327 B/op	     374 allocs/op
BenchmarkNewRouter-8   	   53637	     24013 ns/op	   26327 B/op	     374 allocs/op
BenchmarkNewRouter-8   	   44949	     23069 ns/op	   26327 B/op	     374 allocs/op
BenchmarkNewRouter-8   	   53227	     24415 ns/op	   26327 B/op	     374 allocs/op
BenchmarkNewRouter-8   	   48715	     23561 ns/op	   26327 B/op	     374 allocs/op

(pprof) top
Showing nodes accounting for 14126.33MB, 89.55% of 15774.15MB total
Dropped 47 nodes (cum <= 78.87MB)
Showing top 10 nodes out of 46
      flat  flat%   sum%        cum   cum%
 4861.56MB 30.82% 30.82%  4861.56MB 30.82%  regexp/syntax.(*compiler).inst (inline)
 2828.89MB 17.93% 48.75%  2828.89MB 17.93%  regexp.onePassCopy
 2431.26MB 15.41% 64.17%  2431.26MB 15.41%  regexp/syntax.(*parser).newRegexp (inline)
 1096.36MB  6.95% 71.12%  2483.41MB 15.74%  regexp.makeOnePass
  705.04MB  4.47% 75.59%   705.04MB  4.47%  regexp.newQueue (inline)
  588.09MB  3.73% 79.31% 14490.29MB 91.86%  regexp.compile
  507.01MB  3.21% 82.53%   682.01MB  4.32%  regexp.makeOnePass.func1
  449.05MB  2.85% 85.38%  3459.33MB 21.93%  regexp/syntax.parse
  349.52MB  2.22% 87.59% 15359.84MB 97.37%  github.com/gorilla/mux.newRouteRegexp
  309.54MB  1.96% 89.55%   309.54MB  1.96%  github.com/gorilla/mux.(*Router).NewRoute
```

After (internal/mux + regexp + optimizations for allocations):

```
# go test -bench=. -benchmem -memprofile memprofile.out -cpuprofile profile.out -count 10
goos: linux
goarch: amd64
pkg: github.com/TykTechnologies/tyk/internal/mux
cpu: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
BenchmarkNewRouter-8   	  514605	      2526 ns/op	    1544 B/op	      49 allocs/op
BenchmarkNewRouter-8   	  464392	      2577 ns/op	    1544 B/op	      49 allocs/op
BenchmarkNewRouter-8   	  506593	      2549 ns/op	    1544 B/op	      49 allocs/op
BenchmarkNewRouter-8   	  505387	      2561 ns/op	    1544 B/op	      49 allocs/op
BenchmarkNewRouter-8   	  515288	      2568 ns/op	    1544 B/op	      49 allocs/op
BenchmarkNewRouter-8   	  508510	      2467 ns/op	    1544 B/op	      49 allocs/op
BenchmarkNewRouter-8   	  516144	      2632 ns/op	    1544 B/op	      49 allocs/op
BenchmarkNewRouter-8   	  421120	      2726 ns/op	    1544 B/op	      49 allocs/op
BenchmarkNewRouter-8   	  501598	      2530 ns/op	    1544 B/op	      49 allocs/op
BenchmarkNewRouter-8   	  459364	      2688 ns/op	    1544 B/op	      49 allocs/op

(pprof) top
Showing nodes accounting for 7078.59MB, 94.77% of 7469.56MB total
Dropped 16 nodes (cum <= 37.35MB)
Showing top 10 nodes out of 24
      flat  flat%   sum%        cum   cum%
 2578.86MB 34.52% 34.52%  2578.86MB 34.52%  github.com/TykTechnologies/tyk/internal/mux.(*Router).NewRoute (inline)
 2135.18MB 28.59% 63.11%  4111.22MB 55.04%  github.com/TykTechnologies/tyk/internal/mux.newRouteRegexp
  686.52MB  9.19% 72.30%   686.52MB  9.19%  strings.(*Builder).Write (inline)
  474.51MB  6.35% 78.65%   474.51MB  6.35%  github.com/TykTechnologies/tyk/regexp.(*regexpCache).do
  247.50MB  3.31% 81.97%   247.50MB  3.31%  github.com/TykTechnologies/tyk/internal/mux.braceIndices
  246.01MB  3.29% 85.26%   246.01MB  3.29%  github.com/TykTechnologies/tyk/internal/mux.NewRouter (inline)
  226.50MB  3.03% 88.29%   226.50MB  3.03%  github.com/TykTechnologies/tyk/internal/mux.(*Route).addMatcher (inline)
  183.50MB  2.46% 90.75%   183.50MB  2.46%  regexp.QuoteMeta
  152.50MB  2.04% 92.79%   152.50MB  2.04%  strings.genSplit
  147.50MB  1.97% 94.77%  7465.10MB 99.94%  github.com/TykTechnologies/tyk/internal/mux_test.BenchmarkNewRouter
```

Here's a summary of the relative changes between the before and after optimization benchmarks:

Before Optimization (gorilla/mux 1.8.0):

Average runtime: ~23470 ns/op
Average memory usage: ~26326 B/op
Average allocations: ~374 allocs/op

After Optimization (internal/mux + regexp + optimizations for allocations):

Average runtime: ~2583 ns/op (approx. 89.0% improvement)
Average memory usage: ~1544 B/op (approx. 94.1% reduction)
Average allocations: ~49 allocs/op (approx. 86.9% reduction)

The optimized version shows significant improvements across the board, with notable reductions in runtime, memory usage, and allocations. The optimized version of the code demonstrates substantial gains in efficiency compared to the previous implementation.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5462/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5954160877)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5462/merge
Commit: 3d80768039d573ba65f7c36b01d1a1c6fb7e63f5 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5954381453)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5462/merge
Commit: e677d3721fb89dc1ca110720cc1cd4536f0a119a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5954702161)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5462/merge
Commit: 46a1d355badf6157b2564897c68312d14db32211 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5956177372)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5462/merge
Commit: 46a1d355badf6157b2564897c68312d14db32211 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5956177372)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5462/merge
Commit: d2e38bde933f027dfbc8e1b0c0d48637eb8ec6a9 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5956489099)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5462/merge
Commit: b207c3c64bb0f8d0fafc4d64bd115a915f5f325f 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5967256942)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5462/merge
Commit: 29ef0a6070b5a4b540678844bf33b6e192d074ec 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6010482940)

**Comment by jeffy-mathew** [comment]
LGTM

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5462/merge
Commit: 29ef0a6070b5a4b540678844bf33b6e192d074ec 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6010482940)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5462/merge
Commit: 1a072e21b1ce22d328f722950c76391d061e691b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6013203375)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5462/merge
Commit: 1a072e21b1ce22d328f722950c76391d061e691b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6013203375)

**Pull request closed without merging**
