### PR TITLE
Update gRPC, Protocol Buffers and other dependencies

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Currently we're using the gRPC package that was released in 2016, this package had different enhancements in the past years, see [here](https://github.com/grpc/grpc-go/releases).
These aren't breaking changes and the Protocol Buffers versions is still 3.x. Have tested this with a few gRPC plugin samples we have.

Updates/adds the following dependencies as well (required by the gRPC and Protocol Buffers package)
- golang.org/x/net/context
- golang.org/x/net/http2
- golang.org/x/net/trace

### CODE REVIEW

**Comment by matiasinsaurralde** [comment]
Found this: https://grpc.io/2017/08/22/grpc-go-perf-improvements.html

**Comment by buger** [comment]
Can we benchmark this change, do we have gRPC plugin benchmark, and if don't can we add?

**Comment by matiasinsaurralde** [comment]
Sure, did some quick tests with `hey` while testing #1623 using the latest gRPC package and they looked positive. Will work on it.

**Comment by buger** [comment]
Does it mean that we updated dependencies based on their masters? I thought we going to use stable tags?

**Comment by matiasinsaurralde** [comment]
Yes, `master` is stable, we could also use the last release tag

**Comment by asoorm** [comment]
@matiasinsaurralde have you looked at: https://github.com/gogo/protobuf

**Pull request merged**
