### PR TITLE
TT-851 fix/response coprocess headers are truncated

### PR DESCRIPTION
**Pull request by sredxny**
## Description

In order to fix the issue reported in TT-851 it was necessary to modify the structure of how the headers are stored and passed to the response middlewares, it happens that one header can have multiple values (Eg: Set-Cookie header) and the gateway currently considers only one value per header.
So, this PR contains:

- Update of the protobuf files and added a new field to handle the Headers, this is a repeated value instead a string and its name is `multivalue_headers`.
- Update of the update-bindings.sh script
- Updated the bindings for go, python, ruby
- Updated the code in gateway/coprocess.go to work with headers represented as Key => []Values

Is good to mention that now the object passed to the middleware contains the old format header (one key - one value) and the new format header (the mutivalue headers: one key- multiple values). So:

- If a new header is added in the old field, then this will be added as well in the new field
- If a header is removed from the old field, then it will be removed as well in the new field
- If a value of a header is updated then it will overwritte all the values for that header in the new field.

In the end, the new field is the one being used to put all the headers back in the response, because after calling the middleware a synchronization process of headers is executed just to ensure that all the changes are replicated in the new field, therefore, all the values for every header are transmitted to the end user.

## Related Issue

https://tyktech.atlassian.net/browse/TT-851

## Motivation and Context

Give solution to https://tyktech.atlassian.net/browse/TT-851

## How This Has Been Tested

The same as reported in the ticket

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5270903786)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: f275a4f0239b69e2b379025006945c1880e8f4d3 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5271035533)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: 962245daf5937e25f20072fd4d41756967977635 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5272443673)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: 60137036ad5f297c54ab044fcb13e1acc9ea02c4 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5272483281)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: 4c7790186fefd8953c31de9c1f0b35e2f6afbfde 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5273903700)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: 85360edb4d1709d8e1188ce350028f10c094b9a5 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5273984109)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: eee08537a8ce512fdd785552df9627f4110e1f44 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5274254091)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: 75c05b64eb44edd065fd08b9380ff95f69f9e35c 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5274348992)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: 1474f19a553432efbbf7cb52b8de83ba4d210949 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5278144952)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: 471966a76d7b2abbf27a3045fc28f04239c76798 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5278196349)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: ecb2758abb0d6b9b411a12f9064d6e9187bc6292 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5281749595)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5140/merge
Commit: d53f340b6cc7f9f40a3c90da045537d9c4567a41 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5281926470)

**Comment by sredxny** [comment]
Closed in favor of https://github.com/TykTechnologies/tyk/pull/5173

**Pull request closed without merging**
