### PR TITLE
[TT-6145] Bump goverify module

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Support for PKCS#8 private keys and PKCS#1 public keys was added in [14a38508f39c859205d572dee8fde4009c50e85b](https://github.com/TykTechnologies/goverify/commit/14a38508f39c859205d572dee8fde4009c50e85b).

Signing functionality is available for gateway notifications and plugin bundles. The change doesn't break support of existing key types but instead adds new types.

## Description
This change updates the GW dependencies to use latest `goverify` changes. https://github.com/TykTechnologies/goverify/pull/1

## Related Issue
TT-6145

## Motivation and Context
Improve key support.

## How This Has Been Tested
Manually tested.

## Screenshots (if appropriate)
-

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [x] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [x] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4226/merge
Commit:  
Triggered by: pull_request (@matiasinsaurralde)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2820910381)

**Review by sredxny — APPROVED** [review]
lgtm

**Review by tbuchaillot — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4226/merge
Commit: 80f8b0a6d6044034aa8cc6fcd9f566992cc84935 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3058693813)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: bf85cba8665cbbe573bc0c6f5c9a145e1f425f3d Bump goverify module (#4226)

Co-authored-by: tbuchaillot <tombuchaillot89@gmail.com>
Triggered by: push (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3058819519)

**Pull request merged**
