### PR TITLE
Fix parsing HMACFieldValues from auth header

### LINKED ISSUE #2530: HMAC not working with murmur64
**Branch/Environment/Version**
- Branch/Version: tested on 1.7 / 1.9
- Environment: On-prem

**Describe the bug**
My HMAC api does not work when I use murmur64 key hashes. I don't have any problems with murmur32

I see this error in the gateway logs
`Header field value malformed (need two elements in field)`

```
[Sep 19 17:02:48] DEBUG Received DRL data: {MacBook-Pro-Maciej.local 01022f64-0ade-468b-462f-bcdd1efa62f0 1 0 test}
[Sep 19 17:02:48] DEBUG Active Nodes: : 1 [Token Bucket Value]: 100 [Current Load p/s]: 1 [Current Load]: 0.000000
[Sep 19 17:02:48] DEBUG Getting exp for key: analytics-tyk-system-analytics
[Sep 19 17:02:48] DEBUG Started api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo mw=RateCheckMW org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/ ts=1568905368831973000
[Sep 19 17:02:48] DEBUG Finished api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo code=200 mw=RateCheckMW ns=922425 org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/
[Sep 19 17:02:48] DEBUG Started api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo mw=OrganizationMonitor org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/ ts=1568905368832939000
[Sep 19 17:02:48] ERROR Couldn't unmarshal session object (may be cache miss): unexpected end of JSON input
[Sep 19 17:02:48] DEBUG Finished api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo code=200 mw=OrganizationMonitor ns=1419682 org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/
[Sep 19 17:02:48] DEBUG Started api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo mw=VersionCheck org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/ ts=1568905368834625000
[Sep 19 17:02:48] DEBUG Finished api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo code=200 mw=VersionCheck ns=40176 org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/
[Sep 19 17:02:48] DEBUG Started api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo mw=HMAC org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/ ts=1568905368835110000
[Sep 19 17:02:48] ERROR Field extraction failed api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo error=Header field value malformed (need two elements in field) key=****%3D" mw=HMAC org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/
[Sep 19 17:02:48]  INFO Authorization field missing or malformed api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo mw=HMAC org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/
[Sep 19 17:02:48] DEBUG pub-sub: Sending notification{gateway-log {"api_id":"b397b88d10e74b9f63cb429db664b056","api_name":"foo","error":"Header field value malformed (need two elements in field)","key":"****%3D\"","level":"error","msg":"Field extraction failed","mw":"HMAC","org_id":"5d8397349858dc10ae7606f4","origin":"127.0.0.1","path":"/foo/","time":"2019-09-19T17:02:48+02:00"}
 5d8397349858dc10ae7606f4 2019-09-19 17:02:48.835199 +0200 CEST m=+361.359477793}
[Sep 19 17:02:48] DEBUG pub-sub: Sending notification{gateway-log {"api_id":"b397b88d10e74b9f63cb429db664b056","api_name":"foo","level":"info","msg":"Authorization field missing or malformed","mw":"HMAC","org_id":"5d8397349858dc10ae7606f4","origin":"127.0.0.1","path":"/foo/","time":"2019-09-19T17:02:48+02:00"}
 5d8397349858dc10ae7606f4 2019-09-19 17:02:48.835255 +0200 CEST m=+361.359534193}
[Sep 19 17:02:48] DEBUG EVENT FIRED: AuthFailure
[Sep 19 17:02:48] DEBUG Checking: 5d8397349858dc10ae7606f4 api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo mw=HMAC org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/
[Sep 19 17:02:48] DEBUG no cached entry found, returning 7 days api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo mw=HMAC org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/
[Sep 19 17:02:48] DEBUG Finished api_id=b397b88d10e74b9f63cb429db664b056 api_name=foo code=400 error=Authorization field missing, malformed or invalid mw=HMAC ns=930148 org_id=5d8397349858dc10ae7606f4 origin=127.0.0.1 path=/foo/
```
**Reproduction steps**
check the video on how to create and test HMAC 
https://www.youtube.com/watch?v=46heAlBBMv4

1. setup gateway to use murmur64 hashing algorithm 
2. create new HMAC api
3. create new HMAC key
4. generate proper Authorization signature (check above video)
5. try to send some traffic to your api

**Actual behavior**
GW throws error `Header field value malformed (need two elements in field)`

**Expected behavior**
HMAC should work with murmur64 hashes

**Additional context**
This might be a red herring but, murmur64 uses '=' sign inside the hash. 
So my Authorization header looks like this (check KeyId):

```
Signature KeyId="eyJvcmciOiI1ZDgzOTczNDk4NThkYzEwYWU3NjA2ZjQiLCJpZCI6ImU2M2M2MTg4ZjFlYzQ2NzU4N2VlMTA1MzZkYmFjMzk0IiwiaCI6Im11cm11cjY0In0=",algorithm="hmac-sha1",signature="j27%2FQtZHmlQuWmnQT%2BxLjHcgPl8%3D"
```

Is it possible that this causes problems here? :
https://github.com/TykTechnologies/tyk/blob/a7300a6c9145ce7c90105bbb239bf22f9a4abac8/gateway/mw_hmac.go#L259

### PR DESCRIPTION
**Pull request by gernest**
This properly handles scanning key/value pairs from auth header
using text/scanner package.

Fixes #2530

### CODE REVIEW

**Comment by buger** [comment]
Is murmur64 related here at all?

**Comment by gernest** [comment]
Maybe, The thing is `KeyID="eyJvcmciOiI1ZDgzOTczNDk4NThkYzEwYWU3NjA2ZjQiLCJpZCI6ImU2M2M2MTg4ZjFlYzQ2NzU4N2VlMTA1MzZkYmFjMzk0IiwiaCI6Im11cm11cjY0In0="`

See the problem? We are splitting with `=` expecting `key="{value}"`  not considering the possibility of value containing `=` in our case we will get incorrect 2 items the last one being `"`

**Comment by buger** [comment]
Ah, makes sense now.

**Pull request merged**
