### PR TITLE
Refactor RequestValid function to not return an interface

### PR DESCRIPTION
**Pull request by craicoverflow**
## Description

This is primarily a refactoring to no longer return interface in the `RequestValid` function. This PR also reduces the number of return values in a couple of places for simplicty and readibility.
 
This also reduces the number of return values in some functions for
simplicity.

## Related Issue

This is based off of an old TODO: https://github.com/TykTechnologies/tyk/blob/bf5ddd0c3a381e97782b734033b80561d439b0d5/gateway/api_definition.go#L1312

Related issue is https://github.com/TykTechnologies/tyk/pull/776

## Motivation and Context

This removes a code smell with the current logic where an interface is being type asserted and the result is used to determine what to do next.

## How This Has Been Tested

I have set up a sample API and performed some basic requests, eg to: `http://localhost:8080/test-api/hello`. I'm looking for guidance for extra steps that can help me to fully review/test this change.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [x] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by craicoverflow** [comment]
Regarding the following:

```shell
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`
```

I noticed that the lintion action does not work, see https://github.com/TykTechnologies/tyk/issues/3599

**Comment by craicoverflow** [comment]
> All new and existing tests passed.

I struggled to run the tests locally, so gave up on it and hope that they will succeed on this PR 🙃

**Comment by craicoverflow** [comment]
Bumping this one for review.

**Review by vaske — APPROVED** [review]

**Comment by vaske** [comment]
merged manually to 4-lts

**Pull request merged**
