### PR TITLE
[TT-9987] [4-lts] Fix plugin compiler cves

### PR DESCRIPTION
**Pull request by titpetric**
https://tyktech.atlassian.net/browse/TT-9987

### CODE REVIEW

**Review by jeffy-mathew — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: 60dd100c81b4692b5350cb934f7a211af2380b54 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6389645989)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4-lts
Commit: 6102d718c5a50b2dbd3ca2cf80904a3169515902 Go mod tidy (#5579)

Fix go.mod somehow in dirty state

Co-authored-by: Tit Petric <tit@tyk.io>
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6389642272)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: 9838a446eb0500e30cb9814a7329fbeaf3c69715 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6389765422)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: 54b29af615fee3771bfcaf32a84851c529e9bcc1 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6389978957)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: f1689828409ea30089abe02796031d58ad25e24d 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6390078308)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: 85c7c507c6cc7924120bc71cca68b40fd81ba524 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6390417963)

**Comment by alephnull** [comment]
There appears to be a problem building the el7 version of the image as can be seen from the checks.

**Comment by titpetric** [comment]
> There appears to be a problem building the el7 version of the image as can be seen from the checks.

Right. Any advice there? It seems like an usual flaky CI timeout.

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4-lts
Commit: 06fcdde26b06c901ea01e31d5d0962f7403de241 [tests] Fix TestGroupResetHandler (#5583)

Update a failing test.

Co-authored-by: Tit Petric <tit@tyk.io>
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6402580878)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: f9683844252aeb8e990340ae33c580eaad1ed707 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6402583252)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: a114de04b7564c9c852a73a8e22abc0a490dbd32 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6402805288)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: 7ac61a7e1c98dbe28fbcb213fc7f0da5ddef95c9 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6403439735)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: 73cb3d95779af21301f1385f4470e94128e25e39 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6403533902)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: 117c69e27888de7ad26d909d7b20ef0657ab08b2 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6403619251)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: a043c56210d130253152fe919831e30807fe6f80 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6404712537)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5578/merge
Commit: ba4258dc9bbdb6e98d5b65f66fcb21af0d970c23 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6404735754)

**Comment by titpetric** [comment]
note: this removes CVEs from main plugin compiler image; el7 has been left alone until we figure out what to do with the EOL debian stretch distribution (frexian, etc.)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4-lts
Commit: 77a1362262ec37e0ef11989e70eac4de08164c65 [TT-9987] [4-lts] Fix plugin compiler cves (#5578)

https://tyktech.atlassian.net/browse/TT-9987

---------

Co-authored-by: Tit Petric <tit@tyk.io>
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6415399444)

**Pull request merged**
