### PR TITLE
Remove OPTIONS from the safe method check.

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
This is described in #376.

### CODE REVIEW

**Comment by buger** [comment]
👍

**Comment by mvdan** [comment]
If the commit message includes "Fixes #n", the issue will be automatically closed when the commit is merged. Unless I misunderstand and this doesn't actually fix it?

**Comment by matiasinsaurralde** [comment]
> If the commit message includes "Fixes #n", the issue will be automatically closed when the commit is merged. Unless I misunderstand and this doesn't actually fix it?

Updated

**Comment by buger** [comment]
I just realized that "OPTIONS" was not removed from dashboard UI. @matiasinsaurralde can you create an Issue in analytics repo and explain @lghiur how to find it?

**Pull request merged**
