### PR TITLE
Integrate plugin bundler

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
This is built on top of #1738, reimplements the plugin bundler as part of the new CLI code (#1492).
The syntax for this subcommand is the same and the logging has been enhanced with `logrus`.

### CODE REVIEW

**Comment by buger** [comment]
@matiasinsaurralde pls fix conflicts

**Comment by matiasinsaurralde** [comment]
Have rebased this and also added tests to cover errors and a simple Python bundle build scenario 👍

**Comment by matiasinsaurralde** [comment]
Also removed the `server` subcommand references, it will be a different PR

**Comment by matiasinsaurralde** [comment]
Finally fixed this, besides the race that was happening randomly (not related to this PR), there was an issue with the `kingpin` command test 👍

**Pull request merged**
