### PR TITLE
[TT-9310] Building Node Info on every call to getGroupLoginCallback with synchroniser enabled

### PR DESCRIPTION
**Pull request by mativm02**
## Description
We're now building the node info every time `getGroupLoginCallback` is called and syncroniser is enabled. Previous behavior was executing this function only once, so if the state of the info changed, MDCB wouldn't notice it. Now, we're calling `buildNodeInfo()` to fetch this data from Redis on each call. The same scenario was already happening when syncroniser wasn't enabled.

## Related Issue
https://tyktech.atlassian.net/browse/TT-9310?atlOrigin=eyJpIjoiM2MwZTY0OWJhZjEwNGQzMWE3NzJmNjUwZGFiM2RkOGUiLCJwIjoiaiJ9

## How This Has Been Tested
Manual test and unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5404/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5822179697)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5404/merge
Commit: c8bfbd35e6e3c75929f6ab85baf0ea066380d6e9 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5822228871)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5404/merge
Commit: bd5afa7c26b5c0bc4bff1f95885ab58fecf02a90 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5822332986)

**Review by sredxny — APPROVED** [review]
looks good! we need to test the impact of calling many times `getNodeDataFunc()` which I guess is almost null, otherwise we can think in wrap this up inside a sync.

**Review by tbuchaillot — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5404/merge
Commit: f88c1ef49e59da2582a379299ce1df981c77625d 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5829852224)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5404/merge
Commit: 7659a48396d3798621d461bf2bd5551325bfe395 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5832288572)

**Pull request merged**
