### PR TITLE
refactor: remove optimisations_use_async_session_write from configs

### PR DESCRIPTION
**Pull request by armujahid**
## Description
This option was removed in https://github.com/TykTechnologies/tyk/pull/3366 but it still exists in configs

## Related Issue
TT-580

## Motivation and Context
Mentioned in description and related issue

## How This Has Been Tested
N/A

## Screenshots (if appropriate)
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by armujahid** [comment]
Is there anything I can do to get this merged?

**Comment by buger** [comment]
Sorry for the delay! And thank you for contribution. Looks good!

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 602cca34f7b7d3265c60ecf5ed749664e3b48621 refactor: remove optimisations_use_async_session_write from configs (#4368)

This option was removed in https://github.com/TykTechnologies/tyk/pull/3366 but it still exists in configs
Triggered by: push (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3543037591)

**Pull request merged**
