### PR TITLE
when adding a new certificate check if exists by using the Exist method and not Get

### PR DESCRIPTION
**Pull request by sredxny**
## Description
In MDCB env when a new certificate is synchronized, we need to use the Exists function to check if its already in the database rather than use the Get function as it would lead us to an infinite loop in and MDCB cert storage.

## Related Issue
https://tyktech.atlassian.net/browse/TT-4980

## Motivation and Context
Let certificates be in sync with management layer

## How This Has Been Tested
- Ran full flow:
- Execute MDCB env
- Create cert via dasboard
- Cert is synchronized

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4003/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2154152328)

**Review by matiasinsaurralde — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4003/merge
Commit: 004024bcfe3386fa27f02bce2c25b2a89d6d2965 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2182927878)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4
Commit: a770fae709738ce3e79a1c6a555884accdd9142b fix race condition in Test_loadOASSchema (#3980)


[changelog]
fixed: race condition in loadOASSchema.

(cherry picked from commit d6b0486fccf206b63e01e0fca4e72c4498d0b681)
Triggered by: push (@tykbot[bot])
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2183525476)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4003/merge
Commit: 8097b76d232d60cfd11660eec74eb75d3e459b52 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2183540677)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4
Commit: c78468d3259d189ccbcca557e50489b016954aad when adding a new certificate check if exists by using the Exist method and not Get (#4003)

* when adding a new certificate check if exists by using the Exist method and not Get

* gofmt & goimports

Co-authored-by: Jeff <jeffy.mathew100@gmail.com>
Triggered by: push (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2183602100)

**Pull request merged**
