### PR TITLE
[TT-1213] JSVM: trigger middleware error when JSVM isn't enabled

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
## Description
When Tyk tries to execute JS middleware and JSVM is disabled on the gateway (`enable_jsvm` set to `false`), a panic occurs. This PR ensures the error is present in the logs.

I've tried to come up with a test for this one but seems [all JSVM tests don't follow `processSpec` flow at all](https://github.com/TykTechnologies/tyk/blob/master/gateway/mw_js_plugin_test.go#L110). We manually inject JSVM into the spec of test APIs. I think that a separate ticket could be created for improving JSVM tests with a logic that resembles the API loader one.

At the same time I believe a middleware logic is safest than just allow the MW to pass, in rich plugins [we do the same](https://github.com/TykTechnologies/tyk/blob/master/gateway/coprocess.go#L362).

## Related Issue
TT-1213

## Motivation and Context
Improve JSVM usage.

## How This Has Been Tested
- Setup an API with JS middleware.
- Start Tyk with `enable_jsvm` set to `false`.
- Send a request to the API.

## Screenshots (if appropriate)
-

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4206/merge
Commit:  
Triggered by: pull_request (@matiasinsaurralde)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2737180712)

**Review by sredxny — APPROVED** [review]
lgtm

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4206/merge
Commit: 902267bd5fa41ce6b0e1ccd1f1a49e86c0b2885c 
Triggered by: pull_request (@matiasinsaurralde)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2747526150)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 689b274739103943314b91298a00b630dbf66bc1 mw_js_plugin: trigger middleware error when JSVM isn't enabled (#4206)
Triggered by: push (@matiasinsaurralde)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2747656565)

**Pull request merged**
