### PR TITLE
[TT-5307] update jaeger-client-go

### PR DESCRIPTION
**Pull request by jeffy-mathew**
[changelog]
internal: update jaeger-client-go

## Description
this unblocks go mod update in tyk analytics

```
go: github.com/TykTechnologies/tyk-analytics/dashboard imports
	github.com/TykTechnologies/tyk/config imports
	github.com/uber/jaeger-client-go/config imports
	github.com/uber/jaeger-client-go/internal/baggage/remote tested by
	github.com/uber/jaeger-client-go/internal/baggage/remote.test imports
	github.com/uber-go/atomic: github.com/uber-go/atomic@v1.9.0: parsing go.mod:
	module declares its path as: go.uber.org/atomic
	        but was required as: github.com/uber-go/atomic
```

fix released in https://github.com/jaegertracing/jaeger-client-go/pull/464#issuecomment-550596918

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4049/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2317949841)

**Review by titpetric — APPROVED** [review]

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4049/merge
Commit: 0bab330fbecd84aff62422168c99509ab00bde6e 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2319564854)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: e7d134e2c79342a51efc7d61cf00436be1d73971 [TT-5307] update jaeger-client-go (#4049)

* update jaeger-client-go to next minor

[changelog]
internal: update jaeger-client-go to next minor
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2320041315)

**Pull request merged**
