### PR TITLE
add detailed smoke test for plugin bundling

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description
This PR intends to add smoke tests for plugin bundle flow.

### CODE REVIEW

**Review by alephnull — APPROVED** [review]
Thanks for this, it should help a lot.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3841/merge
Commit: f292f7a45344867810b3b9414dfd0d6e29cd0a10 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1772922769)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3841/merge
Commit: a520e0cb3435aedbc9b2e09ef37a481a2d16619d 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1773599313)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3841/merge
Commit: bb7449045889a66c1e67a16e8faf9fd2c5f85b91 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1773651312)

**Comment by jeffy-mathew** [comment]
closing since no traction

**Pull request closed without merging**
