### PR TITLE
[TT-8265] Drop satori go.uuid package

### PR DESCRIPTION
**Pull request by titpetric**
## Description

This PR removes satori/go.uuid in favor of gofrs/uuid.

## Related Issue

https://tyktech.atlassian.net/browse/TT-8265

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [x] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4849/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4384066303)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4849/merge
Commit: 7a96b4bdffe2978ad75403e3dd4440cdc3dc7964 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4384191252)

**Review by jeffy-mathew — APPROVED** [review]

**Review by buger — APPROVED** [review]

**Pull request merged**
