### PR TITLE
[TT-7387] Delete API version atomically in OSS

### PR DESCRIPTION
**Pull request by furkansenharputlu**
https://tyktech.atlassian.net/browse/TT-7387

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4586/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3788505785)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4586/merge
Commit: 29fb8e2f200de2e4770e089d4913f11cbaa3955f 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3789231644)

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: bdfa216478a0a322235b50a11e8c42591ff66e9d [TT-7387] Delete API version atomically in OSS (#4586)

https://tyktech.atlassian.net/browse/TT-7387
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3793028196)

**Pull request merged**
