### PR TITLE
[TT-9534] Gw span attributes to resources attributes

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

This PR moves the Gateway related attributes from Span Attributes to Resources attributes since they are related to the system configuration and no to the request.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5383/merge
Commit:  
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5749437235)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5383/merge
Commit: 5b1022a145311f35068872e3aa2136b29ec3c7d6 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5760477901)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5383/merge
Commit: 77c0ac8f6aeb1cc92a1d820e42663dadc5a58a2f 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5760470987)

**Review by mativm02 — APPROVED** [review]
lgtm!

**Pull request merged**
