### PR TITLE
[TT-7323] remove unused map.

### PR DESCRIPTION
**Pull request by jeffy-mathew**
[changelog]
internal: remove unused map.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4556/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3729965171)

**Review by titpetric — APPROVED** [review]

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4556/merge
Commit: bf489b31650331d909d710fe83cfebd3cea8a9ee 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3730901730)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: ff74cc32e76e64aa324933885c007643397d8685 [TT-7323] remove unused map. (#4556)

[changelog]
internal: remove unused map.
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3730987839)

**Pull request merged**
