### PR TITLE
[DX-1084] Add documentation to protobuf source code files for review

### PR DESCRIPTION
**Pull request by dcs3spp**
[DX-1084](https://tyktech.atlassian.net/browse/DX-1084)

## Description

- Added documentation for protobuf messages and service for review
- Task file has been updated to use a Python virtual environment.
- The PR includes the bindings regenerated
- The PR is large and has 22 files that includes the comments in the regenerated bindings. If required I can include just the protobuf files and then once reviewed include a separate PR for the bindings?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

[DX-1084]: https://tyktech.atlassian.net/browse/DX-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by titpetric** [comment]
@dcs3spp CI is failing on this, also a lot to review. Can you follow godoc style comments in proto files, as discussed previously?

**Comment by dcs3spp** [comment]
@titpetric I have updated comment style and fixed previous CI linting error. There is an error relating to [Sonar Cloud](https://github.com/TykTechnologies/tyk/pull/6251#issuecomment-2129177422)?

**Review by titpetric — APPROVED** [review]
This PR comes with a few CI updates to verify the changes.

- CI: run `task lint`
- /Taskfile.yml - implement `task lint` and extend with tests
- coprocess/Taskfile.yml - implement `task lint` to pass against the coprocess pkg

The change covers godoc verification under /coprocess, verifying the change.

@dcs3spp thank you simon for a LOT of work and patience.

**Comment by titpetric** [comment]
Ok, I'll be copying the changes to release-5.3. This is done because it being a common documentation requirement (updating LTS docs). This PR doesn't represent a functional change, so we can still apply it. I'll link this PR from there.

**Pull request merged**
