### PR TITLE
[TT-6743] Add the skeleton for external OAuth middleware

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR adds the skeleton for the external OAuth middleware. The functionalities are:
- jwt validation
- introspection
- creating a virtual session for the validated access tokens and setting to context.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4344/merge
Commit: 18c6e767f1f2b24e2004722766ae1ab46284ac40 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3235299015)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4344/merge
Commit: b433079a4ebb8e8bf9b0b061d87135d712352380 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3235291888)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4344/merge
Commit: d67e32ce7483ab6e840a8c1185636e13917fffcb 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3235335879)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4344/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3235271184)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4344/merge
Commit: af96bc6a336b66e42edcaa13e0bbc25868087e36 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3235730437)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4344/merge
Commit: 29c9a4196e9e2e26c01725853c1c783e439e3469 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3235745419)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4344/merge
Commit: ba96e3b384a287d55aeec5ab97686f946f717453 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3240550159)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4344/merge
Commit: 70de6ccc60c4da8dfcad1c670c6bb7e3160b896f 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3240801790)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 2bc6c2eb0b616901722e161dbe71d1e5608e2a7b Add the skeleton for external OAuth middleware (#4344)
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3240883987)

**Pull request merged**
