### PR TITLE
Upgrade to go-jwt 3

### PR DESCRIPTION
**Pull request by sje397**
Implement the fix recommended in the migration guide for breaking changes in go-jwt version 3.

### CODE REVIEW

**Comment by lonelycode** [comment]
We've already done all this in our develop branch :-(

**Comment by sje397** [comment]
No problem - it was small...and tests fail. But atm if you just checkout and build master, it fails.

**Comment by lonelycode** [comment]
Yeah, we recently did a small patch and found the same - the OpenID middleware is also broken, so our fork needed updating.

Develop will be merged to master very soon so it should all be stable then. 

For hot fixes have been temporarily vendoring older versions

**Comment by lonelycode** [comment]
Thank you though! Really do appreciate it, nothing worse than upstream library changes breaking your code! M.

**Comment by sje397** [comment]
No worries at all. Thanks for building Tyk! :)

**Pull request closed without merging**
