### PR TITLE
[TT-4363] Port changes for build matrix for el7, and non-el7 builds to master.

### PR DESCRIPTION
**Pull request by asutosh**
## Description
Port the changes already made as part of #3855 to the `master` branch.

## Related Issue
[TT-4363]

## Motivation and Context
el/7, xenial and other distros use an older version of glibc, to support these, we'll need separate build jobs.
This PR adds support in the release pipeline for enabling this.

## How This Has Been Tested
Tested as part of the release pipeline as part of #3855 , also tested locally. 

[TT-4363]: https://tyktech.atlassian.net/browse/TT-4363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3881/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1812266845)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3881/merge
Commit: 156d19d5659a19a7fd05534577fb53220c637a6b 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1812281535)

**Review by alephnull — APPROVED** [review]
LGTM.

**Review by buger — APPROVED** [review]

**Comment by buger** [comment]
I'm not get used to have it so green 🤩

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 401670a563f026f28b53ed88f7d0cf1ccbeeba92 [TT-4363] Port changes for build matrix for el7, and non-el7 builds to master. (#3881)

* Sync from templates- el7 changes

* Added the api functionality smoketest

- Also update other smoke-tests.
- Fixes for existing tests
- Fixes for plugin-compiler build Dockerfile.

Co-authored-by: Leonid Bugaev <leonsbox@gmail.com>
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1816426341)

**Pull request merged**
