### PR TITLE
[TT-10908] Update graphql-go-tools

### PR DESCRIPTION
**Pull request by buraksezer**
See https://github.com/TykTechnologies/graphql-go-tools/pull/415 for details.

### CODE REVIEW

**Review by pvormste — APPROVED** [review]

**Review by kofoworola — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5955/merge
Commit: 766ed1bd362d4fbbcf51f9c02b1013aa167efc23 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7583784074)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5955/merge
Commit: 766ed1bd362d4fbbcf51f9c02b1013aa167efc23 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7583784074)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: e7f0f9ab403969e3bf0627359a82e14b3dc3f9e8 [TT-10908] Update graphql-go-tools (#5955)

See https://github.com/TykTechnologies/graphql-go-tools/pull/415 for
details.
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7584029476)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: e7f0f9ab403969e3bf0627359a82e14b3dc3f9e8 [TT-10908] Update graphql-go-tools (#5955)

See https://github.com/TykTechnologies/graphql-go-tools/pull/415 for
details.
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7584029476)

**Pull request merged**
