### PR TITLE
Add conditions as to when to run the Release CI

### PR DESCRIPTION
**Pull request by titpetric**
- do not run on pull requests
- enable manual run on pull requests
- force run on paths changed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4701/merge
Commit: 50fa03faa0aebb7e700d13f6d646501312489884 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4009245149)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4701/merge
Commit: 7a9c998c328d82b1c9e63110680c130be5b170c3 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4009296868)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4701/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4009177669)

**Review by jeffy-mathew — APPROVED** [review]

**Review by alephnull — CHANGES_REQUESTED** [review]
We depend on the release workflow to make sure that,
- no one breaks the build unknowingly
- auto-merged code does not break the build
This PR breaks both.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4701/merge
Commit: 913de7a172347d8e752e9b5f11e067072c96910b 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4016886169)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4701/merge
Commit: 184921b3b34bee25727112e9a4a9c7a6c0a7ac33 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4016893884)

**Review by ermirizio — APPROVED** [review]
looks good for me

**Review by alephnull — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4701/merge
Commit: dbd14f286434e96993aa88e0b71761468fe76c62 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4045085776)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4701/merge
Commit: 8ec86ea5b39cfeb57e9f04270ed8cc5784b92112 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4045918728)

**Comment by buger** [comment]
@alephnull @ermirizio pls update Gromit. Can me done for all the repos we have.

**Pull request merged**
