### PR TITLE
[TD-1044]: Update sync automation

### PR DESCRIPTION
**Pull request by asutosh**
Add Sync automation for tyk

:robot: Beep, boop, this PR has been generated by [automation](https://github.com/TykTechnologies/gromit/blob/master/cmd/policy.go) on Wed Aug 31 11:49:22 UTC 2022
because commits on `master` need to be propagated to the branches `[release-4 release-3.2.3]`
as per the current repository policy.

## Policy for tyk
Commits affecting these files will be ported as listed below.

### Ports
| Source branch | Destination branches |
|---------------|----------------------|
master |  [release-4 release-3.2.3] |

Thank you for reading this far. Since this PR is generated by automation, if there
are inconsistencies in the information provided above, they are bugs and merging
this PR will probably do some damage. Please log a jira in the TD project citing this PR.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4276/merge
Commit:  
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2963622700)

**Comment by alephnull** [comment]
> Policy for tyk
> Commamits

**Review by ermirizio — APPROVED** [review]
looks good

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4276/merge
Commit: 93b72b2a933edb28f6e46f2b3213000a31d65f6a 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2965751474)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4276/merge
Commit: 1a49581fd6b3f4121c937655e1efb4b50500aa3b 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2965774692)

**Review by alephnull — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 324533ea77f9b42a5b207214e1f334d36ef8c017 [TD-1044]: Update sync automation (#4276)

Generated by gromit policy.
Co-authored-by: Gromit <policy@gromit>
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2969284325)

**Pull request merged**
