### PR TITLE
Release 4.0.16 update

### PR DESCRIPTION
**Pull request by lghiur**

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5962/merge
Commit: d0c9a0805478041ddc1562afe88fc3c64d402ddd 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621606660)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.16-update
Commit: d0c9a0805478041ddc1562afe88fc3c64d402ddd OIDC based AWS login

Removed bitrot
Triggered by: push (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621606377)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.16-update
Commit: 7d6431779a7c24550dea9629f71028da7a254d8e test upgrades every time
Triggered by: push (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621653372)

**Review by alephnull — COMMENTED** [review]
There was a problem pushing to CI which was non-critical but I've fixed anyway so that ECR has updated images. I can only confirm the releng code and the other code is best reviewed by someone who knows what is going on.

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5962/merge
Commit: ed353c234af412c8d5ff366becc3ee0369860ad8 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621715171)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.16-update
Commit: ed353c234af412c8d5ff366becc3ee0369860ad8 Merging to release-4-lts: Merging to release-4.3.8: [TT-9964] Prevent new idle connections to be generated. (#5526)

Merging to release-4.3.8: [TT-9964] Prevent new idle connections to be generated. (#5526)

[TT-9964] Prevent new idle connections to be generated. (#5526)
Triggered by: push (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621714933)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5962/merge
Commit: 63faf3c1688b4b3816f3ae025f6782cf7714b4b8 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621801759)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5962/merge
Commit: ddb27bf89d9e6f7221562fbe3e16aafacf92cd7a 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621934761)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.16-update
Commit: 63faf3c1688b4b3816f3ae025f6782cf7714b4b8 vbump
Triggered by: push (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621801586)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.16-update
Commit: ddb27bf89d9e6f7221562fbe3e16aafacf92cd7a vbump
Triggered by: push (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621934629)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5962/merge
Commit: ddb27bf89d9e6f7221562fbe3e16aafacf92cd7a 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621934761)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.16-update
Commit: ddb27bf89d9e6f7221562fbe3e16aafacf92cd7a vbump
Triggered by: push (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7621934629)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5962/merge
Commit: f2488a40d5efff91d55ab3724f178967b780d4a0 
Triggered by: pull_request (@ilijabojanovic)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7624253547)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.16-update
Commit: f2488a40d5efff91d55ab3724f178967b780d4a0 Update api-tests.yml
Triggered by: push (@ilijabojanovic)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7624252965)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4-lts
Commit: 5a9989e8da9695290954f555c67a35ffdd9a0656 Release 4.0.16 update (#5962)

Co-authored-by: Leonid Bugaev <leonsbox@gmail.com>
Co-authored-by: Tit Petric <tit@tyk.io>
Co-authored-by: maciej <39672152+maciejwojciechowski@users.noreply.github.com>
Co-authored-by: Tit Petric <tit.petric@monotek.net>
Co-authored-by: Ilija Bojanovic <ilijabojanovic@gmail.com>
Co-authored-by: Sredny M <sredny.buitrago@gmail.com>
Co-authored-by: Matias <83959431+mativm02@users.noreply.github.com>
Co-authored-by: Tyk-ITS Account <92926870+Tyk-ITS@users.noreply.github.com>
Co-authored-by: Zaid Albirawi <zaid@tyk.io>
Co-authored-by: Jeffy Mathew <jeffy.mathew100@gmail.com>
Co-authored-by: Tomas Buchaillot <tombuchaillot89@gmail.com>
Co-authored-by: Alok G Singh <alephnull@hcoop.net>
Co-authored-by: Alok G Singh <alok@tyk.io>
Triggered by: push (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7628732096)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4.0.16
Commit: 5a9989e8da9695290954f555c67a35ffdd9a0656 Release 4.0.16 update (#5962)

Co-authored-by: Leonid Bugaev <leonsbox@gmail.com>
Co-authored-by: Tit Petric <tit@tyk.io>
Co-authored-by: maciej <39672152+maciejwojciechowski@users.noreply.github.com>
Co-authored-by: Tit Petric <tit.petric@monotek.net>
Co-authored-by: Ilija Bojanovic <ilijabojanovic@gmail.com>
Co-authored-by: Sredny M <sredny.buitrago@gmail.com>
Co-authored-by: Matias <83959431+mativm02@users.noreply.github.com>
Co-authored-by: Tyk-ITS Account <92926870+Tyk-ITS@users.noreply.github.com>
Co-authored-by: Zaid Albirawi <zaid@tyk.io>
Co-authored-by: Jeffy Mathew <jeffy.mathew100@gmail.com>
Co-authored-by: Tomas Buchaillot <tombuchaillot89@gmail.com>
Co-authored-by: Alok G Singh <alephnull@hcoop.net>
Co-authored-by: Alok G Singh <alok@tyk.io>
Triggered by: push (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7629680801)

**Pull request merged**
