### PR TITLE
[TT-11071] Update graphql-go-tools

### PR DESCRIPTION
**Pull request by buraksezer**
This PR updates graphql-go-tools. See https://github.com/TykTechnologies/graphql-go-tools/pull/416 for details.

### CODE REVIEW

**Review by pvormste — APPROVED** [review]

**Review by rhianeKobar — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5970/merge
Commit:  
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7654657749)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5970/merge
Commit:  
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7654657749)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: ea45b59a8a59dcfe8b18f9ee4f865e816e1a2234 [TT-11071] Update graphql-go-tools (#5970)
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7654953017)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: ea45b59a8a59dcfe8b18f9ee4f865e816e1a2234 [TT-11071] Update graphql-go-tools (#5970)
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7654953017)

**Pull request merged**
