### PR TITLE
Add new config flag to enable distributed tracing

### PR DESCRIPTION
**Pull request by titpetric**
Adds `enable_distributed_tracing` (boolean) under the new relic configuration, update usage.

https://tyktech.atlassian.net/browse/TT-4209

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4902/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4510227762)

**Review by jeffy-mathew — APPROVED** [review]

**Review by tbuchaillot — APPROVED** [review]
LGTM

**Pull request merged**
