### PR TITLE
[TT-9105] Fix release build and plugins

### PR DESCRIPTION
**Pull request by titpetric**
## Description

In order to provide better plugin/gateway compatibility, this PR adds:

- `-trimpath` on both sides of the build (gateway, plugin)
- Taskfile.yml with some local test targets (`task test:goreleaser`, `task test:plugin-compiler`)
- Generate `extra_files` in goreleaser from `test:goreleaser`
- inject git tag into plugin compiler from CI pipeline to build `plugin_<version>...`
- Updated plugin compiler to use go workspaces internally.

## Related Issue

https://tyktech.atlassian.net/browse/TT-9105

## How This Has Been Tested

without `-trimpath`

```
# strings tyk | grep gateway/server.go
/opt/tyk-gateway/gateway/server.go
```

with `-trimpath`

```
# strings tyk | grep gateway/server.go
github.com/TykTechnologies/tyk/gateway/server.go
```

Verified on v5.1.0-alpha19+.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5115/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5196712001)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5115/merge
Commit: ccf70f864c464e329b63d688edf965035d120f2b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5196719033)

**Comment by titpetric** [comment]
@alephnull no because smoke tests are broken, see https://github.com/TykTechnologies/tyk/pull/5106.

QA verified gw/plugin compiler by hand.

**Comment by alephnull** [comment]
Is there an alternate automated test of the plugin compiler?

And will you be adding the implementation generating the extra files list in gromit?

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5115/merge
Commit: 7658965fd4e1cefade08fd9fdb9cc86d7188a824 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5196820767)

**Review by furkansenharputlu — APPROVED** [review]

**Comment by titpetric** [comment]
@alephnull `task test:plugin-compiler` is one and a test case has also been added to tyk-build-integration-tests in addition to QA manual test and some verification of outputs as described. The linked PR fixes smoke tests, but has TT-9111 to address to make them pass.

If you file up a ticket, I'm sure we can refine it and pull it into a future sprint. Gromit is a bit outside of our area at the moment. cc @andyo-tyk

**Pull request merged**
