### PR TITLE
[TT-10184] Support "detailed_tracing" in API def for GQL APIs

### PR DESCRIPTION
**Pull request by buraksezer**
PR for [TT-10184](https://tyktech.atlassian.net/browse/TT-10184)

I chose an interface-based design to implement the requested feature. In this way, a minimum amount of intervention was required for the existing implementation.

`GraphqlMiddleware Validation` span is also considered as a part of "detailed tracing". So that span has been disabled if `detailed_tracing` is set to `false`. 

`TykOtelExecutorI` interface has been added to define Tyk/UDG-specific methods.

If `detailed_tracing` is set to `false`:

Screenshot 2023-11-06 at 13 51 39

If `detailed_tracing` is set to `true`:

Screenshot 2023-11-06 at 13 45 20

[TT-10184]: https://tyktech.atlassian.net/browse/TT-10184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5740/merge
Commit: f42c52aadc1155e63a9aa2d9993e023c26987f28 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6769957409)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5740/merge
Commit: 0104edd74b42684a4025064c755403a84a97daa5 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6770244604)

**Review by kofoworola — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5740/merge
Commit: 742c22d9995dde3c2a4553775f71c8894bbec1ba 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6785989601)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5740/merge
Commit: 13c5729dab2ef6b3bd7aec427586c7f332f3098a 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6795702430)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5740/merge
Commit: a05317e4a57be8cf91c1937b74372f5d665e7e8b 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6796075330)

**Review by pvormste — APPROVED** [review]

**Pull request merged**
