### PR TITLE
Revert "[TT-13422] Do not allow empty string in upstream auth configuration strings"

### PR DESCRIPTION
**Pull request by jeffy-mathew**
Reverts TykTechnologies/tyk#6699
temporary revert with common change for AuthSource

### CODE REVIEW

**Comment by buger** [comment]
<p>:broken_heart: The detected issue is not in one of the allowed statuses :broken_heart: </p>    
   <table>
     <tr>
        <th>Detected Status</th>
        <td>DoD Check</td>
        <td>:x:</td>
     </tr>
     <tr>
        <th>Allowed Statuses</th>
        <td>In Dev,In Code Review,Ready for Testing,In Test,In Progress,In Review</td>
        <td>:heavy_check_mark:</td>
      </tr>
   </table>
   <p>Please ensure your jira story is in one of the allowed statuses</p>

**Review by lghiur — APPROVED** [review]

**Comment by buger** [comment]
<p>:broken_heart: The detected issue is not in one of the allowed statuses :broken_heart: </p>    
   <table>
     <tr>
        <th>Detected Status</th>
        <td>DoD Check</td>
        <td>:x:</td>
     </tr>
     <tr>
        <th>Allowed Statuses</th>
        <td>In Dev,In Code Review,Ready for Testing,In Test,In Progress,In Review</td>
        <td>:heavy_check_mark:</td>
      </tr>
   </table>
   <p>Please ensure your jira story is in one of the allowed statuses</p>

**Pull request merged**
