### PR TITLE
[TT-7958] Rename Tyk native to Tyk classic

### PR DESCRIPTION
**Pull request by jeffy-mathew**
Team agreed upon naming Tyk API definition to be Tyk Classic API definition.
Renaming for consistency.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4676/merge
Commit: ef4039848f4dfefe4447c33bee73334a32c9c965 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3986361757)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4676/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3986355840)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4676/merge
Commit: 1da589ba5eed8800770bc6ce7eafb2fe804d5137 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4111908036)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4676/merge
Commit: 1da589ba5eed8800770bc6ce7eafb2fe804d5137 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4111908036)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4676/merge
Commit: fe15cab6496a5e3399ab8eff5278382016bcc670 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4132673902)

**Review by lghiur — APPROVED** [review]

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4676/merge
Commit: 7639c5e7021921e8e2a4d234226379caa828f519 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4134313661)

**Pull request merged**
