### PR TITLE
Bugfix/fix custom auth

### LINKED ISSUE #2543: I shouldn't need to set "token" metadata when using ID extractor in Custom Auth
**Branch/Environment/Version**
All - when I am using custom authentication plugin and returning a session to Tyk, Tyk gateway will throw an error if the session doesn't include metadata with a "token" and ANY value.  

**Describe the bug**
If I'm using ID extractor, I don't need to set "token".  "token" only needs to be set if I am NOT using ID Extractor.

```javascript
object.Session = &coprocess.SessionState{

		LastUpdated:         time.Now().String(),
		Rate:                5,
		Per:                 10,
		QuotaMax:            int64(0),
		QuotaRenews:         time.Now().Unix(),
		IdExtractorDeadline: extractorDeadline,
		Metadata: map[string]string{
			"jwt":   jot,
			"Hello": "world",
		},
		ApplyPolicies: policiesToApply,
	}
```

This throws an error by Tyk because we didn't set `token`

### PR DESCRIPTION
**Pull request by sedkis**
fix #2543

### CODE REVIEW

**Comment by sedkis** [comment]
Which branch does this need to get merged into?

**Comment by buger** [comment]
Everything should be merged to master first

**Comment by sedkis** [comment]
aha. ok i will rebase

**Comment by sedkis** [comment]
done, @buger

**Comment by buger** [comment]
Do you want to try to modify existing tests to confirm this fix?

**Pull request closed without merging**
