### PR TITLE
[TT-7711] Drop empty gatewayTags in migration

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Review by jeffy-mathew — APPROVED** [review]

**Review by Yasintrm — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4695/merge
Commit: 7605e3e72704c31478872b8427ccf76eaa358f9d 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3999702045)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4695/merge
Commit: 2f3bc54c8ca43126f796c2d1e6b99b3ea44781c9 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3999764840)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4695/merge
Commit: f3ff2b92e6058dbae353a8f907765747edd328ed 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3999831322)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4695/merge
Commit: 2f3bc54c8ca43126f796c2d1e6b99b3ea44781c9 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3999838144)

**Pull request merged**
