### PR TITLE
[TT-7737] Fix multiple version migration

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Review by Yasintrm — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4707/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4025505228)

**Review by maciejwojciechowski — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4707/merge
Commit: ac7bbadeaee8aa0bd441ab9fd49043f7973ca4dc 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4025919049)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4707/merge
Commit: 1fe65c741b40cfe416677f1f909de2cf1e36bec4 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4025968953)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4707/merge
Commit: 83d5377d01f81217e2caf8091e706d80bd868e0e 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4025978484)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4707/merge
Commit: 432629f1ef17a41e5e6eaac516f58cb0b660a78f 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4025995398)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4707/merge
Commit: db70bf7036b33ec813889bdc46013cf8a97c4717 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4026084963)

**Pull request merged**
