### PR TITLE
[TT-11126] fix internal endpoint middleware not working in conjunction with other middleware enabled

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description

internal endpoint middleware doesn't work when other middlewares are enabled on the same endpoint. 
This PR fixes it. 

## Related Issue
https://tyktech.atlassian.net/browse/TT-11126

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6037/merge
Commit: 4b852445211f1436ab8c457e6e26de14dab232f1 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7828526272)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6037/merge
Commit: 4b852445211f1436ab8c457e6e26de14dab232f1 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7828526272)

**Review by lghiur — APPROVED** [review]

**Review by andrei-tyk — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: ac386a196b9f756816ce433a6c27772c696bd7df [TT-11126] fix internal endpoint middleware not working in conjunction with other middleware enabled (#6037)
Triggered by: push (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7897435995)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: ac386a196b9f756816ce433a6c27772c696bd7df [TT-11126] fix internal endpoint middleware not working in conjunction with other middleware enabled (#6037)
Triggered by: push (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7897435995)

**Pull request merged**
