### PR TITLE
[TT-3973] Fix/flaky hmac tests

### PR DESCRIPTION
**Pull request by jeffy-mathew**
Also fixes
https://tyktech.atlassian.net/browse/TT-5228
https://tyktech.atlassian.net/browse/TT-4069

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4199/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2710364801)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4199/merge
Commit: 181444cbc3daed3172c0ecda93d0bb46507e53a5 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2710630805)

**Review by furkansenharputlu — APPROVED** [review]

**Review by titpetric — APPROVED** [review]
This should close three tickets, please link them in the description and coordinate with John to close all three.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4199/merge
Commit: 7f37b613b58bdddef973843fa27fef2270b07b37 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2711253643)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4199/merge
Commit: 944b18f18051605c85aabd44950e55a853f49921 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2717262353)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 890d81e04fa8fd7f2a7015b69aeb5ce03c27874b [TT-3973] Fix/flaky hmac tests (#4199)

* Fix TestHMACAuth flaky tests due to two different *Test instances


[changelog]
internal: fix flaky hmac tests.

Co-authored-by: Tit Petric <tit.petric@monotek.net>
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2717399448)

**Pull request merged**
