### PR TITLE
Github actions: don't escape content for GITHUB_OUTPUT anymore

### PR DESCRIPTION
**Pull request by titpetric**
## Description

Since ::set-output has been replaced with GITHUB_OUTPUT, the git-state comment from CI has been inaccurate, or rather the newlines have been escaped according to old format. New output set according to [official docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4843/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4367021407)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4843/merge
Commit: c43c255cf8e6492e2c71650a80dbb1b94a5fd5a8 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4367050031)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4843/merge
Commit: 827245a8fa508957578f65028bbb1830d41bf58a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4367087952)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4843/merge
Commit: 42420eef3674f3dd7b6a3384ca8fc1955f6d66e5 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4367154207)

**Review by ermirizio — APPROVED** [review]
lgtm

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4843/merge
Commit: f547ee1bef6914407bbeecdf10d420fd05a675d7 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4367390086)

**Review by maciejwojciechowski — APPROVED** [review]

**Pull request merged**
