### PR TITLE
[TT-5956] Generate Python bindings using latest protoc, remove unused files

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Updated Python bindings using latest `protoc` version.

## Description
We're improving PB support for Tyk Plugins, besides doing a Protobuf module version bump, bindings update is also required.

## Related Issue
TT-5956

## Motivation and Context
Keep PB support up to date.

## How This Has Been Tested
Manually tested.

## Screenshots (if appropriate)
-

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [x] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [x] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4182/merge
Commit:  
Triggered by: pull_request (@matiasinsaurralde)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2665873073)

**Comment by tbuchaillot** [comment]
@matiasinsaurralde `github.com/TykTechnologies/tyk/coprocess/python ` tests are failing, can you check?

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4182/merge
Commit: 1a9ea684a75405073de146e489e3e939e5d346e7 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3018460063)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4182/merge
Commit: 0c1b30cd3662d6977cdfd620ecda9e0c6faa1e9f 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3036059185)

**Comment by buger** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4182/merge
Commit: 725d3e74665f99b9d3cce3e3e82b40e31045a970 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3061465555)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4182/merge
Commit: e33bb18980ba61a816fdb3038c3341ac4da62155 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3137575426)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4182/merge
Commit: e33bb18980ba61a816fdb3038c3341ac4da62155 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3137575426)

**Pull request closed without merging**
