### PR TITLE
TD-876/release-4-lts-cleanup

### PR DESCRIPTION
**Pull request by ermirizio**
Cleanup of the files that were already moved under the ci folder

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3919/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1946739361)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3919/merge
Commit: 0cf33c247cc57ea3e77e9d5f270f89e90b5847f1 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1946794533)

**Comment by alephnull** [comment]
CI tests are failing due to gofmt. @asutosh also had the identical problem, is it your editor making this happen?

**Comment by ermirizio** [comment]
I'm not sure honestly, I do have a VSC extension for GO, but I have not done and/or touched those files really, so I think this is something that existed already

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3919/merge
Commit: 2d36a7b4556af6e20479b5cc70272c745dc4af70 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1965657960)

**Comment by ermirizio** [comment]
After fixing the format issues with gofmt, we have the following test issues:

1. https://github.com/TykTechnologies/tyk/runs/5502975216?check_suite_focus=true#step:10:1691
2. https://github.com/TykTechnologies/tyk/runs/5502975216?check_suite_focus=true#step:10:1705
3. https://github.com/TykTechnologies/tyk/runs/5502975216?check_suite_focus=true#step:10:1777
4. https://github.com/TykTechnologies/tyk/runs/5502975216?check_suite_focus=true#step:10:1788
5. https://github.com/TykTechnologies/tyk/runs/5502975216?check_suite_focus=true#step:10:1809
6. https://github.com/TykTechnologies/tyk/runs/5502975216?check_suite_focus=true#step:10:1816
7. https://github.com/TykTechnologies/tyk/runs/5502975216?check_suite_focus=true#step:10:1823
8. https://github.com/TykTechnologies/tyk/runs/5502975216?check_suite_focus=true#step:10:1838
9. https://github.com/TykTechnologies/tyk/runs/5502975216?check_suite_focus=true#step:10:2005

@sredxny , @furkansenharputlu , could you take a look?

**Comment by alephnull** [comment]
Rebase from master required

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3919/merge
Commit: ecf58ca9d7a8ea17744360a0dfd54053c3e12163 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1998123016)

**Comment by ermirizio** [comment]
after talking with @furkansenharputlu I confirmed the CI issues are due to flaky tests, we are good to merge.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4-lts
Commit: 5fbf289c89a9ffba8a52c3dfa022b0473830d882 TD-876/release-4-lts-cleanup (#3919)

* internal: unused moved files cleanup

* internal: change smoke-tests path

* fix server.go format
Triggered by: push (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2000173551)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4.0.1
Commit: 5fbf289c89a9ffba8a52c3dfa022b0473830d882 
Triggered by: push (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2021453869)

**Pull request merged**
