### PR TITLE
[TT-1455] - json parser added latest version

### PR DESCRIPTION
**Pull request by vaske**
This PR updates jsonparser to latest version

### CODE REVIEW

**Comment by buger** [comment]
Pls run go mod vendor too. We still use it (but planning to drop it)

**Review by furkansenharputlu — CHANGES_REQUESTED** [review]
Why does it have vendor files?

**Comment by vaske** [comment]
@furkansenharputlu removed

**Review by furkansenharputlu — APPROVED** [review]
We can merge when the tests are green.

**Review by buger — APPROVED** [review]

**Comment by vaske** [comment]
manually merged to release-4

**Comment by vaske** [comment]
and to release-3-lts release-3.2 respectively

**Pull request merged**
