### PR TITLE
remove usage of github.com/pkg/errors

### PR DESCRIPTION
**Pull request by mitjaziv**
## Description

Change removes usage of github.com/pkg/errors from code base.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [X] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4057/merge
Commit:  
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2341198014)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4057/merge
Commit:  
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2341198014)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4057/merge
Commit:  
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2341198014)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4057/merge
Commit:  
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2341198014)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4057/merge
Commit:  
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2341198014)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: be10d21eb6423bd5c87e12c364b2e51a58f757b3 remove usage of github.com/pkg/errors (#4057)

Change removes usage of github.com/pkg/errors and replaces it with standard library errors.
Triggered by: push (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2344209010)

**Pull request merged**
