### PR TITLE
[TT-8944]: Feat: Added variable validation stage to graphql middleware

### PR DESCRIPTION
**Pull request by kofoworola**
## Description
This PR upgrades the graphql-go-tools library to make use of the new input validation step added to the library. It also adds tests to validate this new feature. Now variables passed to graphql queries are validated before execution so a proper error can be returned instead of the generic 500 error (Error proxying request)]

[TT-8944](https://tyktech.atlassian.net/browse/TT-8944)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

[TT-8944]: https://tyktech.atlassian.net/browse/TT-8944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5125/merge
Commit: b9c43be3842683fa498c6966e69fe5bd3c3d65d5 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5212689550)

**Comment by rhianeKobar** [comment]
The linter seems to be upset

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5125/merge
Commit: b9c43be3842683fa498c6966e69fe5bd3c3d65d5 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5212689550)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5125/merge
Commit: 4615f4c5ffe6aeef828e2e4e9c446c96da55278f 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5255510968)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5125/merge
Commit: 3c15d1d2ebebc0d0edb4b90b1ab4de375205c850 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5255545105)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5125/merge
Commit: 88896878588111df60382b396d028ce9f7b76a34 
Triggered by: pull_request (@behcio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5265631421)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5125/merge
Commit: 4bbc88c7bd196aa883e2a2b630af7ebca5882d7d 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5280044951)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5125/merge
Commit: 0700cfb809243d85f01b9d29e1567c491cd6edb8 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5287365341)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5125/merge
Commit: c93d8c92e3ffe6a0feff362eed593c9e2fc7b1a4 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5287861453)

**Pull request merged**
