### PR TITLE
[TT-154] fix custom auth middleware with jsvm

### LINKED ISSUE #2512: JSVM authentication broken when using bundles
**Branch/Environment/Version**
- Branch/Version: Master
- Environment: On-prem

**Describe the bug**
I've been testing JSVM authentication with a bundle, seems that `DynamicMiddleware` doesn't get initialized with the right flag, when using an authentication hook: https://github.com/TykTechnologies/tyk/blob/master/gateway/middleware.go#L63

In `api_loader.go` we have the following code:
```go
		if ottoAuth {
			logger.Info("----> Checking security policy: JS Plugin")

			authArray = append(authArray, createDynamicMiddleware(mwAuthCheckFunc.Name, true, false, baseMid))
		}
```

This call will always initialize `DynamicMiddleware` with `Auth` set to `false`. To fix this we could extend `createDynamicMiddleware` and add an argument. After a quick test, I've found that this fixes the issue.
[bundle.zip](https://github.com/TykTechnologies/tyk/files/3623811/bundle.zip)

**Reproduction steps**

1. Configure an API with the following settings:

```js
    "custom_middleware_bundle": "bundle.zip",
    "enable_coprocess_auth": true,
```
2. Serve the attached bundle (`bundle.zip`).

**Actual behavior**
The middleware gets called but the user receives the following error:

```sh
% curl localhost:8080/quickstart/ -H 'Authorization: foobar'
{
    "error": "Session state is missing or unset! Please make sure that auth headers are properly applied"
}
```

**Expected behavior**
When sending `foobar`, the authentication should be successful.

### PR DESCRIPTION
**Pull request by gernest**
When using custom `js` middleware  for authorisation. The  session object is not  set in context, causing `KeyExpired` middleware to throw   `400` error with message `Session state is missing or unset! Please make sure that auth headers are properly applied`

## Description

This sets `DynamicMiddleware.Auth` to true when initialising the middleware, forcing session to always be set in context.

## Related Issue

Fixes #2512

## How This Has Been Tested

 Manually by following steps described in  #2512

With unit tests

```shell
go test -v -run TestJSVM_Auth ./gateway/
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [x] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Review by matiasinsaurralde — APPROVED** [review]
Looking good

**Review by sredxny — APPROVED** [review]
LGTM! 👍

**Pull request merged**
