### PR TITLE
[TT-13761] add batch request to the latest open api specs

### PR DESCRIPTION
**Pull request by yurisasuke**
<details open>
  <summary><a href="https://tyktech.atlassian.net/browse/TT-13761" title="TT-13761" target="_blank">TT-13761</a></summary>
  <br />
  <table>
    <tr>
      <th>Summary</th>
      <td>add batch request to the latest open api specs</td>
    </tr>
    <tr>
      <th>Type</th>
      <td>
        Story
        Story
      </td>
    </tr>
    <tr>
      <th>Status</th>
      <td>In Code Review</td>
    </tr>
    <tr>
      <th>Points</th>
      <td>N/A</td>
    </tr>
    <tr>
      <th>Labels</th>
      <td>-</td>
    </tr>
  </table>
</details>

---

When the new Gateway Open Api spec was created. The Batch request endpoint was left out .This should be added to the gateway OAS.

This pr also fixes an issue where the external OAS Url we were using now return error 404. This pr changes that to use a local copy of the external oas . I.e we have changed from :  https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json  to https://raw.githubusercontent.com/TykTechnologies/tyk/refs/heads/master/apidef/oas/schema/3.0.json

Link: https://tyk.io/docs/5.5/tyk-gateway-api/ 

[TT-13761]

[TT-13761]: https://tyktech.atlassian.net/browse/TT-13761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by buger** [comment]
<p>I'm a bot and I 👍 this PR title. 🤖</p>

**Comment by buger** [comment]
<p>I'm a bot and I 👍 this PR title. 🤖</p>

**Review by lghiur — APPROVED** [review]

**Pull request merged**
