### PR TITLE
[TT-7753] fix custom plugin OAS migration.

### PR DESCRIPTION
**Pull request by jeffy-mathew**
- Remove duplicated code from SetDisabled flags.
- add missed Fill and ExtractTo methods for postAuthenticationPlugin, postPlugin and responsePlugin

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4746/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4110612364)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4746/merge
Commit: 12bb77b0ffcc7dac39a02f828a1e6d974d834e38 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4110643784)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4746/merge
Commit: 12bb77b0ffcc7dac39a02f828a1e6d974d834e38 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4110643784)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4746/merge
Commit: a7e69c2ed387f09018f570ab2e78c35e65e4f440 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4110897703)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4746/merge
Commit: f0daec3a267efddaf3ae41174c8e489ff5f83e93 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4110903528)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4746/merge
Commit: e1bbbda9edf0a76dca4409522e5efff9d8f4f736 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4111106568)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4746/merge
Commit: beec1b36abd7391e17f39c58ca1a2181badb4699 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4111148079)

**Review by titpetric — APPROVED** [review]

**Review by lghiur — APPROVED** [review]

**Pull request merged**
