### PR TITLE
[TT-8222] Remove x-tyk-gateway docs generator

### PR DESCRIPTION
**Pull request by titpetric**
- remove old doc gen for x-tyk-gateway schema (TT-8222)

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6089/merge
Commit: ed3477bd6a893aae54919e158f95b459d647356c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8138033401)

**Review by dcs3spp — COMMENTED** [review]
Why is this file apidef/oas/schema/x-tyk-gateway.md being deleted? Will that effect docs generation?

What is xtyk_doc.go and xtyk_doc_test.go used for?

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v5.0.11-dev
Commit: 98a0a40a7280fbd8e073b5a7d4d593450d244ff4 
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8155780271)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v5.0.11-dev
Commit: 98a0a40a7280fbd8e073b5a7d4d593450d244ff4 
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8155780271)

**Review by dcs3spp — APPROVED** [review]
PR LGTM

**Pull request merged**
