### PR TITLE
[TT-4271] Bump docker version and remove critical CVE dependencies

### PR DESCRIPTION
**Pull request by titpetric**

### CODE REVIEW

**Review by alephnull — COMMENTED** [review]
tbh, if smoke tests pass, this is ok.

**Review by asutosh — APPROVED** [review]
Everything builds locally, and  all smoke tests pass.
Looks good to me!

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3959/merge
Commit: 0d0a883cdf55d0f9a726e67a8c06f5e15acec78d 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2088531418)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3959/merge
Commit: 7e406d03f7da7297181a296d348b93cd9f712ee9 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2089002692)

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 7e3ed75ad67925b1d9f5c2d4a0dbe3f28960f113 [TT-4271] Bump docker version and remove critical CVE dependencies (#3959)

* Bump Dockerfile base image versions
* Bump docker base image to debian11, bullseye

Co-authored-by: Jeffy Mathew <jeffy.mathew100@gmail.com>

[changelog]
security: Update docker base images to resolve CVEs related to older debian releases
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2089249959)

**Pull request merged**
