### PR TITLE
Add release-4-lts policy, require build test to pass

### PR DESCRIPTION
**Pull request by titpetric**
## Description

Make basic build checks a required workflow for 4-lts.

https://github.com/TykTechnologies/tyk/actions/runs/4949324701

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5019/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4994074282)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5019/merge
Commit: 5c44519ac3b0c7541710213b2b2bb97c9e6e53cc 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4994203401)

**Review by ermirizio — APPROVED** [review]
looks good, release-4-lts has been imported as well

**Comment by ermirizio** [comment]
@titpetric this has been applied

**Pull request merged**
