### PR TITLE
[TT-9423] Add godoc taskfile

### PR DESCRIPTION
**Pull request by titpetric**
https://tyktech.atlassian.net/browse/TT-9423

Run it with task -t `.taskfiles/godoc/Taskfile.yml`, or go into `.taskfiles/godoc` and run `task`.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5303/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5519453548)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5303/merge
Commit: 6ea6f4fdd4bd86aa9423faaeeeb61a9967a13742 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5519776964)

**Review by furkansenharputlu — APPROVED** [review]

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5303/merge
Commit: 4dda314db0155aa781858bb51c36ee45bb91667c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5521183813)

**Pull request merged**
