### PR TITLE
Make tests less chatty, other fixes

### PR DESCRIPTION
**Pull request by mvdan**
I noticed the rest while looking for `var log`.

### CODE REVIEW

**Comment by mvdan** [comment]
Travis, wake up.

**Comment by buger** [comment]
Yeah, I was thinking about those maps as well.

@lonelycode is there is any reason why you used pointer to the map? I mean map is already pointer by design. There is lot of places in Tyk when we use double pointers.

**Comment by mvdan** [comment]
There's a lot of `*[]*Foo` that I wanted to tackle next. Those can be useful sometimes, though. Map pointers are certainly wrong.

**Comment by lonelycode** [comment]
> There's a lot of *[]*Foo that I wanted to tackle next. Those can be useful sometimes, though. Map pointers are certainly wrong.

Careful about these :-/

**Comment by mvdan** [comment]
Yep, which is why I left them for another time.

**Comment by lonelycode** [comment]
>  is there is any reason why you used pointer to the map? I mean map is already pointer by design. There is lot of places in Tyk when we use double pointers.

@buger Ah, my golang-fu failing me... if they are already pointers and treated as such then yeah, we can kill the double pointers to maps.

**Pull request merged**
