### PR TITLE
fix graphiql to use default theme

### PR DESCRIPTION
**Pull request by jay-deshmukh**
this PR makes a change to use default graphiql theme

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3966/merge
Commit: da12349c8aac02870b010b1634bc3e99dbc77a15 
Triggered by: pull_request (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2057691468)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3966/merge
Commit:  
Triggered by: pull_request (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2057690728)

**Review by buraksezer — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3966/merge
Commit: 12d3ec362d0214a56122351e6390fbc3610fe10b 
Triggered by: pull_request (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2069474989)

**Review by Aenimus — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: dd7b79e91c2e15ea5cee57dfdaaecac3d3f73e7b fix graphiql to use default theme (#3966)
Triggered by: push (@jay-deshmukh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2070149705)

**Pull request merged**
