### PR TITLE
[TT-9364] Fix formatting float64 to string in tyk_context variables

### PR DESCRIPTION
**Pull request by furkansenharputlu**
`32` bit size rounds and distorts `float64` value.

Fixes https://github.com/TykTechnologies/tyk/issues/5134

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5280/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5466285949)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5280/merge
Commit: b0157aa5060d1892b5c2817ebf99c2c0228928a7 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5466324748)

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5280/merge
Commit: 868b78f82061f27e8a9a7724526fa06e7d7e6727 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5476548504)

**Pull request merged**
