### PR TITLE
[TT-6150] Revert "[TT-3904] fix chunked body logging (#3861)"

### PR DESCRIPTION
**Pull request by furkansenharputlu**
Reasons to revert:
- It causes another bug
- The test is wrong
- No need to copy the request
- Handling response body re-read is not correct

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4238/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2868666464)

**Review by titpetric — APPROVED** [review]

**Comment by furkansenharputlu** [comment]
Reverted from `release-4-lts` manually.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 7dfd82fa587c7af38e1ca11878f3fc995f0eb9a9 Revert "[TT-3904] fix chunked body logging (#3861)" (#4238)

This reverts commit bedf03a3d10f3c704738bdf9449c430bdbb719ca.
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2869236683)

**Pull request merged**
