### PR TITLE
[TT-4936] Disallow loading TCP services on main gateway port

### PR DESCRIPTION
**Pull request by buger**
It will throw meaningful error

### CODE REVIEW

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: f5d12071bc41deb1ff91a89839c1b6b7fd0f898b Disallow loading TCP services on main gateway port (#3984)

It will throw meaningful error
Triggered by: push (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2089335088)

**Pull request merged**
