### PR TITLE
Set session id when openid key doesnt exist.So quota and key is created

### PR DESCRIPTION
**Pull request by sredxny**
## Description
When using OpenID, the first time the key is not found in redis then we need to set the correct SessionID to the new session so apikey and quota is created correctly

## Related Issue
https://tyktech.atlassian.net/browse/TT-4412

## Motivation and Context
Make OpenID work properly

## How This Has Been Tested
- Follow instructions of https://tyk.io/docs/advanced-configuration/integrate/api-auth-mode/oidc-auth0-example/
- Set a quota to the policy
- Consume api
- An apikey and a quota is created in redis with prefix+sufix

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
Now it looks obvious why it did not worked 🤦🏻 

Worth noticing that we're planning to deprecate/redo openid plugin soon, to properly work with access tokens...

👍🏻

**Review by buger — APPROVED** [review]

**Review by matiasinsaurralde — APPROVED** [review]
LGTM

**Review by tbuchaillot — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3852/merge
Commit: 25aa569887b7adb548d1c102908780319ce57319 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1740998659)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: a03d55490bac80d51bb8837154fbd7deeae95092 set session id when openid key doesnt exist.So quota and key is created (#3852)

Co-authored-by: Tomas Buchaillot <tombuchaillot89@gmail.com>
Triggered by: push (@gregdelhon)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/1741000981)

**Pull request merged**
