### PR TITLE
 [TT-774] fix loading jaeger tracing config

### LINKED ISSUE #3338: [TT-774] gateway not reporting any data to jaeger
**Branch/Environment/Version**
- Branch/Version: v2.9.4.2, v2.9.4.3, v2.9.4.4, v2.9.4.5, v3.0.1
- Environment: community edition, docker

**Describe the bug**
Tyk gateway no longer reporting any tracing data to jaeger. Tracing configured in tyk.conf, was previously working in v2.9.4.1. No changes were made to tracing config. Downgrade to v2.9.4.1 resumes data being sent.

**Reproduction steps**

1. Configure tracing via tyk.conf
2. Proxy api request 
3. Check jaeger search for data being reported

tracing config from tyk.conf
```
  "tracing": {
    "enabled": true,
    "name": "jaeger",
    "options": {
      "baggage_restrictions": null,
      "disabled": false,
      "headers": null,
      "reporter": {
        "BufferFlushInterval": 0,
        "collectorEndpoint": "",
        "localAgentHostPort": "jaeger-agent.tracing.svc.cluster.local:6831",
        "logSpans": false,
        "password": "",
        "queueSize": 0,
        "user": ""
      },
      "rpc_metrics": false,
      "sampler": {
        "maxOperations": 0,
        "param": 1,
        "samplingRefreshInterval": 0,
        "samplingServerURL": "",
        "type": "const"
      },
      "serviceName": "tyk-gateway",
      "tags": null,
      "throttler": null
    }
  }
```

**Actual behavior**
No tracing data being reported to jaeger. Error messages being reported in logs:
```
2020/09/28 14:32:57 [ERROR] trace:  error when flushing the buffer: write udp 127.0.0.1:51769->127.0.0.1:6831: write: connection refused
```
A DNS resolution of the jaeger URL in the kubernetes pod results in the correct service IP address. 

We also attempted to configure jaeger via env vars per https://github.com/TykTechnologies/tyk/pull/3112, but no change was observed. 

**Expected behavior**
Tracing data being reported to jaeger for proxied requests.

**Logs (debug mode or log file):**
Errors being observed related to flushing the buffer, as seen above. No other pertinent messages observed.

**Configuration (tyk config file):**
```
{
  "listen_port": 8080,
  "secret": "352d20ee67be67f6340b4c0605b044b7",
  "template_path": "/opt/tyk-gateway/templates",
  "tyk_js_path": "/opt/tyk-gateway/js/tyk.js",
  "middleware_path": "/opt/tyk-gateway/middleware",
  "use_db_app_configs": false,
  "app_path": "/opt/tyk-gateway/apps/",
  "storage": {
    "type": "redis",
    "host": "localhost",
    "port": 6379,
    "username": "",
    "password": "",
    "database": 0,
    "timeout": 10,
    "optimisation_max_idle": 2000,
    "optimisation_max_active": 4000,
    "use_ssl": true
  },
  "enable_analytics": true,
  "analytics_config": {
    "type": "",
    "ignored_ips": []
  },
  "dns_cache": {
    "enabled": false,
    "ttl": 3600,
    "check_interval": 60
  },
  "optimisations_use_async_session_write": true,
  "allow_master_keys": false,
  "policies": {
    "policy_source": "file"
  },
  "hash_keys": true,
  "suppress_redis_signal_reload": false,
  "force_global_session_lifetime": false,
  "max_idle_connections_per_host": 500,
  "allow_insecure_configs": true,
  "local_session_cache": {
    "disable_cached_session_state": false
  },
  "http_server_options": {
    "skip_url_cleaning": true,
    "enable_websockets": true,
    "certificates": [
        {
          "domain_name": "*",
          "cert_file": "/path/to/server.crt",
          "key_file": "/path/to/server.key"
        }
    ]
  },
  "tracing": {
    "enabled": true,
    "name": "jaeger",
    "options": {
      "baggage_restrictions": null,
      "disabled": false,
      "headers": null,
      "reporter": {
        "BufferFlushInterval": 0,
        "collectorEndpoint": "",
        "localAgentHostPort": "jaeger-agent.kube-system.svc.cluster.local:6831",
        "logSpans": false,
        "password": "",
        "queueSize": 0,
        "user": ""
      },
      "rpc_metrics": false,
      "sampler": {
        "maxOperations": 0,
        "param": 1,
        "samplingRefreshInterval": 0,
        "samplingServerURL": "",
        "type": "const"
      },
      "serviceName": "tyk-gateway",
      "tags": null,
      "throttler": null
    }
  }
}
```

**Additional context**
We observe this behavior beginning with the merge of https://github.com/TykTechnologies/tyk/pull/3112. All subsequent version tags after v2.9.4.1 do not work. We also tried v3.0.1 and observed the same behavior. 

If https://github.com/TykTechnologies/tyk/pull/3112 is reverted and the gateway built without that code, tracing starts working again (if configured via tyk.conf, obviously). We attempted this locally as a troubleshooting step, and observed it correct the problem with both v2.9.4.3, and v3.0.1. We did not try other versions.

### PR DESCRIPTION
**Pull request by gernest**
## Related Issue
Fixes #3338
updated config docs and explanationhttps://github.com/TykTechnologies/tyk-docs/pull/1599
## Motivation and Context

The issue here is  tracer object that is used to configure both jaeger and zipking looks like this

```
type Tracer struct {
	Name string `json:"name"`
	Enabled bool `json:"enabled"`
	Options map[string]interface{} `json:"options"`
}
```

Notice options is ` map[string]interface{}` which will contain any values you use to configure jaeger. So we read read config values as json into a `map[string]interface{}` that will look like

```
map[string]interface {}{
    "reporter": map[string]interface {}{
        "queueSize":           float64(0),
        "user":                "",
        "bufferflushinterval": "0s",
        "collectorEndpoint":   "",
        "localAgentHostPort":  "jaeger:6831",
        "logSpans":            bool(true),
        "password":            "",
    },
    "sampler": map[string]interface {}{
        "samplingServerURL":       "",
        "type":                    "const",
        "maxOperations":           float64(0),
        "param":                   float64(1),
        "samplingRefreshInterval": "0s",
    },
    "serviceName": "tyk-gateway",
    "tags":        []interface {}{
    },
    "baggage_restrictions": map[string]interface {}{
        "hostPort":                           "",
        "refreshInterval":                    "0s",
        "denyBaggageOnInitializationFailure": bool(false),
    },
    "headers": map[string]interface {}{
        "TraceContextHeaderName":   "",
        "jaegerBaggageHeader":      "",
        "jaegerDebugHeader":        "",
        "traceBaggageHeaderPrefix": "",
    },
    "throttler": map[string]interface {}{
        "hostPort":                  "",
        "refreshInterval":           "0s",
        "synchronousInitialization": bool(false),
    },
    "disabled":    bool(false),
    "rpc_metrics": bool(false),
}
```

Now, we allso support loading configurations from env vars and the work flow was like this

- 1 Decode the options into a `jaeger.Configuration`
- 2 Process loading of env vars on the jaeger config
- 3 Encode the jeager config back to a map[string]interface{} and update the options to use this  value . This is important because we write the config file to disc and we want it to be correct when we read back from it.

Now all the 3 steps are performed for both jaeger and zipkin. The issue was decoding/encoding ( step 1 and 3) both used json. However `jaeger.Configuration` onlly has `yaml` tags

```go
type Configuration struct {
	// ServiceName specifies the service name to use on the tracer.
	// Can be provided via environment variable named JAEGER_SERVICE_NAME
	ServiceName string `yaml:"serviceName"`

	// Disabled can be provided via environment variable named JAEGER_DISABLED
	Disabled bool `yaml:"disabled"`

	// RPCMetrics can be provided via environment variable named JAEGER_RPC_METRICS
	RPCMetrics bool `yaml:"rpc_metrics"`

	// Tags can be provided via environment variable named JAEGER_TAGS
	Tags []opentracing.Tag `yaml:"tags"`

	Sampler             *SamplerConfig             `yaml:"sampler"`
	Reporter            *ReporterConfig            `yaml:"reporter"`
	Headers             *jaeger.HeadersConfig      `yaml:"headers"`
	BaggageRestrictions *BaggageRestrictionsConfig `yaml:"baggage_restrictions"`
	Throttler           *ThrottlerConfig           `yaml:"throttler"`
}
```

Meaning encoding this tomap[string]interface{} as json  will give us this

```
map[string]interface {}{
    "ServiceName": "tyk-gateway",
    "RPCMetrics":  bool(false),
    "Tags":        []interface {}{
    },
    "Disabled": bool(false),
    "Sampler":  map[string]interface {}{
        "SamplingRefreshInterval": float64(0),
        "Type":                    "const",
        "Param":                   float64(1),
        "SamplingServerURL":       "",
        "MaxOperations":           float64(0),
    },
    "Reporter": map[string]interface {}{
        "BufferFlushInterval": float64(0),
        "LogSpans":            bool(true),
        "LocalAgentHostPort":  "jaeger:6831",
        "CollectorEndpoint":   "",
        "User":                "",
        "Password":            "",
        "QueueSize":           float64(0),
    },
    "Headers": map[string]interface {}{
        "JaegerDebugHeader":        "",
        "JaegerBaggageHeader":      "",
        "TraceContextHeaderName":   "",
        "TraceBaggageHeaderPrefix": "",
    },
    "BaggageRestrictions": map[string]interface {}{
        "DenyBaggageOnInitializationFailure": bool(false),
        "HostPort":                           "",
        "RefreshInterval":                    float64(0),
    },
    "Throttler": map[string]interface {}{
        "HostPort":                  "",
        "RefreshInterval":           float64(0),
        "SynchronousInitialization": bool(false),
    },
}
```

Which is not what we want see that the key name mismatch.

So this PR basically make it that
 
For Jaeger
- 1 Decode with Yaml
- 3 Encode with yaml

For zipkin
- 1 Decode with json
-  3 Encode with json

### CODE REVIEW

**Comment by buger** [comment]
What was the reason why it broke starting from v2.9.4.1? 

Also I do not understand what was the root cause of the issue. 
Pls add implementation details. 

I do not understand why plain files with tyk config need be used. Why we can't just use Config struct, and apply viper on top of it? And use smth like reflect.DeepEqual to compare them?

**Comment by gernest** [comment]
@buger 

> Also I do not understand what was the root cause of the issue.
Pls add implementation details

I just updated the PR comment please see it above.

>I do not understand why plain files with tyk config need be used. Why we can't just use Config struct, and apply viper on top of it? And use smth like reflect.DeepEqual to compare them

I just didn't want to take any chances. The bug was a result of only having unit tests. This covers more ground with how we load configs. They are just sample files.

**Comment by buger** [comment]
Can we have then a minimal config file which cover only opentracing options?

**Comment by gernest** [comment]
Done

**Review by buger — APPROVED** [review]
Approve, but QA team should be very careful.

**Comment by buger** [comment]
@gernest can you record a small video on how to do setup and test this bug?

**Comment by gernest** [comment]
sure

**Comment by gernest** [comment]
I have demo video, can't share here because github complains they are  too big. 
Will share with QA if they need them.

On the demo I am basically following instructions from  the original Jira ticket TT-774 to reproduce the issue and also confirming it is fixed.

**Review by matiasinsaurralde — APPROVED** [review]

**Comment by matiasinsaurralde** [comment]
Manually merged to `release-3-lts` (45e0056d471d887ba2ccb0c3d9c48c67f5d77173).

**Pull request merged**
