### PR TITLE
[TT-3154] Fix stripping listen path when it contains regexp

### PR DESCRIPTION
**Pull request by buger**
We already had old code which stripped regexp https://github.com/TykTechnologies/tyk/pull/2466/files
But it worked only if you define a named variable inside it.
Current logic changed to use more simple algorithm from this PR https://github.com/TykTechnologies/tyk/pull/2277/files

## Related Issue
https://github.com/TykTechnologies/tyk/pull/2466/files
https://github.com/TykTechnologies/tyk/pull/2277/files

## How This Has Been Tested
Added unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4104/merge
Commit: d0fac671a4bb8ba5fabb4a4b60252ae47b231264 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2430036194)

**Review by furkansenharputlu — APPROVED** [review]

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: c53e2be15abc13c066b2d1675789662a16a9c4cf [TT-3154] Fix stripping listen path when it contains regexp (#4104)

We already had old code which stripped regexp https://github.com/TykTechnologies/tyk/pull/2466/files
But it worked only if you define a named variable inside it.
Current logic changed to use more simple algorithm from this PR https://github.com/TykTechnologies/tyk/pull/2277/files

## Related Issue
https://github.com/TykTechnologies/tyk/pull/2466/files
https://github.com/TykTechnologies/tyk/pull/2277/files



## How This Has Been Tested
Added unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist


- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`
Triggered by: push (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2446772481)

**Pull request merged**
