### PR TITLE
[TT-6022] Kafka data source should subscribe to multiple topics

### PR DESCRIPTION
**Pull request by buraksezer**
This PR updates the GraphQL config adapter and graphql-go-tools commit hash. 

See [TT-6022](https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/26?modal=detail&selectedIssue=TT-6022) for details.

[changelog]
internal: Updating graphql-go-tools commit hash.
internal: Update GraphQL config adapter to support multiple Kafka topics.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4233/merge
Commit:  
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2839564176)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4233/merge
Commit: fe6302559cce664c0908b21b8d626ad9399fbfe1 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2839883356)

**Review by kofoworola — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: d71b256806f26baa7455214a2368d94585dc5e3c [TT-6022] Kafka data source should subscribe to multiple topics (#4233)

* [TT-6022]

[changelog]
internal: Updating graphql-go-tools commit hash.
internal: Update GraphQL config adapter to support multiple Kafka topics.

* [TT-6022]

[changelog]
internal: Updating graphql-go-tools commit hash.
Triggered by: push (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2840119462)

**Pull request merged**
