### PR TITLE
Update drl to latest tagged version

### PR DESCRIPTION
**Pull request by alephnull**
This probably only manifested itself now when the vendor dir was removed.

## Description
An attempt to resolve the problem in tyk-analytics:
```
@...ies/tyk-analytics(master)$ go get github.com/TykTechnologies/tyk@690d6515876ce055dc05a23c622112ad45a2cbef
# github.com/TykTechnologies/tyk/gateway
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/host_checker.go:62:22: undefined: tunny.WorkPool
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/host_checker.go:238:32: cannot use 0 (type int) as type func(*proxyproto.Conn) in argument to proxyproto.NewConn
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/host_checker.go:360:16: undefined: tunny.CreatePool
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/le_helpers.go:17:22: undefined: letsencrypt.Manager
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/le_helpers.go:42:20: undefined: letsencrypt.Manager
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/le_helpers.go:93:55: undefined: letsencrypt.Manager
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/mw_graphql_granular_access.go:43:26: undefined: graphql.FieldRestrictionList
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/mw_graphql_granular_access.go:48:27: gqlRequest.ValidateFieldRestrictions undefined (type *graphql.Request has no field or method ValidateFieldRestrictions)
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/mw_graphql_granular_access.go:48:107: undefined: graphql.DefaultFieldsValidator
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/server.go:82:14: undefined: letsencrypt.Manager
../../../../pkg/mod/github.com/!tyk!technologies/tyk@v1.9.2-0.20210223162253-690d6515876c/gateway/mw_graphql_granular_access.go:48:107: too many errors
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [x] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Review by gernest — APPROVED** [review]

**Comment by alephnull** [comment]
Nope. This is entirely wrong. Abandoning.

**Comment by gernest** [comment]
Why?

**Comment by alephnull** [comment]
> Why?

https://github.com/TykTechnologies/tyk/runs/1969383627?check_suite_focus=true

**Comment by gernest** [comment]
My bad I didn't check the logs , the errors there have nothing to do with drl

**Comment by alephnull** [comment]
```
[/home/runner/work/tyk/tyk/gateway/distributed_rate_limiter.go:17:18: too few arguments in call to drlManager.Init /home/runner/work/tyk/tyk/gateway/distributed_rate_limiter.go:52:6: invalid operation: operator ! not defined for DRLManager.Ready (value of type func() bool) /home/runner/work/tyk/tyk/gateway/distributed_rate_limiter.go:94:5: non-boolean condition in if statement -: could not load export data: no export data for \"github.com/TykTechnologies/tyk/gateway\"]"
```
gw _needs_ the old version. I cannot work with the new version. To reproduce:
```
% go get -u github.com/TykTechnologies/drl
go: github.com/TykTechnologies/drl upgrade => v0.0.0-20191115080854-ee12cebaff19
% go build
# github.com/TykTechnologies/tyk/gateway
gateway/distributed_rate_limiter.go:17:17: not enough arguments in call to drlManager.Init
	have ()
	want ("context".Context)
gateway/distributed_rate_limiter.go:52:5: invalid operation: ! func() bool
gateway/distributed_rate_limiter.go:94:2: non-bool DRLManager.Ready (type func() bool) used as if condition
```

**Pull request closed without merging**
