### PR TITLE
[TT-5733] adjust OAS contract onKeyChangeURL to onKeyChangeUrl to be in consistent with OAS naming

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description
adjust OAS contract onKeyChangeURL to onKeyChangeUrl to be in consistent with OAS namings.

### CODE REVIEW

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4133/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2501586829)

**Review by lghiur — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4133/merge
Commit: 617efdc0095e5ea79d1d440bc8ecee1f8a544c94 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2508238438)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 13ef7abacc7624f572b04d7f3a24033319d48b6d adjust OAS contract onKeyChangeURL to onKeyChangeUrl to be in consistent with OAS namings. (#4133)

[changelog]
internal: adjust OAS contract.
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2508388903)

**Pull request merged**
