### PR TITLE
fix plugin imports to current version of tyk

### PR DESCRIPTION
**Pull request by mitjaziv**
Change fixes imports so plugins are build from
current tyk version.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [X] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4058/merge
Commit:  
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2345358312)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4058/merge
Commit: 7259b553a602fe5f28a2cd115a599594f1e63286 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2345469245)

**Review by titpetric — APPROVED** [review]
Lovely.

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4058/merge
Commit: 241e65cb5ee9121d4dcbf08005ce80bc63b0d7d9 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2405034875)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4058/merge
Commit: 1f766d7a0565113e45b9f5017c3c91cf0b2ceaef 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2413630055)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4058/merge
Commit: ee7b12a9c64eb13d231ba4bd985b280c3003912a 
Triggered by: pull_request (@mitjaziv)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2438869071)

**Pull request closed without merging**
