### PR TITLE
loader: set up exactly one sub-router per host

### LINKED ISSUE #1271: API loader is fragile when many endpoints are set up on a single domain
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a hybrid node is reloading, there is a chance that two similar paths that only slightly differ in length will load in a different order.

**What is the expected behavior?**
The endpoints should always load in longest-first order

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Create Two APIs with *slugs* of user and user-login
2. Differentiate them somehow (maybe a header inject)
3. Send requests to the gateway between hot reloads - the match order will swap

**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
Hybrid, potentially others

### PR DESCRIPTION
**Pull request by mvdan**
Plus a test, and another minor loader fix. See the commit messages for details.

Fixes #1271.

/cc @ewah

### CODE REVIEW

**Comment by ewah** [comment]
This solves our issues.

Just one note because Host can be domain regex-es does it need to resort based on Domain length to normalize it even more... 

ie. something like
Host("{fqdn:abc.(?:(dev.)?).com}").Subrouter()
Host("{fqdn:abc.(?:.*.?)com}").Subrouter()

The first should always load before the second.

**Comment by mvdan** [comment]
You're right that this fix does not cover regexes. However, as far as I can tell, we don't officially support regexes there - our docs don't mention regexes anywhere.

I don't know how we could possibly support all regexes here. The router doesn't backtrack - as soon as one `Host()` subrouter matches, it doesn't try the other host sub-routers. We could document that we support regexes with the current approach, as long as they never overlap - if they do, stuff will break as before.

**Comment by ewah** [comment]
@mvdan I'd be happy just doing a sort of length on Domain (regex or not)... it might not be 100% accurate -- but it is 100% consistent.

**Comment by mvdan** [comment]
Ah, I see your point about consistency. Yes, at the moment the host subrouter creation order is not deterministic.

Doing it just by length won't do, as different strings with the same length would still be sorted arbitrarily. I'm thinking of doing first length then alphabetical, or just alphabetical.

The only reason to do first length and then alphabetical is that it may help more often than not with regexes.

**Comment by mvdan** [comment]
Done - ended up using both length and chars, in decreasing order.

@buger PTAL

**Comment by buger** [comment]
Nice! Pls create same PR for release-2.3 branch.

**Pull request merged**
