### PR TITLE
[TT-4083] upgrade go version

### PR DESCRIPTION
**Pull request by jeffy-mathew**
Upgrade go version to go1.16

### CODE REVIEW

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4261/merge
Commit: 5c1a02a2268d7cad5786e4a4872433ac94801522 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2926164611)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4261/merge
Commit: 5e6af15b1c008b1151b7342467664ffa2b4f8dc9 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2931624700)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4261/merge
Commit: a0626a7b79dd4049a590f4f97e91e11a6787aadd 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2931694486)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4261/merge
Commit: 45cabb3d27077b00030bd13428a89abd1d2fdc63 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2931777027)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4261/merge
Commit: 3ccb224723d2d28ccdc1d6dfb3e4d9099c152775 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2932745617)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4261/merge
Commit: 7ae115f695db6720a57a0ba25ce1c40e609cbc91 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2933594354)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4261/merge
Commit: fb1a74546a2f9a2291002c1562d792eb4e20438e 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2933742940)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4261/merge
Commit: a494546a634f57981a907ded09bb877e315174c7 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2968863524)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4261/merge
Commit: a342bda19beeadb85a0c02a098bf7f9692f08fbc 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2969320241)

**Review by lghiur — APPROVED** [review]

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4261/merge
Commit: 1a30873b245c34ffd15d01746622e9b523f11b90 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2969396883)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 4e15968cf98343dedbc22fb2cedf08f8b55bf074 [TT-4083] upgrade go version (#4261)

upgrade go version to go1.16.

[changelog]
internal: upgrade go version to go1.16.
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2969518824)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-3.1.3
Commit: 4e15968cf98343dedbc22fb2cedf08f8b55bf074 
Triggered by: push (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3003685632)

**Pull request merged**
