### PR TITLE
[TT-5956] Ensure Python protobuf version is set to 3.20.1

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Extend changes introduced by #4105.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4184/merge
Commit:  
Triggered by: pull_request (@matiasinsaurralde)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2667592783)

**Comment by ermirizio** [comment]
@matiasinsaurralde this looks good! We could merge this directly but, lets coordinate this with @asutosh, we should actually promote CI changes (changes under CI folder) only from the templates. I know he is currently working on refactor templates so let's wait on hear back from him. I will discuss this with him and go back to this.  Also flaky tests need to pass 🔢

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4184/merge
Commit: fc89cb0b3e6039f5a86bc358efb506ce5bd65adf 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2748996839)

**Review by ermirizio — APPROVED** [review]

**Review by asutosh — APPROVED** [review]
This can be merged, will port the changes to the templates once this is merged so that it's persisted for further reruns,

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 5679edddfd884c471c2f9d4549672babc489706c Ensure Python protobuf version is set to 3.20.1 (#4184)

Co-authored-by: Esteban Ricardo Mirizio <35462288+ermirizio@users.noreply.github.com>
Triggered by: push (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2753635810)

**Pull request merged**
