### PR TITLE
fix race condition in rpc

### PR DESCRIPTION
**Pull request by gernest**
This uses  atomics  to protect access to some racy global data in rpc.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
Do the release branches affected?

**Comment by gernest** [comment]
Yes, this has been around for a while. It just wasn't triggered in tests before.

**Comment by matiasinsaurralde** [comment]
Added to `release-3-lts` (110f388b111275012df822e389d521f15241c4bd) and `release-3.0.3` (6fdf3514656fbdc83966537e36149f3c2c96e4c3).

**Pull request merged**
