### PR TITLE
TT-10344 Fix rpc ClientIsConnected

### PR DESCRIPTION
**Pull request by tbuchaillot**
## Description

Reverting changes introduced in `func (r rpcOpts) ClientIsConnected() bool`  onhttps://github.com/TykTechnologies/tyk/pull/5574.

`clientIsConnected` fn is called on `FuncClientSingleton` https://github.com/TykTechnologies/tyk/blob/master/rpc/rpc_client.go#L469 and if it fails while trying to `GroupLogin`,  the function `recoverOps` will not ever be able to recover https://github.com/TykTechnologies/tyk/blob/master/rpc/rpc_client.go#L444 and exit emergency mode.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5692/merge
Commit:  
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6666339728)

**Review by mativm02 — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5692/merge
Commit: 80ebe149e2157345f9cab7b36aa81ef70e5d6fa3 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6667702184)

**Pull request merged**
