### PR TITLE
Fix and enhance Python call protection

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
I've found several issues when using `dlpython` GIL helper functions, mostly because there might be internal calls that weren't correctly mapped when preparing the bindings. I did many experiments with it and the simplest approach is to control the lock in the Go side, with this we can avoid additional `cgo` overhead (in 2.8 we were controlling the GIL using the CPython calls).

Performance gets slightly better, less context switches and CPU usage as well, I'm comparing 2.8.6 (with previous approach) with this 2.9.x patch. It should protect all calls and ensure no crashes related to `PyCallObject`:

test1
test2

cpuinterrupts
cpuusage

Fix for: https://github.com/TykTechnologies/tyk/issues/2760

### CODE REVIEW

**Comment by christtyk** [comment]
@furkansenharputlu will this be in 2.9.3?

**Comment by furkansenharputlu** [comment]
@christtyk Yes, already merged to release branch.

**Comment by christtyk** [comment]
@furkansenharputlu @matiasinsaurralde will this fix issue for ticket 4492? Client is asking for more context

**Comment by christtyk** [comment]
4631 is the related ticket

**Pull request merged**
