### PR TITLE
[TT-4838] ValidateOASObject method

### PR DESCRIPTION
**Pull request by jeffy-mathew**
Add ValidateOASObject method to validate OAS definition against multiple OAS versions
This uses `go-bindata` to convert static files into go objects, so that it can be used in dashboard as a lib

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3973/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2069186518)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3973/merge
Commit: 28c0fece4c549054f0dba8b3fa3f2eb340faa6a3 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2069199231)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3973/merge
Commit: 33d042b59247d69ae04427db445f25e57b262353 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2069769431)

**Review by titpetric — APPROVED** [review]

**Review by urbanishimwe — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3973/merge
Commit: 02c39feaf3e16fb04532b6376a4c76f08327f9f4 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2070547194)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3973/merge
Commit: 0f7f990d828021fc2d898fca01b798834065b980 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2070773603)

**Pull request merged**
