### PR TITLE
[TT-6093] Ensure headers are updated from response middleware

### PR DESCRIPTION
**Pull request by l3ender**
## Description

This PR fixes an issue where response-based middleware is not able to delete headers before the response is returned to the client.

## Related Issue
Resolves https://github.com/TykTechnologies/tyk/issues/4192.

## Motivation and Context
Response middleware should be able to delete headers returned from the upstream API before sending to the client.

## How This Has Been Tested
Recompiled Tyk after change and used example files in https://github.com/TykTechnologies/tyk/issues/4192 to confirm updated behavior matches expected.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by l3ender** [comment]
Hi @matiasinsaurralde, anything else I can provide for this PR? Thank you!

**Review by matiasinsaurralde — APPROVED** [review]
LGTM, we should add tests

**Comment by l3ender** [comment]
Thanks for the review, @matiasinsaurralde. I am willing to add tests but would need a little guidance. I didn't see any existing response middleware tests and I am not very familiar with golang. If you can point me in a direction, I will give it a shot. Thanks!

**Comment by l3ender** [comment]
Hi @matiasinsaurralde, @buger -- anything else I can do for this PR? Thank you!

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 40ce872aa6e28cd369c674b6d8db52bf9ce5272e [TT-6093] Ensure headers are updated from response middleware (#4193)

## Description

This PR fixes an issue where response-based middleware is not able to delete headers before the response is returned to the client.

## Related Issue
Resolves https://github.com/TykTechnologies/tyk/issues/4192.

## Motivation and Context
Response middleware should be able to delete headers returned from the upstream API before sending to the client.

## How This Has Been Tested
Recompiled Tyk after change and used example files in https://github.com/TykTechnologies/tyk/issues/4192 to confirm updated behavior matches expected.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist


- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [ ] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

Co-authored-by: Sedky Shamalah <sedkyaboushamalah@gmail.com>
Co-authored-by: Leonid Bugaev <leonsbox@gmail.com>
Co-authored-by: Sredny M <sredny.buitrago@gmail.com>
Triggered by: push (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3150569528)

**Pull request merged**
