### PR TITLE
[TT-9882]: update graphql go tools

### PR DESCRIPTION
**Pull request by kofoworola**
## Description
The changes to the tests are to accommodate the introduction of backoff when a subscription fails to execute [here](https://github.com/TykTechnologies/graphql-go-tools/pull/387)

[TT-9882](https://tyktech.atlassian.net/browse/TT-9882)
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

[TT-9882]: https://tyktech.atlassian.net/browse/TT-9882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5606/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6482296920)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5606/merge
Commit: 2225491947152fe209b9c6943c99bd385269adaf 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6492697565)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5606/merge
Commit: f7bc87ca9ca00a17b2d53d75b7a4c1b275a7e637 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6494233985)

**Review by pvormste — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5606/merge
Commit: 346507abbdee9aa4caa3e61f55ae983d65fdc162 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6494326660)

**Pull request merged**
