### PR TITLE
[TT-1475] respect ignored paths in CoProcessMiddleware

### LINKED ISSUE #3383: TT-1475 Ignored extended paths not working for coprocess auth/custom_middleware
**Describe the bug**
We have an endpoint that we would like to be ignored by the API's configured coprocess auth using a custom grpc middleware, but configuring an ignored extended path that we want ignored by this middleware auth does not accomplish that.

**Reproduction steps**
Given and api definition with
```
          "enable_coprocess_auth": true,
          "custom_middleware": {
            "pre": null,
            "post": null,
            "post_key_auth": null,
            "auth_check": {
                "name": "Auth",
                "path": "",
                "require_session": false,
                "raw_body_only": false
            },
            "response": null,
            "driver": "grpc",
            "id_extractor": {
                "extract_from": "header",
                "extract_with": "value",
                "extractor_config": {
                    "header_name": "My-Token"
                }
            }
        },
```
And the extended paths:
```
                  "use_extended_paths": true,
                    "extended_paths": {
                        "ignored": [
                            {
                                "path": "/public",
                                "ignore_case": true,
                                "method_actions": {
                                    "GET": {
                                        "action": "no_action",
                                        "code": 200,
                                        "data": "",
                                        "headers": {}
                                    }
                                }
                            }
                        ]
                    },
                    "global_headers": {
                        "Authorization": "Bearer $tyk_meta.jwt"
                    },
```

**Actual behavior**
a 400 BadRequest from the /public endpoint
```
{
    "error": "Authorization field missing"
}
```

**Expected behavior**
to ignore the coprocess custom middleware auth for the /public endpoint and allow the unauthenticated request through

### PR DESCRIPTION
**Pull request by gernest**
This adds a check before we process request with coprocess middleware to ensure we skip the middleware when we have 
`StatusOkAndIgnore` set in context.

## Related Issue
fixes #3383

## Motivation and Context
If you have coprocess set and ignore extended paths. Then the ignored extended paths won't be respected.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Review by matiasinsaurralde — APPROVED** [review]
Looks good, shouldn't break any existing functionality.

**Review by tbuchaillot — APPROVED** [review]
LGTM

**Pull request merged**
