### PR TITLE
Load open tracing configuration options with environment variables

### LINKED ISSUE #3104: OpenTracing configuration can't be set via ENV variables
**Branch/Environment/Version**
- Branch/Version: master
- Environment: on-prem

**Describe the bug**
OpenTracing configuration can't be set via ENV variables which complicate docker setup a lot.

Tracing functionality configured using nested maps, and at the moment our library which used for reading the ENVs do not support such data structures.

**Reproduction steps**
You can set `TYK_GW_TRACING_ENABLED` and `TYK_GW_TRACING_NAME`, but not options `TYK_GW_TRACING_OPTIONS_REPORTER_URL`.

**Expected behavior**
All configuration should be possible to set via ENV variables.

### PR DESCRIPTION
**Pull request by gernest**
## Description

This refactors loading of configuration  with environment variables to load open tracing configurations for both zipkin and jaeger.
## Related Issue

fixes #3104

## Motivation and Context

Opent tracing options are passed as `map[string]interface{}` this was hard to map to environment variables. This PR add support for custom configuration option loaders that are invoked after the default envconfig loader is complete allowing safe and sane passing of opentracing options as env vars.

Supported zipkin env vars
```
 TYK_GW_TRACER_OPTIONS_REPORTER_URL
 TYK_GW_TRACER_OPTIONS_REPORTER_BATCHSIZE
 TYK_GW_TRACER_OPTIONS_REPORTER_MAXBACKLOG
 TYK_GW_TRACER_OPTIONS_SAMPLER_NAME
 TYK_GW_TRACER_OPTIONS_SAMPLER_RATE
 TYK_GW_TRACER_OPTIONS_SAMPLER_SALT
 TYK_GW_TRACER_OPTIONS_SAMPLER_MOD
```
supported jaeger env vars
```
TYK_GW_TRACER_OPTIONS_SERVICENAME
TYK_GW_TRACER_OPTIONS_DISABLED
TYK_GW_TRACER_OPTIONS_RPCMETRICS
TYK_GW_TRACER_OPTIONS_TAGS
TYK_GW_TRACER_OPTIONS_SAMPLER_TYPE
TYK_GW_TRACER_OPTIONS_SAMPLER_PARAM
TYK_GW_TRACER_OPTIONS_SAMPLER_SAMPLINGSERVERURL
TYK_GW_TRACER_OPTIONS_SAMPLER_MAXOPERATIONS
TYK_GW_TRACER_OPTIONS_SAMPLER_SAMPLINGREFRESHINTERVAL
TYK_GW_TRACER_OPTIONS_REPORTER_QUEUESIZE
TYK_GW_TRACER_OPTIONS_REPORTER_BUFFERFLUSHINTERVAL
TYK_GW_TRACER_OPTIONS_REPORTER_LOGSPANS
TYK_GW_TRACER_OPTIONS_REPORTER_LOCALAGENTHOSTPORT
TYK_GW_TRACER_OPTIONS_REPORTER_COLLECTORENDPOINT
TYK_GW_TRACER_OPTIONS_REPORTER_USER
TYK_GW_TRACER_OPTIONS_REPORTER_PASSWORD
TYK_GW_TRACER_OPTIONS_HEADERS_JAEGERDEBUGHEADER
TYK_GW_TRACER_OPTIONS_HEADERS_JAEGERBAGGAGEHEADER
TYK_GW_TRACER_OPTIONS_HEADERS_TRACECONTEXTHEADERNAME
TYK_GW_TRACER_OPTIONS_HEADERS_TRACEBAGGAGEHEADERPREFIX
TYK_GW_TRACER_OPTIONS_BAGGAGERESTRICTIONS_DENYBAGGAGEONINITIALIZATIONFAILURE
TYK_GW_TRACER_OPTIONS_BAGGAGERESTRICTIONS_HOSTPORT
TYK_GW_TRACER_OPTIONS_BAGGAGERESTRICTIONS_REFRESHINTERVAL
TYK_GW_TRACER_OPTIONS_THROTTLER_HOSTPORT
TYK_GW_TRACER_OPTIONS_THROTTLER_REFRESHINTERVAL
TYK_GW_TRACER_OPTIONS_THROTTLER_SYNCHRONOUSINITIALIZATION
```

## How This Has Been Tested

Provided with unit tests
```
go test ./config
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
nice!

**Comment by letzya** [comment]
Per discussion According to the rules https://tyk.io/docs/tyk-configuration-reference/environment-variables/ it should have been `TYK_GW_TRACING_OPTIONS_REPORTER_URL` but the actual env var is `TYK_GW_TRACER_OPTIONS_REPORTER_URL`

**Pull request merged**
