### PR TITLE
[TT-7488] Add TransformResponseBody schema for OAS APIs

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR adds OAS definition json schema for `transformResponseBody`.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5339/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5616872041)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5339/merge
Commit: 7002110bef8b7b63167ecfc732d039642d7c1a4c 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5616877145)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5339/merge
Commit: 180193ced4fbac317855f978e4c61b386a70f03e 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5620061082)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5339/merge
Commit: 6f317c57dd3ef5f8099188a107f1b38313c0ca27 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5620736938)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5339/merge
Commit: 5503a25a164bb254fa7e3fe802e60bd647566243 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5620734125)

**Pull request merged**
