### PR TITLE
Backport/virtual endpoints

### PR DESCRIPTION
**Pull request by titpetric**

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3572246474)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit: 3f1164b135481638f3dfa9d0d54548302d6f611b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3572276348)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit: e6d5d356f6e65cfabec70fa6204d19618c5b731f 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3572297944)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit: 7e799bba2ed67563a4565f016b7090d34f1f095e 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3572531298)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit: 5546e1b97ae01a721bd5ac8f84544e5a15747d29 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3572667833)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit: 28ac5384d4e9a4ed0f5e2cb534aedab8a61a2c66 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3572825968)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit: 8746db78a908c6946edd9de58b3a238a58a1653b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3572859221)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit: 62a017f7c637b1fdcf8ba1cdd43226e8e5ffbc3c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3573230201)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit: 6aac12ab2d3b364ef8ef8b89345c27c0c9c22b0c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3573390529)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4-lts
Commit: f4bd2bfe26e0249f32823e01256308228ce066e2 Fix goimports warnings (CI) (#4441)

Co-authored-by: Tit Petric <tit@tyk.io>
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3574374823)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/release-4-lts
Commit: a56811e5b9a0a9485aa40461f4bbfd264667a5b2 TT-1799 - prevent show full error to API response (#3743) (#4442)

Co-authored-by: Milan Vasic <milan.vasic.su@gmail.com>
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3574410171)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4434/merge
Commit: 50c1f77c43bdbbde51d9bd5a86cb7904b3af7ce6 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3574498365)

**Comment by titpetric** [comment]
Flaky: `        --- FAIL: TestRequestThrottling/PolicyLevel/SentinelRateLimiter (4.86s)`

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/release-4-lts
Commit: 79682820e06a60ccfc818a202942ddeeca8afa00 Fix middleware order, enabling virtual endpoint caching and cache control from jsvm (#4397) (#4434)
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3577359760)

**Pull request merged**
