### PR TITLE
[TT-7488/TT-9594]modify json schema to allow both body and path if provided

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description

This PR modifies json schema to allow both path and body if provided while creating a transform body (Request/Response) middleware.

## Related Issue
https://tyktech.atlassian.net/browse/TT-9594

## Screenshots (if appropriate)
screenshot after saving the middleware changes
Screenshot 2023-07-27 at 11 56 25 AM

Raw editor
Screenshot 2023-07-27 at 12 33 20 PM

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Review by lghiur — APPROVED** [review]

**Comment by furkansenharputlu** [comment]
Can you please explain why this is required?

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5367/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5677260178)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5367/merge
Commit: 3fa32a819f32d16ea268c5f94618d65566195d87 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5677466859)

**Review by furkansenharputlu — APPROVED** [review]

**Comment by furkansenharputlu** [comment]
LGTM

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5367/merge
Commit: 69e4853afa4fee0b0a0c9d23502f62923e289813 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5677699404)

**Pull request merged**
