### PR TITLE
relax "Stripping version from url" log level

### PR DESCRIPTION
**Pull request by candux**
this creates a lot of unnecessary log messages on a production server

### CODE REVIEW

**Review by furkansenharputlu — APPROVED** [review]

**Comment by furkansenharputlu** [comment]
Thanks for your contribution! We will merge this one.

**Comment by furkansenharputlu** [comment]
It will be released with the version `4.0.1`

**Review by vaske — APPROVED** [review]

**Review by buger — APPROVED** [review]

**Pull request merged**
