### PR TITLE
add configurations for new subscription protocols

### PR DESCRIPTION
**Pull request by pvormste**
This PR adds the possibility to configure 2 new types of subscriptions for GraphQL.

 1. `SSE`: Users can now use SSE for Tyk <-> Upstream connection
 2. `graphql-transport-ws`: The old `graphql-ws` has been deprecated and users can now use the new `graphql-transport-ws` protocol for WebSocket connections between Tyk <-> Upstream.

A new `subscription_type` field has been added to API definition for data source configurations in UDG/Federation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4351/merge
Commit:  
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3265389822)

**Review by Aenimus — APPROVED** [review]

**Review by buraksezer — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4351/merge
Commit: bbf7c14b58acd631c03067af0a3a16d67311194a 
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3279939461)

**Comment by pvormste** [comment]
merged manually to `release-4`

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 5a499161f3a4bcc34bb8ab278233801bcf3e9f1f add configurations for new subscription protocols (#4351)
Triggered by: push (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3280142280)

**Pull request merged**
