### PR TITLE
[TT-6659] Implement OAS schema extractor

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR implements the example extractor from OAS schemas when there is no `example` or `examples` provided in the response path.

### CODE REVIEW

**Review by lghiur — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4320/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3158613504)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4320/merge
Commit: 98dd9241a5e9260eb137fac6d4c7ffe15888a4f1 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3172453205)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: dd05dccf31d63a3037130c9bfc82ba39b78bd032 Implement OAS schema extractor (#4320)
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3172734946)

**Pull request merged**
