### PR TITLE
Allow the user to run the Control API on a different port

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Related to #354.

### CODE REVIEW

**Comment by buger** [comment]
Cool! Can you update PR description with steps on how to configure and test separate port?

**Comment by buger** [comment]
Do not forget that after merging we should update documentation.

**Comment by mvdan** [comment]
@matiasinsaurralde also please rebase onto master instead of merging master onto PR branches

**Comment by lonelycode** [comment]
Has this been tested with hot reload logic?

**Comment by buger** [comment]
Good point, linking #431

**Comment by matiasinsaurralde** [comment]
@lonelycode I was able to reproduce the issue (APIs not being loaded after reload), and after rewriting this part of `listen` it works fine.
@buger Will add the instructions now.

**Comment by matiasinsaurralde** [comment]
@mvdan Updated!

**Comment by lonelycode** [comment]
Lurvely

**Comment by matiasinsaurralde** [comment]
**Test instructions**

By default the control API will be exposed in the same IP/port the gateway is using. For example, to list the APIs:

```
curl -H 'x-tyk-authorization: 352d20ee67be67f6340b4c0605b044b7' http://localhost:8080/tyk/apis/
```

To configure a separate control API port you may set the `control_api_port` field in `tyk.conf`. If you set it to `7777`, you may try this command:

```
curl -H 'x-tyk-authorization: 352d20ee67be67f6340b4c0605b044b7' http://localhost:7777/tyk/apis/
```

It shouldn't be available in the gateway port anymore!

**Comment by ilijabojanovic** [comment]
@buger This is feature request? If is please add label and milestone

**Comment by buger** [comment]
@ilijabojanovic this is PR, label and milestone added to underlying issue mentioned in description.

**Comment by ilijabojanovic** [comment]
@buger thanks for clarification

**Comment by buger** [comment]
@ilijabojanovic ready for testing as well

@matiasinsaurralde can you resolve conflicts in meantime.

**Comment by buger** [comment]
@matiasinsaurralde some of this conflicts potentially dangerous (in main.go), so pls fix conflicts before it goes to QA.

**Comment by buger** [comment]
@matiasinsaurralde bump

**Comment by matiasinsaurralde** [comment]
@leon Updated!

**Comment by buger** [comment]
@ConsM pls update documentation about `control_api_port` flag.

**Comment by ilijabojanovic** [comment]
@buger verified and approved for merge

**Pull request merged**
