### PR TITLE
[TT-10405] Implement fallback to default for old versioning

### PR DESCRIPTION
**Pull request by furkansenharputlu**
Parent: https://tyktech.atlassian.net/browse/TT-9901
Ticket: https://tyktech.atlassian.net/browse/TT-10405

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5718/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6735437127)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5718/merge
Commit: db481b9d3e11a0ba0358e8799e5ce9059a48b481 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6743038865)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5718/merge
Commit: 84d437737c721f667861234c3eaf14485d445147 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6743087287)

**Pull request merged**
