### PR TITLE
[TT-13155] Ensure BaseMiddleware is a middleware scoped copy

### PR DESCRIPTION
**Pull request by titpetric**
This PR reverts https://github.com/TykTechnologies/tyk/pull/5914 for the most part.

It covers BaseMiddleware decisions/requirements in docs/arch/middleware.md

https://tyktech.atlassian.net/browse/TT-13155

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6094/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8142114199)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6094/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8142114199)

**Comment by titpetric** [comment]
@buger yep, there are a few options:

- attach it to the context (meaning, we'd need to pass a context everywhere if we wanted a logger/entry),
- generate an uuid and key the value to the uuid from a sync.Map or similar (same as context but different value key)
- note: how we log is questionable/fragmented, there are several global logger vars, Logger() interfaces, etc.

I'd have a preference to fix for correctness and safety, meaning pass along the values explicitly or in a way so they can remain request scoped (meaning, context value, idealy on stack). Would you consider a context logger (less explicit)?

**Comment by buger** [comment]
<p>:broken_heart: The detected issue is not in one of the allowed statuses :broken_heart: </p>    
   <table>
     <tr>
        <th>Detected Status</th>
        <td>In Refinement</td>
        <td>:x:</td>
     </tr>
     <tr>
        <th>Allowed Statuses</th>
        <td>In Dev,In Code Review,Ready for Testing,In Test,In Progress,In Review</td>
        <td>:heavy_check_mark:</td>
      </tr>
   </table>
   <p>Please ensure your jira story is in one of the allowed statuses</p>

**Comment by buger** [comment]
<p>:broken_heart: The detected issue is not in one of the allowed statuses :broken_heart: </p>    
   <table>
     <tr>
        <th>Detected Status</th>
        <td>In Refinement</td>
        <td>:x:</td>
     </tr>
     <tr>
        <th>Allowed Statuses</th>
        <td>In Dev,In Code Review,Ready for Testing,In Test,In Progress,In Review</td>
        <td>:heavy_check_mark:</td>
      </tr>
   </table>
   <p>Please ensure your jira story is in one of the allowed statuses</p>

**Comment by titpetric** [comment]
This PR drifted, but mainly wasn't applicable. A revert to the shallow-copy state does not present a full solution to the problem. There's some logging conventions to pin down in regards to handling requests, request ids, also considering plugins which could also use passed logging contexts.

**Pull request closed without merging**
