### PR TITLE
[TT-5935] Refactor load of apis from dashboard

### PR DESCRIPTION
**Pull request by furkansenharputlu**

### CODE REVIEW

**Review by jeffy-mathew — APPROVED** [review]

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4168/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2628342162)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4168/merge
Commit: 539a490ea9bcc13d1b1f8b9a0df62236e610342c 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2628345380)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/master
Commit: fdf14b9e01b243f2e7b95c7ee5c154da571f0517 Refactor load of apis from dashboard (#4168)
Triggered by: push (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2628427261)

**Pull request merged**
