### PR TITLE
[TD-1682] vMajor.Minor tags for cloudsmith

### PR DESCRIPTION
**Pull request by alephnull**
Add v{{ .Major }}.{{ .Minor }}{{.Prerelease}} convenience tag for cloudsmith.io

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4888/merge
Commit:  
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4487740063)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4888/merge
Commit: b6a963730a4c566ca3a25acebbd10b6762017bb2 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4497489500)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4888/merge
Commit: a431bf642d98defd70ac5e675a9c9a0debfbe522 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4497492221)

**Review by asutosh — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4888/merge
Commit: 66700bcbce39e3f6a42c6eea8444ca29df877ef2 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4944321442)

**Pull request merged**
