### PR TITLE
api: revert key update error to a 200

### PR DESCRIPTION
**Pull request by mvdan**
To unblock the policies and keys work and their testing, for now. We can
figure out the proper fix later, before 2.4 is out.

Updates #1050.

### CODE REVIEW

**Comment by lghiur** [comment]
@mvdan @buger  with this change, updating keys data works again

**Comment by buger** [comment]
I do not like merging it as a PR, maybe @lghiur can make this change locally in this own branch?

**Comment by lghiur** [comment]
@buger I personally don't need this change, but if this doesn't work then we can't release multiple policies issue as @ilijabojanovic won't be able to test it. This is the main concern. 

Otherwise @mvdan s changes on multiple policies are working from my perspective.

**Comment by mvdan** [comment]
I don't like it either, but I don't see the problem with reverting back to stable behavior on master as a temporary measure.

**Comment by buger** [comment]
It will not help @ilijabojanovic as well because this change does not fix the issue, just ignore it on UI.

If goal is to release this feature, the only way it to fix origin issue.

**Comment by mvdan** [comment]
You're technically right, which is why I opened the issue above. But in practice, stable works and this is a separate issue, so I was simply trying to unblock the other, larger issue.

I'm going to close this for now. I'll look at the regression again, but I'm not sure when we're going to be able to unblock multiple policies.

**Pull request closed without merging**
