### PR TITLE
CI tests cleanups and improvements [Otel]

### PR DESCRIPTION
**Pull request by titpetric**
PR does the following:

- Moves opentelemetry tests from root taskfile into /.taskfiles/opentelemetry.yml
- Moves CI opentelemetry tests into release-tests to reuse docker image built
- Updates to release-tests to reuse ECR details between jobs
- Update to opentelemetry docker compose to use injected `GATEWAY_IMAGE` env
- Create a reusable ecr-login composite action (deduplicate CI pipelines)

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7164778274)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: 76b5899897bd28191ff01fdee53cd66247e09ea8 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7164804305)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: 5ecab6d18b2c6fa0010d68599accfbf6151d5212 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7164889221)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: 5ecab6d18b2c6fa0010d68599accfbf6151d5212 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7164889306)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: 5ecab6d18b2c6fa0010d68599accfbf6151d5212 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7164889306)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: 5ecab6d18b2c6fa0010d68599accfbf6151d5212 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7164889306)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: d18ee3f4615ec87db8070bfdaf7855bf4588d1be 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7165594119)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: bdf533184dcfc90748115d86d67af30a3921a3ad 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7178814111)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: beeb964bcb67850ef5775cc1702dfc71eeb4f393 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7178833251)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: 76f663b9143ad031667565dbd0d4ec045b0c9095 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7179299754)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5857/merge
Commit: 132845fb2567f13bfb3999b7da871ddb82eda99c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7179530693)

**Review by tbuchaillot — APPROVED** [review]
🚀

**Pull request merged**
