### PR TITLE
[FIX] attempt to load go-plugins from non-versioned paths causes panic

### PR DESCRIPTION
**Pull request by patriziobruno**
## Description
Enable Tyk to load plugin bundles that contain plugins compatible with tyk-gateway <=v4.1

Let's say that my plugin name is `super-authorization-plugin`. The solution I devised is:
- build a plugin for v4.0.9 named `super-authorization-plugin.so`
- build a plugin for v4.2.4 named `super-authorization-plugin_v4.2.4_linux_amd64.so`
- put both plugins in the same bundle with a manifest that looks as follows:
  ```json
  {
    "file_list": [
      "super-authorization-plugin_v4.0.9_linux_amd64.so",
      "super-authorization-plugin.so"
    ],
    "custom_middleware": {
      "auth_check": {
        "name": "DojoTykEnvoyAuthorize",
        "path": "super-authorization-plugin.so"
      },
      "driver": "goplugin"
    }
  }
  ```
- **when tyk v4.0.9 tries to load the plugin, it will find `super-authorization-plugin.so` and load it correctly**
- **when tyk v4.2.4 tries to load the plugin, it will find `super-authorization-plugin_v4.0.9_linux_amd64.so` load it correctly**, if it doesn't find it, it'll fall-back to `super-authorization-plugin.so`

## Related Issue
#4447 

## Motivation and Context

Update gateways with a high number of api-definitions using go-plugins from v4.0.x to >=v4.1.x causes down time. Because v4.0 doesn't support bundles containing multiple versions of the same plugin built for different gateway versions, and >=v4.1 is not able to load the correct plugin when a bundle contains plugins compatible with v4.0.

## How This Has Been Tested
Installed tyk-hybrid-gateway using helm on a GKE cluster, changing the container image to one built from this PR.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by sredxny** [comment]
@patriziobruno thank you for your contribution. Indeed we already do that, and it behaves like:

go-plugin-different-tyk-versions

Currently we have an issue with responsePlugins (they're not working with the new naming convention) and we will work in that in our closer sprint, as well as reorganizing precedence of loading goplugins based on naming.

**Comment by patriziobruno** [comment]
> @patriziobruno thank you for your contribution. Indeed we already do that, and it behaves like:
> 
> go-plugin-different-tyk-versions
> 
> Currently we have an issue with responsePlugins (they're not working with the new naming convention) and we will work in that in our closer sprint, as well as reorganizing precedence of loading goplugins based on naming.

@sredxny thanks for getting back to me. I'm aware of the problems, but I probably explained it poorly. The problem is that versions >= 4.1 try to load the unversioned path first and often times end up `panic`king. If it tried to load the versioned path first, this wouldn't happen. Also, I'm using response plugins, and as you mentioned it's currently not supported. This PR addresses both problems and simplifies the plugin loading code.

**Comment by sredxny** [comment]
@patriziobruno ahhh now I understand. Well, good new: we will be working to fix that precedence in the current sprint.

**Comment by sredxny** [comment]
this has been implemented, tested and will be released in tyk v4.3.2.

**Comment by patriziobruno** [comment]
@sredxny thanks! Is a backport to 4.2 and 4.0 to be expected?

**Pull request closed without merging**
