### PR TITLE
[DX-1599] Update ports_whitelist config documentation

### PR DESCRIPTION
**Pull request by dcs3spp**
## Description

Update `ports_whitelist` based on customer feedback reported by @davegarvey. For further details please refer to the ticket below.

[DX-1599](https://tyktech.atlassian.net/browse/DX-1599)

This PR updates the description as follows:

```
    // Defines the ports that will be available for the API services to bind to in the format 
    // documented here https://tyk.io/docs/key-concepts/tcp-proxy/#allowing-specific-ports.
    // Ports can be configured per protocol, e.g. https, tls etc.
    // If configuring via environment variable `TYK_GW_PORTWHITELIST` then remember to escape
    // JSON strings.
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

[DX-1599]: https://tyktech.atlassian.net/browse/DX-1599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
Documentation

___

### **Description**
- Updated the documentation for the `ports_whitelist` configuration in `config/config.go`.
- Added details on configuring ports per protocol (e.g., https, tls).
- Included a note on escaping JSON strings when configuring via the `TYK_GW_PORTWHITELIST` environment variable.
- Provided a reference link to the relevant documentation on Tyk's website.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>config.go</strong><dd><code>Update `ports_whitelist` configuration documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

config/config.go

<li>Updated the documentation for <code>ports_whitelist</code> configuration.<br> <li> Added details on configuring ports per protocol.<br> <li> Included a note on escaping JSON strings when using environment <br>variables.<br> <li> Provided a reference link to the relevant documentation.<br>

</details>

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6454/files#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17">+5/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by davegarvey — APPROVED** [review]
Looks good to me. Though perhaps also worth getting approval from one of the other reviewers too.

**Review by lghiur — APPROVED** [review]

**Pull request merged**
