### PR TITLE
Devenv fix

### PR DESCRIPTION
**Pull request by joshblakeley**
If no connection was made while setting up the docker containers the response object was nil so it would panic. Quick fix by separating out the logic into an else-if.

### CODE REVIEW

**Comment by mvdan** [comment]
Nice find!

**Comment by mvdan** [comment]
You've added a dump file - please remove it.

**Comment by buger** [comment]
👍  Congratulations with the first contribution :)

**Comment by mvdan** [comment]
Also, I'm not sure I understand how this fix works. In the old code, we would use `resp.StatusCode` if and only if `err == nil`. And I'm fairly sure that `Client.Do` will only return nil responses when there is an error.

Are you certain you were running master? Could you show the panic message?

**Comment by buger** [comment]
Actually, good point, missed it. At least one argument resp or err should be non-nil..

**Comment by joshblakeley** [comment]
here's what I was getting:

tyk-gateway_1    | panic: runtime error: invalid memory address or nil pointer dereference
tyk-gateway_1    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb115cc]
tyk-gateway_1    |
tyk-gateway_1    | goroutine 1 [running]:
tyk-gateway_1    | main.(*HTTPDashboardHandler).Register(0xc42025a870, 0x0, 0x0)
tyk-gateway_1    |  /develop/go/src/github.com/TykTechnologies/tyk/dashboard_register.go:84 +0x10c
tyk-gateway_1    | main.handleDashboardRegistration()
tyk-gateway_1    |  /develop/go/src/github.com/TykTechnologies/tyk/main.go:1154 +0x1fa
tyk-gateway_1    | main.listen(0x127c520, 0xc420166020, 0x0, 0x0, 0x12708a0, 0xc4200160a0)
tyk-gateway_1    |  /develop/go/src/github.com/TykTechnologies/tyk/main.go:1202 +0x31b
tyk-gateway_1    | main.main()
tyk-gateway_1    |  /develop/go/src/github.com/TykTechnologies/tyk/main.go:967 +0x1fd
compose_tyk-gateway_1 exited with code 2

**Comment by mvdan** [comment]
Please add debug prints like:

```
fmt.Println(resp)
fmt.Println(err)
fmt.Println(resp.StatusCode)
```

Unfortunately the compiler doesn't use column numbers yet, so it's hard to tell exactly what in that line failed.

**Comment by joshblakeley** [comment]
The resp object is printing as nil so calling resp.StatusCode caused the panic.

**Comment by mvdan** [comment]
This is really weird. And `err` is not nil?

**Comment by joshblakeley** [comment]
Error is "Get http://tyk-dashboard:3000/register/node: dial tcp 172.19.0.6:3000: getsockopt: connection refused"

**Comment by mvdan** [comment]
Hang on, I misread. The issue is that we use `resp` in the body, not in the condition. You are absolutely right.

**Comment by mvdan** [comment]
Remove the dump file (an extra commit is fine) and I'll merge :)

**Comment by mvdan** [comment]
You also undid your other changes :)

**Comment by joshblakeley** [comment]
ah, yes. I until them while i did that debugging. (Idiot)

**Comment by mvdan** [comment]
Note that I squashed all your commits into one and used a better title than "devenv fix". You should try to do those things in the future. But it can always be fixed when merging on the github UI as I did, so it's not a big problem.

For the commits, you can probably find some guide by googling around. Most of the time, you'll want `git commit --amend` to update the last commit instead of creating a new one.

**Comment by joshblakeley** [comment]
Thanks Dan, appreciated!

**Pull request merged**
