### PR TITLE
Some more code simplifications

### PR DESCRIPTION
**Pull request by mvdan**
Also fix a potential bug with string handling.

### CODE REVIEW

**Comment by buger** [comment]
`createConnectionStringFromDashboardObject` function is a really good candidate for unit test. 
Not too complex and without side effects.

**Comment by mvdan** [comment]
@buger you mean it should stick around?

Ping @lonelycode in case any of these were left unused on purpose.

**Comment by buger** [comment]
I mean you should write unit test if you think there is potential bug in it.

**Comment by mvdan** [comment]
Ah, I assumed you meant a function I was removing.

As far as I can tell none of this redis stuff has independent unit tests (no `redis_*_test.go` files) and I'd rather not add yet another file to the root dir. Not sure it's the thing to do right now.

**Comment by lonelycode** [comment]
> Ping @lonelycode in case any of these were left unused on purpose.

They may have been part of old tests that are no longer part of the codebase. 

`createConnectionStringFromDashboardObject` looks like a simple change, no bugfix, just variable renaming so not sure if it needs a unit test just yet ;-)

**Pull request merged**
