### PR TITLE
Add error checking to URL parsing in URLRewriteMiddleware.CheckHostRewrite

### LINKED ISSUE #3326: Panics from unchecked URL parsing errors inside URLRewriteMiddleware.CheckHostRewrite
**Branch/Environment/Version**
- Branch/Version: `v3.0.1`
- Environment: Tyk Cloud (Ara)

**Describe the bug**
Tyk Cloud is reporting panics from `tykio/tyk-gateway:v3.0.1` containers with the following lines in the stack trace:

```log
Sep 21, 2020 @ 19:29:27.294	github.com/TykTechnologies/tyk/gateway.(*URLRewriteMiddleware).CheckHostRewrite(0xc0001732c0, 0xc00018e000, 0x1, 0xc0003da640, 0x44, 0xc00011ea00)
Sep 21, 2020 @ 19:29:27.294		/go/src/github.com/TykTechnologies/tyk/gateway/mw_url_rewrite.go:438 +0x60
```

These lines are as follows:

```go
	oldAsURL, _ := url.Parse(oldPath)
	newAsURL, _ := url.Parse(newTarget)
	if newAsURL.Scheme != LoopScheme && oldAsURL.Host != newAsURL.Host {
```

Any parsing error inside either of the `url.Parse` calls will return a `nil` which, when referenced directly without checking the returned errors, are causing the panics.

**Reproduction steps**
Send some unparseable/malformed URLs through this middleware.

**Actual behavior**
Panics as described above.

**Expected behavior**
Errors should be handled and not ignored.

**Screenshots/Video**

**Logs (debug mode or log file):**
See above.

**Configuration (tyk config file):**

**Additional context**

### PR DESCRIPTION
**Pull request by jlucktay**
## Description

Added error checking where there was none.

## Related Issue

Fixes #3326.

## Motivation and Context

Spurred by panics reported by some gateways running on Ara.
Not checking error returns is bad form.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [x] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Review by adelowo — APPROVED** [review]

**Comment by christtyk** [comment]
@jlucktay do we need to merge this one?

**Comment by jlucktay** [comment]
> @jlucktay do we need to merge this one?

Yes please 🙏

**Review by buger — APPROVED** [review]
Looks good!

**Review by furkansenharputlu — APPROVED** [review]

**Pull request merged**
