### PR TITLE
[TT-2161] make apiDefinition accessible to go response plugins

### PR DESCRIPTION
**Pull request by rshlin**
## Description
For now there's no way to access API Spec or API Definition in native response hooks.
This PR solves it by adding API Definition into request context before the native plugin is invoked.

## How This Has Been Tested

Unit tests included.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [x] `go fmt -s`
  - [x] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
Nice! Looks solid! 

Will forward to our product team, so we can schedule it.

**Comment by joshblakeley** [comment]
Thanks a lot for this @rshlin I managed to overlook this part when adding the response hooks!

**Comment by gregdelhon** [comment]
nice one, thanks @rshlin !

**Pull request merged**
