### PR TITLE
[TT-7458] Do not check some actions after merge again redundantly

### PR DESCRIPTION
**Pull request by furkansenharputlu**
Just a trial to get rid of some redundant checks after merged PR.

### CODE REVIEW

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4600/merge
Commit: a2d9874b6dc39ab245d4eb12a06be854b7e9a855 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3800076862)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4600/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3800004445)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4600/merge
Commit: acd25917d8ce77ab297fddce5c58d1ad5ebabe23 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3800089527)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4600/merge
Commit: 5f75b8e40f0ddcc2bf724b9254c65ebf4395ee2b 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3800090511)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4600/merge
Commit: 6899b19cdb674c4bdaa78b19e64c21df18936fc9 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3800266688)

**Comment by furkansenharputlu** [comment]
Manually merged to `release-4`

**Pull request merged**
