### PR TITLE
[CI] Sync automation: Syncing commits from master

### PR DESCRIPTION
**Pull request by Tyk-ITS**
PR auto generated by the CI Sync automation.
          Picks the CI changes from the commit 2fb70cca9caed191e202ba686ad202b2987dde5d
          on master.
          Please make any additional changes required before
          merging.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4681/merge
Commit:  
Triggered by: pull_request (@Tyk-ITS)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3989289628)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4681/merge
Commit: dabe8e4d78f15cadb376624f564310b9ee851d43 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4022034430)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4681/merge
Commit: 8d66d7dd57f6517450f9776148d0e9103d39c3a7 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4022032258)

**Comment by alephnull** [comment]
This is not needed.

**Pull request closed without merging**
