### PR TITLE
[TT-5121] modify X-Tyk-Operations to have patternProperties for key

### PR DESCRIPTION
**Pull request by jeffy-mathew**
[changelog]
fixed: modify X-Tyk-Operations to have patternProperties in key

## Description
here, the schema is not validated while API CRUD operations are made, even though validation is enabled.
eg, enabled flag is required in validateRequest
or errorResponseCode must be an integer etc.
Upon checking the schema definition for object `X-Tyk-ValidateRequest` itself is fine.
however in `X-Tyk-ApiGateway` object in our code, it has `Operations` as a `type Operations map[string]*Operation` .
To accommodate  this, we must have the string path as a pattern properties, to have the key - value relations represented in JSON schema.
However, currently it is just additional properties, which misses out the key-value relationship.

Also disable additional properties so that non paths keys are added

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4013/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2195395446)

**Review by titpetric — APPROVED** [review]

**Review by urbanishimwe — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4013/merge
Commit: 4900d7a1208c05d3251845e4d3a1692a5c6033c8 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2195943051)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 58bd9bf2d6c90607796e935bf47c1d1495f630a9 [TT-5121] modify X-Tyk-Operations to have patternProperties for key (#4013)

* modify X-Tyk-Operations to have patternProperties for key
* disable additional properties for X-Tyk-Operations.

[changelog]
fixed: modify X-Tyk-Operations to have patternProperties in key
added: disable additional properties for X-Tyk-Operations.
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2197835291)

**Pull request merged**
