### PR TITLE
Adds a setting for skipping SSL verification, it's disabled by default.

### LINKED ISSUE #693: Allow endpoints with insecure SSL certificates
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Currently, Tyk can't send a request to API endpoints with self-signed certificates.
**What is the expected behavior?**
Add option which skips verification for self-signed certificates
**Which versions of Tyk affected by this issue? Did this work in previous versions of Tyk?**
All

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
Fixes #693.

### CODE REVIEW

**Comment by buger** [comment]
I made an issue while creating this task, and actually confused you a bit. 

The real goal of this functionality is to allow Tyk query https endpoints with self-signed certificates. Currently it shows `http: proxy error: x509: certificate is valid for ...` error.  So instead of allowing insecureSSL for Tyk API, we should disable SSL checks for our reverse proxy.

```go
    tr := &http.Transport{
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }
    client := &http.Client{Transport: tr}
    _, err := client.Get("https://golang.org/")
    if err != nil {
        fmt.Println(err)
    }
```

**Comment by mvdan** [comment]
I was also confused by the original issue - I thought it was about setting up the gateway to listen on HTTPS with an insecure cert.

Could this PR still be useful, separately?

**Comment by buger** [comment]
Yeah, I think we can leave this option in `http_server_option` group, but a new one should be added to the different section.

**Comment by mvdan** [comment]
Removed from the milestone since I assume we won't backport this.

Should we wait until QA tests this before merging?

**Comment by buger** [comment]
Well, if @matiasinsaurralde can do this task this week, it can be included into 2.3.5. 

Recent merge of X.3.5 branches was made to start testing what we already have, and rest of the tasks will be backported if we will have time and bandwith.

**Comment by matiasinsaurralde** [comment]
@buger Looks simple, will have it on my list

**Comment by matiasinsaurralde** [comment]
Updated!

**Comment by buger** [comment]
@ilijabojanovic ready for testing

**Comment by ilijabojanovic** [comment]
During testing this PR i found issue.

Reproduction steps:
1. Add new option in tyk gateway configuration (proxy_ssl_insecure_skip_verify:true)
2. Create new api definition with target url which have self signed cert 
3. Over post-man try to get api definition 

In console we have this error:
 ```
tyk-gateway_1    | time="May  8 21:03:45" level=debug msg="Outbound Request: https://self-signed.badssl.com/"
tyk-gateway_1    | time="May  8 21:03:45" level=error msg="http: proxy error: x509: certificate signed by unknown authority" api_id=c9b6fa404f164d4267723eb8237e8fb2 org_id=5910d6c5714d08026acfafe2 server_name=self-signed.badssl.com user_id= user_ip=172.18.0.1 user_name=

[23:04] 
tyk-gateway_1    | time=“May  8 21:03:45” level=debug msg=“Outbound Request: https://self-signed.badssl.com/”
tyk-gateway_1    | time=“May  8 21:03:45” level=error msg=“http: proxy error: x509: certificate signed by unknown authority” api_id=c9b6fa404f164d4267723eb8237e8fb2 org_id=5910d6c5714d08026acfafe2 server_name=self-signed.badssl.com user_id= user_ip=172.18.0.1 user_name=
```

Here is api definition:
```
{
    "id": "5910d6f3714d08026acfafe6",
    "name": "test",
    "slug": "test",
    "api_id": "c9b6fa404f164d4267723eb8237e8fb2",
    "org_id": "5910d6c5714d08026acfafe2",
    "use_keyless": true,
    "use_oauth2": false,
    "use_openid": false,
    "openid_options": {
        "providers": [],
        "segregate_by_client": false
    },
    "oauth_meta": {
        "allowed_access_types": [],
        "allowed_authorize_types": [],
        "auth_login_redirect": ""
    },
    "auth": {
        "use_param": false,
        "param_name": "",
        "use_cookie": false,
        "cookie_name": "",
        "auth_header_name": ""
    },
    "use_basic_auth": false,
    "enable_jwt": false,
    "use_standard_auth": false,
    "enable_coprocess_auth": false,
    "jwt_signing_method": "",
    "jwt_source": "",
    "jwt_identity_base_field": "",
    "jwt_client_base_field": "",
    "jwt_policy_field_name": "",
    "notifications": {
        "shared_secret": "",
        "oauth_on_keychange_url": ""
    },
    "enable_signature_checking": false,
    "hmac_allowed_clock_skew": -1,
    "base_identity_provided_by": "",
    "definition": {
        "location": "header",
        "key": "x-api-version"
    },
    "version_data": {
        "not_versioned": true,
        "versions": {
            "Default": {
                "name": "Default",
                "expires": "",
                "paths": {
                    "ignored": [],
                    "white_list": [],
                    "black_list": []
                },
                "use_extended_paths": true,
                "extended_paths": {},
                "global_headers": {},
                "global_headers_remove": [],
                "global_size_limit": 0,
                "override_target": ""
            }
        }
    },
    "uptime_tests": {
        "check_list": [],
        "config": {
            "expire_utime_after": 0,
            "service_discovery": {
                "use_discovery_service": false,
                "query_endpoint": "",
                "use_nested_query": false,
                "parent_data_path": "",
                "data_path": "",
                "port_data_path": "",
                "target_path": "",
                "use_target_list": false,
                "cache_timeout": 60,
                "endpoint_returns_list": false
            },
            "recheck_wait": 0
        }
    },
    "proxy": {
        "preserve_host_header": false,
        "listen_path": "/test/",
        "target_url": "https://self-signed.badssl.com/",
        "strip_listen_path": true,
        "enable_load_balancing": false,
        "target_list": [],
        "check_host_against_uptime_tests": false,
        "service_discovery": {
            "use_discovery_service": false,
            "query_endpoint": "",
            "use_nested_query": false,
            "parent_data_path": "",
            "data_path": "hostname",
            "port_data_path": "port",
            "target_path": "/api-slug",
            "use_target_list": false,
            "cache_timeout": 60,
            "endpoint_returns_list": false
        }
    },
    "disable_rate_limit": false,
    "disable_quota": false,
    "custom_middleware": {
        "pre": [],
        "post": [],
        "post_key_auth": [],
        "auth_check": {
            "name": "",
            "path": "",
            "require_session": false
        },
        "response": [],
        "driver": "",
        "id_extractor": {
            "extract_from": "",
            "extract_with": "",
            "extractor_config": {}
        }
    },
    "custom_middleware_bundle": "",
    "cache_options": {
        "cache_timeout": 60,
        "enable_cache": true,
        "cache_all_safe_requests": false,
        "cache_response_codes": [],
        "enable_upstream_cache_control": false
    },
    "session_lifetime": 0,
    "active": true,
    "auth_provider": {
        "name": "",
        "storage_engine": "",
        "meta": {}
    },
    "session_provider": {
        "name": "",
        "storage_engine": "",
        "meta": null
    },
    "event_handlers": {
        "events": {}
    },
    "enable_batch_request_support": false,
    "enable_ip_whitelisting": false,
    "allowed_ips": [],
    "dont_set_quota_on_create": false,
    "expire_analytics_after": 0,
    "response_processors": [],
    "CORS": {
        "enable": false,
        "allowed_origins": [],
        "allowed_methods": [],
        "allowed_headers": [],
        "exposed_headers": [],
        "allow_credentials": false,
        "max_age": 24,
        "options_passthrough": false,
        "debug": false
    },
    "domain": "",
    "do_not_track": false,
    "tags": [],
    "enable_context_vars": false
}
```

Note: This issue is visible on protected and non-proteceted api definitions

**Comment by buger** [comment]
@ilijabojanovic 
> Over post-man try to get api definition
Can you clarify this step? You mean calling `/tyk/apis` endpoint?

**Comment by buger** [comment]
It is possible to test this functionality using `httptest.NewTLSServer`

**Comment by ilijabojanovic** [comment]
@buger 
No i mean generate proxy request e.g. http://{gateway}/{api_definition}

**Comment by matiasinsaurralde** [comment]
@ilijabojanovic 
The configuration wasn't loaded/ready yet when setting `TykDefaultTransport`, moving this to `GetDefaultTransport` fixed it.

Setting `proxy_ssl_insecure_skip_verify` to `true` will ignore invalid certificates for the TLS connection to upstream APIs, this is a global setting inside `tyk.conf`.

The other option that's covered by this PR is `ssl_insecure_skip_verify`, which is inside `http_server_options`, this involves the HTTP listener: loading an invalid certificate to Tyk itself!

**Comment by ilijabojanovic** [comment]
I tested this PR with bad certs found on this site:
https://badssl.com/

Everything working as expected

**Comment by matiasinsaurralde** [comment]
@ilijabojanovic Nice, that website is very useful

**Pull request merged**
