### PR TITLE
[TT-11413] Fix apidef GlobalRateLimit migrations

### PR DESCRIPTION
**Pull request by titpetric**
## **Type**
bug_fix, enhancement

___

## **Description**
- Added a `Disabled` boolean field to the `GlobalRateLimit` struct to explicitly enable or disable global rate limits.
- Modified migration logic to consider the new `Disabled` flag, setting it to true if either `Per` or `Rate` is less or equal to 0.
- Updated existing tests and added new ones to cover the changes in global rate limit logic.
- Adjusted OpenAPI Specification (OAS) related code to utilize the new `Disabled` flag for rate limiting.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>api_definitions.go</strong><dd><code>Add Disabled Flag to GlobalRateLimit Struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/api_definitions.go
<li>Added <code>Disabled</code> field to <code>GlobalRateLimit</code> struct.<br> <li> This change allows for explicit disabling of global rate limits.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-9961ccc89a48d32db5b47ba3006315ef52f6e5007fb4b09f8c5d6d299c669d67">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>migration.go</strong><dd><code>Enhance GlobalRateLimit Migration Logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/migration.go
<li>Modified condition to disable global rate limit based on new <code>Disabled</code> <br>flag.<br> <li> Adjusted logic to set <code>GlobalRateLimit.Disabled</code> true if <code>Per</code> or <code>Rate</code> is <br>less or equal to 0.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-e1d9b55a26f9d6225d56d6f0161959217308e5ad4d6934e7d7df4595d9c2a130">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>upstream.go</strong><dd><code>Use GlobalRateLimit Disabled Flag in RateLimit Struct</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/oas/upstream.go
<li>Updated <code>RateLimit</code> struct methods to use <code>GlobalRateLimit.Disabled</code> for <br>enabling/disabling rate limits.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-7b0941c7f37fe5a2a23047e0822a65519ca11c371660f36555b59a60f000e3f4">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>migration_test.go</strong><dd><code>Update Tests for GlobalRateLimit Migration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/migration_test.go
<li>Updated tests to reflect new <code>Disabled</code> flag logic in global rate limit.<br> <li> Added test cases for various scenarios of <code>Per</code> and <code>Rate</code> values.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-d79d77f814074b9e483554e36687e22fda759045141c3b094b039428744ff94c">+26/-3</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>oas_test.go</strong><dd><code>Initialize GlobalRateLimit Disabled in Tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apidef/oas/oas_test.go
- Initialized `GlobalRateLimit.Disabled` to false in test setup.

</details>
    

  </td>
  <td><a href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-74029ee88132d30d6478c96a35f8bb2200e0c8e6f42f2c9b147dc6bb7ce74644">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6086/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8110001005)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 5e0b679a564d1b0b1a517aae4894063782bae838 [TT-11413] Fix apidef GlobalRateLimit migrations (#6086)

## **Type**
bug_fix, enhancement


___

## **Description**
- Added a `Disabled` boolean field to the `GlobalRateLimit` struct to
explicitly enable or disable global rate limits.
- Modified migration logic to consider the new `Disabled` flag, setting
it to true if either `Per` or `Rate` is less or equal to 0.
- Updated existing tests and added new ones to cover the changes in
global rate limit logic.
- Adjusted OpenAPI Specification (OAS) related code to utilize the new
`Disabled` flag for rate limiting.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>api_definitions.go</strong><dd><code>Add Disabled Flag
to GlobalRateLimit Struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

apidef/api_definitions.go
<li>Added <code>Disabled</code> field to <code>GlobalRateLimit</code>
struct.<br> <li> This change allows for explicit disabling of global
rate limits.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-9961ccc89a48d32db5b47ba3006315ef52f6e5007fb4b09f8c5d6d299c669d67">+3/-2</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>migration.go</strong><dd><code>Enhance GlobalRateLimit
Migration Logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; </dd></summary>
<hr>

apidef/migration.go
<li>Modified condition to disable global rate limit based on new
<code>Disabled</code> <br>flag.<br> <li> Adjusted logic to set
<code>GlobalRateLimit.Disabled</code> true if <code>Per</code> or
<code>Rate</code> is <br>less or equal to 0.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-e1d9b55a26f9d6225d56d6f0161959217308e5ad4d6934e7d7df4595d9c2a130">+4/-4</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>upstream.go</strong><dd><code>Use GlobalRateLimit
Disabled Flag in RateLimit Struct</code>&nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

apidef/oas/upstream.go
<li>Updated <code>RateLimit</code> struct methods to use
<code>GlobalRateLimit.Disabled</code> for <br>enabling/disabling rate
limits.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-7b0941c7f37fe5a2a23047e0822a65519ca11c371660f36555b59a60f000e3f4">+2/-2</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>migration_test.go</strong><dd><code>Update Tests for
GlobalRateLimit Migration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

apidef/migration_test.go
<li>Updated tests to reflect new <code>Disabled</code> flag logic in
global rate limit.<br> <li> Added test cases for various scenarios of
<code>Per</code> and <code>Rate</code> values.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-d79d77f814074b9e483554e36687e22fda759045141c3b094b039428744ff94c">+26/-3</a>&nbsp;
&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>oas_test.go</strong><dd><code>Initialize
GlobalRateLimit Disabled in Tests</code>&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

apidef/oas/oas_test.go
- Initialized `GlobalRateLimit.Disabled` to false in test setup.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-74029ee88132d30d6478c96a35f8bb2200e0c8e6f42f2c9b147dc6bb7ce74644">+1/-0</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions

---------

Co-authored-by: Tit Petric <tit@tyk.io>
Triggered by: push (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8169581030)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 5e0b679a564d1b0b1a517aae4894063782bae838 [TT-11413] Fix apidef GlobalRateLimit migrations (#6086)

## **Type**
bug_fix, enhancement


___

## **Description**
- Added a `Disabled` boolean field to the `GlobalRateLimit` struct to
explicitly enable or disable global rate limits.
- Modified migration logic to consider the new `Disabled` flag, setting
it to true if either `Per` or `Rate` is less or equal to 0.
- Updated existing tests and added new ones to cover the changes in
global rate limit logic.
- Adjusted OpenAPI Specification (OAS) related code to utilize the new
`Disabled` flag for rate limiting.


___



## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant
files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>api_definitions.go</strong><dd><code>Add Disabled Flag
to GlobalRateLimit Struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

apidef/api_definitions.go
<li>Added <code>Disabled</code> field to <code>GlobalRateLimit</code>
struct.<br> <li> This change allows for explicit disabling of global
rate limits.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-9961ccc89a48d32db5b47ba3006315ef52f6e5007fb4b09f8c5d6d299c669d67">+3/-2</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>migration.go</strong><dd><code>Enhance GlobalRateLimit
Migration Logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; </dd></summary>
<hr>

apidef/migration.go
<li>Modified condition to disable global rate limit based on new
<code>Disabled</code> <br>flag.<br> <li> Adjusted logic to set
<code>GlobalRateLimit.Disabled</code> true if <code>Per</code> or
<code>Rate</code> is <br>less or equal to 0.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-e1d9b55a26f9d6225d56d6f0161959217308e5ad4d6934e7d7df4595d9c2a130">+4/-4</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>upstream.go</strong><dd><code>Use GlobalRateLimit
Disabled Flag in RateLimit Struct</code>&nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

apidef/oas/upstream.go
<li>Updated <code>RateLimit</code> struct methods to use
<code>GlobalRateLimit.Disabled</code> for <br>enabling/disabling rate
limits.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-7b0941c7f37fe5a2a23047e0822a65519ca11c371660f36555b59a60f000e3f4">+2/-2</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
<summary><strong>migration_test.go</strong><dd><code>Update Tests for
GlobalRateLimit Migration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

apidef/migration_test.go
<li>Updated tests to reflect new <code>Disabled</code> flag logic in
global rate limit.<br> <li> Added test cases for various scenarios of
<code>Per</code> and <code>Rate</code> values.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-d79d77f814074b9e483554e36687e22fda759045141c3b094b039428744ff94c">+26/-3</a>&nbsp;
&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
<summary><strong>oas_test.go</strong><dd><code>Initialize
GlobalRateLimit Disabled in Tests</code>&nbsp; &nbsp; &nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
</dd></summary>
<hr>

apidef/oas/oas_test.go
- Initialized `GlobalRateLimit.Disabled` to false in test setup.


</details>
    

  </td>
<td><a
href="https://github.com/TykTechnologies/tyk/pull/6086/files#diff-74029ee88132d30d6478c96a35f8bb2200e0c8e6f42f2c9b147dc6bb7ce74644">+1/-0</a>&nbsp;
&nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools
and their descriptions

---------

Co-authored-by: Tit Petric <tit@tyk.io>
Triggered by: push (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/8169581030)

**Pull request merged**
