### PR TITLE
change OAS AddServers signature to return error.

### PR DESCRIPTION
**Pull request by jeffy-mathew**
[changelog]
changed: OAS AddServers.

### CODE REVIEW

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4375/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3360743469)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4375/merge
Commit: 08777a42b2d047bee5f9515182a60d348dde25e9 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3360885127)

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/heads/master
Commit: 501e860523888b88c2ac3f4669e7377aa7f7b149 change OAS AddServers signature to return error. (#4375)

[changelog]
changed: OAS AddServers.
Triggered by: push (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3361163132)

**Pull request merged**
