### PR TITLE
TT-7759 Fix persistent queries 

### PR DESCRIPTION
**Pull request by zalbiraw**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4717/merge
Commit:  
Triggered by: pull_request (@zalbiraw)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4049124432)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4717/merge
Commit: 08329e8e7cc77f01e96f94688e6ce9328680893e 
Triggered by: pull_request (@zalbiraw)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4049967378)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4717/merge
Commit: 269a6845d5024e16b24e4c6e1e0eec618b7b29b6 
Triggered by: pull_request (@zalbiraw)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4050498778)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4717/merge
Commit: df441b40cec45f3ada592c18c50aaf28488b285f 
Triggered by: pull_request (@zalbiraw)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4050581327)

**Comment by buger** [comment]
How it actually fix the issue? Why it forces response path to "/"?

**Review by kofoworola — DISMISSED** [review]

**Comment by zalbiraw** [comment]
@buger the issue is that when want to reverse proxy to a graphql API we need to remove the trailing path. Since the persistent queries have to live on a path, that path gets added to the proxied request. So if the customer is only serving their graphql endpoint on `/` any other path will be rejected. 

For example:

You create a Tyk API with the `/hello-world` listen path and `mygql.com/graphql` as a host.
Then you add a path in the endpoint designer that is `/hello`

The request to `gateway/hello-world/hello` will be translated to `mygql.com/graphql/hello` instead of just `mygql.com/graphql`.

Setting the `URL.Path` value to "/" will fix the issue because you will never need to hit a specific endpoint on a graphql API. But if you do then you just need to modify the target url to include whatever you want to include

**Review by kofoworola — APPROVED** [review]

**Comment by kofoworola** [comment]
Some checks are failing but thank you for posting!

**Comment by zalbiraw** [comment]
np!

**Review by pvormste — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4717/merge
Commit: a77df9722d0eea628c0e8ead9ac34546969fb4d6 
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4125794731)

**Pull request merged**
