### PR TITLE
[TT-7121] Bump fasthttp dependency

### PR DESCRIPTION
**Pull request by titpetric**
## Description

Bump test dependency valyala/fasthttp to latest, run komuw/ote to group test dependencies in go mod.

Original only bumped to 1.34, while a newer version exists.

## Related Issue

https://tyktech.atlassian.net/browse/TT-7121

Closes #4411 #3949 

## Motivation and Context

Resolve CVE security report for the dependency.

## How This Has Been Tested

`go test -run=TestBatch -count=1 -v .` (pass)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4502/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3646576281)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4502/merge
Commit: e53e8101bcf080b400dbf908cd3b61ad1cd0c31a 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3649004291)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4502/merge
Commit: 32f776e7e4efe19c421f6aca9ec1217b20f3f9d6 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3651498229)

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 131a184aa1c2f073298848f995c508d67a70444a [TT-7121] Bump fasthttp dependency (#4502)



## Description


Bump test dependency valyala/fasthttp to latest, run komuw/ote to group
test dependencies in go mod.

Original only bumped to 1.34, while a newer version exists.

## Related Issue






https://tyktech.atlassian.net/browse/TT-7121

Closes #4411 #3949 

## Motivation and Context


Resolve CVE security report for the dependency.

## How This Has Been Tested






`go test -run=TestBatch -count=1 -v .` (pass)

## Screenshots (if appropriate)

## Types of changes



- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist





- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why

Co-authored-by: chncaption <101684156+chncaption@users.noreply.github.com>
Co-authored-by: Tit Petric <tit@tyk.io>
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3651646817)

**Pull request merged**
