### PR TITLE
Test to check sbom generation

### PR DESCRIPTION
**Pull request by buger**
This PR fixes a bug on the tags pushed for CI images and also adds a new tag that includes the FULL sha which is used by sbom.

>             type=ref,event=branch
>             type=ref,event=pr
>             type=sha
>             type=sha,format=long,prefix=        <---- NEW
>             type=semver,pattern=v{{major}}.{{minor}}
>             type=semver,pattern=v{{version}}

There was a bug on the workflow bash script that was preventing from push all the tags contained on ${{ steps.metadata.outputs.tags }}. Only the first tag inside the variable was being pushed and the for loop got cut prematurely, now every tag goes through as intended

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5591/merge
Commit:  
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6418563533)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5591/merge
Commit: 2ec0055c28a08231fe15df5f84f96cb13f20bc22 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6421467059)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5591/merge
Commit: 62238b10b8dce49a90adff1bb27c5cb46ccacc3d 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6421655883)

**Comment by ermirizio** [comment]
CC @buger is fixed now

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5591/merge
Commit: 6a99289a1bde94f595336d6f5b9afada6e4c016f 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6422365967)

**Pull request merged**
