### PR TITLE
[TT-10181] Fix error message when trying to use classic enpoint for OAS API

### PR DESCRIPTION
**Pull request by furkansenharputlu**
Ticket: https://tyktech.atlassian.net/browse/TT-10181

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5764/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6822353814)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5764/merge
Commit: 9443dd3a7c67f9996e7d009edeca0da3eb3a9903 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6957161593)

**Pull request merged**
