### PR TITLE
[TT-10286] plugin compiler local tests

### PR DESCRIPTION
**Pull request by titpetric**
This PR extends the local test capabilities of `ci/tests/plugin-compiler`.

It adds a Taskfile.yml to test locally. See README.md for instructions.

It moves the test plugins into `testdata/` to be excluded by go tooling when doing builds.

### CODE REVIEW

**Comment by titpetric** [comment]
Smoke tests pass, api-tests failure seems unrelated to PR

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5635/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6557939099)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5635/merge
Commit: 1a08cd6362c06770b3fd4030451d345cf7b38050 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6558261845)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5635/merge
Commit: 9b141a09edc26e259c4bd469549e69fa51f96b26 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6559383725)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5635/merge
Commit: fcaa9d7529dc08cdb96ae33e5dd1173e0bc5f20e 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6559560245)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5635/merge
Commit: d8ccb8a5bfe5ee6140665f844d6cbf3aa2571e49 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6559652997)

**Pull request merged**
