### PR TITLE
Some more cleanups, remove commented out code

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
Coveralls isn't happy because a lot of the now shorter code was covered. Shouldn't matter.

**Comment by mvdan** [comment]
Out of curiosity, why was this squashed? If you wanted me to squash, I could have done it myself.

**Comment by buger** [comment]
Most likely by accident. Github remembers your choice when you are merging using UI button.

**Comment by mvdan** [comment]
Ah right, no problem :)

**Pull request merged**
