### PR TITLE
[TT-9551] Fix scope issues

### PR DESCRIPTION
**Pull request by titpetric**
## Description

This addresses a few scope / compilation issues.

- It removes a deprecated https://pkg.go.dev/golang.org/x/net/context
- It aliases use of stdlib apis via internal packages (1 import from gw package, no fragmentation)
- The `coprocess_api.go` imports C, put it behind a `cgo` build tag
- Aliases use of `text/template` and `html/template` (scope differentiation, within the package scope both of those are named `template`, aliasing makes code non-conflicting on itself).
- Fixes a test case to pass sonarcloud (asserting error return in test)

The deprecated context package is coming from the msgpack.v2 dependency (go mod why). Investigate bumping the dependency, or replacing it with an up to date one (out of scope).

## Related Issue
https://tyktech.atlassian.net/browse/TT-9551

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [x] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5343/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5632499579)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5343/merge
Commit: 5d22c1635d40656bed5b8d1a9564bc236fecb19c 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5632512106)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5343/merge
Commit: 5c7e465cce1b526ad9e9ca242cd3117fc315b63b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5632566460)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5343/merge
Commit: b236c7ffc0e59993fe244ccc65839e204a4271c4 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5632655569)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5343/merge
Commit: 6327fd76a049edbbb0f30381424082a47f8bc439 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5632687384)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5343/merge
Commit: 67baf32d8082686ccbfcd74a22d1a4b5f151f3fb 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5641502905)

**Review by jeffy-mathew — APPROVED** [review]

**Pull request closed without merging**
