### PR TITLE
fix non-working single flight

### PR DESCRIPTION
**Pull request by pvormste**
This PR fixes an issue with single flight requests mainly in UDG.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

### CODE REVIEW

**Review by buraksezer — APPROVED** [review]

**Review by Aenimus — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4402/merge
Commit:  
Triggered by: pull_request (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3444883269)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: f2961054dc7e7e8729ad4599337377b09e75791b fix non-working single flight (#4402)
Triggered by: push (@pvormste)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3444951119)

**Pull request merged**
