### PR TITLE
[TT-8711] Fix upstream mTLS when protocol=tcp/tls

### PR DESCRIPTION
**Pull request by furkansenharputlu**
This PR adds the missing upstream certificate configuration for tcp/tls APIs.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5033/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5031287088)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5033/merge
Commit: f2cda3d6517902fd315cde09b5922bce4006f983 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5033773164)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5033/merge
Commit: 7c9abb17ee4e2c7628907c4354f985fa66019c26 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5033749214)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5033/merge
Commit: 3c02156627b1c553a67c9e8914098752dd5d2c5d 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5033791422)

**Review by titpetric — APPROVED** [review]

**Pull request merged**
