### PR TITLE
[TT-7362] Fix validate JSON middleware not loading in worker gateway.

### PR DESCRIPTION
**Pull request by jeffy-mathew**
https://tyktech.atlassian.net/browse/TT-7362

caused by:  https://github.com/TykTechnologies/tyk/pull/4099

### CODE REVIEW

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4719/merge
Commit:  
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4053936346)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4719/merge
Commit: 58bfff3007cec49651cf64ba2059ecf82954f7e4 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4053958522)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4719/merge
Commit: 36317d5cb17899cda0b8eadeff9c8de370814623 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4053966282)

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4719/merge
Commit: 31e64a9cb959fc89d499bf6340d64c98e2dd9400 
Triggered by: pull_request (@jeffy-mathew)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4060709553)

**Pull request merged**
