### PR TITLE
[SYSE-288] Automated tests

### PR DESCRIPTION
**Pull request by ermirizio**
Changes related to SYSE-288

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: ** :no_entry_sign: 
Branch used: refs/pull/5774/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6868065583)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: ** :no_entry_sign: 
Branch used: refs/pull/5774/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6868065583)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: ** :no_entry_sign: 
Branch used: refs/pull/5774/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6868065583)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: ** :no_entry_sign: 
Branch used: refs/pull/5774/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6868065583)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6868065535)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 79d7cfa7e81e9e2906de2b708996e3d6a19c53f0 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6868811638)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 6a71742654abeb75377a997dbe5e8158f39cffba 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6947843335)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 7d88cb12f3bcc0b608b7324e2a77aab06fa84a27 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6947976531)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 7d88cb12f3bcc0b608b7324e2a77aab06fa84a27 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6947976531)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 7d88cb12f3bcc0b608b7324e2a77aab06fa84a27 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6947976441)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 7d88cb12f3bcc0b608b7324e2a77aab06fa84a27 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6947976531)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 7d88cb12f3bcc0b608b7324e2a77aab06fa84a27 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6947976531)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: a8d432814610e0ff27dbe37efa77345463fb3639 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6948088859)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 9856fc7f2a7c39aae202152051f1abeea64b70ee 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6948495013)

**Comment by buger** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5774/merge
Commit: a41cc03c8ba815cd7143941759985496f7838739 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6949028296)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: a41cc03c8ba815cd7143941759985496f7838739 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6949028296)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 68e42dd4b9111e0b0f62fe971bcf365f5eb29047 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6949715562)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 32c853c22f84f61de6e2c9bcafe1ae16c75bbbd7 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6949927204)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 6350b0e2b590b60fe4d94d2f481d3d29a7676627 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6950135285)

**Comment by ermirizio** [comment]
@alephnull this is ready to merge, I have fixed smoke tests , but couldn't make the plugin-compiler smoke test to pass. This can be addressed later since is not related to templates. I will ask @titpetric  to take a look

**Comment by buger** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5774/merge
Commit: c389dd78be876672c557146c89151c52d74b9fc3 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6958561047)

**Comment by buger** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5774/merge
Commit: e5fb4abd51ec013836862ea22b736e36b5400f08 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6958950948)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: f0e60593668734e2aa6af4242944a71414f9416e 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6959272959)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 46a55d2dd43f84405dfc14efaf63c06c47a419d2 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6959817258)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: cf99ef82bd6008e8b1dda2ce9896e3cd4e760ad1 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6962117718)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: d61b7d1b353d88783ac7fc561efa4c10d70a55cd 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6962357133)

**Review by alephnull — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5774/merge
Commit: 033679461b271f73205654451aa8606ac9691d7d 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6971495989)

**Pull request merged**
