### PR TITLE
TT-1683 added config for purge analytics interval

### PR DESCRIPTION
**Pull request by sredxny**
## Description
Added a config to set the interval length (in seconds) on how often we should purge the analytics from the rpc cache.

## Related Issue
https://tyktech.atlassian.net/browse/TT-1683

## Motivation and Context
Give solution to https://tyktech.atlassian.net/browse/TT-1683

## How This Has Been Tested
- Set config to 5
- Set analytics type "rpc"
- Ran GW
- perform some requests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [x] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by sredxny** [comment]
Docuemntation added in https://github.com/TykTechnologies/tyk-docs/pull/1622

**Comment by sredxny** [comment]
Failing test is not related to this change

**Review by matiasinsaurralde — APPROVED** [review]
LGTM

**Review by tbuchaillot — APPROVED** [review]
LGTM

**Pull request merged**
