### PR TITLE
[TT-5852] exclude subgraph from analytics

### PR DESCRIPTION
**Pull request by kofoworola**
## Description

This ticket excludes subgraph requests from being tagged so the mongo-graph-pumps ignore them.

## Related Issue

[TT-5852](https://tyktech.atlassian.net/browse/TT-5852)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4388/merge
Commit:  
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3391435870)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4388/merge
Commit: 20132d3c77ca64ae422667452cad28e2717d324a 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3391441704)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4388/merge
Commit: 952f12c09dc1b0c6c09294c6c3aae5f33450d803 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3391502357)

**Review by pvormste — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4388/merge
Commit: 898526ed9b6cd93eb849c06008147960541ea4a7 
Triggered by: pull_request (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3392449291)

**Review by Aenimus — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 409362503b7d5f7086dc0dc552542c854c68ffe0 [TT-5852] exclude subgraph from analytics (#4388)

* ignore subgraph requests

* exclude subgraph requests from analytics records

* lint
Triggered by: push (@kofoworola)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3392910892)

**Pull request merged**
