### PR TITLE
[TT-10370] Alias imports

### PR DESCRIPTION
**Pull request by titpetric**
This PR aliases imports within gateway packages, so the aliases are non-conflicting inside individual package scopes.

To verify, run the following:

```
go install github.com/TykTechnologies/exp/cmd/go-fsck@978afcf81429325b9dcf51ec2afcc77a3d83e338
```

```
go-fsck lint ; echo $?
```

The command should exit with status 0 printed in the last line; The command prints a few warnings around ignored files due to build tags. This is expected and can be ignored.

https://tyktech.atlassian.net/browse/TT-10370

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5691/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6665868269)

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5691/merge
Commit: 815c55acd6a3a9bba29033c0962f3f2c23573f73 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6665870460)

**Review by tbuchaillot — APPROVED** [review]

**Comment by buger** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5691/merge
Commit: aa50a6aa85c435c3af987e187fd0cde300481028 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/6667345748)

**Pull request merged**
