### PR TITLE
fix: set static protobuf version

### PR DESCRIPTION
**Pull request by ermirizio**
Prevent protobuf version to upgrading to 4.21.0

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4105/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2430707772)

**Comment by buger** [comment]
Looks cool! And we confirmed it working on 3.0.12 branch.

**Pull request merged**
