### PR TITLE
Simplify code, fix non-Go indentation, remove more unused code

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by buger** [comment]
I'm ok with error handling and tab changes. 

Regarding removed code, it's required to get approval from @lonelycode.

-------
Just a tip, when reviewing the code you can add "?ts=2" to URL to set tab size to be 2 spaces. By default, Github sets tab to 8 spaces, and it kinda hard to review all these JSON changes.

**Comment by buger** [comment]
BTW, what linter did you used to remove dead code? Or you found it manually?

**Comment by mvdan** [comment]
> BTW, what linter did you used to remove dead code? Or you found it manually?

https://github.com/dominikh/go-unused

**Comment by lonelycode** [comment]
Looks good to me

**Pull request merged**
