### PR TITLE
[SYSE-87] r5-lts: test-controller job decides test scope

### PR DESCRIPTION
**Pull request by alephnull**
The complete list of features for _tyk:release-5-lts_: releng, el7, plugin-compiler-fix-vendor.

tyk:release-5-lts needs to support RHEL7. RHEL7 support was dropped in 5.1 and then brought back in 5.2.1. This PR may not directly affect RHEL7 support but it may need testing on RHEL7 to make sure it still works. Release/upgrade-tests will perform some basic tests on supported OSes but this is no guarantee of everything being alright.
tyk:release-5-lts needs to be built _without_ module support and the dependencies vendored for the sake of the plugin compiler. This is implemented in release.yml. Note that the plugin compiler itself is _not_ part of the templates and is built by its own workflow, this PR is probably only about the gateway.
:robot: Beep, boop, this PR has been generated by [automation](https://github.com/TykTechnologies/gromit/blob/master/cmd/policy.go). Changes should be limited to templated code. Where allowed, this PR will be automatically merged when the branch protection rules are satisfied. If you think this was made by mistake, or if merging this might cause any instabilities, please bring it up on Slack or log a jira in the TD project.

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit:  
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7551414627)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: 975529c858101d343ebc5b49ca2e1479678ceed1 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7551593440)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: dd7e517bd8f1ef2d7366a9cf5cf83ecba00783e2 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7551621632)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: cb7339112a9c8e798f14030319b51c2aa86f1faa 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7551824799)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: da7ebcdf90359fefd59d3fe5454f4f62c0c036ec 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7551844117)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: 69565e2f297eb25f6482c1fe1489a7ca8fc60972 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7551965699)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: add31ab65a17a6fbcb7f974787190a99397d1326 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7551987090)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: 9a280b6381fab431d1d175b4d8f1cebc37187f10 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7552019898)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: 89e5fa92d281887dad3aa2b67a63fd8b1979ab57 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7552116349)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5944/merge
Commit: b6ad9e8b9f9a32785fafb203d166b542ae3cab18 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7552170808)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: c95e286a58856532fb8208a882f028cd788128d8 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7552135514)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5944/merge
Commit: b6ad9e8b9f9a32785fafb203d166b542ae3cab18 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7552170808)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: b6ad9e8b9f9a32785fafb203d166b542ae3cab18 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7552170722)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: e468011d7a33b466ab563d581f92a32f0739d0f6 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7552220156)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: ea76c8f93ba268bdd681ff1e8984c62228358b1c 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7553172632)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: 817d4f9456025b00c12ecf0eae0296ef12d913b8 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7553320111)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: 3d32c87464dca9d050e2e55e7457ca007ad2fe83 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7555223597)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: d4f97a0d81e834894afc0d32cb221c46d84a9c73 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7565274066)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: 964d0b8a667537408189b785f25b6d5a26352b8b 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7565752573)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: e351a16a64ca529fca604798cafb1806803ee01c 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7565771897)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: 21de58b5fb706eeee70f2a06b8b227b4531a1424 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7566631626)

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/tags/v5.0.11-alpha1
Commit: 21de58b5fb706eeee70f2a06b8b227b4531a1424 
Triggered by: push (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7566820513)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5944/merge
Commit: 32b8af9b88b0f2c48b9cd881ecfbbfc383ed66d7 
Triggered by: pull_request (@asutosh)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7573824285)

**Review by asutosh — APPROVED** [review]

**Pull request merged**
