### PR TITLE
[TD-1809] Releng updates

### PR DESCRIPTION
**Pull request by alephnull**
- OIDC to AWS instead of terraform output munging
- amazon/2 and amazon/2023 added
- multi-arch docker manifests for cloudsmith
- run tyk-automated-tests on push to branches

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5103/merge
Commit:  
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5185985807)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5103/merge
Commit: c39c123d4607bf57d097fa3827c963461136a6e3 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5186165483)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5103/merge
Commit: 1d648f460cb1e02a890ea16c280571f63dc97967 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5186581825)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5103/merge
Commit: 198f7f245b833fd39433d9f9be463a5c2e9395c6 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5186616407)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5103/merge
Commit: aa2a125b2b439bd6630732a8b0a944c4dec74b4f 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5186705097)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5103/merge
Commit: 446e8a6b525f055a762d7394a96ba175c59175ff 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5187072695)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5103/merge
Commit: 8d32e6a6a46e258133db7a7062efab7beff0ec03 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5187048130)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5103/merge
Commit: 6f302b5a3d8c3f528431550f2636c2f28e891794 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5187034726)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5103/merge
Commit: 0b94b646ce52cb403ecb7fb725e88ae9f1032872 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5187370296)

**Comment by ermirizio** [comment]
@alephnull I assume this is still not ready to be merge and is a WIP PR, is there anything you need from my side on this one?

**Review by ermirizio — APPROVED** [review]
Looks good for me, at the current stage

**Comment by alephnull** [comment]
@ermirizio the plan to is to get the automated testing done in this pr.

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5103/merge
Commit: b2dd76abe8f2ff5f9ef3a4e4aa0625a3bc675972 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5454076986)

**Comment by ermirizio** [comment]
Closing this PR, in favour of a new one since we need to rebase from master and a LOT has changed since then

**Pull request closed without merging**
