### PR TITLE
[TT-2987] Update OAS base identity provider schema

### PR DESCRIPTION
**Pull request by furkansenharputlu**
- update OAS `baseIdentityProvider` schema with `custom_auth`
- update documentation

### CODE REVIEW

**Review by lghiur — APPROVED** [review]

**Review by titpetric — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4964/merge
Commit: fc85898cdbff65e1a2f14db01ece6b4665aebd0b 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4732674021)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/4964/merge
Commit: d2b37ac4143e1cf12ece4c87254a4f1e1dfe8c57 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4732662896)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4964/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4732584070)

**Pull request merged**
