### PR TITLE
[TD-1809] Once again templates are compatible

### PR DESCRIPTION
**Pull request by alephnull**
Update/Sync Releng templates for tyk:master

:robot: Beep, boop, this PR has been generated by [automation](https://github.com/TykTechnologies/gromit/blob/master/cmd/policy.go) at 2023-07-26 14:38:45.721546201 &#43;0800 &#43;08 m=&#43;7.914835510

This PR updates the release engineering specific code in the master branch of tyk, and has been generated because some releng code was changed, and the corresponding templates were updated.

These changes should be limited to the `ci/` directory and `.github` directory. This PR should be automatically merged with the branch protection rules are satisfied.

If you think this was made by mistake, or if merging this might cause any instabilities, please bring it up on Slack or log a jira in the TD project.

## Repo Policy for tyk

Default Branch: **master**

### Active  Release Branches

| Branch | Releng Features | Source Branch | Go Version | Tests
| -------| -------------- | ------------- | ---------- | -----
| release-4.0.14 | plugin-compiler,el7 | release-4-lts | 1.15 | Go 1.15 Redis 6
| release-5.1 |  | master |  | 
| release-5.1.1 |  | master |  | 
| release-4-lts | el7,plugin-compiler | master | 1.15 | Go 1.15 Redis 6
| release-5.0.4 | el7,plugin-compiler | release-5-lts | 1.16 | Go 1.16 Redis 5,1.16,1.16-el7
| release-5-lts | el7,plugin-compiler | master | 1.16 | Go 1.16 Redis 5,1.16,1.16-el7

**Generated by gromit on Wed Jul 26 14:38:45 &#43;08 2023**

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5353/merge
Commit:  
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5665515592)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5353/merge
Commit: 55a423f9bf02e62831498b718c033805012dc064 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5665654064)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5353/merge
Commit: 08cfc3bc40c2780d55df7d8effbe3ea95a635438 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5665757755)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5353/merge
Commit: 80e6ddf3c3c15788077924b82d7ca9b2c78022cf 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5666137618)

**Review by asutosh — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5353/merge
Commit: bbbfa3857940cc508fbd84166fead1fdccee31e3 
Triggered by: pull_request (@alephnull)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5666767333)

**Pull request merged**
