### PR TITLE
Fix/update pmylund go cache

### PR DESCRIPTION
**Pull request by titpetric**
Testing change: This PR slightly improves the leaky goroutines behaviour around StartTest/Test.Close. Each test function that invokes startTest may leak several goroutines, one for each of the caches. If not clearing the caches and invoking the garbage collector, leaks accumulate.

Tested with 

Test before: 16 -> 24 -> 31 goroutines
Test after: 16 -> 18 -> 19

- update import paths for pmylund/go-cache, renamed to patrickmn/go-cache on github (same repo),
- add test case to verify goroutine leaks for StartTest() / .Close(),
- add explicit clear caches to nil and GC invocation in Test.Close(),
- add a Close() and mutex to internal/cache (fix race in tests)

The dependency is not bumped, last release is october 2017 and we are already on latest.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5379/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5730066244)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5379/merge
Commit: ba67ef748b0fad7e2889bdcfc3b60ff9a07f1cb0 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5730349995)

**Comment by buger** [comment]
@CodiumAI-Agent review

**Comment by buger** [comment]
@CodiumAI-Agent improve

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5379/merge
Commit: 9dcbede2acb2967cb25ee3ec32c2fe1a57f8332e 
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5735629381)

**Pull request closed without merging**
