### PR TITLE
Deprecate set-output directive

### PR DESCRIPTION
**Pull request by ermirizio**
## Description

Deprecated github CI directives

## Related Issue

https://tyktech.atlassian.net/browse/TD-1269

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4560/merge
Commit:  
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3735475869)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4560/merge
Commit: 278ac1bb1114943425f072425c5e75441705d5e7 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3735594364)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4560/merge
Commit: e4bdff81e525d416395315d3f930bafc7e0ed0e5 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3735603446)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4560/merge
Commit: 38f7faf2f8343635141d717febea0b2647e2f52c 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3735637215)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4560/merge
Commit: bc06b8d1b330810d6afa10e6588af5cda41e764c 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3735684732)

**Review by alephnull — APPROVED** [review]

**Review by asutosh — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4560/merge
Commit: 3a8dab74aabe7e51c34e30f0fb54982e739c097d 
Triggered by: pull_request (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3750427226)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 05918db4f69769742285a40dfd7b41bae2cd704f Deprecate set-output directive (#4560)

## Description

Deprecated github CI directives

## Related Issue

https://tyktech.atlassian.net/browse/TD-1269
Triggered by: push (@ermirizio)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3750545544)

**Pull request merged**
