### PR TITLE
[TT-7393] Add public function to directly access the Redis Universal Client

### PR DESCRIPTION
**Pull request by stewartlord**
## Description

Expose direct access to the underlying Redis Universal Client via `GetUniversalClient`

## Related Issue

https://github.com/TykTechnologies/tyk/issues/4545

## Motivation and Context

This is needed for plugin developers (in some cases) to issue commands that are not supported by the storage abstraction layer or have otherwise had their behavior changed. For example, it is not possible to issue a `SETEX` command. Similarly, the `MGET` command behaves differently and doesn't work in cases where some keys are expected to be missing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by titpetric** [comment]
We have work in progress under storage where we will be adding new drivers, which don't expose a RedisUniversalClient. Adding this function would be problematic, as it would become part of our API and we would have to support it indefinitely.

**Comment by stewartlord** [comment]
> We have work in progress under storage where we will be adding new drivers, which don't expose a RedisUniversalClient. Adding this function would be problematic, as it would become part of our API and we would have to support it indefinitely.

I thought I added this to Redis specific code. Naturally it wouldn't belong on a generic interface. From my understanding this is below the storage abstraction layer.

Am I mistaken about that?

**Comment by titpetric** [comment]
@stewartlord Hi. The underlying singleton() is accessible only in the storage package scope, while your addition would expose it as a public symbol one can use by importing the storage package. Already in-flight storage driver reworking will make it impossible to satisfy redis.UniversalClient as we're focusing on storage drivers improvements to support other kinds of storage drivers as well. The storage interface is intended to only provide a subset of redis functionality and some of our own on top of that required for gateway. This may be less than what you need for custom-behaviour plugins.

Particularly for SetEx however, we implement that behaviour with the underlying 'Set' (already exposed as SetKey() / SetRawKey()). Redis docs: https://pkg.go.dev/github.com/go-redis/redis/v8#Client.Set. I'm curious to learn more about what you're doing, if there are use case details you can share.

**Review by furkansenharputlu — APPROVED** [review]

**Comment by stewartlord** [comment]
Hi @titpetric, sorry for the late reply. Thank you for considering this change. If it doesn't align with your future goals that's understandable. I appreciate the tip on `Set` 🙏

**Pull request closed without merging**
