### PR TITLE
[TT-9628/TT-9724] Fix extractTo of custom plugin

### PR DESCRIPTION
**Pull request by furkansenharputlu**
<details open>
  <summary><a href="https://tyktech.atlassian.net/browse/TT-9724" title="TT-9724" target="_blank">TT-9724</a></summary>
  <br />
  <table>
    <tr>
      <th>Summary</th>
      <td>[DB] Respect classic apidef fields on OAS update</td>
    </tr>
    <tr>
      <th>Type</th>
      <td>
        Sub-task
        Sub-task
      </td>
    </tr>
    <tr>
      <th>Status</th>
      <td>In Code Review</td>
    </tr>
    <tr>
      <th>Points</th>
      <td>N/A</td>
    </tr>
    <tr>
      <th>Labels</th>
      <td>-</td>
    </tr>
  </table>
</details>

---

an extra fix for custom plugin.

Ticket:https://tyktech.atlassian.net/browse/TT-9628
Subtask: https://tyktech.atlassian.net/browse/TT-9724

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
<p>
    Knock Knock! 🔍
  </p>
  <p>
    Just thought I'd let you know that your <em>PR title</em> and <em>story title</em> look <strong>quite different</strong>. PR titles
    that closely resemble the story title make it easier for reviewers to understand the context of the PR.
  </p>
  <blockquote>
    An easy-to-understand PR title a day makes the reviewer review away! 😛⚡️
  </blockquote>
  <table>
    <tr>
      <th>Story Title</th>
      <td>[DB] Respect classic apidef fields on OAS update</td>
    </tr>
    <tr>
        <th>PR Title</th>
        <td>[TT-9628/TT-9724] Fix extractTo of custom plugin</td>
      </tr>
  </table>
  <p>
    Check out this <a href="https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests">guide</a> to learn more about PR best-practices.
  </p>

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5447/merge
Commit:  
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5931823706)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5447/merge
Commit: 6cb5fbd3d9e043adc8f2dfb1e19678003cd4fe46 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5932651673)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5447/merge
Commit: 3e1b0dbf2c58598ab1c6f793413b32aaec7de85b 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5932704423)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5447/merge
Commit: f5bb1723076883c0a8708baa7cd416e58771a95c 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5932751541)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5447/merge
Commit: a860d498f6cfe038c0658212ff2ce312e2c6de09 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5936046402)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5447/merge
Commit: a860d498f6cfe038c0658212ff2ce312e2c6de09 
Triggered by: pull_request (@furkansenharputlu)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5936046402)

**Pull request merged**
