### PR TITLE
Removed unused gorm import, cleaned up go.mod/sum

### PR DESCRIPTION
**Pull request by titpetric**
Somebody left an unused package dependency in gateway, removing.

### CODE REVIEW

**Review by furkansenharputlu — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3954/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2028953031)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3954/merge
Commit: ec56158bf2f8071fd3b7f82222e32c73b45bc67b 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2038709380)

**Review by jeffy-mathew — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3954/merge
Commit: e84f0af50113e09a2fe4efd48ae91d157f5c67ca 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2160874262)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3954/merge
Commit: c13a04b98ab0e0dbd73d9330986a221359889ec4 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2161297495)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3954/merge
Commit: 6dc342361605538c7b9877ee0d086cd2b30643a4 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2554469805)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3954/merge
Commit: 94710c46ddb682d61c485e30575b5806e3a971ad 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2554472780)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/3954/merge
Commit: 8eb455d3d91b28ca4d7636b28c42834f4e8de1e0 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2554492361)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: 09a75318cba9881150d1d28310ffd86955ddd077 Remove gorm, unused (#3954)
Triggered by: push (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2554572641)

**Pull request merged**
