### PR TITLE
TT-9849 rename otel config to be exported as opentelemetry

### PR DESCRIPTION
**Pull request by sredxny**
<details open>
  <summary><a href="https://tyktech.atlassian.net/browse/TT-9849" title="TT-9849" target="_blank">TT-9849</a></summary>
  <br />
  <table>
    <tr>
      <th>Summary</th>
      <td>Publish new Gateway Configurations docs</td>
    </tr>
    <tr>
      <th>Type</th>
      <td>
        Story
        Story
      </td>
    </tr>
    <tr>
      <th>Status</th>
      <td>In Code Review</td>
    </tr>
    <tr>
      <th>Points</th>
      <td>N/A</td>
    </tr>
    <tr>
      <th>Labels</th>
      <td>-</td>
    </tr>
  </table>
</details>

---

## Description

Renamed how we export the struct of opentelemetry to the other gw's packages, currently otel repo have it exposed as `OpenTelemetry` then in internal we renamed it to `Config`, this leads us to issues while running the config doc generator as it will search for a struct named `Config` in the otel repo (and it's not found).

## Related Issue

TT-9849

## Motivation and Context

Allow Config generator to deal with otel structs that doesn't live in the gw repo

## How This Has Been Tested

- Build GW
- Unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
<p>
    Knock Knock! 🔍
  </p>
  <p>
    Just thought I'd let you know that your <em>PR title</em> and <em>story title</em> look <strong>quite different</strong>. PR titles
    that closely resemble the story title make it easier for reviewers to understand the context of the PR.
  </p>
  <blockquote>
    An easy-to-understand PR title a day makes the reviewer review away! 😛⚡️
  </blockquote>
  <table>
    <tr>
      <th>Story Title</th>
      <td>Publish new Gateway Configurations docs</td>
    </tr>
    <tr>
        <th>PR Title</th>
        <td>rename otel config to be exported as opentelemetry</td>
      </tr>
  </table>
  <p>
    Check out this <a href="https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests">guide</a> to learn more about PR best-practices.
  </p>

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5442/merge
Commit:  
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5918145436)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5442/merge
Commit: b690074ede48053f278186bdef3a6e9925053215 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5918220227)

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/5442/merge
Commit: 4f2d99a30f8d491de5de1d62d3c81b819ac7a755 
Triggered by: pull_request (@tbuchaillot)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5935682414)

**Review by mativm02 — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5442/merge
Commit: 837873a66631a50bc74949d7f1ecd427372795b8 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5939923572)

**Pull request merged**
