### PR TITLE
[TT-10697] Update graphql-go-tools

### PR DESCRIPTION
**Pull request by buraksezer**
See [TT-10697](https://tyktech.atlassian.net/browse/TT-10697)

[TT-10697]: https://tyktech.atlassian.net/browse/TT-10697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by kofoworola — APPROVED** [review]

**Comment by buger** [comment]
**API tests result - postgres15-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5918/merge
Commit: 6ff0789c0d451f1bb95e2a550b51f14e819be9ea 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7395245416)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5918/merge
Commit: 6ff0789c0d451f1bb95e2a550b51f14e819be9ea 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7395245416)

**Comment by buger** [comment]
**API tests result - mongo44-murmur64 env: success** :white_check_mark: 
Branch used: refs/pull/5918/merge
Commit: 6ff0789c0d451f1bb95e2a550b51f14e819be9ea 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7395245416)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/5918/merge
Commit: 6ff0789c0d451f1bb95e2a550b51f14e819be9ea 
Triggered by: pull_request (@buraksezer)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7395245416)

**Pull request merged**
