### PR TITLE
WIP: reorganize build tags

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
This is required for #553 and #811.
There are still some things to add and test, I'm working on it at the moment.
Don't merge yet 👍

### CODE REVIEW

**Comment by mvdan** [comment]
@matiasinsaurralde are you going to finish this soon? This touches quite a lot of files, so conflicts are going to be a bit of a problem.

**Comment by mvdan** [comment]
bump @matiasinsaurralde

**Comment by mvdan** [comment]
friendly ping @matiasinsaurralde - we want to freeze for the release soon, so you should get this finished the sooner the better.

**Comment by mvdan** [comment]
Too late for 2.4.

**Comment by buger** [comment]
@matiasinsaurralde can we included this in 2.5? What is the state?

**Comment by matiasinsaurralde** [comment]
About this PR: I suggest merging #1260 first, those tweaks are more important. Then we check this one.

**Comment by buger** [comment]
I'm going to close it because it is too old.

**Pull request closed without merging**
