### PR TITLE
[TT-9194] Deprecating OpenTracing

### PR DESCRIPTION
**Pull request by mativm02**
## Description
Printing a warning log asking users to use OpenTelemetry instead of OpenTracing

## Related Issue
https://tyktech.atlassian.net/browse/TT-9194?atlOrigin=eyJpIjoiNTBlNmJhYTliZDhjNDRiNDk5MDAxZGIzZGZjZWQ5ZjYiLCJwIjoiaiJ9

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5289/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5486578747)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5289/merge
Commit: fae3d8ee69811fe836c698c8d807b1f03baeedd5 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5487335835)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5289/merge
Commit: c4356e6546a54cd929823ebcf4742c2790378dc4 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5487744294)

**Comment by Tyk-ITS** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/5289/merge
Commit: c4356e6546a54cd929823ebcf4742c2790378dc4 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5487744294)

**Review by tbuchaillot — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5289/merge
Commit: 57c2fb9662dec0b271c7faa5039c1d4cdcbdca3d 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5520181505)

**Pull request merged**
