### PR TITLE
[TT-9046] [release-5-lts] fix plugin compiler version, arm64 builds

### PR DESCRIPTION
**Pull request by titpetric**
## Description

This backports a GITHUB_TAG / gateway version value from #5115 for release-5-lts.

This temporarily backports #5135 for release-5-lts.
The PR needs a rebase after 5134 has been merged to remove the arm64 fix.

## Related Issue

https://tyktech.atlassian.net/browse/TT-9046

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5136/merge
Commit:  
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5260816320)

**Comment by titpetric** [comment]
@alephnull is the failing el7 test a known separate issue, or somehow causal? Please advise.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5136/merge
Commit: b888b96fc324f636abaa540cd35ffa6c67385186 
Triggered by: pull_request (@titpetric)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5260932897)

**Comment by asutosh** [comment]
@titpetric The el7 release is failing because the `extra_files` for plugin compiler el7 docker build are not specified in `ci/goreleaser/goreleaser-el7.yml` - the docker build context can't find go.mod and go.sum because goreleaser isn't copying it over as extra file.

**Comment by titpetric** [comment]
Solved with separate commits/cherry-picks. Not needed anymore.

**Pull request closed without merging**
