### PR TITLE
Rotating signing key

### PR DESCRIPTION
**Pull request by alephnull**
Corresponding changes have been made in rpm-sign.sh in the BuddyFS. Please merge to all release branches to handle historical builds in the future.

### CODE REVIEW

**Comment by excieve** [comment]
Should this change the default key ID that the script is using?

**Comment by alephnull** [comment]
I had originally just replaced the file key so this commit was not required. 

This commit is required to keep with the naming convention mentioned by @lonelycode

**Comment by alephnull** [comment]
> Should this change the default key ID that the script is using?

:sweat_smile: Thanks for catching that. Pushed fix.

**Comment by buger** [comment]
Does the `deb` packages have the same signing mechanism?

**Comment by alephnull** [comment]
> Does the `deb` packages have the same signing mechanism?

That is handled by package cloud with their signing key. Debian signing is tied to the repo, not the file.

**Comment by buger** [comment]
Lets put it as part of 2.10 in this case.

**Comment by buger** [comment]
@alephnull pls create a ticket with proper description (and way to test it for the QA), and put it to 2.10 project board.

**Comment by excieve** [comment]
@buger This **needs** to go into the next release (whichever it is).

**Comment by alephnull** [comment]
Failing due to 

```
time="Feb 18 11:48:44" level=info msg="[HOST CHECKER] Stopping poller"
--- FAIL: TestChecker_triggerSampleLimit (28.00s)
    host_checker_test.go:529: expected host down to be fired once got 0 instead
```
Seems unrelated to this change.

**Pull request merged**
