### PR TITLE
[TT-5997] Make MDCB work without group id

### PR DESCRIPTION
**Pull request by mativm02**
## Description
If a gateway worker does not have an assigned `group_id`, it will be defaulted to "ungrouped". Note that having more than one ungrouped worker in different clusters will lead to one of them not receiving any event. 

## Related Issue
https://tyktech.atlassian.net/browse/TT-5997?atlOrigin=eyJpIjoiZmNkYTI0YTJjZGExNDdlOGI4NDNkZDQ4ZjkxOGEyYzUiLCJwIjoiaiJ9

## Motivation and Context
In MDCB we have `Login` and `LoginWithGroup` functions. Both of them have a similar logic, so the idea is to only use one of them. In this case, it's `LoginWithGroup`, since we're setting a default group to all the workers without a `group_id`.
The idea of this PR is to make worker gateways to only execute 

## How This Has Been Tested
It's been manually tested and unit tests were also created.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4678/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/3988639849)

**Review by tbuchaillot — CHANGES_REQUESTED** [review]
@mativm02 I think it would be better to modify it directly into the `getGroupLoginCallback`. Also, in that way, we can easily test the behavior.
What do you think?

**Comment by mativm02** [comment]
> @mativm02 I think it would be better to modify it directly into the `getGroupLoginCallback`. Also, in that way, we can easily test the behavior. What do you think?

After discussing this at Friday's meeting, we agreed on modifying this within the `afterConfSetup` function.

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4678/merge
Commit: f26a4f8ab8c77295105cccf0a49d713d1314d9dc 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4043833709)

**Review by sredxny — APPROVED** [review]
lgtm

**Review by tbuchaillot — APPROVED** [review]
LGTM!

**Comment by Tyk-ITS** [comment]
**API tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/4678/merge
Commit: 5557629de032299883e27287cdd88fbe9cad523e 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/4105428457)

**Pull request merged**
