### PR TITLE
[TT-11269] swagger version update to v5.0.11

### PR DESCRIPTION
**Pull request by jeffy-mathew**
## Description

swagger version update to v5.0.11
## Related Issue
https://tyktech.atlassian.net/browse/TT-11269

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/heads/release-5.0.11
Commit: a9bf5ec3ed1745e4516be689bf3a0f200d9b202e 
Triggered by: push (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7899380331)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/heads/release-5.0.11
Commit: a9bf5ec3ed1745e4516be689bf3a0f200d9b202e 
Triggered by: push (@lghiur)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7899380331)

**Review by andrei-tyk — APPROVED** [review]

**Pull request merged**
