### PR TITLE
[TT-5110] Ensure that key_id is not present in Redis session object

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
## Description
Ensures that `key_id` field is not present in Redis session object.

## Related Issue
TT-5110

## Motivation and Context
While testing latest `master` after changes introduced by #3993, we've found that under some scenarios (for example, the combination of unhashed keys and client certificate auth. mode on slave gateways), the `key_id` is being written to the serialized JSON object that's persisted in Redis.
This shouldn't be exposed due to security reasons.

## How This Has Been Tested
Manual testing and automated tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [x] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [ ] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] Check your code additions will not fail linting checks:
  - [ ] `go fmt -s`
  - [ ] `go vet`

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/4032/merge
Commit:  
Triggered by: pull_request (@matiasinsaurralde)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2270889602)

**Review by tbuchaillot — APPROVED** [review]

**Review by buger — APPROVED** [review]

**Review by kolavcic — APPROVED** [review]
looking good to me

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/heads/master
Commit: ca7232dbd44fd273dbcd3a729f5d2a167bb6d31c user: ensure that key_id is not present in Redis session object (#4032)

Co-authored-by: Tomas Buchaillot <tombuchaillot89@gmail.com>
Triggered by: push (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/2275790920)

**Pull request merged**
