### PR TITLE
Cleanup redis_cache code, simplify storage key error

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by buger** [comment]
Oh, this `ProcessRequest` so big 😨 

@matiasinsaurralde can you help me with review?

**Comment by matiasinsaurralde** [comment]
@buger Sure!

**Comment by mvdan** [comment]
> Oh, this ProcessRequest so big

Would help if you ignored whitespace - a lot of the changed lines are just indentation. This can be `git diff -w`, but I think github supports it too.

**Comment by buger** [comment]
Right, forgot about "?w=1" url param feature. Looks good.

**Pull request merged**
