### PR TITLE
Fix Go Modules

### PR DESCRIPTION
**Pull request by diegobernardes**
## Description
The Go Modules are currently broken at the master branch.

## Related Issue
This affects the use of custom Go plugins. The problem is that Tyk is not implementing correctly the usage of Go Modules.

## Motivation and Context
Basically 2 commands are required to fix the problem:
`find . -type f -name '*.go' -exec sed -i '' -e 's,github.com/TykTechnologies/tyk,github.com/TykTechnologies/tyk/v3,g' {} \;`
and
`go mod edit -module github.com/TykTechnologies/tyk/v3`

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If pulling from your own
      fork, don't request your `master`!
- [X] Make sure you are making a pull request against the **`master` branch** (left side). Also, you should start
      *your branch* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
  - [ ] If you've changed APIs, describe what needs to be updated in the documentation.
  - [ ] If new config option added, ensure that it can be set via ENV variable
- [ ] I have updated the documentation accordingly.
- [X] Modules and vendor dependencies have been updated; run `go mod tidy && go mod vendor`
- [ ] When updating library version must provide reason/explanation for this update.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] Check your code additions will not fail linting checks:
  - [X] `go fmt -s`
  - [X] `go vet`

### CODE REVIEW

**Comment by buger** [comment]
Are you sure that this change is for master? 
It feels like this change should be merged to release-3 branch instead?

**Comment by diegobernardes** [comment]
I don't know Tyk branching workflow. What's the correct branch to push these changes? I can close this PR and push to the next releases branch.

I'm using the release `3.0.1` and the Go Modules are not working with that release.

**Comment by alephnull** [comment]
> Are you sure that this change is for master?
> It feels like this change should be merged to release-3 branch instead?

This should go to `master` _and_ `release-3*` I think.

**Comment by buger** [comment]
@diegobernardes may I ask how exactly you are building the plugins? 

The reason I ask is that we verified that if official Tyk binary is used, and you also using official way to build plugins (plugin-compiler), it works just fine. And the reason because it works, is that plugin gets copied into exactly same environment where original binary was used. Additionally worth noticing that we are using go modules with vendoring.

**Comment by diegobernardes** [comment]
Sorry guys, I didn't have time to fix the PR. But I'll do.

@buger I'm building everything from source, Tyk, and the plugin. I tried to use the [official solution](https://github.com/TykTechnologies/tyk-build-env) but it simply won't work for us because we need to run natively on mac and using kubefwd.

This is the makefile we're using at the moment to allow the developers to run Tyk locally and during the CI to build the release image:
```makefile
TYK_VERSION := 3.0.1

.PHONY: tyk-build
tyk-build:
	@rm -Rf tmp
	@mkdir -p tmp
	@wget -O tmp/tyk.tar.gz https://github.com/TykTechnologies/tyk/archive/v$(TYK_VERSION).tar.gz
	@tar -xzvf tmp/tyk.tar.gz -C tmp
	@rm tmp/tyk.tar.gz
	@mv tmp/tyk-$(TYK_VERSION) tmp/tyk
	@cd tmp/tyk; go mod edit -module github.com/TykTechnologies/tyk/v3
	@cd tmp/tyk; find . -type f -name '*.go' -exec sed -i -e 's,github.com/TykTechnologies/tyk,github.com/TykTechnologies/tyk/v3,g' {} \;
	@cd tmp/tyk; go build -trimpath -mod vendor -tags goplugin -o tyk main.go

.PHONY: tyk-build-plugin
tyk-build-plugin:
	@rm -Rf plugin/vendor
	@cd plugin; go mod vendor
	@cp -R tmp/tyk/vendor plugin/
	@cd plugin; go build -trimpath -mod vendor -buildmode plugin -o plugin.so
	@rm -Rf tmp/tyk/plugins
	@mkdir tmp/tyk/plugins
	@mv plugin/plugin.so tmp/tyk/plugins/

.PHONY: tyk-run
tyk-run:
	@rm -Rf tmp/tyk/apps
	@cp -R apps tmp/tyk/apps
	@cp tyk.conf tmp/tyk/tyk.conf
	@cd tmp/tyk/; ./tyk
```

The main problem that I have at the moment is that the Tyk release v3.0.1 is not following the Go Modules standards and with that, It's really hard to build the plugin.

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by diegobernardes** [comment]
Ok, everything updated. Travis is ok, the linter is complaining but I don't think it's related to my changes.

**Comment by diegobernardes** [comment]
Any update guys?

**Comment by jlucktay** [comment]
I spent some time trying to merge this but I can't get a clean build.

This was the first issue:
```
storage/kv/consul.go:5:2: ambiguous import: found package github.com/hashicorp/consul/api in multiple modules:
        github.com/hashicorp/consul v0.0.0-20171026175957-610f3c86a089 (/Users/jameslucktaylor/go/pkg/mod/github.com/hashicorp/consul@v0.0.0-20171026175957-610f3c86a089/api)
        github.com/hashicorp/consul/api v1.3.0 (/Users/jameslucktaylor/go/pkg/mod/github.com/hashicorp/consul/api@v1.3.0)
```
for which the apparent hack to solve was [this `replace` directive](https://github.com/hashicorp/consul/issues/6019#issuecomment-505782870) which led to the next issue:
```
storage/kv/vault.go:8:2: ambiguous import: found package github.com/hashicorp/vault/api in multiple modules:
        github.com/hashicorp/vault v0.10.3 (/Users/jameslucktaylor/go/pkg/mod/github.com/hashicorp/vault@v0.10.3/api)
        github.com/hashicorp/vault/api v1.0.4 (/Users/jameslucktaylor/go/pkg/mod/github.com/hashicorp/vault/api@v1.0.4)
```
which again should apparently be hacked around with [another `replace` directive](https://github.com/hashicorp/vault/issues/7848#issuecomment-634940863), but then this fails:
```
# github.com/xenolf/lego/acme
../../../../pkg/mod/github.com/xenolf/lego@v0.3.2-0.20170618175828-28ead50ff1ca/acme/dns_challenge.go:195:13: undefined: dns.ErrTruncated
```
so that's as far as I got with it, after resolving all of the merge conflicts for the `/tyk/v3/` package paths.

**Comment by gernest** [comment]
@jlucktay  please check # #3336 

I did play with this and fixed all  issue. You can `go build -mod=vendor` it.

**Comment by furkansenharputlu** [comment]
This is solved.

**Comment by diegobernardes** [comment]
Hi @furkansenharputlu, could you point me to the PR/commit that fixed the problem? I looked at the master branch and it doesn't look that the problem was fixed, maybe this was done in another branch?

**Pull request closed without merging**
