### PR TITLE
[TT-9504] Moving AddTraceID call to ProcessRequest function

### PR DESCRIPTION
**Pull request by mativm02**
## Description
Moving AddTraceID call to ProcessRequest function in order to write the header no matter if the request to the upstream was made or not (i.e. 4xx cases, which fail because of authentication issues)

## Related Issue
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?selectedIssue=TT-9464

## Motivation and Context
https://tyktech.atlassian.net/jira/software/c/projects/TT/boards/42?selectedIssue=TT-9464

## How This Has Been Tested
Manual testing (based on this Loom video: https://www.loom.com/share/d43ed2aa81b843f5908e5b39a09033e7?sid=5c59e225-6dd1-4ac1-9a2e-80f35a2752ab)
and unit tests were already created for this function

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning why it's required
- [ ] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5425/merge
Commit:  
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5878807188)

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5425/merge
Commit: b4b9a34347d441e362a841a8c51551cf39b596ed 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5879083794)

**Review by sredxny — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**API tests result: success** :white_check_mark: 
Branch used: refs/pull/5425/merge
Commit: d672e361e1ca038bce847509301dce6972b86589 
Triggered by: pull_request (@mativm02)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/5890511572)

**Pull request merged**
