### PR TITLE
Merging to release-5-lts: TT-9158 prefetch org expiry when loading the apis (#5798)

### PR DESCRIPTION
**Pull request by buger**
TT-9158 prefetch org expiry when loading the apis (#5798)

## Description

Previously, when operating in a slave configuration, the Tyk Gateway
fetched session expiry information from the master layer the first time
an API was accessed for a given organization. This approach led to a
significant issue: if the MDCB connection was lost, the next API
consumption attempt would incur a long response time. This delay,
typically around 30 seconds, was caused by the gateway waiting for the
session fetching operation to time out, as it tried to communicate with
the now-inaccessible master layer.

Implemented Solution: To mitigate this issue, the PR introduces a
proactive fetching strategy. Now, the gateway fetches the session expiry
information beforehand, while there is an active connection to MDCB. By
doing so, it ensures that this data is already available locally in the
event of an MDCB disconnection.

Outcome: This change significantly improves the API response time under
MDCB disconnection scenarios. It eliminates the need for the gateway to
wait for a timeout when attempting to fetch session information from the
master layer, thus avoiding the previous 30-second delay. This
optimization enhances the resilience and efficiency of the Tyk Gateway
in distributed environments.

This option comes to complement the config option
`slave_options.call_timeout` which defaults to 30sec, users can set a
lower value.

## Related Issue

TT-9158

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test
coverage to functionality)

## Checklist

- [ ] I ensured that the documentation is up to date
- [ ] I explained why this PR updates go.mod in detail with reasoning
why it's required
- [ ] I would like a code coverage CI quality gate exception and have
explained why

### CODE REVIEW

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/6014/merge
Commit:  
Triggered by: pull_request (@buger)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7739778871)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/6014/merge
Commit: 946a501ed881c034525f732bd167c3e4d0895227 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7739926287)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/6014/merge
Commit: 946a501ed881c034525f732bd167c3e4d0895227 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7739926287)

**Comment by buger** [comment]
**API tests result: failure** :no_entry_sign: 
Branch used: refs/pull/6014/merge
Commit: ef42dda42546e32762fab6e1f45b459b42174ede 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7743885938)

**Comment by buger** [comment]
**API tests result - mongo44-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6014/merge
Commit: ef42dda42546e32762fab6e1f45b459b42174ede 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7743886025)

**Comment by buger** [comment]
**API tests result - postgres15-sha256 env: success** :white_check_mark: 
Branch used: refs/pull/6014/merge
Commit: ef42dda42546e32762fab6e1f45b459b42174ede 
Triggered by: pull_request (@sredxny)
[Execution page](https://github.com/TykTechnologies/tyk/actions/runs/7743886025)

**Review by sredxny — APPROVED** [review]

**Pull request merged**
