### PR TITLE
git checkout . after fix vendor in release

### PR DESCRIPTION
**Pull request by jeffy-mathew**
go release throws dirty git state after `go mod tidy`
https://github.com/TykTechnologies/tyk/runs/4787073278?check_suite_focus=true

### CODE REVIEW

**Review by alephnull — COMMENTED** [review]
Does this mean that `go mod tidy` cannot be used on this branch?

Per https://github.com/TykTechnologies/tyk/actions/runs/1686808607 I guess we need the same thing on release-4-lts as well

**Comment by jeffy-mathew** [comment]
> Does this mean that `go mod tidy` cannot be used on this branch?

Nop, we're not using go modules during build since we use GOPATH for building gw. So this change doesn't really make a difference 
Also, this is added to `release-3.2.3` [here](https://github.com/TykTechnologies/tyk/blob/release-3.2.3/.github/workflows/release.yml#L125)

**Review by furkansenharputlu — APPROVED** [review]

**Review by alephnull — APPROVED** [review]
tbh, my head hurts a little :crossed_fingers:

**Pull request merged**
